### PR TITLE
Changed srcElement to target in mini browser

### PR DESCRIPTION
**Pull request by Tpuljak**
Signed-off-by: Toma Puljak <toma.puljak@hotmail.com>

#### What it does

The following pull-request updates the deprecated `scrElement` event prop with `target` for the mini-browser package when handling the <kbd>ENTER</kbd> key to reload the page and update the content to the new location. The change is suggested by [mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement).

#### How to test

In order to test the changes, you can use the `Open URL` command with some minor tweaks. Since the `Open URL` command uses a `readonly` input, it will need to be updated to `show` so the handler can successfully process the <kbd>ENTER</kbd> key code.

1. update the following to `show`:

https://github.com/eclipse-theia/theia/blob/deccec686f295f2b758133048f5a1a3479ca4e8a/packages/mini-browser/src/browser/mini-browser-open-handler.ts#L282

2. rebuild the mini-browser extension using: `npx run build @theia/mini-browser`
3. rebuild the example application (ex: `npx run build @theia/example-electron`)
4. start the application, and using the command palette (<kbd>F1</kbd>) trigger the `Open URL` command
5. input a URL (ex: a file on your filesystem that can be previewed such as `REAMDE.md`)
6. ensure that the input can be updated, and upon pressing <kbd>ENTER</kbd> the content is refreshed and maps to the new location:

webview-enter

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@Tpuljak thank you for your first contribution!

Before we can review your changes please be sure to complete the following:
- Please be sure to add a proper [`sign-off`](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#sign-your-work) to your commit
- Please be sure to sign and complete the [Eclipse Contributor Agreement (ECA)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) with the same email as your `sign-off`.
- Please be sure to update your pull-request description with a `how to test` section which is currently omitted. This section helps reviewers properly understand and test your changes.

**Comment by Tpuljak** [comment]
@vince-fugnitto I've completed everything you asked for 😄

**Review by DukeNgn — APPROVED** [review]
The PR looks good to me 👍 . I believe more information about this change could be found [here](https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement)

**Review by vince-fugnitto — APPROVED** [review]
The changes work well 👍 
With a little bit of changes for the `how to test` I was able to confirm that the `handleInputChange` handler correctly maps the location when <kbd>ENTER</kbd> is triggered:

<div align='center'>

webview-enter

</div>

**Pull request merged**
