### PR TITLE
fix: use node ID instead of running index for menu

### LINKED ISSUE #12493: [electron] Executing the commands from menu items has no effect when the application starts. It worked with 1.36.0
### Bug Description:

Originally from here: https://github.com/arduino/arduino-ide/pull/2027#pullrequestreview-1415843891

Clicking on the menu items have no effect when the application is starting. This has worked with 1.36.0. Presumably, the breaking change has been introduced with the electron version update and affects only the electron app, but this is just a guess so far: https://github.com/eclipse-theia/theia/pull/12299.

### Steps to Reproduce:

1. Open Theia Blueprint 1.37.0, and while the app is starting, click on `File` > `New File`. Nothing happens until the window is fully loaded and the last `setMenu` is called.
2. This works perfectly with Theia Blueprint 1.36.0. When I click `New File` thrice, I will see three new untitled editors once the app is ready.
3.

`1.36.0`: 😄 

https://user-images.githubusercontent.com/1405703/236772360-e55d3a55-93c9-474a-a1dd-d24960a2e904.mp4

`1.37.0`: 😞

https://user-images.githubusercontent.com/1405703/236772435-694e0468-d283-4432-afd0-b1eb09cb9e36.mp4

### Additional Information

- Operating System: macOS
- Theia Version: 1.37.0 Theia Blueprint

### PR DESCRIPTION
**Pull request by kittaakos**
#### What it does

This PR switches from a running index (`number`) menu handler to the menu node's technical ID (`string`).

#### How to test

Start the example electron app, and once you see the `Sample Menu` popping up, click `File` > `New File` multiple times. When the app loads, the highest number of `Untitled-$NUMBER` equals the times you click on the `New File` menu during the app startup. So if you click the menu thrice, expect to see `Untitled-3`.

Closes #12493

https://user-images.githubusercontent.com/1405703/237036355-e5853350-b66f-4a81-bb3d-3549336a19d8.mp4

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
Can you please help with this, @tsmaeder? Thank you!

**Comment by JonasHelming** [comment]
@tsmaeder Ping?

**Comment by tsmaeder** [comment]
@kittaakos finally had time to come back to this one. The implementation here does not really reflect the discussion in https://github.com/eclipse-theia/theia/issues/12493. How shall we proceed?

**Comment by kittaakos** [comment]
Another bug this PR should cover is the very first non-functional context menu item. Handler IDs start from `0`:
https://github.com/eclipse-theia/theia/blob/20e377123c595b2b998d214fc48d169082520b01/packages/core/src/electron-browser/preload.ts#L36

The internal node ID is incremented here:
https://github.com/eclipse-theia/theia/blob/20e377123c595b2b998d214fc48d169082520b01/packages/core/src/electron-browser/preload.ts#L48

But it won't work here because it will be `0`:
https://github.com/eclipse-theia/theia/blob/20e377123c595b2b998d214fc48d169082520b01/packages/core/src/electron-main/electron-api-main.ts#L237

**Comment by tsmaeder** [comment]
> @kittaakos finally had time to come back to this one. The implementation here does not really reflect the discussion in #12493. How shall we proceed?

Ping?

**Comment by kittaakos** [comment]
Thanks for the ping. I have not had time to return to this PR; it's in draft.

Downstream, we use the proposed fix since `1.37.0`.

**Comment by kittaakos** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
