### PR TITLE
Fix tree view selection

### PR DESCRIPTION
**Pull request by xcariba**
Signed-off-by: Alexander Kozinko xcariba@gmail.com

#### What it does

Fixes tree view selection #9672. Original implementation always checked old selection state, I think it was a typo.

#### How to test

1. add the [`vscode-file-explorer-selection`](https://github.com/vince-fugnitto/vscode-file-explorer-selection/releases/download/0.0.1/custom-view-samples-0.0.1.vsix) plugin to the example application
2. start the application, open the explorer and perform a selection in the _tree-view_ **file-explorer**
3. execute the command `FileExplorer: Echo Selection`
4. a notification should appear with the selection path - on master no selection is present

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by msujew** [comment]
Thank you for the contribution. I imagine it works as expected, but could you please provide a working example in the form of a minimal git repo or in a `.vsix` file (wrapped in a .zip file)? It would make reviewing this PR a lot easier.

**Comment by vince-fugnitto** [comment]
We can use the following `plugin` for test-purposes (modified version of `vscode-tree-view-sample`:
- https://github.com/vince-fugnitto/vscode-file-explorer-selection/releases/download/0.0.1/custom-view-samples-0.0.1.vsix

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the changes successfully set the `selection` using the example plugin:

image

On _master_ no selection was present.

**Comment by vince-fugnitto** [comment]
@msujew do you mind performing a quick review as well? I believe it can fit for today's release.

**Review by colin-grant-work — APPROVED** [review]
Looks good to me. I confirm the bug on master and its absence with this code, and the diagnosis of the fault as a typo seems eminently plausible :-).

**Review by msujew — APPROVED** [review]
I can also confirm that the fix is working.

**Pull request merged**
