### PR TITLE
Allow updating user-level task

### PR DESCRIPTION
**Pull request by tsmaeder**
Signed-off-by: Thomas Mäder <tmader@redhat.com>

#### What it does
Allows to programmatically update user-level tasks. Fixes https://github.com/eclipse-theia/theia/issues/7927

#### How to test
Check out this branch and test the scenario from the linked issue.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
@vince-fugnitto the only break folks overriding: calling should be ok.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto the only break folks overriding: calling should be ok.

I see since:

```ts
export type TaskConfigurationScope = string | TaskScope.Workspace | TaskScope.Global;
```

My rationale was that it is always good practice to be explicit in the `changelog` and report any potential breakage for downstream projects. If you don't think it's breakage then I'll leave it up to your discretion.

**Comment by tsmaeder** [comment]
@vince-fugnitto thx for the heads-up.

**Comment by tsmaeder** [comment]
Added a note about the breaking change.

**Pull request merged**
