### PR TITLE
playwright: upgrade dependency

### PR DESCRIPTION
**Pull request by ndoschek**
#### What it does

Update `playwright` to the latest version (and open up version range) as there was a breaking change regarding playwright's Page object.

Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>

Remark: There is currently one flaky test case, see also https://github.com/eclipse-theia/theia/issues/12063.

#### How to test

1. confirm that playwright tests pass via `test:playwright`

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
I created a review for [`@playwright/test/1.30.0`](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6938) given a pull-request from a fork cannot automatically create the review during CI :+1:

**Comment by vince-fugnitto** [comment]
@ndoschek do you mind rebasing to pick up https://github.com/eclipse-theia/theia/pull/12151? It should fix the issue where `playwright-core@1.30.0` was being marked as non-compliant in our "3PP License Check".

**Comment by ndoschek** [comment]
Thank you! I just rebased to latest master

**Review by vince-fugnitto — APPROVED** [review]
LGTM :+1:

**Pull request merged**
