### PR TITLE
[cpp] remove '@theia/cpp' extension

### LINKED ISSUE #6340: [cpp] plan to move the 'cpp' extension into 'theia-cpp-extensions' repo
**Description**

Plan to move the `@theia/cpp` extension into the `eclipse-theia/theia-cpp-extensions` repository.
This also aligns with the cleanup proposed by https://github.com/eclipse-theia/theia/issues/6183, which involves cleaning up the repository and removing/deprecating language extensions while keeping `typescript` the main language present in the repository (for support and test purposes).

**Pre-requisites**
- [x] enable UI tests on the `eclipse-theia/theia-cpp-extensions` repo

**Additional Information**
- https://github.com/eclipse-theia/theia-cpp-extensions/issues/62
- https://github.com/eclipse-theia/theia/issues/6183

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #6340

The `@theia/cpp` extension is planned to move to [theia-cpp-extensions](https://github.com/eclipse-theia/theia-cpp-extensions/) repository.
The pull request has already been started: https://github.com/eclipse-theia/theia-cpp-extensions/pull/69

_This PR:_
- removes the `@theia/cpp` extension.
- removes references to the `@theia/cpp` extension.

#### How to test

- verify that CI passes successfully
- verify that the application correctly starts

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] `@theia/cpp` is merged into [theia-cpp-extensions](https://github.com/eclipse-theia/theia-cpp-extensions/)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@lmcbout I resolved the merge conflict :)
I don't believe there is an explicit need to wait for the `theia-cpp-extensions` pr to be merged first however.

**Comment by lmcbout** [comment]
@vince-fugnitto  The wait for the other PR to be merged is to let the end-user have the alternative ready to use before we cut the CPP  support, Just to be nice to all users.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto The wait for the other PR to be merged is to let the end-user have the alternative ready to use before we cut the CPP support, Just to be nice to all users.

I just need someone to approve the PR from `theia-cpp-extensions` then :)

**Comment by akosyakov** [comment]
Any plans to merge it? Any removed extension makes our build faster.

**Comment by vince-fugnitto** [comment]
> Any plans to merge it? Any removed extension makes our build faster.

Yes, just waiting for https://github.com/eclipse-theia/theia-cpp-extensions/pull/69.
I believe internally we are using https://github.com/eclipse-theia/theia-cpp-extensions/pull/69 this week for a demo so it will likely be merged the beginning of next week. @marcdumais-work

**Comment by vince-fugnitto** [comment]
Merging! :)

**Pull request merged**
