### PR TITLE
WIP: Product Icon Theming

### LINKED ISSUE #9512: Add Product Icon Theme extension compatibility
VSCode supports extensions that can adjust the 'Product Icon Theme', allowing a user to replace the application's default icons with custom icons, giving the editor a custom, branded feel. This was also requested recently in #4831. This would allow for a much easier way to customize the look and feel of Theia's shell without having to provide widget overrides.

[Product Icon Themes](https://code.visualstudio.com/api/extension-guides/product-icon-theme)

### PR DESCRIPTION
**Pull request by kenneth-marut-work**
## WORK IN PROGRESS
Fixes #9512 

#### What it does

Adds support for VSCode product icon themes, allowing for easy customization of the look and feel of Theia's shell. 
[https://code.visualstudio.com/api/extension-guides/product-icon-theme](https://code.visualstudio.com/api/extension-guides/product-icon-theme)

product

#### How to test

**TO DO**
#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kenneth-marut-work** [comment]
Closing this PR since I likely won't have time to work on this any time in the upcoming future and there hasn't been any action for a while.

**Comment by CareyJWilliams** [comment]
Hi @kenneth-marut-work, I'd also be very interested in seeing this supported, and it looks like you made a good start on it.
Would you be able to provide me a summary of where you got up to and what was missing? I do appreciate we're going back a few years now though!

**Comment by kenneth-marut-work** [comment]
Hi @CareyJWilliams ,
It's definitely been a while so I apologize for any lack of details. Looking at the diff and from what I can remember, I was mostly stubbing out classes and methods based on what's going on with the IconThemeService. For example, [this](https://github.com/eclipse-theia/theia/pull/9513/files#diff-211985c65859a72600844ba4d6a2d9d6a8043656008b1d1f5ffb890c23a2fb8cR1056-R1088) method is mostly a copy/paste of the `selectIconTheme` method inside the same class.

From what I can remember, there seemed to be a fair bit of code that handles the swapping of CSS class names for different themes icons etc. (e.g. [here](https://github.com/eclipse-theia/theia/pull/9513/files#diff-e905d9477a4f1d82cbe45177e3835ed954dbbc5035ef76fef15e396606b02653R114-R168)). Ultimately I de-prioritized this task since we had managed to find a good workaround for our theming needs downstream. 

If you feel like continuing this work, I hope that what I've started is gives you a good jumping off point. But like you've mentioned, it has been several years and my approach may be out of date (or maybe not correct) so I won't be offended if you decide to start over :)

Good luck!

**Comment by CareyJWilliams** [comment]
Thanks @kenneth-marut-work! No promises, but I do think this would be an important addition. I'm sure this PR can serve as inspiration at the very least!

**Pull request closed without merging**
