### PR TITLE
Support Anthropic as an LLM provider

### LINKED ISSUE #14613: [Theia AI] Support Anthropic as an LLM provider

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #14613

#### What it does

Adds support for Anthropic as an LLM provider.

#### How to test

Use Anthropic models.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by JonasHelming** [comment]
@sdirix Tool functions do not work yet. That is probably in the way how they are parsed from the stream, but I have no clue how that works for openai TBH, maybe you can have a quick look at this.

**Comment by JonasHelming** [comment]
3PP Check was approved, should succeed with the next rebuild

**Review by sdirix — COMMENTED** [review]
Anthropic works for me, I tested with streaming enabled and disabled.

I also had a look at the tools. The issue is that in our OpenAI language models we directly hand over real Javascript functions into the API which are used by the OpenAI client to resolve the tools, see [here](https://github.com/eclipse-theia/theia/blob/79d55445839d5b37e54f8a8999e552c3be6eb755/packages/ai-openai/src/node/openai-language-model.ts#L221).

Anthropic seemingly does not support this but instead expects a new message from the "user", see the [first example here](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#tool-use-examples).

Suggestion: For the first implementation we skip the tool support and add this in a followup. Of course feel free to add it here too if you want to see it supported.

**Review by sdirix — APPROVED** [review]
Works for me!

**Pull request merged**
