### PR TITLE
Remove obsolete QUIT command

### LINKED ISSUE #7370: [quality] Removed the obsolete Quit command
### Description
 

It's unused. Left from here: https://github.com/eclipse-theia/theia/issues/1331#issue-298864179

https://github.com/eclipse-theia/theia/blob/5fb75c73bea6fc54563c4b969551c3f3cd8c8d62/packages/core/src/browser/common-frontend-contribution.ts#L210-L213

We had this for escaping some keybindings, but it did not work and is legacy now.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by anir1ghosh**
Signed-off-by: Anirban Ghosh <anir1ghosh@gmail.com>

#### What it does
Fixes #7370 

Remove the obsolete QUIT command

#### How to test
yarn test

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by anir1ghosh** [comment]
Hi @kittaakos , could you please take a look?

**Comment by akosyakov** [comment]
> yarn test 

How is it related to QUIT command?

**Comment by anir1ghosh** [comment]
> > yarn test
> 
> How is it related to QUIT command?

I was just making sure that removing QUIT command doesn't break any existing functionality through the preexisting tests. Since the QUIT command is not referenced anywhere else, I couldn't think of a way to test this specifically. Would you know of a way to test it out?

**Comment by kittaakos** [comment]
> Would you know of a way to test it out?

No, but please rewrite the commit message. The `QUIT` command is not redundant, but not used, obsolete. Thanks!

**Comment by anir1ghosh** [comment]
> > Would you know of a way to test it out?
> 
> No, but please rewrite the commit message. The `QUIT` command is not redundant, but not used, obsolete. Thanks!

I have updated the message to say obsolete. Thanks!

**Comment by kittaakos** [comment]
> I have updated the message

Thank you, I mean the commit message: https://github.com/eclipse-theia/theia/pull/7378/commits/ff85c66bfdfb3ca2d6ccf2c812d3e631f81785c9
Not the message of the PR.

**Comment by anir1ghosh** [comment]
> Thank you for the cleanup, @anir1ghosh! +1
> 
> I will merge the changes once the builds are green.

Thanks a lot for reviewing :)

**Pull request merged**
