### PR TITLE
Set electron dialogs to modal by default

### PR DESCRIPTION
**Pull request by zole40**
#### What it does

I found regression in related to the electron dialogs https://github.com/eclipse-theia/theia/issues/13042
#### How to test
1. Build the electron example
2. Run electron example 
3. Go to the file menu and click on the open folder

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by AlexandraBuzila — COMMENTED** [review]
Hi @zole40! Thank you for the fix, it works as expected :+1: 

However, I think it would be better if the `modal` prop was already initialized in the `toOpenDialogOptions` and `toSaveDialogOptions` from the [ElectronFileDialogService](https://github.com/eclipse-theia/theia/blob/f33547ef9e2521b5a7e3507badaaf34b35da5d70/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts#L102-L157), together with the other dialog options.

**Comment by zole40** [comment]
> Hi @zole40! Thank you for the fix, it works as expected 👍
> 
> However, I think it would be better if the `modal` prop was already initialized in the `toOpenDialogOptions` and `toSaveDialogOptions` from the [ElectronFileDialogService](https://github.com/eclipse-theia/theia/blob/f33547ef9e2521b5a7e3507badaaf34b35da5d70/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts#L102-L157), together with the other dialog options.

Should we set a default value if it is undefined?
For example: `result.modal = props.modal ?? true;`

**Comment by AlexandraBuzila** [comment]
> Should we set a default value if it is undefined? For example: `result.modal = props.modal ?? true;`

Yes, exactly. That would ensure that the options already have the default value for the `modal` prop when it is checked in `electron-api-main.ts`

**Review by AlexandraBuzila — APPROVED** [review]
Thank you, it looks good to me! 

@JonasHelming could you have a look as well, please?

**Review by tsmaeder — APPROVED** [review]

**Pull request merged**
