### PR TITLE
Bumped nsfw to 1.2.9

### LINKED ISSUE #6315: [Fylesystem] Renaming a file on windows generates the wrong event
### Description
 
When a file or a folder is renamed on Windows, [I would expect Theia to generate 2 events, 1 for the file getting deleted and another one for the file getting created](https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-watcher.ts#L122). This doesn't happen, due to [an unexpected behaviour of`nsfw`](https://github.com/Axosoft/nsfw/issues/26).

### Reproduction Steps

On Windows, try to rename a file that is watched by `NsfwFileSystemWatcherServer`. When doing that 2 events are generated by `nsfw`, one for the renamed file with type RENAMED'containing both the old path and the new path and another one with type CREATED for the deleted file. The second event is then merged with the events generated for the file renaming according to the rule [DELETED + ADDED => UPDATED](https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/node/file-change-collection.ts#L29) and the result is the old file being described as UPDATED instead of DELETED.

I think this is a bug in `nsfw`, but it begs the question, do you fillit might be appropriate to address this in Theia?

**OS and Theia version:**

Seen on Windows 10, with the latest Theia version (master). 

**Diagnostics:**

### PR DESCRIPTION
**Pull request by federicobozzini**
#### What it does

It bumps nsfw version to 1.2.9.

This fixes #6315 . It should also help with #7510 since the napi changes that were breaking the build are not included in this release.

#### How to test

As for #6315 just moving a file on Windows should now fire the correct events.

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Hi,

I am unable to reproduce on Ubuntu 18.04, using the suggested `theia-apps` application. I notice that it's already pulling `nsfw@1.2.9`

Probably doesn't hurt to bump the `nsfw` dependency version though. I do not have a Windows machine to test the bug specific to that platform.

**Comment by marcdumais-work** [comment]
@federicobozzini have you gone through our 3rd party dependencies [license check process](https://github.com/eclipse-theia/theia/wiki/Registering-CQs#wip---new-ecd-theia-intellectual-property-clearance-approach-experimental) to confirm that everything recursively pulled along the new version of `nsfw` is still ok for the Foundation, license-wise? 

If not can you give it a try? I can help if you have questions.

**Comment by benoitf** [comment]
by default it's specified `^1.2.2` so it will resolve to `1.2.9` if you drop yarn.lock

**Comment by federicobozzini** [comment]
@marcdumais-work 

>@federicobozzini have you gone through our 3rd party dependencies license check process to confirm that everything recursively pulled along the new version of nsfw is still ok for the Foundation, license-wise?

There are no new dependency as far as I can tell. With this PR `nsfw` version bumps to 1.2.9. and as a consequence a few unused recursive dependencies are dropped. That's all.

**Comment by marcdumais-work** [comment]
> There are no new dependency as far as I can tell. With this PR `nsfw` version bumps to 1.2.9. and as a consequence a few unused recursive dependencies are dropped. That's all.

A new version of any production dependency is enough to trigger the need for the license check

**Comment by vince-fugnitto** [comment]
> > There are no new dependency as far as I can tell. With this PR `nsfw` version bumps to 1.2.9. and as a consequence a few unused recursive dependencies are dropped. That's all.
> 
> A new version of any production dependency is enough to trigger the need for the license check

I did a quick verification regarding the license check for the updated version following the steps as described [here](https://github.com/eclipse-theia/theia/wiki/Registering-CQs#howto), and it looks fine :)

**Comment by marcdumais-work** [comment]
> by default it's specified `^1.2.2` so it will resolve to `1.2.9` if you drop yarn.lock

So, just playing devil's advocate: since a new ok `v1.2.x` that works has been released, that will be picked-up by clients with no `yarn.lock`, do we still need this PR?

**Comment by akosyakov** [comment]
> So, just playing devil's advocate: since a new ok v1.2.x that works has been released, that will be picked-up by clients with no yarn.lock, do we still need this PR?

Yes, we need to test the latest nsfw by us.

**Comment by akosyakov** [comment]
merging or anything else has to be resovled?

**Comment by marcdumais-work** [comment]
> merging or anything else has to be resovled?

Good from my side :+1:

**Pull request merged**
