### PR TITLE
Exposed the metadata scanner to the API.

### PR DESCRIPTION
**Pull request by kittaakos**
So extensions developer can subclass the hoster plugin reader.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does

Sets the `MetadataScanner` (`scanner`) visibility from `private` to `protected`.

#### How to test

Review the change set on GH.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
I found another issue with the `HosterPluginReader`. It implements the `BackendApplicationContribution` but no-one binds it, so subclasses cannot do much with `onStart`.

I fix this withing this PR.

**Comment by benoitf** [comment]
would be interesting to know why you need to subclass ?

**Comment by kittaakos** [comment]
> would be interesting to know why you need to subclass ?

No secret: I am trying to add a schema on the fly to the redhat YAML VS Code extension without creating or modifying the user or workspace settings.

**Comment by benoitf** [comment]
You may use another VS Code extension like

https://github.com/Azure/vscode-kubernetes-tools/blob/16ee367c0943097abee7ad098f3907f9663ef8b8/src/yaml-support/yaml-schema.ts#L30-L36

**Pull request merged**
