### PR TITLE
Update filesystem.ts

### PR DESCRIPTION
**Pull request by JesterOrNot**
#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Sean Hellum seanhellum45@gmail.com

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@JesterOrNot thank you for your first contribution! 👍 

In general, before the changes can be accepted, the following would be required:
- clean the history
    - squash the commits into a single commit
- ensure that the commit has a proper [sign-off](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#sign-your-work) and that the [Eclipse ECA](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) is signed
    - it is the reason for the failed `eca` check
- [minor] describe the changes a little better in the commit title/message - `update filesystem.ts` is a little too generic, something like `fix documentation typo in filesystem.ts` would be more appropriate

**Comment by JesterOrNot** [comment]
How do I squash commits @vince-fugnitto

**Comment by vince-fugnitto** [comment]
> How do I squash commits @vince-fugnitto

In general, I use `git rebase -i` (git rebase interactive), but you may search online for how to squash commits (ex: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).

If you are having trouble, it is always possible to close the pull request and open another if you'd like.

**Comment by JesterOrNot** [comment]
How do I get this check to pass I added the signoff key as seen in my initial comment thing

**Comment by akosyakov** [comment]
Try:
```
git reset --soft origin/HEAD
git commit -m "your commit message" -s
```

First line remove all your commit but preserve changes. Second line create a new signed-off commit with your message.

**Comment by vince-fugnitto** [comment]
@JesterOrNot please let us know if you still require help :)

**Comment by vince-fugnitto** [comment]
@JesterOrNot thank you for the contribution, it has been handled in https://github.com/eclipse-theia/theia/pull/6745.
Please don't hesitate to contribute in the future :)

**Pull request closed without merging**
