### PR TITLE
chore(dogfooding in che): Fix theia dev environment in multiroot mode

### PR DESCRIPTION
**Pull request by sunix**
#### What it does
Fix path to theia sources in a Che dev environment

#### How to test
Run this devfile in Che. Making sure commands/tasks to build Theia works

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by azatsarynnyy — COMMENTED** [review]
Strange... I get an error:
`
Failed to run the workspace: "Plugins installation process failed. Error: Plugin brokering process for workspace workspaceonj8fho9dmq5lsf8 failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://codeready-codeready-workspaces-operator.apps.sandbox.x8i5.p1.openshiftapps.com/plugin-registry/v3/plugins/che-incubator/typescript/latest/meta.yaml': Downloading https://codeready-codeready-workspaces-operator.apps.sandbox.x8i5.p1.openshiftapps.com/plugin-registry/v3/plugins/che-incubator/typescript/latest/meta.yaml failed. Status code 404.
`
It's not related to the changes, of course. Don't we have typescript plug-in in DevSandbox's plug-in registry?

**Review by azatsarynnyy — APPROVED** [review]
Works well. Thanks for the fix!

**Comment by sunix** [comment]
@azatsarynnyy could you merge it ? looks like I don't have write access

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy could you merge it ? looks like I don't have write access

Sure. No problem.

**Pull request merged**
