### PR TITLE
Bump version of Xtermjs to 4.4.0

### PR DESCRIPTION
**Pull request by alexl0gan**
#### What it does
Bump version of Xtermjs to 4.4.0

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Alex Logan <Alex.Logan@arm.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
@alexl0gan How did you test that it does not introduce any regressions? Usually a contributor should feel in `How to test` explanation.

**Comment by varmanishant** [comment]
While doing `yarn`, I found a minor problem in my local:

The [leaveCallback ](https://github.com/ARMmbed/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/terminal/src/browser/terminal-linkmatcher.ts#L53-L55)function takes no args currently as per the [spec](https://xtermjs.org/docs/api/terminal/interfaces/ilinkmatcheroptions/#optional-leavecallback), but we are supplying a function with 2 args?
https://xtermjs.org/docs/api/terminal/interfaces/ilinkmatcheroptions/#type-declaration

Didn't you hit that?

**Comment by akosyakov** [comment]
@varmanishant Where is it used?

**Comment by varmanishant** [comment]
@akosyakov , I have hyperlinked the usage and specification. Pasting for clarity:

Usage:
https://github.com/ARMmbed/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/terminal/src/browser/terminal-linkmatcher.ts#L53-L55

Specification:
https://xtermjs.org/docs/api/terminal/interfaces/ilinkmatcheroptions/#optional-leavecallback

I think we need to remove the args? I got this error while doing a `yarn`, I think @alexl0gan should have got it as well?

**Comment by akosyakov** [comment]
args are not used, so you can remove them

**Comment by alexl0gan** [comment]
@varmanishant yes, just using `.fit()` would be better.

I didn't have any issues with yarn...

**Comment by akosyakov** [comment]
> @varmanishant yes, just using .fit() would be better.

@alexl0gan it was not about fit, but https://travis-ci.com/eclipse-theia/theia/jobs/288778200#L672

Would you be able to look at other build failures?

**Comment by varmanishant** [comment]
@alexl0gan and @akosyakov  ,Thanks, now it looks correct. I removed the comment regarding `fit`. In Theia we are actually subtracting the row/col before resizing. Since I don't know why that is done, it is better to use the equivalent API in this case. Otherwise `fit` would have been better!

**Comment by akosyakov** [comment]
@alexl0gan could you squash commits which fix issues in the original commit, please see https://github.com/eclipse-theia/theia/blob/master/doc/pull-requests.md#checklist-commit-history

thank you for fixing everything, it looks good now, but someone has to double check

@marcdumais-work Do you think it would be fine to merge after the next release?

**Comment by marcdumais-work** [comment]
> @marcdumais-work Do you think it would be fine to merge after the next release?

Yes, I think so. 

Has anyone done the dependencies [license check](https://github.com/eclipse-theia/theia/wiki/Registering-CQs#case-new-or-updated-npm-production-dependency) for this new dependency?

**Comment by akosyakov** [comment]
@marcdumais-work I don't think so

**Comment by varmanishant** [comment]
Looks like the new dependency `xterm-addon-fit` has come because `xterm.j`s has been split into various component for modularity. However,I will check if I can run what you have mentioned above over the weekend.

**Comment by marcdumais-work** [comment]
> However,I will check if I can run what you have mentioned above over the weekend.

Awesome, If you have any questions or are unsure about anything, please ping me.

**Comment by varmanishant** [comment]
@marcdumais-work , here is the `package-lock.json`:

```
{
  "name": "license-testing",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "xterm-addon-fit": {
      "version": "0.3.0",
      "resolved": "https://registry.yarnpkg.com/xterm-addon-fit/-/xterm-addon-fit-0.3.0.tgz",
      "integrity": "sha1-NBcQdBAn3p1kip+EQVoB3f275xU="
    }
  }
}

```

I dropped it to ClearlyDefined and it said MIT Licence which should be OK? It doesn't have any nested dependencies; but  there is a peer dependency `xterm.js` ... but I didn't consider that since it is an existing library. Please let me know if this is fine?

@akosyakov, once this is added I will add the `cursorWidth` feature.

**Comment by AndrienkoAleksandr** [comment]
Hello. I created CQ for xterm.js 4.4.0 and xterm-addon-fit 0.3.0:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21696
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21697

**Comment by AndrienkoAleksandr** [comment]
I tested a bit this pr, for me it looks not bad. I will continue testing in Monday.

**Comment by akosyakov** [comment]
@AndrienkoAleksandr we only need that someone checks that license is compatible with ours, Eclipse Foundation does not require CQs for prod dependencies for Theia project: https://github.com/eclipse-theia/theia/wiki/Registering-CQs#wip---new-ecd-theia-intellectual-property-clearance-approach-experimental

**Comment by marcdumais-work** [comment]
Hi @varmanishant 

> I dropped it to ClearlyDefined and it said MIT Licence which should be OK?

MIT [confirmed](https://github.com/xtermjs/xterm.js/blob/master/addons/xterm-addon-fit/LICENSE). I think we're good to go.

**Comment by akosyakov** [comment]
@alexl0gan Release is through. Could you rebase it? I will test it again and if everything is fine going to merge.

**Comment by akosyakov** [comment]
@alexl0gan please let me know if you have time, if not i can rebase this PR, it is good time to merge it to have the entire month for testing.

**Comment by alexl0gan** [comment]
@akosyakov just rebased

**Comment by akosyakov** [comment]
@alexl0gan thanks, but it does not compile 😬

**Comment by AndrienkoAleksandr** [comment]
Hello, I think we should appy to one more dependency:
https://dev.eclipse.org/ipzilla/show_bug.cgi  
xterm-addon-search 0.5.0

**Comment by AndrienkoAleksandr** [comment]
P.S.: it doesn't matter, but all CQ passed:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21696 
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21697
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21698

**Comment by akosyakov** [comment]
@AndrienkoAleksandr Could you finish the review and merge it if it looks good to you?

**Comment by akosyakov** [comment]
There seem to be regressions https://github.com/eclipse-theia/theia/issues/7304 If someone can have a look it would help.

**Comment by AndrienkoAleksandr** [comment]
> There seem to be regressions #7304 If someone can have a look it would help.

@akosyakov No it's regression after https://github.com/eclipse-theia/theia/pull/7179

**Pull request merged**
