### PR TITLE
Add missing DebugConsoleMode enum to vscode API

### PR DESCRIPTION
**Pull request by amiramw**
Signed-off-by: Amiram Wingarten <amiram.wingarten@sap.com>

#### What it does
Add missing DebugConsoleMode enum to vscode API

#### How to test
One can try to access `vscode.DebugConsoleMode` from vscode extension code. Before this change it was undefined. Now it works.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
The changes look good to me (I haven't tested however).
I understand that the changes only add the `enum` but do we also want to make use of similarly to vscode for compatibility: [startDebugging](https://github.com/microsoft/vscode/blob/437260c606ef0ea0404bf25be33d62629b6d2356/src/vs/workbench/api/common/extHostDebugService.ts#L296-L303).

**Comment by amiramw** [comment]
> The changes look good to me (I haven't tested however).
> I understand that the changes only add the `enum` but do we also want to make use of similarly to vscode for compatibility: [startDebugging](https://github.com/microsoft/vscode/blob/437260c606ef0ea0404bf25be33d62629b6d2356/src/vs/workbench/api/common/extHostDebugService.ts#L296-L303).

@vince-fugnitto maybe in a different PR? As far as I understand theia works with single repl and the task should be to support `Separate` option of the enum.

**Comment by vince-fugnitto** [comment]
> > The changes look good to me (I haven't tested however).
> > I understand that the changes only add the `enum` but do we also want to make use of similarly to vscode for compatibility: [startDebugging](https://github.com/microsoft/vscode/blob/437260c606ef0ea0404bf25be33d62629b6d2356/src/vs/workbench/api/common/extHostDebugService.ts#L296-L303).
> 
> @vince-fugnitto maybe in a different PR? As far as I understand theia works with single repl and the task should be to support `Separate` option of the enum.

I'm fine with that, do you mind opening an issue so we at least track supporting the options?

**Review by vince-fugnitto — APPROVED** [review]

**Comment by amiramw** [comment]
Opened separate issue: https://github.com/eclipse-theia/theia/issues/8518

**Pull request merged**
