### PR TITLE
Fix updating items in the quick-pick menu

### PR DESCRIPTION
**Pull request by vinokurig**
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

#### What it does

Rework the quick-input API to use the [`$createOrUpdate`](https://github.com/eclipse-theia/theia/blob/5c5b5ba0d7f03511fd714087d699b3e45c932932/packages/plugin-ext/src/main/browser/quick-open-main.ts#L197) method in the step of initialising the quick-pick instead of using a separate method [`$showCustomQuickPick`
](https://github.com/eclipse-theia/theia/blob/5c5b5ba0d7f03511fd714087d699b3e45c932932/packages/plugin-ext/src/main/browser/quick-open-main.ts#L300)
#### How to test

1. Clone and compile the test plugin: https://github.com/microsoft/vscode-extension-samples/tree/main/quickinput-sample
2. Start hosted plugin
3. Execute the `Quick Input Samples` from the command palette.
4. Try all the submenus, especially `quickOpen` as it is broken in master.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by azatsarynnyy — COMMENTED** [review]
I'm not sure if it's the right behavior, but when I'm choosing `quickOpen` I see
Screenshot from 2021-09-08 22-36-34

**Comment by vinokurig** [comment]
@azatsarynnyy 
This command works in the same way in vscode:
Screenshot 2021-09-09 at 08 47 32

**Comment by azatsarynnyy** [comment]
I see. Except `quickOpen`, it seems other commands work the same as in master branch.

**Review by azatsarynnyy — APPROVED** [review]

**Review by tsmaeder — APPROVED** [review]
The code changes look fine to me. As @azatsarynnyy has tested the changes, I'm fine with merging them.

**Pull request merged**
