### PR TITLE
Fix for secondary button text not visible in light theme

### PR DESCRIPTION
**Pull request by balajiv113**
Signed-off-by: Balaji V <kuttibalaji.v6@gmail.com>

#### What it does

Fixes the issue #9006

#### How to test

Follow the steps given in the issue

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] Check the changes in multiple themes
- [x] Check that there is no impact in Discussion UI (As this change was introduced as a part of  #8870)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@balajiv113 thank you for providing a fix for the styling, do you mind reverting the unnecessary changes (formatting) since it adds noise to the pull-request and makes it more difficult to review. Else, you can group the formatting changes in a secondary commit 👍

**Comment by balajiv113** [comment]
@vince-fugnitto Grouped the changes into 2 separate commits as mentioned.

**Review by vinokurig — APPROVED** [review]
Tested the scenario from the issue and Pull Requests comments. Works as expected. Thank you @balajiv113

**Comment by vince-fugnitto** [comment]
@balajiv113 do you mind rebasing the pull-request on the latest `master` (it should resolve the build errors).

**Comment by balajiv113** [comment]
@vince-fugnitto Re-based with current master 👍

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Re-based with current master 👍

Thank you for your contribution, and being responsive :)

**Pull request merged**
