### PR TITLE
GH-7909: Inline variable values in editor.

### LINKED ISSUE #7909: [monaco][debug] Inline variable values in source code
> Inline Debugger
Inline debugging an interesting and unique feature of IntelliJ IDEA. The inline debugger
displays the values of variables within the code, right next to the line where they were
used. Whenever the value of the variable changes, the inline debugger highlights it with a
different color. To check out the values, there’s no need to move to the Debug window or
hover over each variable one-by-one like with Eclipse and NetBeans

VS Code Ref: https://code.visualstudio.com/updates/v1_9#_inline-variable-values-in-source-code
> to show variable values inline in the source while stepping through the code

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #7909.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does

screencast 2020-05-28 16-41-24

#### How to test

 - Create a JS module, set a few breakpoints here and there, steps through your module, you can see the inline value decorations,
 - Start another debug session while the previous is up and running, you can see the value decorators get updated when you alter the active debug session,

screencast 2020-06-02 11-04-32

 - Terminate the debug session, decorators are removed.

screencast 2020-06-02 11-07-07

 - Also, close the editor you debug, but do not terminate the debug session. When you reopen the file, the inline value decorations are there.

screencast 2020-06-02 11-03-27

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
This PR is ready for the review/preview.

**Comment by kittaakos** [comment]
I am happy to drop [the fix](https://github.com/eclipse-theia/theia/pull/7921/commits/bd0dbfdb58ddf3588b7610414a226147f4b93f09) for #7918.

**Comment by akosyakov** [comment]
> I am happy to drop the fix for #7918.

I think this state does not belong to the widget, but `DebugConfigurationManager`. Could we rather implement it there, i.e. store when the current is changed and read at proper time when current is accessed.

**Comment by kittaakos** [comment]
> I think this state does not belong to the widget, but `DebugConfigurationManager`. Otherwise there can be race conditions when proper current from the manager is ignored because there is state to restore in the widget. Could we rather implement it there, i.e. store when the current is changed and read at proper time when current is accessed. Maybe with another PR?

Sure. I hated to reset the desired launch config during the development, so that's why the messy fix.

Regarding the required changes; it is a little bit tricky.  There is no clear event on the `DebugSessionManager` when were the configs loaded. First, we have a config for the current workspace root without any config (we make `initialized` resolve), then we have a preference change event and we populate the configs for the workspace root.

**Comment by akosyakov** [comment]
I meant we could preserve current in https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/debug-configuration-manager.ts and restore it on the initialization, i.e. on first `updateModels`.

**Comment by kittaakos** [comment]
> I meant we could preserve current in https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/debug-configuration-manager.ts and restore it on the initialization, i.e. on first `updateModels`.

Sure sure, I understood it, as we do for the editor navigation history. I will open a separate PR for that.

**Comment by kittaakos** [comment]
> The only question whether we need a CQ for copied code.

I am going to take care of it.

**Comment by kittaakos** [comment]
@marcdumais-work, can you please confirm whether we need a new CQ for this PR or not? Thank you!

https://github.com/eclipse-theia/theia/blob/9a29154e742c311c5d88c338509113579e3adc26/packages/debug/src/browser/model/debug-stack-frame.tsx#L99

https://github.com/eclipse-theia/theia/blob/9a29154e742c311c5d88c338509113579e3adc26/packages/debug/src/browser/editor/debug-inline-value-decorator.ts#L21

**Comment by marcdumais-work** [comment]
> @marcdumais-work, can you please confirm whether we need a new CQ for this PR or not? 

Hi @kittaakos ,

I believe so - AFAIK we've never requested these files examined for "forking" (CQ type B). Please use links to the upstream vscode repo when opening the CQ.

**Comment by marcdumais-work** [comment]
Also, please add the Microsoft copyright header in file: `debug-stack-frame.tsx` like you did for the other file.

**Comment by kittaakos** [comment]
> Also, please add the Microsoft copyright header in file: `debug-stack-frame.tsx` like you did for the other file.

Good point, thanks!

**Comment by kittaakos** [comment]
CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22247

**Comment by marcdumais-work** [comment]
I gave this PR a quick try on Gitpod. I installed `vscode-clangd` and `cdt-gdb-vscode` from the extensions view and used the test workspace and launch config from [here](https://github.com/eclipse-theia/theia-cpp-extensions/tree/master/examples/cpp-debug-workspace).

It worked nicely!

image

**Comment by kittaakos** [comment]
@marcdumais-work, how long does it usually take to get a CQ approved? I have seen an almost prompt approval (with  the `+` sign) on Bugzilla, but nothing has happened since then. The workflow state is the same. I do not have much experience with CQs 😕 could you please check whether [the one for this PR](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22247) is going in the good direction. Thank you!

**Comment by marcdumais-work** [comment]
> @marcdumais-work, how long does it usually take to get a CQ approved? I have seen an almost prompt approval (with the `+` sign) on Bugzilla, but nothing has happened since then. The workflow state is the same. I do not have much experience with CQs  could you please check whether [the one for this PR](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22247) is going in the good direction. Thank you!

The CQ above looks good - it has one approval so far from a PMC member. It has been opened 2 work days ago, so I'd give it a couple more, and then "ping" on the CQ itself if still unresolved.

**Comment by kittaakos** [comment]
@marcdumais-work, does it make sense to ask about the CQ on Bugzilla?

**Comment by marcdumais-work** [comment]
> @marcdumais-work, does it make sense to ask about the CQ on Bugzilla?

I am not sure that there is a better way. I remember @akosyakov having some success with pinging. Let me give it a try.

**Comment by akosyakov** [comment]
Maybe already vacation time 🌴

**Comment by kittaakos** [comment]
We have an [update](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22247#c7), I can see:

> You may proceed to check the content into the Eclipse repository.

And also

> We will perform a comprehensive analysis at a later date based on IP work queue.

Is it yes or no? 😕

**Comment by akosyakov** [comment]
We can merge when CQ has `checkin`.  It does, so you can proceed!

**Comment by kittaakos** [comment]
Thank you all for the help on this PR.

**Pull request merged**
