### PR TITLE
ui/ux: styling input validation

### LINKED ISSUE #12243: dialog: provide visual feedback for input validation
#### Feature Description:

The framework provides some nice input validation for the "search in workspace" and "preferences" views. The goal is to provide this experience for the `SingleTextInputDialog` as well for a consistent look and feel and better feedback.

For example:

image

### PR DESCRIPTION
**Pull request by vladarama**
#### What it does

This PR fixes #12243 by providing visual feedback for input validation that is consistent with the input validation in the `search-in-workspace` and the `preferences` views. It adds this input validation for the `SingleTextInputDialog` to create better feedback for the user.

#### How to test

1. Try causing an error when renaming a file
2. Try causing an error when creating a file from the workspace using `New File`
3. Try causing an error when creating a new folder from the workspace using `New Folder`
4. Try causing an error when editing key bindings using `File` -> `Preferences` -> `Keyboard Shortcuts`
5. The error styling should be consistent with the one in `Preferences` and `search-in-workspace`

Preferences Error Validation: 
MicrosoftTeams-image

Easy errors to test include: creating a file/folder with no name or a duplicate name, renaming a file to the same name, creating empty key bindings ...

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
I think we should align with vscode regarding the styling of the validation marker:

image

We need to adjust this:

```css
.theia-settings-container .theia-input[type="number"]:focus {
  outline-width: 1px;
}
.dialogContent .error:not(:empty),
.theia-settings-container .pref-content-container .pref-input .pref-input-container .pref-error-notification {
  border-width: 1px;
}
```

**Comment by vladarama** [comment]
Thanks for the feedback Mark, aligning the styling with VS Code makes it look a lot cleaner.

**Review by msujew — APPROVED** [review]
Looks good to me 👍

**Comment by kittaakos** [comment]
Hello, please mention such a breaking modification in the changelog next time. Thanks for the great work!

**Pull request merged**
