### PR TITLE
[git] update to latest dugite-extra, dugite-no-gpl

### PR DESCRIPTION
**Pull request by marcdumais-work**
#### What it does

This PR updates `@theia/git` to consume the latest `dugite-extra`, which in turn uses the latest, recently uplifted `dugite-no-gpl`. The later is a fork of upstream `dugite` _(minus GPL-licensed git binaries added at install time)_, that had not been updated in nearly 3 years. 

Update: investigating a `@theia/git` unit test failure (see below), I noticed we needed to update `@theia/git` -> `git-model` -> `GitError enum` to match dugite-no-gpl, that had evolved since the last uplift. See commit message for more details.

#### How to test

Make sure the unit tests pass. Some manual testing of theia git extension would probably be a good idea to make sure nothing was broken.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
We have a unit test failure in @theia/git, that I will address by addding a commit: 

```
 @theia/git:   1) git
@theia/git:        ls-files
@theia/git:          errorUnmatched - ../outside.txt should not exist:
@theia/git:      Uncaught GitError: This path is not a valid path inside the repository.
@theia/git:       at new GitError (D:\a\theia\theia\node_modules\dugite-extra\lib\core\git.js:91:28)
@theia/git:       at D:\a\theia\theia\node_modules\dugite-extra\lib\core\git.js:266:27
@theia/git:       at step (D:\a\theia\theia\node_modules\dugite-extra\lib\core\git.js:59:23)
@theia/git:       at Object.next (D:\a\theia\theia\node_modules\dugite-extra\lib\core\git.js:40:53)
@theia/git:       at fulfilled (D:\a\theia\theia\node_modules\dugite-extra\lib\core\git.js:31:58)
@theia/git:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
@theia/git: error Command failed with exit code 1.
@theia/git: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in '@theia/git'
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by marcdumais-work** [comment]
cc: @thegecko :  This is the PR that introduces the uplifted `dugite-no-gpl`, that I mentioned recently. Can someone in your team help review and test?

**Comment by thegecko** [comment]
cc @arekzaluski @mcgordonite could you check this please?

**Comment by marcdumais-work** [comment]
@vince-fugnitto I have rebased this PR on the latest master - thanks for volunteering to review it!

**Review by vince-fugnitto — APPROVED** [review]
LGTM :+1: 

I confirmed the following:

- [x] git decorations work as expected (added, modified, deleted)
- [x] `stage` works as expected
- [x] `stage all` works as expected
- [x] `unstage` works as expected
- [x] `unstage all` works as expected
- [x] `discard` works as expected
- [x] `discard all` works as expected
- [x] toggling `tree` vs `list` works as expected
- [x] correct git status in the statubar
- [x] `git diff` works as expected
- [x] switching repository in a multi-root workspace works as expected

**Pull request merged**
