### PR TITLE
[Workspace] Rename command resolves with FileStat

### LINKED ISSUE #12101: [workspace]: `file.rename` command should resolve with the file stat after the successful execution
When executing the `file.rename` command, the caller does not know if the command has been executed or not. Maybe the user has canceled the operation. Clients could use the command if the new file state is returned from the handler after the rename. Currently, it's not possible to reuse the command:

https://github.com/eclipse-theia/theia/blob/f925bdb18160ecdfebc77f7bba96660d24435e28/packages/workspace/src/browser/workspace-commands.ts#L302

### Feature Description:

Please return the file stat from the command handler when the operation is OK. Otherwise, `undefined`.

Pipe-dream: expose the rename operation like other workspace command handlers (delete, duplicate) to help Theia extensibility.

### PR DESCRIPTION
**Pull request by FernandoAscencio**
#### What it does
Closes #12101 
Rename command now resolves with `FileStatWithMetadata` on success and `undefined` when not.

#### How to test
The second commit includes changes for testing.
1. Start Theia
2. Right click the file to rename
3. Select `Test: File Rename` in the context menu
4. Check results are as expected.

image

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
cc @kittaakos

**Comment by kittaakos** [comment]
Thanks for the fix. I checked out 923cac4d7 and verified it with the electron example app.

> #### How to test
> The second commit includes changes for testing.
> 
> 1. Start Theia
> 2. Right click the file to rename
> 3. Select `Test: File Rename` in the context menu
> 4. Check results are as expected.
> 
> image

Interesting way to verify the changeset 🙃 I see the URI in the notification with 923cac4d7. I cannot reproduce the `undefined` counter-example, but this is expected.


https://user-images.githubusercontent.com/1405703/225058374-c9547c12-2ccd-4198-883c-722b654f6968.mp4

**Comment by kittaakos** [comment]
> The undefined example should happen when you cancel the name change.

Verified. Thank you!


https://user-images.githubusercontent.com/1405703/225410292-d5e61ca0-5071-4eda-b3d0-a632d03f17a4.mp4

**Comment by FernandoAscencio** [comment]
The testing commit has been dropped for merging.

**Review by vince-fugnitto — APPROVED** [review]
LGTM :+1: 

- [x] confirmed that the `rename` command works as expected for files and folders
- [x] confirmed that the stat is returned on successful renames

**Pull request merged**
