### PR TITLE
monaco: fix symbol icons

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes: https://github.com/eclipse-theia/theia/issues/11357.

The pull-request fixes the symbol icons for multiple views (outline, callhierarchy, treehierarchy) by re-using codicons similarly to vscode. Previously we used `svg` which were removed from our sources so we defaulted to an incorrect icon.

_outline_:

outline-fix

_call-hierarchy_:

call-hierarchy-fix

#### How to test

1. start the application
2. open multiple files, for each file opened confirm that the symbols in the outline-view for the file are correct
3. confirm that expanding/collapsing nodes in the outline view correctly display their symbols
4. confirm that the `call-hierarchy` symbols are correct

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Review by paul-marechal — APPROVED** [review]
I confirm that the proper icons are now displayed in the outline view!

**Review by colin-grant-work — APPROVED** [review]
The changes update to show the correct symbol icons for each symbol type in call hierarchy, outline, and breadcrumbs. 👍

**Comment by kittaakos** [comment]
This is great!

Out of curiosity, where's `--theia-sprite-y-offset` defined? I wanted to understand how it worked but could not find the CSS constant definition. Thanks for the help!

**Comment by kittaakos** [comment]
> It's likely that it is leftovers

Thank you so much for checking <3 I also thought this is/was leftover.

**Pull request merged**
