### PR TITLE
GH-5100: Update the menu if the frontend is ready.

### LINKED ISSUE #5100: [electron][menu][osx] The application menu is incomplete on app start up
I have to lose the focus from the browser window, then select it again to have all the desired menu items. For instance, see that `Download` and `Upload Files...` are missing unless the focus is lost and reset.

Sometimes, I have to select an item in the `Navigator` too; I do not know if it is related or not.

I did not try it on Windows and Linux.

electron-application-menu-osx

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #5100.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does
 - Forcefully sets the application menu once the frontend application is `ready`.

#### How to test

 - See details and corresponding screencast [here](https://github.com/eclipse-theia/theia/issues/5100#issue-442102469).

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

🌞

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by thegecko** [comment]
The code looks good to me, which desktop platforms does it need testing on?

**Comment by kittaakos** [comment]
> which desktop platforms does it need testing on?

I experienced #5100 on macOS only, I do not know if it is an issue on Windows/Linux or not. The dynamic menu item related change (#446) should affect all supported platforms.

**Comment by thegecko** [comment]
I see no issue on MacOS

**Comment by kittaakos** [comment]
> won't work though if commands should be enabled/disabled based on internal widget state

This. I will investigate VS Code's solution a bit more thoroughly.

> Also it flickers when I click in the editor on Ubuntu 16.04, doesn't do it on master :/

Thanks for the feedback. I will try how VS Code behaves on my Ubuntu image and will compare it with Theia. Perhaps, I have to add some debouncing logic.

**Comment by kittaakos** [comment]
@akosyakov, I have dropped the dynamic electron menu part.
@marechal-p, could you please review the PR again. I have changed the `window` argument to `electronWindow` based on your [feedback](https://github.com/eclipse-theia/theia/pull/5140#discussion_r283964697). Thank you!

**Pull request merged**
