### PR TITLE
3632-plugin-installation-progress-indication

### PR DESCRIPTION
**Pull request by danarad05**
Added progress notification when deploying plugin by id and notification if deployed successfully or not

Signed-off-by: Dan Arad <dan.arad@sap.com>

#### What it does
Fixes: #3632

#### How to test
1. deploy valid plugin-id: should result is deployed successfully message - i.e.:
start deploy:
image
deploy result:
image
(this notification of deploy result is closed after 5 secs automatically)

2. deploy invalid plugin-id:  should result if deploy failure message - i.e.:
start deploy:
image
deploy result:
image
(this notification of deploy result is closed after 5 secs automatically)

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by danarad05** [comment]
@vince-fugnitto could you assign a reviewer for this PR?
Thanks

**Review by azatsarynnyy — DISMISSED** [review]
I've tested that the issue https://github.com/eclipse-theia/theia/issues/3632 has been fixed. Now, the user can see the progress and result of deploying the plug-ins. Code-wise looks good to me. Thank you @danarad05 for working on it!

**Comment by EstherPerelman** [comment]
@msujew @vince-fugnitto and any available reviewer... I have rebased this PR and it's ready for recheck...

**Review by vince-fugnitto — COMMENTED** [review]
@EstherPerelman the pull-request works well for the most part, but in some cases it will not deploy a plugin and display an error which is too quick:

- [x] correctly deploys `vscode:extension/foxhoundn.synthax` with success message
- [x] correctly displays an error for an id such as `abcdefg`

But in the following case it will fail to deploy (which is correct) but will output a message that is too quick to read:

`vscode:extension/a.abc`

_Error_:

```
root INFO [a.abc]: trying to resolve latest version...
root ERROR Failed to resolve plugins from 'vscode:extension/a.abc' Error: Extension with id a.abc not found at https://open-vsx.org/api/-/query?extensionId=a.abc&includeAllVersions=true
    at OVSXClient.getAllVersions (/home/evinfug/workspaces/theia/dev-packages/ovsx-client/lib/ovsx-client.js:81:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OVSXClient.getLatestCompatibleExtensionVersion (/home/evinfug/workspaces/theia/dev-packages/ovsx-client/lib/ovsx-client.js:99:28)
    at async VSXExtensionResolver.resolve (/home/evinfug/workspaces/theia/packages/vsx-registry/lib/node/vsx-extension-resolver.js:53:27)
    at async PluginDeployerImpl.resolvePlugin (/home/evinfug/workspaces/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:239:13)
    at async /home/evinfug/workspaces/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:140:51
    at async Promise.all (index 0)
    at async PluginDeployerImpl.resolvePlugins (/home/evinfug/workspaces/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:138:13)
    at async PluginDeployerImpl.deployMultipleEntries (/home/evinfug/workspaces/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:101:24)
root INFO Deploy plugin entry took: 179.9 ms
```


_Video_:


https://user-images.githubusercontent.com/40359487/139678568-fdf2b4a2-28c2-475f-a7aa-0d4c2195f5ce.mp4

**Pull request closed without merging**
