### PR TITLE
manage cache lifetime explicitly

### PR DESCRIPTION
**Pull request by tsmaeder**
Signed-off-by: Thomas Mäder <tmader@redhat.com>

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@tsmaeder no need to look yet correct? If not please elaborate a bit in `What it does` section please 🙏

**Comment by tsmaeder** [comment]
It's a "counterproposal" to https://github.com/eclipse-theia/theia/pull/7536. I did it in 2 hours and can't guarantee I caught all the cases. Still would be interested in hearing your opinion on the approach. If you had a look at provided-tasks-configurations.ts, that would be useful.

**Comment by tsmaeder** [comment]
Looks like I inherited the job ;-) @akosyakov I'll get back to this within the next 2-3 weeks.

**Comment by akosyakov** [comment]
@tsmaeder ok, then I will look next week

**Comment by akosyakov** [comment]
I think it is somehow related to https://github.com/eclipse-theia/theia/pull/7670#issuecomment-621727390

We should rather remove caches and compute task map to resolve whenever a user wants to run or a VS Cod extension wants to fetch tasks. I think that's actually an effect of this PR it clean caches each such time, but then what is the point of a cache.

cc @RomanNikitenko @elaihau

**Comment by elaihau** [comment]
> I think it is somehow related to [#7670 (comment)](https://github.com/eclipse-theia/theia/pull/7670#issuecomment-621727390)
> 
> We should rather remove caches and compute task map to resolve whenever a user wants to run or a VS Code extension wants to fetch tasks. I think that's actually an effect of this PR it clean caches each such time, but then what is the point of a cache.

Yes I will put my work on hold until your recent changes and this PR get merged :)

**Pull request closed without merging**
