### PR TITLE
Do not show the Timeline panel if no Timeline providers were registered

### PR DESCRIPTION
**Pull request by vinokurig**
#### What it does

Check if a timeline provider is registered, before adding the `Timeline` panel to the `Explorer`. If no providers were registered, do not add the `Timeline` panel to the `Explorer`.
#### How to test

1. Close the `Explorer` (right mouse button click to the `Explorer` icon => close)
2. Open the `Explorer` (menu `View` => `Explorer`)

See: the `timeline` panel mustn't be present in the `Explorer` part.
#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vinokurig** [comment]
@akosyakov @westbury any updates on this?

**Review by azatsarynnyy — APPROVED** [review]
I have tested it - works as described. Thanks!

**Comment by vinokurig** [comment]
@akosyakov @westbury is it OK for you to merge?

**Comment by vinokurig** [comment]
I am going to merge it today, if there are no objections?

**Pull request merged**
