### PR TITLE
Fix tree text highlighting

### PR DESCRIPTION
**Pull request by justinang1**
Issue: #6919 

#### What it does

- Matches color of highlighted text when filtering within the explorer window & file dialog. 

#### How to test

- Filter by typing within the explorer window. To check File Dialog, select File -> Open Workspace, then attempt to type within the file viewer. 

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
Please pay attention to different trees in different themes during the review, not only to the navigator in the default theme.

**Comment by akosyakov** [comment]
@jbicker does not seem to be a committer on github anymore for this repo, although he is on the eclipse page, cc @marcdumais-work @eclipsewebmaster 

wanted to assign him as a reviewer

**Comment by kittaakos** [comment]
Nice, @justinang1 👍 

Dark Theme:

VS Code:
Screen Shot 2020-01-31 at 09 44 56

Theia
Screen Shot 2020-01-31 at 09 44 09

Theia (File Dialog):
Screen Shot 2020-01-31 at 09 39 42


-----

Light Theme:

VS Code:
Screen Shot 2020-01-31 at 09 47 58


Theia:
Screen Shot 2020-01-31 at 09 47 49


> not only to the navigator

It seems, only the navigator supports the search.
https://github.com/eclipse-theia/theia/blob/d7cf6ecc116d5f1f6c9fcfa326e65467e79a68c4/packages/navigator/src/browser/navigator-container.ts#L31

**Comment by marcdumais-work** [comment]
> @jbicker does not seem to be a committer on github anymore for this repo, although he is on the eclipse page, cc @marcdumais-work @eclipsewebmaster
> 
> wanted to assign him as a reviewer

Confirmed - I do not see Jan in the members of `eclipse-theia` org. @jbicker there has been this type of issue with a few committers already. In at least one case the root cause was with the Eclipse Foundation sync script that keeps the org membership in-sync with current committers. It might also be that the invite email was lost. e.g. in your spam folder. 

The simplest is for you to open a bugzilla about the issue. Start [here](https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community) and chose `GitHub` as component. Please keep us updated with the progress.

**Comment by marcdumais-work** [comment]
> @jbicker does not seem to be a committer on github anymore for this repo, although he is on the eclipse page, cc @marcdumais-work @eclipsewebmaster
> 
> wanted to assign him as a reviewer

FYI, Similar was just reported for a Red Hat committer:
https://github.com/orgs/eclipse-theia/teams/ecd-theia-committers/discussions/2

**Comment by jbicker** [comment]
Hi, 
@marcdumais-work: thank you for the help. I wasn't able to open the link to the discussion but I've already send a mail to @eclipsewebmaster anyways. It turned out that I had to add my GitHub ID to my Eclipse Account. So, I hope to get a new invitation from the eclipse sync tool to join the theia world again.

**Pull request merged**
