### PR TITLE
Issue-8310

### LINKED ISSUE #8310: Deprecated code completions crash
### Bug Description:

When providing code completion result with deprecated: true property there is an error on code completion and no suggestions are displayed.

### Steps to Reproduce:

[lsp-sample-deprecated.zip](https://github.com/eclipse-theia/theia/files/5028388/lsp-sample-deprecated.zip) contains the vscode extension source code for reference.
[vsix.zip](https://github.com/eclipse-theia/theia/files/5028409/vsix.zip) contains two vsix files lsp-sample-deprecated-item-1.0.0.vsix that provides deprecated code completion. It works on vscode but not on theia. The other one provide code completions without deprecated items and it work on both.

1. Deploy vscode extension lsp-sample-deprecated-item-1.0.0.vsix
2. Create empty text file
3. Try to do code completion.

Nothing works and the browser console shows this error:

Uncaught Error: Cannot read property 'Deprecated' of undefined

TypeError: Cannot read property 'Deprecated' of undefined
    at asCompletionItem (c:\Users\i066470\AppData\Local\Temp\vscode-unpacked\lsp-sample-deprecated-item-1.0.0.vsix\extension\client\node_modules\vscode-languageclient\lib\protocolConverter.js:244:50)
    at Array.map (<anonymous>)
    at asCompletionResult (c:\Users\i066470\AppData\Local\Temp\vscode-unpacked\lsp-sample-deprecated-item-1.0.0.vsix\extension\client\node_modules\vscode-languageclient\lib\protocolConverter.js:171:26)
    at http://localhost:3000/vs/editor/editor.main.js:1532:31

On VS code it works like this:

vsc

### Additional Information

- Operating System: windows, debian
- Theia Version: master

### LINKED ISSUE #8475: [vscode] css code completion doesn't work - Cannot read property 'Deprecated' of undefined
### Bug Description:
There are no completion results when working on css file.

### Steps to Reproduce:

1. Create an empty css file.
2. Hit ctrl + space.  

There are no results:
css-theia

In addition the following error appears in browser console:
```
TypeError: Cannot read property 'Deprecated' of undefined
    at y (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163850)
    at c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163962
    at C (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163998)
    at Array.map (<anonymous>)
    at asCompletionResult (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:170409)
    at http://localhost:3000/vs/editor/editor.main.js:1607:31
```

vscode:
css-vscode

### Additional Information

- Operating System: Windows 10
- Theia Version: master

### PR DESCRIPTION
**Pull request by esterw1109**
Issue-8310: Deprecated code completions crash
Signed-off-by: Esther Perelman <wwr1109@gmail.com>

#### What it does

Fixes #8310 
Fixes #8475

#### How to test
Steps to reproduce on #8310 

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by danidoedel** [comment]
I guess #8475 is related and this change will fix it as well?

**Review by vince-fugnitto — COMMENTED** [review]
Thank you for your contribution @esterw1109 :+1: 
Please be sure to [sign-off](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#sign-your-work) your commit so we can accept the changes (it is necessary for the eca check).

**Comment by esterw1109** [comment]
> Thank you for your contribution @esterw1109 👍
> Please be sure to [sign-off](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#sign-your-work) your commit so we can accept the changes (it is necessary for the eca check).

I have signed-off my commit but it's still has an error, What can it be?

**Comment by amiramw** [comment]
> > Thank you for your contribution @esterw1109 👍
> > Please be sure to [sign-off](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#sign-your-work) your commit so we can accept the changes (it is necessary for the eca check).
> 
> I have signed-off my commit but it's still has an error, What can it be?

https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by vince-fugnitto** [comment]
@esterw1109 I see that you have signed-off your commit and your ECA is valid:

image

The issue is that your authorship email does not match your sign-off (`git log`):

```
commit c40abaef09b0095bffd89a05d4e125abf1a2bb5f (HEAD -> esterw1109-8310-Deprecated-code-completions-crash)
Author: Esther Perelman <34027100+esterw1109@users.noreply.github.com>
Date:   Thu Sep 17 13:23:10 2020 +0300

    Issue-8310
    
    Issue-8310: Deprecated code completions crash
    Signed-off-by: Esther Perelman <wwr1109@gmail.com>

```

**Comment by esterw1109** [comment]
@vince-fugnitto Thanks! That was the problem I changed my author-email and recreate a PR on #8517

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Thanks! That was the problem I changed my author-email and recreate a PR on #8517
> Should I close current PR?

I'll close it for you, thank you for providing the fix :+1:

**Pull request closed without merging**
