### PR TITLE
Add `index` to unstage command

### LINKED ISSUE #11633: Git/SCM - Unstage resets all files!
### Bug Description:

Unsure if this is a problem with git or scm, but if you are working and stage some files.  If you use the GUI to stage and then unstage (the minus button that says "Unstange Changes"), it will in fact reset all modified files.

Not just the one file.  Poof, all your work gone.

Also, 'unstage all' does the same thing.

### Steps to Reproduce:

1. make changes in a git repo
2. stage a file
3. unstage file

All modified files are reset.  If the file you unstage is new, it will also be gone.

### Additional Information

- Operating System: Linux ee15-1--web-584c4b74bb-9qfft 5.10.0-14-cloud-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
- Theia Version: 1.29.0

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #11633

#### How to test

1. Open a Git repository.
2. Modify several files.
3. Stage one or more of them.
4. Unstage one of the staged files using the SCM UI.
5. That single file should be unstaged, other staged files should remain staged, and the content of no file should be changed.
---
1. Try commands in the SCM widget at different levels (Resource Group, Folder)
2. Confirm that they behave as expected.

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by jaredkipe** [comment]
I could be wrong, but there are multiple `this.git.unstage(repository, uris)` calls in the file that seem like they may benefit from this solution.   I tried patching the file in Docker but I was unsuccessful without just reverting the library itself.  So I cannot 'review' it as working.

**Comment by vince-fugnitto** [comment]
> I could be wrong, but there are multiple this.git.unstage(repository, uris) calls in the file that seem like they may benefit from this solution.

@jaredkipe there is only one other `git.unstage` call I can identify and it correctly uses the default `all` option to `unstage all`:

https://github.com/eclipse-theia/theia/blob/a07b74644372ebc6c5f04e153bd7d8607a5afc5c/packages/git/src/browser/git-scm-provider.ts#L318-L326

**Review by vince-fugnitto — APPROVED** [review]
I confirm it works as expected 👍 I'll give @msujew a chance to review as well.

**Review by msujew — APPROVED** [review]
Looks good to me 👍 I can confirm that the issue exists on `master` and is addressed by this change.

**Pull request merged**
