### PR TITLE
[output]: Made editor and model factory customizable

### PR DESCRIPTION
**Pull request by kittaakos**
#### What it does

Made editor and model factory customizable so that extenders can customize and rebind the factories of the  _Output_.

#### How to test

No behavioral changes are expected.

- After a successful build, 
- Open IDE,
- Execute the `Toggle Output View` command,
- Select the `API Sample: my test channel`,
- It works.

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — APPROVED** [review]
LGTM 👍

**Comment by paul-marechal** [comment]
What's preventing someone from doing the following?

```ts
export class MyOutputEditorFactory extends OutputEditorFactory { ... }
// ...
rebind(MonacoEditorFactory).to(MyOutputEditorFactory).inSingletonScope();
```

**Comment by kittaakos** [comment]
> What's preventing someone from doing the following?

Ingenious workaround for the time being. Thank you!


----

As an extension developer, I expect to `rebind` the `OutputEditorFactory` when I want to customize the `OutputEditorFactory` in Theia.

**Comment by kittaakos** [comment]
Hi, is there anything blocking this PR? Thank you!

**Comment by msujew** [comment]
@paul-marechal Are you fine with seeing this merged? I don't see anything blocking this PR.

**Comment by paul-marechal** [comment]
Note that I wasn't blocking the PR either, I'll make sure to use `Request Changes` if I were to do so :)

On the other hand I don't think it's critical, but I can't help but think over-binding things to be a code smell. With dependency injection we should handle abstractions, not concretions/implementations.

**Pull request merged**
