### PR TITLE
GH-1614, GH-4532: Various dev experience enhancements for win32

### LINKED ISSUE #1614: Possible improvements in the Windows building documentation
I just tried to build Theia in a windows 10 developer vbox image and following the steps [here](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#building-on-windows) to build it several steps failed. 

`choco install yarn --version 1.2.1 -y` Failed because we already installed a later version (1.5.0) at the time of this writing beforehand. But I also wondered if you couldn't install this one directly without doing that `choco install yarn` command before.

Also I noticed that we use both `cmd/Powershell/Git bash` just to build and run theia according to the docs. Maybe there's a good reason for using git bash but If possible I would like to avoid having that dependency in the documentation. It makes it so that new developers have to *possibly* install another program before running it. @kittaakos I know you tested a lof of stuff of Windows, so probably there's a valid reason for this (I just tried `yarn` in powershell and it didn't work and resulted in weird errors...).

### LINKED ISSUE #4532: [dev-experience][windows] Investigate whether we can enable parallel execution with Lerna
Due to deadlock issues, we have explicitly disabled the parallel (`lerna`) execution on Windows.

https://github.com/theia-ide/theia/blob/f5cec4444315651c1c583f740adcfeb6bef5a33f/scripts/lerna.js#L24

This is a pain for Windows users. Check whether we can re-enable the parallel execution. It might require bumping up the `lerna` version.

### PR DESCRIPTION
**Pull request by kittaakos**
#### What it does

 - Enables parallel `lerna` execution on Windows (closes #4532),
 - [Fixes](https://github.com/eclipse-theia/theia/pull/6893#issuecomment-575622816) the exclusion path for the circular dependency check on Windows,
 - Brings the Windows dev steps up to date (closes #1614).

Please read the individual commit messages for more details or ask. 

#### How to test

The CI should test it.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
> * Fixes the exclusion path

See, no more `node_modules`.

[Before](https://api.travis-ci.com/v3/job/276172066/log.txt):
```
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\inversify\lib\syntax\binding_on_syntax.js -> ..\..\node_modules\inversify\lib\syntax\binding_when_syntax.js -> ..\..\node_modules\inversify\lib\syntax\binding_on_syntax.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\inversify\lib\syntax\binding_when_syntax.js -> ..\..\node_modules\inversify\lib\syntax\binding_on_syntax.js -> ..\..\node_modules\inversify\lib\syntax\binding_when_syntax.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\monaco-languageclient\lib\vscode-api.js -> ..\..\node_modules\monaco-languageclient\lib\vscode-compatibility.js -> ..\..\node_modules\monaco-languageclient\lib\vscode-api.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\monaco-languageclient\lib\vscode-compatibility.js -> ..\..\node_modules\monaco-languageclient\lib\vscode-api.js -> ..\..\node_modules\monaco-languageclient\lib\vscode-compatibility.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\react-virtualized\dist\es\Grid\types.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\utils\ScalingCellSizeAndPositionManager.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\utils\CellSizeAndPositionManager.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\types.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\react-virtualized\dist\es\Grid\utils\CellSizeAndPositionManager.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\types.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\utils\ScalingCellSizeAndPositionManager.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\utils\CellSizeAndPositionManager.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\react-virtualized\dist\es\Grid\utils\ScalingCellSizeAndPositionManager.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\utils\CellSizeAndPositionManager.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\types.js -> ..\..\node_modules\react-virtualized\dist\es\Grid\utils\ScalingCellSizeAndPositionManager.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\react-virtualized\dist\es\WindowScroller\WindowScroller.js -> ..\..\node_modules\react-virtualized\dist\es\WindowScroller\utils\onScroll.js -> ..\..\node_modules\react-virtualized\dist\es\WindowScroller\WindowScroller.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\react-virtualized\dist\es\WindowScroller\utils\onScroll.js -> ..\..\node_modules\react-virtualized\dist\es\WindowScroller\WindowScroller.js -> ..\..\node_modules\react-virtualized\dist\es\WindowScroller\utils\onScroll.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\xterm\lib\Buffer.js -> ..\..\node_modules\xterm\lib\BufferLine.js -> ..\..\node_modules\xterm\lib\Buffer.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\xterm\lib\BufferLine.js -> ..\..\node_modules\xterm\lib\Buffer.js -> ..\..\node_modules\xterm\lib\BufferLine.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\quick-open\index.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-service.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\quick-view-service.js -> ..\..\packages\core\lib\browser\quick-open\index.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\quick-view-service.js -> ..\..\packages\core\lib\browser\quick-open\index.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-service.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\quick-open\quick-command-service.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\quick-view-service.js -> ..\..\packages\core\lib\browser\quick-open\index.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-service.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\quick-view-service.js -> ..\..\packages\core\lib\browser\quick-open\index.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-service.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\quick-view-service.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\tree\tree-widget-selection.js -> ..\..\packages\core\lib\browser\tree\tree-widget.js -> ..\..\packages\core\lib\browser\tree\tree-widget-selection.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\tree\tree-widget.js -> ..\..\packages\core\lib\browser\tree\tree-widget-selection.js -> ..\..\packages\core\lib\browser\tree\tree-widget.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\debug\lib\browser\debug-frontend-application-contribution.js -> ..\..\packages\debug\lib\browser\view\debug-widget.js -> ..\..\packages\debug\lib\browser\view\debug-configuration-widget.js -> ..\..\packages\debug\lib\browser\debug-frontend-application-contribution.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\debug\lib\browser\view\debug-configuration-widget.js -> ..\..\packages\debug\lib\browser\debug-frontend-application-contribution.js -> ..\..\packages\debug\lib\browser\view\debug-widget.js -> ..\..\packages\debug\lib\browser\view\debug-configuration-widget.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\debug\lib\browser\view\debug-widget.js -> ..\..\packages\debug\lib\browser\view\debug-configuration-widget.js -> ..\..\packages\debug\lib\browser\debug-frontend-application-contribution.js -> ..\..\packages\debug\lib\browser\view\debug-widget.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js -> ..\..\packages\plugin-ext\lib\main\browser\main-context.js -> ..\..\packages\plugin-ext\lib\main\browser\webviews-main.js -> ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\plugin-ext\lib\main\browser\debug\debug-main.js -> ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js -> ..\..\packages\plugin-ext\lib\main\browser\main-context.js -> ..\..\packages\plugin-ext\lib\main\browser\debug\debug-main.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\plugin-ext\lib\main\browser\main-context.js -> ..\..\packages\plugin-ext\lib\main\browser\webviews-main.js -> ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js -> ..\..\packages\plugin-ext\lib\main\browser\main-context.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\packages\plugin-ext\lib\main\browser\webviews-main.js -> ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js -> ..\..\packages\plugin-ext\lib\main\browser\main-context.js -> ..\..\packages\plugin-ext\lib\main\browser\webviews-main.js
```

[After](https://api.travis-ci.com/v3/job/276200144/log.txt):
```
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\quick-open\index.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-service.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\quick-view-service.js -> ..\..\packages\core\lib\browser\quick-open\index.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\quick-view-service.js -> ..\..\packages\core\lib\browser\quick-open\index.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-service.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\quick-open\quick-command-service.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\quick-view-service.js -> ..\..\packages\core\lib\browser\quick-open\index.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-service.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\quick-view-service.js -> ..\..\packages\core\lib\browser\quick-open\index.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-service.js -> ..\..\packages\core\lib\browser\quick-open\quick-command-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\quick-view-service.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\tree\tree-widget-selection.js -> ..\..\packages\core\lib\browser\tree\tree-widget.js -> ..\..\packages\core\lib\browser\tree\tree-widget-selection.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\tree\tree-widget.js -> ..\..\packages\core\lib\browser\tree\tree-widget-selection.js -> ..\..\packages\core\lib\browser\tree\tree-widget.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\core\lib\browser\widget-open-handler.js -> ..\..\packages\core\lib\browser\shell\index.js -> ..\..\packages\core\lib\browser\shell\view-contribution.js -> ..\..\packages\core\lib\browser\common-frontend-contribution.js -> ..\..\packages\core\lib\browser\navigatable.js -> ..\..\packages\core\lib\browser\widget-open-handler.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\debug\lib\browser\debug-frontend-application-contribution.js -> ..\..\packages\debug\lib\browser\view\debug-widget.js -> ..\..\packages\debug\lib\browser\view\debug-configuration-widget.js -> ..\..\packages\debug\lib\browser\debug-frontend-application-contribution.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\debug\lib\browser\view\debug-configuration-widget.js -> ..\..\packages\debug\lib\browser\debug-frontend-application-contribution.js -> ..\..\packages\debug\lib\browser\view\debug-widget.js -> ..\..\packages\debug\lib\browser\view\debug-configuration-widget.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\debug\lib\browser\view\debug-widget.js -> ..\..\packages\debug\lib\browser\view\debug-configuration-widget.js -> ..\..\packages\debug\lib\browser\debug-frontend-application-contribution.js -> ..\..\packages\debug\lib\browser\view\debug-widget.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js -> ..\..\packages\plugin-ext\lib\main\browser\main-context.js -> ..\..\packages\plugin-ext\lib\main\browser\webviews-main.js -> ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\plugin-ext\lib\main\browser\debug\debug-main.js -> ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js -> ..\..\packages\plugin-ext\lib\main\browser\main-context.js -> ..\..\packages\plugin-ext\lib\main\browser\debug\debug-main.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\plugin-ext\lib\main\browser\main-context.js -> ..\..\packages\plugin-ext\lib\main\browser\webviews-main.js -> ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js -> ..\..\packages\plugin-ext\lib\main\browser\main-context.js
@theia/example-electron: WARNING in Circular dependency detected:
@theia/example-electron: ..\..\packages\plugin-ext\lib\main\browser\webviews-main.js -> ..\..\packages\plugin-ext\lib\hosted\browser\hosted-plugin.js -> ..\..\packages\plugin-ext\lib\main\browser\main-context.js -> ..\..\packages\plugin-ext\lib\main\browser\webviews-main.js
```

**Comment by vince-fugnitto** [comment]
Pinging @marechal-p since he has a Windows machine to test on :smiley:

**Comment by kittaakos** [comment]
By the way, here are some performance numbers for the build (`yarn`). I would say the speed up is insignificant on the CIs but looks much better on a local notebook with multiple cores:

 - CI build before: `Done in 750.73s`,
 - CI build after: `Done in 737.61s`,
 - Local build before: `Done in 446.32s`, and
 - Local build after: `Done in 322.80s`.

**Comment by marechal-p** [comment]
Ah, pinged Rob since I know Mbed Studio is an electron app on Windows, might not really impact him though. Feel free to wait or merge.

**Comment by thegecko** [comment]
Thanks @marechal-p We use a separate set of scripts to build, so this is unlikely to impact. Likely we can steal some of the ideas, though :)

Please go ahead and merge.

@westbury @mcgordonite Is there anything in here which can help with Windows build speed?

**Pull request merged**
