### PR TITLE
Authentication Plugin API fixes

### PR DESCRIPTION
**Pull request by vinokurig**
#### What it does

* Do not add a `sign out` menu if a session from given authentication provider is already exists in the authentication menu.
* Fix a bug of duplicating new session requests if more then one authentication session is present.
* Fix the sign out message if an authentication session is not stored in the account usages

#### How to test

1. Remove `"@theia/git": "^1.5.0"` from `examples/browser/package.json` file.
2. Download [vscode-git-1.49.3](https://open-vsx.org/api/vscode/git/1.49.3/file/vscode.git-1.49.3.vsix) and copy it to the `plugins` folder.
3. Download [vscode built-in github plugin](https://open-vsx.org/api/vscode/github/1.50.1/file/vscode.github-1.50.1.vsix) and copy it to the `plugins` folder.
4. Download [vscode GitHub Pull request plugin](https://github.com/microsoft/vscode-pull-request-github/releases/download/0.20.0/vscode-pull-request-github-0.20.0.vsix) and copy it to the `plugins` folder.
5. Apply GitHub authentication provider:
* Git clone the [github authentication plugin](https://github.com/vinokurig/github-authentication-plugin.git) to the `plugins` folder.
* Paste [your GitHub token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) to the plugin [here](https://github.com/vinokurig/github-authentication-plugin/blob/89b951d1a4280aee62635f5fa2b99feaf92aeacb/src/github-authentication-plugin.ts#L26).
* Compile the plugin. Note that errors might appear in the compilation log but it doesn't prevent the plugin from working properly.
6. Start Theia and check the accounts menu:
screenshot-serverg0cevid1-che-dev-server-3010 192 168 99 253 nip io-2020 09 23-11_42_23
7. Run `Publish to GitHub` command and allow the authentication session:
screenshot-localhost_3000-2020 11 06-12_41_49
8. Check the accounts menu:
screenshot-localhost_3000-2020 11 06-12_43_31
9. Sign in the GitHub Pull Requests plugin:
screenshot-newtab-2020 11 06-13_01_45
10.  Check the accounts menu and click the `sign out` item:
screenshot-localhost_3000-2020 11 06-13_03_24
11. See the notification: 
screenshot-localhost_3000-2020 11 06-13_05_29
12. Click `Yes` and check the accounts menu, it must reset to the initial state:
screenshot-serverg0cevid1-che-dev-server-3010 192 168 99 253 nip io-2020 09 23-11_42_23
#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by RomanNikitenko — APPROVED** [review]
Tested the changes - it works as described in the PR description:

github_auth

**Comment by RomanNikitenko** [comment]
btw: where it should be handled if a token is not valid?
I revoked my token to test such case:

revoke_token

bad_credentials

Maybe some notification should be displayed for user...
Is it responsibility of VS Code plugin or should be handled on `Theia` side?

**Comment by vinokurig** [comment]
@RomanNikitenko 
Thank you for your review. This use-case is handled by authentication provider which is registered in the [GitHub authentication plugin](https://github.com/vinokurig/github-authentication-plugin.git). This is a demo plugin for theia, in Che-theia we have our own [GitHub authentication provider plugin](https://github.com/eclipse/che-theia/tree/master/plugins/github-auth-plugin) which is using Che  oAuth API to retrieve tokens, instead of manually generating a token in GitHub. So even if we revoke the Che oAuth application in GitHub, the token would be stored in keycloak and would be valid for the GitHub plugins.

**Review by azatsarynnyy — COMMENTED** [review]
What the command `Publish to GitHub` does? Publish the repository? I can't find where it's contributed from.

BTW, after executing `Publish to GitHub` command, there's always running "Activating ..." message

Peek 2020-11-11 12-12

Is it expected?

**Comment by vinokurig** [comment]
@azatsarynnyy
> What the command `Publish to GitHub` does? Publish the repository? I can't find where it's contributed from.

`Publish to GitHub` comes from `github` built-in vscode extension and it creates a repository from the workspace folder, see https://stackoverflow.com/questions/46877667/how-to-add-a-new-project-to-github-using-vs-code
> BTW, after executing Publish to GitHub command, there's always running "Activating ..." message

It is expected, to make the GitHub Pull Requests plugin work you need to authenticate it separately, see item 9 of the **How to test** section.

**Review by azatsarynnyy — APPROVED** [review]
Thanks for the explanation @vinokurig 
Everything works as described.

**Pull request merged**
