### PR TITLE
Stub proposed APIs used by Python debugger

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Closes https://github.com/eclipse-theia/theia/issues/13881

Stubs the APIs listed in the [package.json](https://github.com/microsoft/vscode-python-debugger/blob/444cbb37b3c75fcdadf60787a079779571df7d19/package.json#L7-L11) of the vscode-python-debugger plugin.

#### How to test

1. Download and install the `Python` extension suite (that includes the `Python Debug` extension)
2. Open a Python file.
3. There should be no notification that the extension crashes during startup.
4. You could also test that debugging works as expected for a simple python file.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by rschnekenbu — APPROVED** [review]
That looks good to me, code wise and runtime wise. I could run the python debugger without any log messages.

**Comment by zoof** [comment]
Any idea when 1.52.0 is expected?  I'm anxious to try Theia but as it stands now, it's unusable.

**Comment by msujew** [comment]
Hey @zoof, we release a new version of the framework on every last Thursday of the month, so likely on the 25th. You can expect a new version of the Theia IDE a few days after that.

**Comment by zoof** [comment]
Wonderful, thank you!

**Pull request merged**
