### PR TITLE
Fix #9396: Can't access a resource file in vsix package from webview

### LINKED ISSUE #9396: can't acess a resource file in vsix package from vebview/custom editor, vscode no problem
I create a custom editor with webview, in javascript of it, require a properties file failed

the link of file like below
http://bf5b194a-acf2-4b21-b335-131801837208.webview.localhost:3000/webview/theia-resource/file///c%3A/Users/i062754/AppData/Local/Temp/vscode-unpacked/mck-wing-1.0.210219.vsix/extension/web/mck-editor/i18n/i18n_en.properties

the code like this
xhr.open("GET", url, true);
.....
xhr.send

the same vsix package work well on vscode, js and css seems no problem

### PR DESCRIPTION
**Pull request by EstherPerelman**
Signed-off-by: Esther Perelman <Esther.Perelman@sap.com>

#### What it does
Fixes #9396 

#### How to test
Example extension & instructions [here](https://github.com/eclipse-theia/theia/issues/9396#issuecomment-832429805)
#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by EstherPerelman** [comment]
@vince-fugnitto Can you review?

**Comment by EstherPerelman** [comment]
> why is the change necessary as it deviates from vscode:
> 
> https://github.com/microsoft/vscode/blob/a0ce27feda8fb46a1ef18a384483149cd0824895/src/vs/workbench/contrib/webview/browser/pre/service-worker.js#L326

Most of the changes that this is an issue with VSCode too (I ran vsCode web but it seems that extensions not working at all (can't install extension or search for one in the marketPlace)).

> can you describe why the change is necessary (there is no information in the commit message or pull-request description)

I wrote a comment on the code.., 
I'll try to explain:
Webview has iframe inside iframe, The service worker is created for the outer/parent iframe and also listen to the nested/child iframe
**On electron the webview service-worker clients urls are:** 
1. The parent with the url - `<webviewId>.<localhost>/theia-resource/webview/...**index.html**`, 
2. The child with the url - `<webviewId>.<localhost>/theia-resource/webview/...**fake.html**`, 
**On browser the webview service-worker clients urls are:** 
1. The parent with the url - `<webviewId>.<localhost>/theia-resource/webview/...**index.html**`, 
2. The child with the url - `<webviewId>.<localhost>/theia-resource/webview/...**index.html**`, 
The child iframe get it's parent url (a behavior of service-worker on browser)
On the `getOuterIframeClient` client is return if it ends with the `index.html` prefix which works for electron but not for browser
That's why I added a check to not return the child client itself...

**Comment by marechal-p** [comment]
@EstherPerelman next time please explain all of that in your commit message/pr description :)

Even if a change is small, we don't necessarily know why it is required or how it fixes the issue.

**Comment by EstherPerelman** [comment]
Hi @vince-fugnitto @marechal-p Who can approve this PR?

**Comment by vince-fugnitto** [comment]
> Hi @vince-fugnitto @marechal-p Who can approve this PR?

Please be a little patient, the pull-request was only opened a few days ago and there are many pull-requests currently under review. 

In addition cannot reproduce the issue on `master`, the example plugin works correctly for me on `electron` and `browser` (chrome and firefox).

_master_: firefox

image

_master_: chrome

image

_vscode_:

image

I'm not sure what I should be expecting in the webview, but it is the same result I see when running the extension in vscode.

**Comment by EstherPerelman** [comment]
> Please be a little patient, the pull-request was only opened a few days ago and there are many pull-requests currently under review.

You are right, We just having serious problem because of this bug so we need it as soon as possible...

> In addition cannot reproduce the issue on `master`, the example plugin works correctly for me on `electron` and `browser` (chrome and firefox).

I have no idea what the difference is, But `master` `chrome` gives me the next: (`i18n.properties` pending for 30000 seconds and then return an error) Besides it reproduced for another two besides me...
bug
 After 30000 seconds:
bug error

**Comment by vince-fugnitto** [comment]
> I have no idea what the difference is, But `master` `chrome` gives me the next: (`i18n.properties` pending for 30000 seconds and then return an error) Besides it reproduced for another two besides me

The `i18n.properties` request is fast for me, and works on `master` (`17 ms` after clicking the button - `status 200`):

image

**Comment by wangshen-sap** [comment]
still can be produced on newest master branch, 
nodejs version: v12.19.0
OS: windows 10
sync the newest master branch code and call yarn
run with "Lanch Browser Backend", and navigate to http://localhost:3000

image
image
image

**Comment by EstherPerelman** [comment]
@vince-fugnitto Thought the bug not reproduce for you - it still fixes our issue (also for @wangshen-sap [here](https://github.com/eclipse-theia/theia/pull/9464#issuecomment-844859500)) and do not attack the existing code, Might this be a good reason to merge it? (I can also think of the option that from some reason on your tests you get by chance the good frame from `getOuterFrame` because the order of client is different, But the issue still exists)
WDYS?

**Comment by EstherPerelman** [comment]
> I have been trying on `Linux`, is it perhaps related to `Windows`?
> 
> You may request that others try and review as well, or if it fixes your use-case perhaps you can include the change directly in your product.

Most likely it is related to Windows...
@colin-grant-work @marechal-p any reviewer?

**Comment by vince-fugnitto** [comment]
For additional information (if its related), I still get intermittent `404` errors with the changes (linux):

image

**Comment by EstherPerelman** [comment]
> For additional information (if its related), I still get intermittent `404` errors with the changes (linux):

@vince-fugnitto Getting `404` with this PR changes?
I have tested on windows master `firefox` and the problem **didn't** reproduce, After debugging I did found that as I thought - the order of clients in `getOuterIframeClient` was different from the testing with `chrome` that means that the parent/outer is the first in the `allClients` array so it returns the parent correctly, But if the order was different it would return the child instead of the parent because the both pass the condition, That's why the fix is needed to ensure client won't return..
Have a look at the `clientId` against `allClients` `id`s while debugging `firefox`:
sw

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Getting `404` with this PR changes?

Yes, I'm not sure if the pull-request is meant to fix such errors but I do sometimes get `404` errors with the changes  (Firefox):

image

**Comment by EstherPerelman** [comment]
> > @vince-fugnitto Getting `404` with this PR changes?
> 
> Yes, I'm not sure if the pull-request is meant to fix such errors but I do sometimes get `404` errors with the changes (Firefox):

@vince-fugnitto Does it happen without the changes too? If so - this is not the issue I focused here... (I would love to fix it but can't reproduce this `404` on `firefox`)

**Comment by PomanoB** [comment]
We have same issue and this change fixes "pending" status for font requests from css file

**Comment by EstherPerelman** [comment]
> We have same issue and this change fixes "pending" status for font requests from css file

Glad to see, so far no one reviewed this, Hope it will be approved soon.

**Review by wangshen-sap — APPROVED** [review]

**Comment by offer8** [comment]
@vince-fugnitto  I see this issue - https://github.com/eclipse-theia/theia/issues/7190 which already created more than 1 year ago.
Can this be related to the 404 you're also experiencing?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I see this issue - #7190 which already created more than 1 year ago.
> Can this be related to the 404 you're also experiencing?

Possibly, but the 404 was not the reason I was holding back the pull-request: https://github.com/eclipse-theia/theia/pull/9464#issuecomment-845163297.

**Comment by EstherPerelman** [comment]
Any reviewer?

**Comment by yannickowow** [comment]
I guess my issue was not related to this one (I guess?), but it is still related to VS Code vs Theia API.
It looks like an issue with `vscode.Uri.joinPath` implementation in Theia. My experiments are on Windows.

VS Code OK / Theia NOK
```ts
function getUri(webview: vscode.Webview, extensionUri: vscode.Uri, pathList: string[]) {
    return webview.asWebviewUri(vscode.Uri.joinPath(extensionUri.fsPath, ...pathList));
}
```

VS Code OK / Theia OK (Windows)
```ts
function getUri(webview: vscode.Webview, extensionUri: vscode.Uri, pathList: string[]) {
    return webview.asWebviewUri(vscode.Uri.file(win32.join(extensionUri.fsPath, ...pathList)));
}
```

Issue is located at `joinPath` or at least in the Uri implementation.
Uri returned with NOK implem.
`/webview/theia-resource/file///c:\c:\Users\username.theia\extensions\extensionName-0.0.1.vsix\extension\assets\vscode.css`
Uri returned with OK implem.
`/webview/theia-resource/file///c:/Users/username/.theia/extensions/extensionName-0.0.1.vsix/extension/assets/vscode.css`

**Comment by colin-grant-work** [comment]
> I guess my issue was not related to this one, but it is still related to VS Code vs Theia API. It looks like an issue with `vscode.Uri.joinPath` implementation in Theia. My experiments are on Windows.


@yannickowow, thanks for looking into the problem further. I've created [an issue](https://github.com/eclipse-theia/theia/issues/10370) to track what you're seeing, but it does indeed seem unrelated to the fix proposed here.

**Comment by vince-fugnitto** [comment]
Closing as the pull-request has been opened for some time without activity, or a clear and reproducible way to verify the problem on master. We can always re-open if problems re-occur and a reproducible bug is provided.

**Pull request closed without merging**
