### PR TITLE
Applies DOMSanitize.sanitize to innerHTML write

### PR DESCRIPTION
**Pull request by LukeWood**
This commit sanitizes the text applied to innerHTML of the linkNode
attribute on OpenUriCommandHandler.  This is an attempt to limit the
xss sink surface in Theia.

If there is no reason to do so or this breaks some intended behavior
please leave a comment indicating so.

Signed-off-by: Luke Wood <lukewood@google.com>

Change-Id: Ibee9829b3a44f87d15c9d46b9bc342332e5ccf08

#### What it does
sanitizes text assigned to innerHTML in an anchor element

#### How to test
This is not to address a specific bug - just a precaution.

### CODE REVIEW

**Comment by LukeWood** [comment]
just accepted CLA

**Comment by LukeWood** [comment]
Any update on this one?

**Review by vince-fugnitto — APPROVED** [review]
Sorry about the delay, I didn't get the notification 👍 
The changes look good to me, thank you for taking care of it!

**Review by vince-fugnitto — COMMENTED** [review]
@LukeWood can you include the `dompurify` dependency as part of `@theia/plugin-ext` (at the moment it is only provided by `@theia/preview`)? This will ensure that if a downstream app includes `@theia/plugin-ext` and not `@theia/preview` it will still work correctly.

**Comment by vince-fugnitto** [comment]
@LukeWood would you like me to take care of the outstanding issue https://github.com/eclipse-theia/theia/pull/8388#pullrequestreview-490041566 so it can be merged?

**Comment by LukeWood** [comment]
apologies - I didn't realize there were still outstanding issues.  If you could do that it would be great - I though I pushed a local copy but I must be mistaken

**Comment by vince-fugnitto** [comment]
> apologies - I didn't realize there were still outstanding issues. If you could do that it would be great - I though I pushed a local copy but I must be mistaken

No problem! I updated the pull-request to include the necessary dependencies in the `plugin-ext` extension. I'll wait for CI to pass and likely merge tomorrow morning.

**Pull request merged**
