### PR TITLE
eslint: update rules for 'theia.d.ts'

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

The following commit enables linting of the 'theia.d.ts' file which had many linting violation and caused issues during reviews. The code has also been fixed to meet linting rules, and should be fine for the future.

#### How to test

Verify that the build successfully passes, linting should be fixed for `theia.d.ts`.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by marechal-p** [comment]
Will this make contributing to this file harder whenever someone brings code over from VS Code?

**Comment by vince-fugnitto** [comment]
> Will this make contributing to this file harder whenever someone brings code over from VS Code?

It shouldn't, code that was copied was not properly formatted and now it should be enforced.

**Review by marechal-p — APPROVED** [review]
I see you also fixed typos, LGTM

**Comment by vince-fugnitto** [comment]
@benoitf @RomanNikitenko any objections to making `theia.d.ts` comply or follow eslint rules?

**Comment by benoitf** [comment]
@vince-fugnitto I saw the PR and I have no objection 👍  (I like it)

**Comment by vince-fugnitto** [comment]
I'll merge, there may be some errors from the file if others do not rebase their pull-requests (although I do not see many open pull-requests that affect `theia.d.ts`).

**Pull request merged**
