### PR TITLE
drop support for node 12

### PR DESCRIPTION
**Pull request by paul-marechal**
Keep supporting Node 14.x but recommend Node 16.x.

Closes https://github.com/eclipse-theia/theia/issues/10013

#### How to test

Nothing should have changed. Everything should work like before with Node 14 or Node 16.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by paul-marechal** [comment]
Related: https://github.com/eclipse-theia/theia/discussions/11198

**Comment by paul-marechal** [comment]
Turns out Node 18.x requires a glibc version greater than what's available on Ubuntu 18.04.

**Comment by vince-fugnitto** [comment]
We can probably close https://github.com/eclipse-theia/theia/issues/10013 thanks to the changes.

**Comment by paul-marechal** [comment]
Turns out Node 18.x uses `::1` as default address for its http servers now. This broke our test code by creating an invalid url.

I now explicitly set the default hostname to `localhost` in the `BackendApplication`.

**Comment by paul-marechal** [comment]
I dropped trying to test on Node 18, it will require more investigation to get working.

**Review by vince-fugnitto — APPROVED** [review]
LGTM :+1: The build and tests pass successfully.

**Review by msujew — APPROVED** [review]
Looks good to me as well 👍

**Pull request merged**
