### PR TITLE
[ip] pin jschardet to v1.6.0

### PR DESCRIPTION
**Pull request by marcdumais-work**
#### What it does

Our jschardet has been stepped to a new major version and we missed
it. Since this dependency is licensed under the LGPL, it requires a
special permission from the Eclipse Board, before we are allowed
to use a new version, as part of a release.

There is only a bit more than 2 weeks before our next release, and
I do not know when the next board meeting may happen. So it looks
like we might have to delay the release or momentarily go back to
the previous, approved, dependency version.

This is what this PR does, using a resolution.

CQ (need to be committer to see):
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22481

#### How to test

Check that CI passes and that the example application still works correctly.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
I have reached-out to Sharon to let her know about this, in addition to opening a CQ for the new dependency version (see description). It looks very tight to have the new dependency version Board-approved by the end of the month, but we'll see what she says.

**Comment by marcdumais-work** [comment]
This is not working. `jschardet@1.6.0` does not have TS typings, while the newer `2.1.1` does. 

I had assumed this was an update but it's a new use of `jschardet`, from `@theia/core`, that has never worked with older version. So more work would be needed to potentially make it work with v`1.6.0`. 

@akosyakov as far as you know, once we get pass the typing issue, would the older `jschardet` likely work, as used in the `encoding service`? 

@vince-fugnitto Can you watch what's happening with the CQ, and if it does not look that it will be approved in time for the August release, complete this PR and have it merged before release?

**Comment by marcdumais-work** [comment]
> I have reached-out to Sharon to let her know about this, in addition to opening a CQ for the new dependency version (see description). It looks very tight to have the new dependency version Board-approved by the end of the month, but we'll see what she says.

Good news: the previous Eclipse Board approval for our use of `jschardet` was not version-specific, so we're still covered as far as getting the required special permission to use/distribute a LGPL-license dependency. So only the normal license checks are necessary to make sure the license has not changed in the meantime, which I hope will be relatively quick.

**Comment by akosyakov** [comment]
> @akosyakov as far as you know, once we get pass the typing issue, would the older jschardet likely work, as used in the encoding service?

probably, we will need to test

**Pull request closed without merging**
