### PR TITLE
[vscode] semantic highlighting support

### LINKED ISSUE #7608: Activating extension rust-analyzer failed: vscode.languages.registerDocumentSemanticTokensProvider is not a function.
### Description

The rust-analyzer extension requires functions that are not yet implemented by Theia

### Reproduction Steps

Download rust-analyzer.vsix from https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-04-13

Copy it to the plugins folder in theia's git tree

Also download the `rust-analyzer-linux` binary and name it `rust-analyzer` and make sure it's in Theia's server process PATH variable

run: `$ yarn start:browser`

Open http://localhost:3000 in your browser

Open a rust project, e.g. `cargo init` in a folder

Or clone some Rust project such as: https://github.com/yewstack/yew

**OS and Theia version:**

a187f0141015f3e00e0844bec10dd9c97414b7ec
Fedora on ppc64le (architecture not relevant to the bug, don't worry)

**Diagnostics:** 

An error message appears on the bottom right:

"Activating extension rust-analyzer failed: vscode.languages.registerDocumentSemanticTokensProvider is not a function."

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #7608: porting VS Code support of  semantic highlighting
- [x] CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22677 (waiting for check-in approval)

#### How to test

- start theia
- open application-shell.ts
- observe how imports are colored before ts smartness is ready and after
  - you can see whether ts smartness initialization progress in the status bar
- open preferences side by side with the editor, find semantic highligting toggle, use it and see how highlighting is changing in the editor

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
There is more work to support proper styling based on themes.

**Comment by akosyakov** [comment]
It's turned out that it is required Monaco 0.21.0. Monaco 0.20.0 is not complete. I've patched the theming standalone service for now with fixed from 0.21.0. We should remove the patch after next migration.

**Review by JanKoehnlein — APPROVED** [review]
LGTM.

**Comment by kittaakos** [comment]
@akosyakov,
 - Do you know if the current changeset will be (fully) compatible with the [LSP-based semantic-highlighting](https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.semanticTokens.ts) out of the box once it's released? Or will that be available only with monaco `0.22.x` or `0.23.x`?
 - Can you please recommend another VS Code extension I could use to try out the new feature of this PR?
 - It seems the [formatter does not work correctly](https://github.com/eclipse-theia/theia/pull/8593/files#diff-c12f4cfff29006870b5f6654b73c2f8d) on your side. Please fix the indentations.

Thank you!

**Comment by dunnry** [comment]
The F# Ionide Extension uses this feature if you want to test it. @kittaakos

**Comment by JanKoehnlein** [comment]
So does the Java extension

**Comment by vince-fugnitto** [comment]
I believe the CQ has now been successfully approved :+1:

**Comment by akosyakov** [comment]
Could someone help with rebasing and merging it?

**Comment by azatsarynnyy** [comment]
I just wonder are we allowed to use the code in an Eclipse repo if the related CQ is still in `awaiting_analysis` state?
Does that mean it's approved?

**Comment by akosyakov** [comment]
We only need `checkin` tag as far as I know. cc @marcdumais-work

**Comment by vince-fugnitto** [comment]
> I just wonder are we allowed to use the code in an Eclipse repo if the related CQ is still in `awaiting_analysis` state?
> Does that mean it's approved?

@azatsarynnyy I know in the past we proceeded to merge pull-requests when they granted permission, namely the following:

> We have completed a high level triage of the attachment and you may now check the content into your project’s source code repository.

I believe at this point they will continue to verify the content (`awaiting_analysis`), and if an issue arises they will notify us.

**Comment by azatsarynnyy** [comment]
Thanks @vince-fugnitto for the explanation!

**Comment by vince-fugnitto** [comment]
@akosyakov do we want to merge for today's release?

**Comment by akosyakov** [comment]
@vince-fugnitto merge when it suites you

**Review by vince-fugnitto — APPROVED** [review]
I reviewed the changes and they work well :+1: 
I'll merge and if there are issues we have the month to resolve any of them.

**Pull request merged**
