### PR TITLE
Split off from git package the stuff provided by the git builtin plugin

### PR DESCRIPTION
**Pull request by westbury**
fixes https://github.com/eclipse-theia/theia/issues/7152

Currently when using the VS Code git builtin, all the extra stuff available in Theia is no longer available.  For example and 'amend' section disappears, as does the history view.

#### What it does

This PR solves that.  The Git contribution to the Source Control view is moved to another package.  This allows the git package to be used alongside the builtin.

#### How to test

1. Include the `@theia/git` and `@theia/git-native` packages and check it works as before.  Check that you should see the 'amend' section and the history view.

2. Include `@theia/git` and the VS Code builtin plugin.  Check that the plugin is fully working and other plugins that depend on the git builtin also work.  Check that you get the 'amend' section and the history view.

One issue is that the Source Control view is slow to react to changes effected from the 'amend' section.  I don't know if there is some way of prodding the Git builtin to refresh.
  
#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
I hoped the solution won't require watching git twice. There are 2 issues with it: 
- performance of git status from vscode and theia extension
- inconsistent state between vscode and theia views

I hoped that amend view can rely on status changes produced by vscode extension, so views reflect the same state and there is not double git polling.

**Comment by westbury** [comment]
@akosyakov I've changed it so it uses the plugin's change watcher.  This is a slightly inferior solution because the git builtin does not actually watch the files, it just updates if a change was initiated through the plugin or if the refresh command was run.  So changes to history or the amend state are not updated if git is used on the command line.  However you are right that it should be consistent.

Sorry to be so long getting back to this.  I was not sure if the move over to the git builtin was actually ever going to happen given how unreliable it is.  In fact there is no reason to use the builtin at all except at the moment that is the only way to install plugins that depend on git.  We should really get the git native package to emulate the git plugin, then we get the best of both.  I can put in a PR for that if there is any interest.

**Comment by westbury** [comment]
@vince-fugnitto I've rebased this, if you now want to take a look.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I've rebased this, if you now want to take a look.

@westbury thank you I'll take a look. Looking at the description, you've included `@theia/git-native` to the examples which provides git, and described that either the extension or the builtin should be used. The idea would be to possibly drop testing the native extension in the framework (and maintain it elsewhere, likely in its own repo) and instead use the builtin going forward.

**Comment by westbury** [comment]
> Looking at the description, you've included `@theia/git-native` to the examples which provides git

@vince-fugnitto Yes, correct.  The PR does not switch out the Git extension in the examples, nor does it move anything to other repositories.  I assume those will be decisions that will be made in due course.  For now the PR is just a refactoring that does not change the examples nor force extenders to make significant changes.

**Comment by thegecko** [comment]
This PR is no longer a priority for Arm and has become stale. Will keep the branch in case it requires re-opening in future.

**Pull request closed without merging**
