### PR TITLE
WIP - set initial size and position of secondary windows

### PR DESCRIPTION
**Pull request by marcdumais-work**
#### What it does

Set the initial size and position of secondary windows. For example, sized the same as the original widget that was extracted into it's own windows and position the new window at the same place as the widget was. Alternatively, attempt to position it to the side of the current Theia app.  

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by JonasHelming** [comment]
@vince-fugnitto @vladarama This might be something for @vladarama to complete?

**Comment by vladarama** [comment]
@JonasHelming 
Thanks for the suggestion Jonas, I will take this on.

**Comment by JonasHelming** [comment]
@vladarama I guess we can close this one, correct?

**Comment by vladarama** [comment]
@JonasHelming Yes we can.

**Pull request closed without merging**
