### PR TITLE
[file-search] improve results obtained when performing file search

### LINKED ISSUE #5636: [file-search] As a user I want exact matches to show up in file search
### Description
 
I cannot see `os.ts` in the file search when I search for `os.ts` in the workspace.

### Reproduction Steps

 - Open a workspace on the Theia source.
 - <kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>
 - Type: `os.ts`.
 - I cannot see `os.ts`.

Expected:
 - I can see `os.ts` among the items.

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #5636

_Description:_

The current logic of the `file-search` meant that fuzzy results were being returned over exact results due to the limit. This PR quickly addresses that issue by ensuring that exact matches are prioritized, and thus returns better results. The PR has been tested with large workspaces (and even multi-root workspaces) and the performance stayed largely identical. There is likely to be a tradeoff of performance for better results which in the end I believe users would appreciate.

_Implementation_

The idea is to `cancel` the search if the `exact` matches hits the allowed limit.
Only the limit of results is sent over the wire.

#### How to test

- perform `file-search` on a large workspace (or multi-root workspace)
- verify the performance and if the results are better than previously (ex: searching for `os.ts`)

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
> So the idea is "not stop the search until the number of exact matches exceeds the limit".
> 
> The code lowers the "worst-case performance", and should not have major impacts to the "average case performance". I am OK with this change.


Yes, the general idea is to use the limit only for the `exact matches` (attempt to get the most best possible matches), and some fuzzy results. In the end only the limit is passed over the wire.

It improves the results obtained while also not being too much of a radical change.
I'll get other's opinions on the change before merging :) Thank you for the review!

**Comment by vince-fugnitto** [comment]
@lmcbout do you mind trying out this pull request for me when you get the chance?

**Comment by lmcbout** [comment]
I will test it

**Comment by vince-fugnitto** [comment]
If possible, I'd really like to get more opinions/reviews on this pull request before merging.
I attempted to improve the ordering of search results while keeping the changes/impact to a minimum including performance and complexity.

**Comment by akosyakov** [comment]
I'm fine to try.

**Comment by vince-fugnitto** [comment]
> I'm fine to try.

Sounds good, we can try to see if the behavior is better, and if anything it is always possible to rollback/revert the changes as they are in history.

**Pull request merged**
