### PR TITLE
[drag and drop] prevent default dnd behavior

### LINKED ISSUE #674: [ui] Drag & Drop a file inside THEIA editor should not replace THEIA web page
Select a file in the outside folder of THEIA (Home folder in UNIX), select, DRAP and DROP it in the  THEIA workspace EDITOR section --> THEIA goes away and is replace by a web editor with the URI of the file to open  instead of opening the file as a new file on THEIA editor.
2 options to consider:
- Should not replace the THEA URI application.  If the "Drag and Drop" use the web application , it should create a new tab on the web and open the file there
- If the user "Drop" his selection inside THEIA "Editor" section, it should open the file as a new file in THEIA application.

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #674

- prevent default dnd (drag & drop) behavior when dragging a file from
the filesystem into Theia. The default browser behavior meant that
the application was replaced by the browser attempting to open the file
as a URL.
- [minor] fix a few typos in the same file.

**Tested**
- tested in `Chrome`, `Firefox` and `Safari`

#### How to test

1. open a workspace
2. when no files are currently opened, attempt to drag a file from your filesystem into the application's main panel
3. the application should not be replaced with the browser attempting to open the file as a URL (in `master` this is the case
4. make sure that other dnd events (ex: `explorer`) still work correctly

<details>
<summary>Example</summary>
<div align='center'>

<br />

</div>
</details>

**Additional Notes**

In the future, we can attempt to open the file in an editor if possible, but looking at the current web API, obtaining the path of a file and opening it does not seem possible. Perhaps we can come up with a workaround as to download the file, store it temporarily, and then open it.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
Please as part of verification check that it does not break d&d of file in the navigator, and parts in the debug view.

**Comment by vince-fugnitto** [comment]
> Please as part of verification check that it does not break d&d of file in the navigator, and parts in the debug view.

I've verified the following cases in the `explorer`:
- dnd a file from my filesystem into a folder in the explorer
- dnd a file from one folder to another in the explorer
- also tested the same two scenarios in a multi-root workspace

How can I verify dnd in the `debug` view?

**Comment by akosyakov** [comment]
> How can I verify dnd in the debug view?

Move parts, e.g. `Variables` after `Breakpoints`.

**Comment by vince-fugnitto** [comment]
> > How can I verify dnd in the debug view?
> 
> Move parts, e.g. `Variables` after `Breakpoints`.

Thanks, I confirmed it still works correctly.

**Pull request merged**
