### PR TITLE
various fixes to make git and gitlens vscode extension work

### LINKED ISSUE #4902: vscode plugin gitlens not support
### Description
https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
not support
image
image

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #4902: support of gitlens extension

Please see individual commits, they reference relevant issues and description. Please ask if something is not clear i will try to clarify commits.

TODO:
- [x] add tests for exposed OpenerService Monaco APIs
- [x] add integration tests for keybinding regressions and bugs
- [x] fix integration tests
- [x] add missing commands, see https://github.com/eamodio/vscode-gitlens/blob/30e1d290e8f337d56596a030ff097eeabdd98eb7/src/constants.ts#L11
- [x] clicking on a file in repositories view opens an empty diff editor -> https://github.com/eclipse-theia/theia/pull/6921/commits/465921d1882c917dcae3f02b5fabbfe47b720368
  - It seems to be a bug in the editor preview widget, after pinning it works nicely.
- [x] no compare with previous revision in the navigator context menu because of https://github.com/eclipse-theia/theia/issues/6948
- [x] Uncaught command 'gitlens.diffWith' NOT known from markdownRenderer.ts:73 -> resolved by hooking OpenerService in Monaco
- [x] changing layout on welcome page trigger many overwrite dialog boxes: https://github.com/eclipse-theia/theia/issues/6845 (resolved by #7110)
- [x] clicking on `source content layout` in the welcome screen does nothing -> the command open handler was not handling Object as an argument, so string argument was spread to an array of characters
- [x] Error: No tree view with id gitlens.views.compare:gitlens when trying to change layouts from the welcome page -> extension issue https://github.com/eamodio/vscode-gitlens/issues/966, the same in VS Code
- [x] root ERROR Failed to fetch children for 'gitlens.views.repositories:gitlens' Error: No tree view with id gitlens.views.repositories:gitlens while refreshing repositories view -> could not reproduce it after fixing other issues
- [x] editor navigation with keys to left and right does not work, key context for gitlens is not updated properly
  - quick pick cancellation was not handled properly (reproducible by trying to navigate with alt+left/right after using the more quick pick from gitlens hover)
  - valid keybindings were removed as collided without evaluating context/when closures (reproducible by trying to navigate with left/right always)
- [x] errors on the initial startup (reproducible by deleting ~/.theia/plugin-storage/global-state.json file) -> configuration for sub section was not properly cloned, see https://github.com/eclipse-theia/theia/pull/6921/commits/c4b2ff3dfb1a6d6a3474e536bf4ace8fe1a3c33b
- [x] MonacoEditorModel backed up by resources from the plugin system are leaking as well as these resources

#### How to test

- remove `@theai/git` dependency  from `examples/browser/package.json` and rebuild the browser example
- install vscode git built-in extension: https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/git-1.39.1-prel.vsix
- install gitlens extension of version 10.2.0: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
- test functionality of both extensions

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
I've addressed as much as could without going into rewriting WorkspaceService, unfortunately it would require to fix some commands.

Now git and gitlens extensions should be stably loaded each time on first time and reloads and initialised, there should not be apparent bugs, except some missing functions. For missing functions like custom workspace naming and unsupported menu locations we already have bugs.

**Comment by svenefftinge** [comment]
Tried to run the compare commands, but it didn't work. Neither from the command palette nor from the view. Otherwise looks very promising 👍

**Comment by azatsarynnyy** [comment]
Checked some of the features from the extension's readme.
Spotted that `Show in File History View` command from file context menu does nothing.

**Comment by akosyakov** [comment]
@azatsarynnyy It seems to be a bug in gitlens extension. It works for me only first time in VS Code, after that nothing happens.

**Comment by akosyakov** [comment]
@svenefftinge @azatsarynnyy Could you have a look again?

It turned out that logic of revealing the plugin tree and dynamically updating the quick pick items were completely broken. Now the compare commands should work. 

`Show in File History View` does not work in VS Code as well.

@eclipse-theia/ecd-theia-committers helping testing is welcomed!

**Comment by azatsarynnyy** [comment]
When I click between the end of the line and line blame annotation, the cursor jumps several symbols to the left. See the screencast:
Peek 2020-05-06 17-19

The issue isn't reproducible with the disabled line blame annotations:
image

**Comment by azatsarynnyy** [comment]
GitLens Settings page doesn't display the images:
image
comparing to VS Code:
image

**Comment by azatsarynnyy** [comment]
no commiters avatars in the views
image
comparing to VS Code
image

**Comment by azatsarynnyy** [comment]
There's a difference when clicking `Toggle Line Layout` button.

In VS Code, the button icons are changed on click:
Peek 2020-05-06 18-01

In Theia, the button icons aren't changed on click but after hiding/showing:
Peek 2020-05-06 18-00

**Comment by azatsarynnyy** [comment]
When I switched to a tab in the editor area which doesn't represent a workspace file (e.g. Preferences), all the GitLens views still display the information about the last opened file.

In VS Code, all GitLens views display the messages like the following
image

**Comment by azatsarynnyy** [comment]
`View -> Open View...` shows duplicated items:
image

Opening any view from the list adds the corresponding view to the Source Control view-container
image
and they're always empty.

In VS Code, it opens and focuses the corresponding view in GitLens view-container.

**Comment by akosyakov** [comment]
@azatsarynnyy thank you for the review, i will have a look at your comments today. ❤️  I think there are several issues related to how we retrieve images and refresh trees.

**Comment by akosyakov** [comment]
> GitLens Settings page doesn't display the images:

Interestingly for this case I have pictures in Gitpod:
Screenshot 2020-05-07 at 09 15 52

Where do you try it? Maybe it is related to how webviews are deployed in your environments.

**Comment by akosyakov** [comment]
Avatar icons are regressions after https://github.com/eclipse-theia/theia/pull/7583 I will limit this fix only to `hostedPlugin/` endpoint.

**Comment by akosyakov** [comment]
Wow, it turned out there are 2 substantial bugs in how we manage documents:
- when code of synching active editor was copied, null value was lost, only undefined preserve, but it actually had different meaning, null means no active editor, undefined means no change, so active editor was working by luck so far
- vscode.window.visibleTextEditors actually returns only visible, not all as we do

We push a commit fixing it.

**Comment by akosyakov** [comment]
@azatsarynnyy Could you try latest changes please?

I left out:
- jumping cursor, there is something wrong with how the editor decorations from VS Code extensions are installed
- and rerendering view toolbar items, it is a generic issue with our view containers.

I will file follow-up issues for them. The rest should be fixed.

**Comment by azatsarynnyy** [comment]
> > GitLens Settings page doesn't display the images:
> 
> Interestingly for this case I have pictures in Gitpod:
> Screenshot 2020-05-07 at 09 15 52
> 
> Where do you try it? Maybe it is related to how webviews are deployed in your environments.

@akosyakov I tried it running the browser example of vanilla Theia on my machine.

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy Could you try latest changes please?
> 
> I left out:
> 
> * jumping cursor, there is something wrong with how the editor decorations from VS Code extensions are installed
> * and rerendering view toolbar items, it is a generic issue with our view containers.
> 
> I will file follow-up issues for them. The rest should be fixed.

I re-checked and can confirm that the rest is fixed now. Thanks!

**Comment by akosyakov** [comment]
I'm merging tomorrow morning If no one has objections.

**Comment by akosyakov** [comment]
@azatsarynnyy I filed https://github.com/eclipse-theia/theia/issues/7795 and https://github.com/eclipse-theia/theia/issues/7796 for remaining issues.

**Pull request merged**
