### PR TITLE
Removed the leftover `@theia/json` dependency.

### LINKED ISSUE #8183: [quality][json] Check why we depend on `@theia/json` in the TS tests
### Bug Description:

Follow-up of: https://github.com/eclipse-theia/theia/issues/8181

Let's check why we have this in the code and how does the test pass?
https://github.com/eclipse-theia/theia/blob/9afc819182ae94cd44f19efe42828ce704d9fecc/examples/api-tests/src/typescript.spec.js#L115

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

### PR DESCRIPTION
**Pull request by kittaakos**
Signed-off-by: Akos Kitta <kittaakos@typefox.io>

**NOTE**: This PR was opened against #8151 and not the `master`.

#### What it does

It removes the `@theia/json` dependency from the test. I am not sure if this PR makes any sense. Can you please look into it, @akosyakov? Thank you!

Closes #8183

#### How to test

The CI should be green.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
> open the changes on top of #8151 which make the api integration suite more robust and fixes other issues.

Smart 👍  I'll do that.

**Comment by akosyakov** [comment]
Fine with me if tests are green.

**Comment by vince-fugnitto** [comment]
@kittaakos when the base was changed it looked like travis didn't start (since it was not based off `master`), but the api-tests were recently merged. Do we want to rebase this pull-request to start travis?

**Comment by kittaakos** [comment]
> when the base was changed it looked like travis didn't start (since it was not based off `master`)

Yes, I can confirm.

> but the api-tests were recently merged. Do we want to rebase this pull-request to start travis?

I'd leave the decision to @akosyakov.

**Pull request closed without merging**
