### PR TITLE
Revert #11011

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

This PR reverts #11011 after several issues were discovered with it after merge.

Issues: #11203 (critical), #11199

#### How to test

1. CI should pass and the application should be have as it did before #11011.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by JonasHelming** [comment]
I cannot enter code review at the moment, but I +1 this

**Comment by JonasHelming** [comment]
and thank you @colin-grant-work for taking care of this!

**Comment by colin-grant-work** [comment]
After a false start, this should be a full reversion of #11011, if CI gives the all clear.

**Review by vince-fugnitto — APPROVED** [review]
LGTM 👍 CI passes, and I performed a quick sanity check myself.

**Pull request merged**
