### PR TITLE
update: vs-code-extensions build badge

### PR DESCRIPTION
**Pull request by jim4067**
#### What it does

Fixes: #9910 
Updated the readme to use vscode-extensions badge provided.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@jim4067 thank you for your first contribution to the project 👍 

In order to accept the changes you'll need to make sure to sign the [eclipse contributor agreement (eca)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) with the same email as your authorship (it is the reason for the failed CI check).

**Comment by jim4067** [comment]
Sorry. 

I filled out the agreement form.

**Comment by alvsan09** [comment]
> @marcdumais-work @alvsan09 any objection to using the `publish-latest` workflow in order to determine the build status for the badge?

No objections, I think `plublish-latest` is the most used target and it's state has more weight, in my opinion!

**Comment by marcdumais-work** [comment]
@vince-fugnitto ok with me too

**Review by vince-fugnitto — APPROVED** [review]
@jim4067 thank you for your contribution :+1:

**Comment by jim4067** [comment]
Glad to have helped 😊

**Pull request merged**
