### PR TITLE
fix file tree scroll bug

### PR DESCRIPTION
**Pull request by shuyaqian**
Signed-off-by: shuyaqian 717749594@qq.com

#### What it does

fix [#9407](https://github.com/eclipse-theia/theia/issues/9407)

#### How to test

1. click 'open workspace' menu
2. scroll
3. other tree widgets still scroll fine with `overflow: auto`

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that it fixes the issue with scrolling in file dialogs (no more continuous scroll).
I'm not sure if it causes any regressions to other trees but I was not able to identify any.

**Review by msujew — APPROVED** [review]
I can confirm that this fixes the endless scrolling issue on the file tree. LGTM.

**Comment by tsmaeder** [comment]
@vince-fugnitto push the merge button? You can, right?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto push the merge button? You can, right?

Yes, I just like to let pull-request's sit a bit in case others want to review.

**Pull request merged**
