### PR TITLE
GH-7349: Support for Node.js 12.x

### LINKED ISSUE #7349: Installation failed with LTS Node version12.16.1
### Reproduction Steps
following the https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start guid fails with 

error @theia/monorepo@0.0.0: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <12". Got "12.16.1"

**OS and Theia version:**
OS is Ubuntu 18.04
Node Version is 12.16.1 (LTS)
Git cloned latest theia version

**Diagnostics:** 
no further analytics requiered thought you want see the problem with old docker images

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #7349

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does

With this PR you can build Theia with Node.js 12.x.

#### How to test

This is a good question. We build it on both Node.js 10.x and 12.x on the CI. Any further ideas?

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
I leave this decision to the community. We can support the latest electron version too: https://github.com/eclipse-theia/theia/pull/7968

**Comment by akosyakov** [comment]
> This is a good question. We build it on both Node.js 10.x and 12.x on the CI. Any further ideas?

We smoke test languages, git, file watching, keyboard detection and so on for browser and electron targets. Especially for places where we make use of native Node modules. The same for Electron 9 PR.

If we agree to go for Electron 9 I would prefer to have one PR which bums Node and Electron and we test it only once.

**Comment by kittaakos** [comment]
> If we agree to go for Electron 9 I would prefer to have one PR which bumps up Node and Electron and we test it only once.

Sure. Let's wait for other's feedback on this and I am happy to make the changes if we decide to move forward.

**Comment by benoitf** [comment]
I think it's great if we have support for nodejs 10 and 12 for a while, so downstream can update to 12 as well and then like one release later, nodejs 10 support can be removed with Electron 9 requirement.

**Comment by akosyakov** [comment]
> I think it's great if we have support for nodejs 10 and 12 for a while, so downstream can update to 12 as well and then like one release later, nodejs 10 support can be removed with Electron 9 requirement.

Sounds reasonable If noone needs new Electron urgently and can wait till August. Added to next dev meeting.

In anyway it would be good to merge this PR rather soon, if we want to have it in next release. Also adding a notice in CHANGELOG that Node.js 10 support is going to be dropped after 1.3.0 and notifying about it on Spectrum after merging the PR.

**Comment by kittaakos** [comment]
> notice in CHANGELOG that Node.js 10 support is going to be dropped

Why does it mean we have to drop Node.js 10.x? Can someone please explain this to me? 😊What's the problem here? Is it that we might introduce something new that is available only with Node.js 12.x API?

**Comment by akosyakov** [comment]
> Why does it mean we have to drop Node.js 10.x?

- Because Electron 9 requires Node.js 12.14 as the minimal version and we use Electron Node version as our baseline.
- Node.js 10.x is not maintained since April 2021, we need to move our baseline to the active LTS: https://nodejs.org/en/about/releases/

**Comment by marechal-p** [comment]
> Why does it mean we have to drop Node.js 10.x? [...] Is it that we might introduce something new that is available only with Node.js 12.x API?

Yes. So if we start using those new features/apis someone on Node 10 won't be able to run it. I remember we had a similar issue with some missing `Object.entries` in some runtime but I don't remember exactly.

**Comment by thegecko** [comment]
> I remember we had a similar issue...

Yes we did, I'd rather we avoided that again. If we have a strong reason to support versions outside of the electron version being supported, we need to have a strong CI in place!

That being said an upgrade is fine if we can do electron at the same time IMO :)

**Comment by kittaakos** [comment]
> remember we had a similar issue with some missing `Object.entries` in some runtime

I found [this](https://github.com/eclipse-theia/theia/issues/3693) and [this](https://github.com/eclipse-theia/theia/issues/3730). Correct, it was a Node.js incompatibility issue, but the other way around, the electron version was outdated (8.x). We have already switched to Node.js 10.x for the development and used new APIs. It failed under electron (8.x); the solution was to update the electron version (10.x). Correct me if I am wrong.
I do not understand why couldn't we support both versions for one or two releases. Let's stick to the 10.x API (with the typings) for the development, but we can already support electron 9.x (12.x), can't we? 😊

I am closing this PR in favor of https://github.com/eclipse-theia/theia/pull/7968. I want to merge the updates into one. Let's move the conversation there. Thank you!

**Comment by akosyakov** [comment]
@kittaakos What you are saying is fine. But we should notify adopters in advance that we are going to drop Node 10 support in 1-2 releases. I am not sure what is the proper channel. I also don't think that's a really big deal, Node adopters have to take care this year anyway to get rid of using Node 10. I've checked with Gitpod, the only component which rely on Node 10 is Theia, everything else was already moved to the active LTS. We have issue in theia-apps to use Node 12 as well: https://github.com/theia-ide/theia-apps/issues/358#issuecomment-627435430

**Comment by kittaakos** [comment]
> But we should notify adopters in advance that we are going to drop Node 10 support in 1-2 releases.

Sure, I totally agree.

> I am not sure what is the proper channel.

Spectrum, GH, npm log (if `<12.14.1`), etc.. 😄

**Pull request closed without merging**
