### PR TITLE
Fix the issue of not updating recentList on unload

### PR DESCRIPTION
**Pull request by newliuyaoyan**
#### What it does

Fixed the issue of not updating the recentList file after the window was closed. This issue is caused by the late update of files when the window is closed.
#### How to test

After each window close, check if the recentList file has been updated
#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
Hey @newliuyaoyan, thank you for your first contribution.

Unfortunately, the code doesn't compile. I would recommend you to do something else:

```ts
onWillStop(): OnWillStopAction {
  return {
    action: () => this.server.setMostRecentlyUsedWorkspace(this._workspace ? this._workspace.resource.toString() : ''),
    reason: 'Saving most recently used workspace',
    // Attempt to run this last
    priority: 1000
  }
}
```

**Comment by newliuyaoyan** [comment]
Thank you for your help. I have now made the modifications as you suggested

**Comment by JonasHelming** [comment]
@msujew Can you re-review, please?

**Comment by JonasHelming** [comment]
@msujew ping :-)

**Comment by msujew** [comment]
Will get to it next week :)

**Pull request closed without merging**
