### PR TITLE
plugin: findFiles should handle ignored files

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes: #8451 

The following commit updates the `findFiles` plugin API to respect `exclude: null` which indicates that the search should yield results in all files (no exclude or ignored constraints).

_Before:_

image

_Pull-Request:_

image

#### How to test

1. use the vscode extension: [vscode-find-files](https://github.com/vince-fugnitto/vscode-find-files/releases/download/1.0.0/vscode-find-files-0.0.1.vsix)\
(the extension searches for all readme files and prints those within `node_modules` (gitignored))
2. start the application
3. execute the command `echo files`
4. there should be results in `node_modules`

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by sapirpol** [comment]
Hi @vince-fugnitto,

Why not just to change [useGitIgnore param](https://github.com/eclipse-theia/theia/blob/master/packages/file-search/src/node/file-search-service-impl.ts#L44) to false?

**Comment by vince-fugnitto** [comment]
> Why not just to change [useGitIgnore param](https://github.com/eclipse-theia/theia/blob/master/packages/file-search/src/node/file-search-service-impl.ts#L44) to false?

@sapirpol since searching in ignored files should not always be turned on, it should only be turned on if `exclude = null` based on the documentation:

```ts
/**
* Find files across all [workspace folders](#workspace.workspaceFolders) in the workspace.
*
* @sample `findFiles('**​/*.js', '**​/node_modules/**', 10)`
* @param include A [glob pattern](#GlobPattern) that defines the files to search for. The glob pattern
* will be matched against the file paths of resulting matches relative to their workspace. Use a [relative pattern](#RelativePattern)
* to restrict the search results to a [workspace folder](#WorkspaceFolder).
* @param exclude  A [glob pattern](#GlobPattern) that defines files and folders to exclude. The glob pattern
* will be matched against the file paths of resulting matches relative to their workspace. When `undefined` only default excludes will
* apply, when `null` no excludes will apply.
* @param maxResults An upper-bound for the result.
* @param token A token that can be used to signal cancellation to the underlying search engine.
* @return A thenable that resolves to an array of resource identifiers. Will return no results if no
* [workspace folders](#workspace.workspaceFolders) are opened.
*/
export function findFiles(include: GlobPattern, exclude?: GlobPattern | null, maxResults?: number, token?: CancellationToken): Thenable<Uri[]>;
```

For `exclude` it states (note that vscode uses `files.exclude` to control the default excludes):

```ts
When `undefined` only default excludes will apply, when `null` no excludes will apply.
```

---

Here are two examples:

```ts
vscode.workspace.findFiles('**/README.md', undefined, 50)... // search for files respecting the default exclude
vscode.workspace.findFiles('**/README.md', null, 50)... // search for files in all files (exclude is `null`)
```

**Review by marechal-p — APPROVED** [review]
LGTM, the extension worked.

**Comment by vince-fugnitto** [comment]
I'll merge tomorrow if there are no objections :)

**Pull request merged**
