### PR TITLE
fix typos present in '@theia/core'

### PR DESCRIPTION
**Pull request by justinang1**
Issue: #6899

#### What it does
* fixes various typos throughout the codebase. 

#### Review checklist
* [x]  as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers
* as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by justinang1** [comment]
Still figuring out how merges work. Reset fork to point to upstream, then created a branch from fork with changes for this issue (previously i was just pushing to master).

**Comment by vince-fugnitto** [comment]
The branch does look to be in a weird state however as it cannot be rebased safely:

<div align='center'>

Screen Shot 2020-01-24 at 11 22 38 AM


</div>

Perhaps follow the general guide described in the article I mentioned.

**Comment by justinang1** [comment]
I think it's fixed, but if the upstream repo is updated then I will update the branch again.

**Comment by justinang1** [comment]
I'm not sure what happened, but the pull request closed itself. Is there any way to fix this? The branch still exists.

**Pull request merged**
