### PR TITLE
Stick to vscode-languageserver@6.0.0-next.1

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### Reference issue
https://github.com/eclipse-theia/theia/issues/6542

#### What it does
Stick to `vscode-languageserver@6.0.0-next.1` for `vscode-json-languageserver`

#### How to test
1. Remove `node_modules`
2. Build the project
3. Open `tasks.json` and check if autocompletion works

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@marechal-p Would next `yarn upgrade` rewrite yarn.lock for this dependency? With yarn resolutions, it should not, right?

**Comment by tsmaeder** [comment]
Could a workaround be to explicitly require vscode-languageserver:6.0.0-next.1 in packages/json/package.json? That way, it is likely that we change the required version when we update the langugage server version.

**Comment by akosyakov** [comment]
@tsmaeder it should be another way around. If pinning is possible in package.json then it is the best way. It will work for all adopters. But as far as I understood it is not, so then yarn resolutions is cleaner than changing yarn lock file. Yarn lock file will be rewritten by next execution of `yarn upgrade` without resolutions.

**Comment by AlexTugarev** [comment]
> With yarn resolutions, it should not, right?

> In case the "resolutions" fix suggested by @akosyakov does not work.

not sure if it's known already, there is a typo at https://github.com/eclipse-theia/theia/blob/master/package.json#L9, it should be `resolutions`

**Comment by marechal-p** [comment]
@akosyakov The `resolution` field will update the lock file, because it effectively updates the dependency tree resolved by yarn, so it will write it down.

A better solution than the current change would be to indeed add this resolution field in this repo, and advise dependents to do the same in their repositories.

A better long term solution would be to find and fix whatever package is pulling and using the wrong version of this vscode package, since this is quite broken.

**Comment by tolusha** [comment]
@marechal-p @akosyakov 
The PR is updated to use `resolutions`

**Comment by tolusha** [comment]
That is pretty important for Eclipse Che, could some one validate the PR

**Comment by marechal-p** [comment]
Keep in mind that this won't fix Che, unless your build system is different from just consuming Theia packages from some registry. Dependents should add the same thing you did in their own application's package.json.

**Comment by tolusha** [comment]
@marechal-p 
thank you!

**Pull request merged**
