### PR TITLE
stream webview resources to avoid blocking a web socket

### LINKED ISSUE #8358: loading python notebooks is slow
After loading is fine though, but before Theia even goes offline sometimes.

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #8358: stream webview resources to avoid blocking a web socket

#### How to test

- install python extension from open vsx registry
- call `Create New Blank Jupyter Notebook`
- UI should not be blocked, the notebook should be loaded promptly

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by AlexTugarev** [comment]
> install python extension from open vsx registry

installed, but with error

Screen Shot 2020-08-12 at 10 59 08

after reload it seems to be activated, at least the python selection was computed in background 👍 

creating a new notebook is slow for the first time, I bet the reason is the local notebook server which is spinning up in background.

after reload, a new notebook is opened within ~5 seconds.
when trying to navigate the directories in the explorer view, it seems to be blocking for a second or so.

**Comment by AlexTugarev** [comment]
@akosyakov, how to you measure `notebook should be loaded promptly`?

**Comment by AlexTugarev** [comment]
BTW, `Uncaught (in promise) Error: Illegal theme base!` is logged a few times.

**Comment by AlexTugarev** [comment]
Screen Shot 2020-08-12 at 11 11 59

is this known or new?

**Comment by AlexTugarev** [comment]
UPDATE: 

https://github.com/eclipse-theia/theia/pull/8359#issuecomment-672753937 is probably caused by some cache issues.

Other than that, it's working, but not very fast, mainly because it takes quite some time to load the resources from the python extension. the biggest fish is "ipywidgets.js"

Screen Shot 2020-08-12 at 11 47 04

**Comment by akosyakov** [comment]
Just a note I've used actually a version from MS marketplace which is much smaller from the opne vsx reigstry. That's why it is fast for me to open notebooks. The version in the open vsx registry should be fixed.

**Comment by brianking** [comment]
> > @akosyakov, how to you measure notebook should be loaded promptly?
> 
> Just a note I've used actually a version from MS marketplace which is much smaller than from the open vsx reigstry. That's why it is fast for me to open notebooks. The version in the open vsx registry should be fixed.

Can you file an issue at https://github.com/eclipse/open-vsx.org/issues please if necessary.

**Comment by akosyakov** [comment]
@brianking It was fixed yesterday: https://github.com/open-vsx/publish-extensions/pull/115

@azatsarynnyy I think you can try to install the system proxy to emulate the bad connection. It should make it very visible that before you won't be able to do any other requests to the backend while notebooks are openning.

**Pull request merged**
