### PR TITLE
Split license files for better recognition

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

GitHub is using [`licensee`](https://github.com/licensee/licensee) to identify license information in repositories. The project identifies licenses on a **per file basis** and therefore has trouble with our double-license-in-one-file format. 

I've split the `LICENSE` file into `LICENSE-GPL` and `LICENSE-EPL`, so that GitHub can correctly identify them. See [this test repo](https://github.com/msujew/license-test) where GitHub is able to successfully identify the two used licenses.

#### How to test

Merge this PR and assert that the license information in the repository is correctly updated. 

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by JonasHelming — APPROVED** [review]

**Comment by marcdumais-work** [comment]
Thank you @SpessartZiegler - it's indeed wrong to have "GPL-2.0" detected for this repo. I will look into your suggestions!

**Comment by marcdumais-work** [comment]
@msujew I think we may have the root cause of the GitHub license detection issue: https://github.com/eclipse-theia/theia/pull/12424#issuecomment-1551349506 . The SPDX we've been using for the secondary license is not correct. It's also incorrect in all our source code header files, and the license name is mentioned wrong in many `.md` files. As also noticed by @SpessartZiegler, the text of our "GNU General Public License v2.0 w/Classpath exception" text has changed during the split, now looking like one that was customized by Oracle (contains an extra [Oracle-specific paragraph](https://github.com/eclipse-theia/theia/blob/e9cd6873e05b00b2c2b2ad7eefa486bf3e8a3a9c/LICENSE-GPL#L343-L347)). 

I will open an issue about this.

**Comment by marcdumais-work** [comment]
PR https://github.com/eclipse-theia/theia/pull/12584

**Comment by marcdumais-work** [comment]
> Thank you @SpessartZiegler - it's indeed wrong to have "GPL-2.0" detected for this repo. I will look into your suggestions!

update: 
Now that I investigated this a bit deeper, I no longer think that it's necessarily wrong for GitHub to report "GPL-2.0" as a detected license. It's technically correct. I guess I hoped GitHub would detect [1] the exact "with classpath exception" variant of the license, but it does not and it's probably ok. 

[1]: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license

**Pull request merged**
