### PR TITLE
documentation: updated changelog for 1.4.0

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

The following pull-request updates the **changelog** for the **v1.4.0** release.
The updates include recording important changes during the month including any potential breaking changes for downstream applications and developers.

#### How to test

Verify the [rendered](https://github.com/eclipse-theia/theia/blob/7eb39fd1d21d6f4c9006175959ad92115c6c41c4/CHANGELOG.md) changelog.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
I'm planning to merge https://github.com/eclipse-theia/theia/pull/8268, is it fine?

**Comment by vince-fugnitto** [comment]
> I'm planning to merge #8268, is it fine?

Sure, I can always rebase after to include it :smiley: there's no real reason to wait for CI when changing a markdown file anyways.

**Comment by lmcbout** [comment]
@akosyakov Yes, we still have ~ 1 hours before I start the release.

**Comment by lmcbout** [comment]
@akosyakov Anything else you would like to merge before the release?

**Pull request merged**
