### PR TITLE
navigator: handle middle-click behavior

### PR DESCRIPTION
**Pull request by vladarama**
#### What it does

Fixes: #12762 
Fixes: #12788 

This PR handles the middle-click button behavior in various tree-widgets, such as the `explorer`, `search-in-workspace`, `references` ... Like in VS Code, selecting a file using the middle-button will open that file as an open-editor instead of simply selecting it. This achieves the same functionality as double-clicking on a file, but it is faster.

Demo:
middle-click demo

#### How to test

1. Start Theia
2. Open a Workspace / Folder
3. Go to the `Explorer` / `Search-in-workspace` / `SCM` /... views
4. Select a file by pressing the mouse's middle button (scroll wheel)
5. The file should be selected and added as an open-editor

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
I noticed a bug when opening multiple editors using middle-click where we would incorrectly paste the clipboard into the editor (Linux):

1. start the application
2. confirm that content exists in the clipboard
3. open multiple editors from the explorer using middle-click
4. confirm the bug exists where clipboard content is being pasted into previous editors

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the changes work as expected :+1: 

- [x] middle-click in the explorer, and other trees (ex: siw) works as expected
- [x] middle-clicking collapsible nodes correctly expands/collapses nodes
- [x] the auto-scroll behavior was fixed (confirmed on Firefox)

**Review by msujew — APPROVED** [review]
Works well for me as well 👍

**Comment by vince-fugnitto** [comment]
I'll merge, we can catch any potential regressions throughout the month if necessary.

**Pull request merged**
