### PR TITLE
fix: file-saving dialog with dirty editors

### PR DESCRIPTION
**Pull request by vladarama**
#### What it does

Fixes: https://github.com/eclipse-theia/theia/issues/12859

This PR fixes a bug where cancelling the file-saving dialog when closing a dirty editor would actually close the editor.
With the new changes, cancelling the dialog will leave the dirty editor opened, which is the intended behavior.

#### How to test

1. Open Theia application.
2. Create a new untitled text file (`File` -> `New Text File` or `Alt+N`).
3. Try to close the editor by pressing the `X` or `Alt+W`.
4. The file saving dialog should appear -> Press `Cancel`.
5. The editor should stay opened.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
Interestingly enough, I now have the exact opposite issue: When closing an untitled file and saving it to a new location, the editor isn't closed. Instead the model now points to the newly created file. VSCode correctly closes the editor after saving the untitled file.

**Review by vladarama — COMMENTED** [review]
@msujew 
Yeah this is a different issue that I also noticed on master (#12860). This PR only fixes #12859 but they are quite related so I will try to fix the other issue as well.

**Comment by JonasHelming** [comment]
@vladarama Are you planning to make this other fix part of this PR?

**Comment by vladarama** [comment]
@JonasHelming 
I still haven't had the chance to work on the other fix, but I will make a different PR for it when its ready.
As for the current PR, it should be ready for review.

**Review by msujew — APPROVED** [review]
Ok, sure. If you want to address the other issue separately, then I'm fine with merging this PR. LGTM 👍

**Comment by JonasHelming** [comment]
@vince-fugnitto Do you want to merge this?

**Review by msujew — CHANGES_REQUESTED** [review]
Dismissing my approval, the change leads to failing browser tests.

**Review by vladarama — COMMENTED** [review]
Hey @msujew ,
When we cancel the file-saving dialog, the dirty editor should not be disposed. I updated the browser tests to reflect this behavior. It should be good to go now.

**Review by msujew — APPROVED** [review]
Awesome, looks good to me 👍

**Comment by JonasHelming** [comment]
@vince-fugnitto Do you want to merge this now?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Do you want to merge this now?

@JonasHelming sure, we can merge for the release :)

**Pull request merged**
