### PR TITLE
preferences: fix duplicated resolution

### PR DESCRIPTION
**Pull request by paul-marechal**
The `WorkspacePreferenceProvider` can do one of two things: It may return preferences from the current workspace folder if the workspace is a single root workspace, or it may return preferences as defined in the workspace file if the workspace is a multi-root workspace.

Whenever we want to resolve a preference, the following scopes are queried: `Default`, `User`, `Workspace`, and `Folder`.

When a single root workspace is opened the following happens:

- Query `Default` scope [...]
- Query `User` scope [...]
- Query `Workspace` scope: use `WorkspacePreferenceProvider` which delegates to `FoldersPreferenceProvider`.
- Query `Folder` scope: use `FoldersPreferenceProvider`.

Conclusion: The `FoldersPreferenceProvider` is queried twice.

In order to fix that issue this commit introduces a new component: `TogglePreferenceProvider` which extends `PreferenceProvider` and wraps another provider so that it can be enabled/disabled.

Whenever we are running a single root workspace, we'll enable the `FoldersPreferenceProvider` used by `WorkspacePreferenceProvider` and disable the one bound to the `Folder` scope.

Whenever we are running a multi root workspace, we'll disable the `FoldersPreferenceProvider` used by `WorkspacePreferenceProvider` and enable the one bound to the `Folder` scope.

Fixes https://github.com/eclipse-theia/theia/issues/12153

#### How to test

See instructions in https://github.com/eclipse-theia/theia/issues/12153

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by paul-marechal** [comment]
cc @AlexandraBuzila

**Comment by paul-marechal** [comment]
I didn't know what to do with our current preference infrastructure. It's a mess, and this patch doesn't make things really nicer... In the meantime, this patch seems to work (on my machine) and it's not super invasive. If anyone has a better idea please open an alternative PR, or push directly to this one if you can.

**Comment by AlexandraBuzila** [comment]
Hi @paul-marechal 

I also found a bug in the PreferenceProvider while investigating this issue: the merge of array values was producing duplicates. I pushed my changes here https://github.com/eclipsesource/theia/commit/eb8d246ca7a09a8c8da89ecdd7daf0f6188e7211
If you agree with them, it would be fine for me if you were to integrate them in your PR.

With my changes alone, some tests from  `examples/api-tests/src/launch-preferences.spec.js` were still failling. While investigating them, I saw that preferences were merged twice, so your changes might have fixed the issues I was seeing when running the tests. I couldn't verify this ATM since the tests won't run now anymore, I think they might need to be adapted to account for the new provider.

**Comment by planger** [comment]
@paul-marechal I saw that this PR impacts the Playwright page objects. On a first glance, it looks like the selector of the modification indicator in the gutter needs to be adapted. Please let me know if you'd like us to assist with that.

**Comment by paul-marechal** [comment]
@AlexandraBuzila my problem is that from the code alone:

https://github.com/eclipse-theia/theia/blob/371ab02dda5c6df2c1381ab68b2f5ae341f7d258/packages/core/src/browser/preferences/preference-provider.ts#L225-L246

I can't see why values would be duplicated, _unless_ we pass two arrays containing the same data together.

If you read the PR description I highlighted the root cause of the duplication, that is the preference system calls twice the same handler. Since the previous logic didn't properly merge arrays, that didn't seem to cause an issue.

With that in mind, this PR addresses this problem of `FoldersPreferencesProvider` being called twice, and so far this seemed to have fixed the duplicated config issue.

**Comment by paul-marechal** [comment]
@planger I don't think this PR should require updating Playwright object models, let me see if I can fix the issues that appeared in CI first.

**Comment by paul-marechal** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/pull/12174

**Pull request closed without merging**
