### PR TITLE
GH-3791 don't swallow output from shell tasks

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Signed-off-by: Jan Koehnlein <jan.koehnlein@typefox.io>

### CODE REVIEW

**Comment by simark** [comment]
I am working on tasks and process stuff, so I'd like to have a bit of time to look at this, if possible.

**Comment by simark** [comment]
Apart from the discussions we have on #3791, I tried this locally.  I noticed that the shell stays open after the "task" (the process we want to run) has ended, which means the task never properly ends.

**Comment by simark** [comment]
If we want to run things through a shell (and we'll want to, that's the point of shell tasks), I think we'll want to run them using `bash -c '...` or equivalent.  I dug in node's `child_process.spawn` code a while ago, I think that's how it does.

**Comment by marechal-p** [comment]
Also seems to be breaking [some tests](https://travis-ci.org/theia-ide/theia/jobs/465987886#L2936).

**Comment by vince-fugnitto** [comment]
I believe the pull-request can be closed, at the moment it is quite outdated (2018) and is inactive.
I propose we open a new pull-request if we ever want to revisit such a feature.

**Pull request closed without merging**
