### PR TITLE
Update eslint to the latest version

### PR DESCRIPTION
**Pull request by benoitf**
#### What it does
Update eslint to the latest version
Need to rename no-shadow to @typescript-eslint/no-shadow as specified there
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-shadow.md

#### How to test
build should be working as I changed only comments in source code

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Change-Id: Ib864501e48772b224b4999718f4f8dfbeb8964d6
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by vince-fugnitto — APPROVED** [review]
I verified the following :+1: 
- I confirmed that the new dependencies are license compatible following the [guidelines](https://github.com/eclipse-theia/theia/wiki/Registering-CQs#case-new-or-updated-npm-production-dependency).
- I confirmed that the new rule works correctly, and pre-existing rules also work with the new eslint update.

**Comment by benoitf** [comment]
@vince-fugnitto should I wait somehow to have travis-ci back ?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto should I wait somehow to have travis-ci back ?

@benoitf I build the pull-request locally, and ran the tests (at least on Linux).
I'm not sure how long it will take to have Travis back (since we ran out of credits), it is likely we will need to replace it with GitHub actions. However, if you'd like to be safe we can bring it up in the dev meeting if you think we should hold off pull-requests till the release.

**Comment by benoitf** [comment]
so we've successful builds on linux (your case) and macos (my case) so I would say we're fine to merge.

**Comment by vince-fugnitto** [comment]
> so we've successful builds on linux (your case) and macos (my case) so I would say we're fine to merge.

I believe so, I can have a colleague test on windows if you'd like?

**Comment by benoitf** [comment]
@vince-fugnitto that would be perfect

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto that would be perfect

@DukeNgn do you mind confirming the changes work correctly on `windows`? (since there is no CI at the moment)

**Review by DukeNgn — APPROVED** [review]
I have tested on Windows and confirmed that the new rules work great and the existing rules are also working well with the update 👍

**Pull request merged**
