### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by RDIL**
Various small dependency updates

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
Thank you for your first contribution! @RDIL 

In order for us to accept the contribution you must make sure to [sign-off](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#sign-your-work) your commits, and ensure that the [Eclipse Contributor Agreement (ECA)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) is signed. Also, can you please squash your commits (in general we prefer single commits unless functionality can be logically divided into multiple commits).

**Comment by RDIL** [comment]
Ok, I signed the CLA so now I just need a few to sign the changes

**Comment by vince-fugnitto** [comment]
> Ok, I signed the CLA so now I just need a few to sign the changes

It's a lot easier when squashing the commits into a single-commit and signing it off.
(in the end we will request that a single commit is present anyways).

**Comment by RDIL** [comment]
I tried to @vince-fugnitto, but it doesn't look like the old commits got erased.

**Comment by vince-fugnitto** [comment]
> I tried to @vince-fugnitto, but it doesn't look like the old commits got erased.

In general, I would not advise you to perform your changes directly on your forks `master` but rather create new branches for all your feature requests. This is a more natural workflow, will allow you to easily organize your changes, perform amends, and also potentially allow for simultaneous pull-requests. It is something that is often expressed such as the following [guide](https://gist.github.com/Chaser324/ce0505fbed06b947d962#create-a-branch) when working with forks.

If you are having too much difficulty with the current workflow, it is possible to re-apply your changes or even open a new pull-request.

**Comment by RDIL** [comment]
Are you able to help me out?  You should have write, and I'm very busy the next few days.

**Comment by vince-fugnitto** [comment]
> Are you able to help me out? You should have write, and I'm very busy the next few days.

Sure, I’ll likely be busy with the release tomorrow but when I get some spare time I’ll see if I can resolve the issue :)

**Comment by vince-fugnitto** [comment]
> Are you able to help me out? You should have write, and I'm very busy the next few days.

I don’t think there is much I can do on my end, I unfortunately cannot perform a `sign-off` in your behalf. There is no rush to merge such a pull-request so it is perfectly acceptable to do so whenever you get an opportunity. It would however be nice to know how such dependencies were updated, did you perform a `yarn upgrade` perhaps? We will need to make sure that the dependencies are properly covered by CQs.

**Comment by RDIL** [comment]
Ok hang on

**Pull request closed without merging**
