### PR TITLE
Fix sorting problem in QuickFileOpenService

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

There were a couple of problems in the sort function for the file quick pick and in the tests for them:

A positive returns means left [_after_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description) right, so these values are reversed.

https://github.com/eclipse-theia/theia/blob/be4eba9d5aeb08e29f5a7dcf646c6defb25c28d4/examples/api-tests/src/file-search.spec.js#L41-L42

I've replaced the return expectations with actual passes through a sort function so that we're guaranteed to mirror the actual behavior of the function in its intended context of use.

---

To test whether L before R, these should also be reversed (but since the test expectations were reversed, the tests passed)

https://github.com/eclipse-theia/theia/blob/be4eba9d5aeb08e29f5a7dcf646c6defb25c28d4/packages/file-search/src/browser/quick-file-open.ts#L272

---

Fuzzy scores can be greater than `Scores.max` (1000), so imperfect matches could get a lead over perfect matches.

https://github.com/eclipse-theia/theia/blob/be4eba9d5aeb08e29f5a7dcf646c6defb25c28d4/packages/file-search/src/browser/quick-file-open.ts#L254

#### How to test

1. Mostly see if the tests pass.
2. Create a workspace with files with the filenames used in the new test.
3. Search for the perfect match.
4. Observe that it is ordered above the very good match.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@colin-grant-work unfortunately the changes do not work for me, the file-search is broken when I tried in the browser and electron. The following error is reported multiple times:

```
quick-file-open.ts:247 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'score')
    at score (/home/evinfug/workspaces/theia/examples/electron/lib/packages_file-search_lib_browser_file-search-frontend-module_js.bundle.js:346)
    at Array.compareByLabelScore (/home/evinfug/workspaces/theia/examples/electron/lib/packages_file-search_lib_browser_file-search-frontend-module_js.bundle.js:355)
    at compareWithDiscriminators (/home/evinfug/workspaces/theia/examples/electron/lib/packages_file-search_lib_browser_file-search-frontend-module_js.bundle.js:523)
    at QuickFileOpenService.compareItems (/home/evinfug/workspaces/theia/examples/electron/lib/packages_file-search_lib_browser_file-search-frontend-module_js.bundle.js:361)
    at /home/evinfug/workspaces/theia/examples/electron/lib/packages_file-search_lib_browser_file-search-frontend-module_js.bundle.js:305
    at Array.sort (<anonymous>)
    at handler (/home/evinfug/workspaces/theia/examples/electron/lib/packages_file-search_lib_browser_file-search-frontend-module_js.bundle.js:305)
```

**Steps to Reproduce**:
1. start the application with `theia` as a workspace
2. search for `pack`
3. the file-search is broken

**Comment by colin-grant-work** [comment]
> 3. the file-search is broken

@vince-fugnitto, good catch. The perils of only doing searches that work in a small workspace (and of trusting the declared types...)! I've pushed a commit that handles the `null` returns from `fuzzy`, and I also noticed that we were mishandling the `file results` (not `recently opened`) separator and fixed that.

**Review by vince-fugnitto — APPROVED** [review]
I confirm that the changes work as expected following the update, and the tests successfully pass :+1: 
I verified using a large workspace with exact, good and invalid results and it works fine, even with recent results.

**Review by JonasHelming — APPROVED** [review]
Looks good to me, I did a smoke test as well.

**Pull request merged**
