### PR TITLE
Update doc comments on service-connection-provider.ts

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does

Add some documentation to make the usage of the local/remote service id's more understandable.

contributed on behalf of STMicroelectronics

#### How to test

n/a

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
@eneufeld

**Review by msujew — COMMENTED** [review]
Looks good, two points of improvement on this:

1. You mention SSH a bunch, but this isn't the only way to use a remote system (dev container being another one).
2. I think we can avoid further confusion by specifying that, if the user isn't using a remote system (i.e. normal Electron/Browser system), both `LocalConnectionProvider` and `RemoteConnectionProvider` point towards the same system.

**Comment by tsmaeder** [comment]
> You mention SSH a bunch, but this isn't the only way to use a remote system

The idea is not to give a complete description of the system here, only an example.

**Review by msujew — APPROVED** [review]
Thanks, it's definitely an improvement over the previous doc 👍

**Pull request merged**
