### PR TITLE
Prepare branch for community release 1.29.x

### PR DESCRIPTION
**Pull request by martin-fleck-at**
#### What it does
Prepare branch for community release 1.29.x

#### How to test
Same as release 1.29 plus the following cherry-picked commits: https://github.com/eclipse-theia/theia/issues?q=label%3ACommunityReleasePatch1.29+is%3Aclosed
- https://github.com/eclipse-theia/theia/pull/11693
- https://github.com/eclipse-theia/theia/pull/11636

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — CHANGES_REQUESTED** [review]
@martin-fleck-at I don't think we want to merge into `release/1.29.0`? Should't you just branch off of `release/1.29.0`, cherry-pick the commits we need and push that branch?

cc @JonasHelming

**Comment by martin-fleck-at** [comment]
@vince-fugnitto You are right, we do not want to merge into `release/1.29.0` but I had to choose some base for the PR (to run the CI). The branch itself is https://github.com/eclipse-theia/theia/tree/v.1.29.x-community-release which contains the two commits (+ now the temporary commit with the CI run as it usually only runs on master which I will remove soon). So you only want the branch without PR, is that what you are saying?

**Comment by martin-fleck-at** [comment]
@vince-fugnitto No no, not for the actual release, I only did the changes so I could trigger the CI within this PR - I will remove the PR and the workflow changes if everything is green ;-)

**Comment by martin-fleck-at** [comment]
Perfect, the CI is green:
image

Therefore all tests (both mocha and playwright) have been run locally and in the CI. I additionally tested the two cherry-picked PRs manually. So I think the branch is good as it is. I removed the last commit with the workflow changes again, so the branch is ready at: https://github.com/eclipse-theia/theia/tree/v.1.29.x-community-release

**Comment by martin-fleck-at** [comment]
@vince-fugnitto I close this PR now. The community release branch is based on theia/release/1.29.0 with the two PRs mentioned in the description of this PR. If you have any problems, please let me know.

**Comment by JonasHelming** [comment]
@vince-fugnitto : branch should be ready (see above)

**Pull request closed without merging**
