### PR TITLE
Update Code of Conduct

### PR DESCRIPTION
**Pull request by garethwhittaker**
#### What it does

Resolves: #6691
Update the code of conduct to the new version adopted by the Eclipse Foundation.

#### How to test

Ensure the updated Code of Conduct matches the new version adopted by the Eclipse Foundation.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@garethwhittaker do you mind providing the link to where you retrieved the updated code of conduct? The most updated one I see is of [October 21, 2019](https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php).

**Comment by garethwhittaker** [comment]
I'll just change to use this date.
I wasn't sure if we should be setting our own date (ie. today) when updating ours.

**Comment by vince-fugnitto** [comment]
> I'll just change to use this date.
> I wasn't sure if we should be setting our own date (ie. today) when updating ours.

I'm not 100% sure either, but I think we should keep the date present in the actual code of conduct from Eclipse to be safe.

**Comment by vince-fugnitto** [comment]
@marcdumais-work just wanted to confirm it'd be fine to merge, the pull-request consists of adopting an updated `code of conduct` from the Eclipse Foundation.

**Comment by vince-fugnitto** [comment]
@garethwhittaker do you mind rebasing and fixing the conflict?

**Comment by marcdumais-work** [comment]
> @marcdumais-work just wanted to confirm it'd be fine to merge, the pull-request consists of adopting an updated `code of conduct` from the Eclipse Foundation.

Having a look now

**Comment by marcdumais-work** [comment]
Thanks @garethwhittaker - merging.

**Pull request merged**
