### PR TITLE
Add migration step for the socket.io update on Theia 1.23

### PR DESCRIPTION
**Pull request by drochgenius**
#### What it does

Add new migration step in the Migration Guide related to the socket.io update on Theia 1.23.

#### How to test

Nothing to test, it's a documentation update.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by paul-marechal — APPROVED** [review]
Thanks!

**Comment by paul-marechal** [comment]
Ah, could you make sure to sign the Eclipse ECA? Your commit must be authored by the email registered there.

**Comment by drochgenius** [comment]
Hi @paul-marechal , I have signed the Eclipse ECA.

**Comment by paul-marechal** [comment]
The ECA keeps failing even after revalidation. I don't know what email you used when signing, but the Git commit was made using `dominique.rochefort@hmhco.com`. Make sure you used the same email while both signing the ECA and authoring commits.

**Comment by drochgenius** [comment]
I have signed the agreement, but somehow it doesn't want to clear the check.

**Pull request merged**
