### PR TITLE
New File dialog doesn't accept Enter for default

### PR DESCRIPTION
**Pull request by dhuebner**
#### What it does

Allow to accept the File Dialog by pressing `Enter` and canceling by pressing `Escape`. 

See #13582 

#### How to test

In `theia-main-menu.test.ts` the "Create file via New File menu and accept" test uses `Enter` to accept the File Dialog an save a file. 

Or follow the description in  #13582 

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
@dhuebner is this a problem on Mac only? I can accept the file dialog with enter on Windows.

**Comment by dhuebner** [comment]
@tsmaeder 
No, I don't think it is Mac specific. The problem was, that the tree widget eats the Enter and ESC key stroke events so that the dialog can not be closed using keyboard. One need to click on the corresponding buttons or use TAB to jump to them and then hit Enter.

**Comment by dhuebner** [comment]
@tsmaeder 
Now, I see. You need to use the menu "File" -> "New File...". Then save the untitled file and you will get this dialog.

**Comment by tsmaeder** [comment]
That's what I'm doing: in the video, I just press "Enter" when the "Save as"-dialog opens. What am I missing?


https://github.com/user-attachments/assets/a82dd52a-ba23-42a4-b56b-f0b35b6733fe

**Comment by dhuebner** [comment]
@tsmaeder 
The problem only occurs when running in the browser. In the electron version the system dialog is used and works fine.
Sorry for the confusion, I need to better explain how to test.

**Review by tsmaeder — APPROVED** [review]
Seems to do the trick. I'm still not convinced we should not handle the keyboard focus differently, but that's a larger discussion.

**Comment by dhuebner** [comment]
@tsmaeder 
Thank you for the review!

**Pull request merged**
