### PR TITLE
Update Themes

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Updates the specification of our default themes to match recent VSCode.

#### How to test

1. Open a TS file.
2. Move through the built-in themes.
3. Observe that they behave as expected.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23884

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by msujew — APPROVED** [review]
The updated themes look good. I could not notice any regressions 👍 

Has the CQ already been approved? Do you mind linking it?

**Comment by colin-grant-work** [comment]
@msujew, I'm having a lot of trouble accessing the CQ - changed my password several times, but still can't log into Bugzilla. I'll try to resolve it with the Eclipse  Foundation, but in the meantime, I've put the link in the description...

**Comment by ccorn** [comment]
`grep`ing through `package.json` for `theme` leads me to this question:

What about `vscode.vscode-theme-seti`? That one has not been updated.
(I suppose that there is a reason. Just asking.)

**Comment by colin-grant-work** [comment]
@ccorn, this was related to work on semantic colorization, and file themes were not part of that work.

**Comment by JonasHelming** [comment]
@colin-grant-work  CQ is approved ;-)

**Comment by colin-grant-work** [comment]
> @colin-grant-work CQ is approved ;-)

@JonasHelming, thanks for the heads up, and thanks for pushing it through! 🙏

**Pull request merged**
