### PR TITLE
Replace `nsfw` with `@parcel/watcher`

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Continuation of https://github.com/eclipse-theia/theia/pull/12784

Closes https://github.com/eclipse-theia/theia/issues/14015

Replaces our `nsfw` dependency with `@parcel/watcher` to align with vscode.

#### How to test

Test file watching related capabilities and confirm that there are no regressions:
* Editing files on the file system should be reflected in the editor
* Editing `settings.json` should be reflected in changes in the preferences
* Editing `launch.json` should be reflected in the debug view

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by msujew** [comment]
@tsmaeder I'll be on vacation for a week starting Friday. In case you want to change anything in the PR, please feel free :)

**Comment by tsmaeder** [comment]
There is a basic scenario that seems to be broken with the new watcher: 

1. Open a workspace with the theia source
2. Do `yarn` to populate the node_modules folder
3. Expand some the folders inside the node_modules folder
4. In the Windows explorer, select all folders inside the node_modules folder
5. Press delete
6. Observe: Windows moves the folders to the trash
7. Observe: the changes inside the node_modules folder are not picked up inside Theia file explorer

In master, the deletion of the modules is reflected in the Theia file navigator

**Comment by msujew** [comment]
@safisa It might fix the issue, yes.

**Comment by msujew** [comment]
@planger Could you have a look at the failing playwright tests? The errors are not reproducible on Windows and the tests don't run for me on Ubuntu (Gitpod) for some reason.

**Comment by tsmaeder** [comment]
I've looked into the failures of the Playwright tests. They only fail on Linux. IMO, this is a bug in the "compressed tree" and is probably unrelated to the change at hand. So, with the resources folder from the playwright test, you can do the following scenario:

1. delete "nestedFolder2"
2. Observe: there is no change visible and a `console.log` in the rendering of the compressed rows is not hit.
3. Select the row in question
4. Observe: `nestedFolder2` disappears from the row.

The same events seem to be sent on Linux and Windows, so my suspicion is that this is a reordering of async  blocks du to the different timings on the respective platforms.

**Comment by planger** [comment]
Thanks for looking into this @tsmaeder! This makes sense, looking at the logs briefly.

We can take a look at the failing test in more detail, but I also suspect it might be an actual UI issue on Linux. To avoid having failing tests, I would suggest skipping this failing test for now and open a new issue.

**Review by tsmaeder — APPROVED** [review]

**Pull request merged**
