### PR TITLE
fix next publishing and temporarly disable typedocs

### PR DESCRIPTION
**Pull request by paul-marechal**

### CODE REVIEW

**Review by marcdumais-work — APPROVED** [review]
LGTM - merging will be the real test, to confirm we are again able to  publish `next` packages!

**Review by vince-fugnitto — APPROVED** [review]
:champagne:

**Comment by marcdumais-work** [comment]
Publish failed, because of an authentication issue. I'll try re-setting the `npm token` and restart the CI, when I have a minute.

**Comment by marcdumais-work** [comment]
This might be the issue: https://github.com/lerna/lerna/issues/2788

I'll try setting a normal token instead of an automation token. If confirmed, it means that we can't enable 2 FA on the npm account.

**Pull request merged**
