### PR TITLE
Use webcontents ID in `isSender` check

### LINKED ISSUE #11600: Cannot create new window after reload the current empty window
### Bug Description:

New Window does not work after reload the current window.  

BTW, you can open a new window (window 2) before reload it (window 1) and reload the window 2. And then, the menu item New Window of window 2 (that means window 2 is actived) does not work anymore, but the menu item New Window of window 1 (that means window 1 is actived) still works.

### Steps to Reproduce:

1. Run the electron example: (We can see the window 1)
    

2. Reload the window: (Reload the window 1)
    
    

3. Click the New Window in the menu but it does not work: (Cannot create a new window)
    

### Additional Information

- Operating System: MacOS
- Theia Version: master branch

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #11600 according to @kittaakos suggestion.

#### How to test

1. Run the electron example: (We can see the window 1)
1. Reload the window: (Reload the window 1)
1. Click the New Window in the menu, and it _does_ work.
---
1. Open a file and make it dirty.
1. Click to exit the application.
1. See a dialog prompting you for whether you want to exit.
1. Click no
1. The window should remain open.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
Thank you for the prompt fix!

> #### How to test
> 1. Run the electron example: (We can see the window 1)
> 2. Reload the window: (Reload the window 1)
> 3. Click the New Window in the menu, and it _does_ work.

It does not work for me. I have checked out 4a646ebcf2b and built it locally. It also does not work when opening a new window with <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>. I am investigating what's going on.


https://user-images.githubusercontent.com/1405703/189289041-8ae43ee3-c638-4949-9980-d3c2e0baa8d1.mp4

**Comment by kittaakos** [comment]
[This](https://github.com/colin-grant-work/theia/compare/bugfix/empty-window-creation...kittaakos:theia:remove-window-multiplexer) change fixes the issue for me. I think the window multiplexer should be removed from the map when the window reloads/closes.

**Comment by colin-grant-work** [comment]
Since this doesn't seem to have improved anything, I'll close it. @kittaakos, if you'd like to make a PR with your changes, feel free.

**Comment by kittaakos** [comment]
It fixes the reload error described in #11600 for me.

**Pull request closed without merging**
