### PR TITLE
[vsx-registry] Use new 'query' API endpoint

### PR DESCRIPTION
**Pull request by spoenemann**
#### What it does
The root issue is https://github.com/eclipse/openvsx/issues/163: Some API endpoints of Open VSX were written such that they return HTTP status 200 even when the resource identified by the URL does not exist, which is inconsistent with HTTP standards. The motivation for this was that fetching data with a non-OK response from the browser always leads to an error being logged in the console (see https://bugs.chromium.org/p/chromium/issues/detail?id=124534). This is being improved in https://github.com/eclipse/openvsx/pull/183 by introducing a new POST endpoint that should be used by Theia and other IDEs. The originally used endpoints will retain the current behavior for a few weeks, but then they'll be changed to return status 404 when the resource does not exist.

This PR changes VSXRegistryAPI to use the new API endpoint of Open VSX. The PR should not be merged until the upstream change has been deployed, but it is already possible to test this.

#### How to test
 * Start a [Gitpod workspace at eclipse/openvsx#183](https://gitpod.io/#https://github.com/eclipse/openvsx/pull/183)
 * Set the Theia environment variable `VSX_REGISTRY_URL` to the URL obtained by typing `gp url 8080` in the openvsx workspace.
 * Start Theia, open the Network tab in the developer tools and observe the requests to the `query` endpoint. Most of them return an empty array because the test instance of openvsx has very few published extensions, but some return the requested extension metadata.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by marechal-p — APPROVED** [review]
Could not test because of a Gitpod error, but LGTM code-wise.

**Review by azatsarynnyy — COMMENTED** [review]
Can't start OpenVSX registry
image

**Comment by svenefftinge** [comment]
@spoenemann the Gitpod link points to a merged PR where the branch is deleted. So it is not openable.
But change looks good.

**Comment by marechal-p** [comment]
@svenefftinge is this a Gitpod limitation? Sounds like it would help being able to open merged changes, just like we tried here.

**Comment by spoenemann** [comment]
I forgot to mention that after deleting the PR branch you can still test the new API using the master branch of Open VSX:

https://gitpod.io/#https://github.com/eclipse/openvsx

**Pull request merged**
