### PR TITLE
fix #8171: Upgrade vscode-ripgrep to 1.8.0

### LINKED ISSUE #8171: Upgrade vscode-ripgrep, to solve proxy issue
### Bug Description:
Current used version of vscode-ripgrep doesn't handle proxy settings correctly. This is fixed in version 1.8.0. Upgrade yarn.lock file to use this version

vscode-ripgrep@^1.2.4:
  version "1.8.0"
  resolved "https://registry.yarnpkg.com/vscode-ripgrep/-/vscode-ripgrep-1.8.0.tgz#dfe7c2ae2a2032df8a8108765c2feef73474888a"
  integrity sha512-/Q5XtePkTLLi8yplr5ai24pVEymRF62xH9xXrtj35GTaDCJg3zq1s1/L1UqhVbfNDv4OcMBYjyIAt/quEi3d5w==
  dependencies:
    https-proxy-agent "^4.0.0"
    proxy-from-env "^1.1.0"

### Steps to Reproduce:

1. do yarn behind a proxy
2. without the upgraded vscode-ripgrep it will fail like #7384

### PR DESCRIPTION
**Pull request by datou0412**
Signed-off-by: 二凢 <dingyu.wdy@alibaba-inc.com>

#### What it does

Fixes: #8171 

Upgrade vscode-ripgrep to 1.8.0.

#### How to test

- yarn start:browser
- open a workspace
- search in workspace
image
- quick open any file
image

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by shahidhs-ibm** [comment]
+1 

We want to upgrade `vscode-ripgrep` version for different reason. The current version of vscode-ripgrep in che-theia i.e. [1.7.0](https://github.com/eclipse/che-theia/blob/7.16.0/yarn.lock#L12931) resolve to `ripgrep` version [v11.0.1-6](https://github.com/microsoft/vscode-ripgrep/blob/v1.7.0/lib/postinstall.js#L19) which don't have support for s390x in their [release](https://github.com/microsoft/ripgrep-prebuilt/releases/tag/v11.0.1-6) for unknown reasons. 
This is causing below error when we are trying to build che-theia on s390x:
```
#50 245.0 error /home/theia-dev/theia-source-code/che-theia/node_modules/vscode-ripgrep: Command failed.
#50 245.0 Exit code: 1
#50 245.0 Command: node ./lib/postinstall.js
#50 245.0 Arguments:
#50 245.0 Directory: /home/theia-dev/theia-source-code/che-theia/node_modules/vscode-ripgrep
#50 245.0 Output:
#50 245.0 Finding release for v11.0.1-6
#50 245.0 GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-6
#50 245.0 Deleting invalid download cache
#50 245.0 Downloading ripgrep failed: Error: Asset not found with name: ripgrep-v11.0.1-6-s390x-unknown-linux-gnu.tar.gz
#50 245.0     at getAssetFromGithubApi (/home/theia-dev/theia-source-code/che-theia/node_modules/vscode-ripgrep/lib/download.js:188:15)
#50 245.0     at process._tickCallback (internal/process/next_tick.js:68:7)
#50 245.0 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#50 ERROR: executor failed running [/bin/sh -c if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     cd plugins && ./foreach_yarn]: buildkit-runc did not terminate successfully
```

Upgrading `vscode-ripgrep` version to 1.8.0 will resolve the issue for s390x.

**Comment by marcdumais-work** [comment]
I just restarted the failed CI build after clearing its Travis cache.

**Comment by marcdumais-work** [comment]
It failed again :(

@datou0412 : the way this PR works, we are changing the version range for our `vscode-ripgrep` runtime dependency, so that the minimal acceptable version is the (currently) latest one, that correctly supports working behind a proxy to fetch the `ripgrep` executable, after npm package install. 

That's arguably one way to go about it. However it would also work to remove the `vscode-ripgrep` entry from the repo's `yarn.lock` and rebuild - the latest version then would be picked-up and saved in `yarn.lock`, which we can then check-in. 

The main difference is that, with the later approach, we leave downstream projects free to continue to use their current `vscode-ripgrep` version if they want, that's currently pinned in their app's `yarn.lock`. Probably many will want to switch to the latest version, but there could be some who will not. Should we force them?

**Comment by marcdumais-work** [comment]
> It failed again :(

I believe that the failure is unrelated to the content of the PR. The root cause is probably that the PR originates from a fork and so the encrypted environment variables are disabled:

https://travis-ci.com/github/eclipse-theia/theia/jobs/363120105#L75

One such variable is the GitHub token. Not having it usually this results in frequent failure to download the `ripgrep` executable from GitHub (unauthenticated API rate limit), and consequently the failure of CI tests that rely on `ripgrep`

In theory we should be able to get it to pass eventually if we re-try a few times.

**Comment by datou0412** [comment]
> > It failed again :(
> 
> I believe that the failure is unrelated to the content of the PR. The root cause is probably that the PR originates from a fork and so the encrypted environment variables are disabled:
> 
> https://travis-ci.com/github/eclipse-theia/theia/jobs/363120105#L75
> 
> One such variable is the GitHub token. Not having it usually results in frequent failure to download the `ripgrep` executable from GitHub (unauthenticated API rate limit), and consequently the failure of CI tests that rely on `ripgrep`
> 
> In theory we should be able to get it to pass eventually if we re-try a few times.

Should I do something?

**Comment by marcdumais-work** [comment]
> @datou0412 : the way this PR works, we are changing the version range for our `vscode-ripgrep` runtime dependency, so that the minimal acceptable version is the (currently) latest one, that correctly supports working behind a proxy to fetch the `ripgrep` executable, after npm package install.
> 
> That's arguably one way to go about it. However it would also work to remove the `vscode-ripgrep` entry from the repo's `yarn.lock` and rebuild - the latest version then would be picked-up and saved in `yarn.lock`, which we can then check-in.
> 
> The main difference is that, with the later approach, we leave downstream projects free to continue to use their current `vscode-ripgrep` version if they want, that's currently pinned in their app's `yarn.lock`. Probably many will want to switch to the latest version, but there could be some who will not. Should we force them?

@akosyakov Do you have an opinion on this? A minimal fix would not require changing the dependency's version range but also would not affect/benefit downstream projects unless they also upgrade their yarn.lock for this dependency.

**Comment by marcdumais-work** [comment]
> Should I do something?

Nothing to do I think about the failing CI.

**Comment by marcdumais-work** [comment]
If we go with the dependency range change, it might be good to mention it in CHANGELOG.md - it might break downstream builds if they use `yarn --frozen-lockfile`

**Comment by marcdumais-work** [comment]
> In this case it would mean leaving the version range for `vscode-ripgrep` as it is on master and instead updating the related entry in `yarn.lock`.

I have created a PR that does this: https://github.com/eclipse-theia/theia/pull/8280

**Comment by marcdumais-work** [comment]
This PR is now obselete, following https://github.com/eclipse-theia/theia/pull/8280 being merged. Closing

**Pull request closed without merging**
