### PR TITLE
Change Debug Panel reveal to false

### PR DESCRIPTION
**Pull request by vincentjocodes**
#### What it does

When Debug console is launched it will open but won't reveal. Syncs with VSCode behavior. 

Discussed in https://github.com/eclipse-theia/theia/discussions/8085.

#### How to test

Load this plugin in Theia: https://github.com/vincentjocodes/theia-hello-world-plugin. 
Load this plugin in VSCode: https://github.com/kittaakos/output-channel-example. 

You will notice that the Debug Panel will not show but only the Output Panel on both.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
> their default values.

There should some difference between the VS Code and Theia debug config defaults. Just a guess though.

**Comment by vince-fugnitto** [comment]
> > their default values.
> 
> There should some difference between the VS Code and Theia debug config defaults. Just a guess though.

I noticed that the current default is inconsistent with vscode (vscode defaults to [`openOnSessionStart`](https://github.com/microsoft/vscode/blob/b988f09b1e7c9aca37b8f312ba34c6422757617b/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L232)) but no matter if we set the value to `openOnSessionStart` or `openOnFirstSessionStart` the debug console is never opened with these changes (when executing the mocha tests for example).

https://github.com/eclipse-theia/theia/blob/4c63f08a6283f19f6f28727727378f7c1e38e316/packages/debug/src/browser/debug-preferences.ts#L38-L42

**Comment by vincentjocodes** [comment]
> Do we instead want:
> 
> ```ts
>  this.console.openView({
>   reveal: true
>   activate: false
> });
> ```
> 
> We want the view to open (reveal) but probably not activate if the options are respected.
> Else, we might need to look at uses of `openSession` and update the `reveal` when necessary like the following:
> 
> ```ts
> this.openSession(session, { reveal: false }
> ```

@vince-fugnitto Thanks for the suggestion! This works with the sample application I built with. Please take another look.

**Comment by vince-fugnitto** [comment]
Restarted the CI and it passed, I'll merge :)
Thank you for your contribution @vincentjocodes! 👍

**Comment by vincentjocodes** [comment]
> Restarted the CI and it passed, I'll merge :)
> Thank you for your contribution @vincentjocodes! 👍

Thanks! I appreciate it.

**Pull request merged**
