### PR TITLE
plugin: support deprecated code completion items

### LINKED ISSUE #8310: Deprecated code completions crash
### Bug Description:

When providing code completion result with deprecated: true property there is an error on code completion and no suggestions are displayed.

### Steps to Reproduce:

[lsp-sample-deprecated.zip](https://github.com/eclipse-theia/theia/files/5028388/lsp-sample-deprecated.zip) contains the vscode extension source code for reference.
[vsix.zip](https://github.com/eclipse-theia/theia/files/5028409/vsix.zip) contains two vsix files lsp-sample-deprecated-item-1.0.0.vsix that provides deprecated code completion. It works on vscode but not on theia. The other one provide code completions without deprecated items and it work on both.

1. Deploy vscode extension lsp-sample-deprecated-item-1.0.0.vsix
2. Create empty text file
3. Try to do code completion.

Nothing works and the browser console shows this error:

Uncaught Error: Cannot read property 'Deprecated' of undefined

TypeError: Cannot read property 'Deprecated' of undefined
    at asCompletionItem (c:\Users\i066470\AppData\Local\Temp\vscode-unpacked\lsp-sample-deprecated-item-1.0.0.vsix\extension\client\node_modules\vscode-languageclient\lib\protocolConverter.js:244:50)
    at Array.map (<anonymous>)
    at asCompletionResult (c:\Users\i066470\AppData\Local\Temp\vscode-unpacked\lsp-sample-deprecated-item-1.0.0.vsix\extension\client\node_modules\vscode-languageclient\lib\protocolConverter.js:171:26)
    at http://localhost:3000/vs/editor/editor.main.js:1532:31

On VS code it works like this:

vsc

### Additional Information

- Operating System: windows, debian
- Theia Version: master

### LINKED ISSUE #8475: [vscode] css code completion doesn't work - Cannot read property 'Deprecated' of undefined
### Bug Description:
There are no completion results when working on css file.

### Steps to Reproduce:

1. Create an empty css file.
2. Hit ctrl + space.  

There are no results:
css-theia

In addition the following error appears in browser console:
```
TypeError: Cannot read property 'Deprecated' of undefined
    at y (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163850)
    at c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163962
    at C (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163998)
    at Array.map (<anonymous>)
    at asCompletionResult (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:170409)
    at http://localhost:3000/vs/editor/editor.main.js:1607:31
```

vscode:
css-vscode

### Additional Information

- Operating System: Windows 10
- Theia Version: master

### PR DESCRIPTION
**Pull request by esterw1109**
Issue-8310: Deprecated code completions crash

Signed-off-by: Esther Perelman <wwr1109@gmail.com>

#### What it does
Fixes #8310 
Fixes #8475 

#### How to test
Steps to reproduce on #8310 

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by shahar-h** [comment]
I can confirm that #8475 is resolved with this fix.

**Review by vince-fugnitto — APPROVED** [review]
The changes look good to me :+1: 

I confirmed that the `vscode-builtin-css-language-features` extension works correctly
(provides auto-completion).

**Comment by amiramw** [comment]
#8310 with this change display code completion which didn't happen before.
 
However it doesn't show any indication for the deprecated one:
image

While in vscode it showed:
image

@shahar-h @vince-fugnitto, did you get the same behavior in your tests? 

If so do you think this gap should be part of this PR or a separate issue?

**Comment by shahar-h** [comment]
It's strange, I couldn't find any deprecated completion items in css.
However, I noticed that in your sample repo you use `deprecated` property in completion item, which is deprecated in favor of `tags`, see: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion.
 
Try to use `tags` instead, and in addition maybe also `deprecated` property should be supported in `CompletionItem`.

**Comment by amiramw** [comment]
Also for `tags: [1]` (1 is deprecated) I don't get any indication in the UI.

**Review by amiramw — APPROVED** [review]
Appreved, 
@esterw1109 please open another issue for the UI indication

**Comment by danidoedel** [comment]
When will this PR be merged? This bug bothers me quite some time already and I can't wait to see it fixed 😁

**Comment by EstherPerelman** [comment]
> Approved,
> @esterw1109 please open another issue for the UI indication

Opened #8552

**Pull request merged**
