### PR TITLE
Align the Comments plugin API with the latest vscode

### PR DESCRIPTION
**Pull request by vinokurig**
#### What it does

Align the Comments plugin API with the latest vscode: https://github.com/microsoft/vscode/blob/42226a9169340756897e12b65045c721af9f860b/src/vs/vscode.d.ts#L11411-L11695

This is dummy implementation, there is an issue to replace it with full implementation: https://github.com/eclipse-theia/theia/issues/8492

#### How to test

1. Remove `"@theia/git": "^1.5.0"` from `examples/browser/package.json` file.
2. Download [vscode-git-1.44.2](https://github.com/che-incubator/vscode-git/releases/download/1.44.2/vscode-git-1.44.2.vsix) and copy it to the `plugins` folder.
3. Download the [vscode GitHub Pull request plugin](https://github.com/microsoft/vscode-pull-request-github/releases/download/0.19.0/vscode-pull-request-github-0.19.0.vsix) and copy it to the `plugins` folder.
4. Apply GitHub authentication provider:
* Git clone the [github authentication plugin](https://github.com/vinokurig/github-authentication-plugin.git) to the `plugins` folder.
* Paste [your GitHub token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) to the plugin [here](https://github.com/vinokurig/github-authentication-plugin/blob/89b951d1a4280aee62635f5fa2b99feaf92aeacb/src/github-authentication-plugin.ts#L26).
* Compile the plugin. Note that errors might appear in the compilation log but it doesn't prevent the plugin from working properly.
5. Start Theia and sign in the GitHub provider:
screenshot-serverg0cevid1-che-dev-server-3010 192 168 99 253 nip io-2020 09 23-11_42_23

It should be possible to open a pull-request in the editors view:
screenshot-localhost_3030-2020 09 21-17_07_34

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by benoitf** [comment]
Hi @vinokurig 

there is something wrong with the test steps

` vscode GitHub Pull request plugin` has entry

```json
  "extensionDependencies": [
    "vscode.git"
  ],
```

but the referenced git extension has package.json
```json
  "name": "vscode-git",
  "publisher": "vscode",
```

so FQN is `vscode.vscode-git` (incorrect)

so it's downloading vscode.git@latest which is 1.49.1 and then there are duplicates

If I look at https://open-vsx.org/api/vscode/git/1.44.2/file/vscode.git-1.44.2.vsix

I've
```json
  "name": "git",
  "publisher": "vscode",
```

**Comment by vinokurig** [comment]
@benoitf I've updated the `How to test` section and the `vscode-git` extension. Now it works.

**Comment by azatsarynnyy** [comment]
FYI: https://github.com/eclipse-theia/theia/pull/8525 is approved, so you can get rid of step 5 in `How to test`

**Comment by vinokurig** [comment]
@akosyakov @benoitf any updates?

**Comment by azatsarynnyy** [comment]
> How to test
> ...
> 5. Merge the onStartupFinished activation event to Theia, compile and start Theia

@vinokurig is step 5 still mandatory? I believe the steps for testing it can be a bit simpler if this PR is rebased on the master changes :wink:

**Comment by vinokurig** [comment]
@azatsarynnyy You are right, I merged it today, updated the description, thank you.

**Comment by vinokurig** [comment]
And rebased :smile:

**Review by azatsarynnyy — COMMENTED** [review]
> Git clone the github authentication plugin to the plugins folder

Doesn't `GitHub Pull Requests` VS Code extension already provide GitHub Authentication Provider?

I suppose `github authentication plugin` has to be compiled first. Because I got
image

After cloning `github authentication plugin`, I've tried to compile it but:
```
node_modules/@theia/plugin/src/theia-proposed.d.ts:618:34 - error TS1005: ';' expected.

618         readonly items: readonly TimelineItem[];
                                     ~~~~~~~~~~~~


node_modules/@theia/plugin/src/theia-proposed.d.ts:618:47 - error TS1011: An element access expression should take an argument.

618         readonly items: readonly TimelineItem[];
                                                  


node_modules/@theia/plugin/src/theia-proposed.d.ts:679:1 - error TS1128: Declaration or statement expected.

679 }
    ~


error Command failed with exit code 2.
```

**Review by vince-fugnitto — COMMENTED** [review]
> After cloning `github authentication plugin`, I've tried to compile it but:

I experienced the same issue trying to compile the provided plugin.

**Comment by vinokurig** [comment]
@azatsarynnyy 
> Doesn't GitHub Pull Requests VS Code extension already provide GitHub Authentication Provider?

No, vscode has its own [built-in GitHub authentication provider](https://github.com/microsoft/vscode/blob/8eb9cdaba94b6d23f87810c97fd81803726e1ecf/extensions/github-authentication/src/extension.ts#L25). In Che we are going to have such provider in the [github-auth plugin](https://github.com/eclipse/che-theia/pull/841).
> I suppose `github authentication plugin` has to be compiled first.

Yes, it must be compiled before the theia start.

@azatsarynnyy @vince-fugnitto
> After cloning github authentication plugin, I've tried to compile it but: ...

Sorry, I forgot to mention that those errors do not prevent the plugin from working properly.
I don't want to spend time on it because its just a sample plugin that is not going to be merged anywhere.
I updated the description with it.

**Comment by vinokurig** [comment]
@azatsarynnyy @vince-fugnitto Could you please review it again?

**Comment by azatsarynnyy** [comment]
Thanks @vinokurig!

I opened a workspace with Theia sources. It shows me that the plugin activation is in progress and never ends
image

Also, GitHub view is empty
image

**Comment by azatsarynnyy** [comment]
When I'm switching to GitHub view
```
root ERROR TypeError: Cannot use 'in' operator to search for 'uri' in undefined
    at http://localhost:3000/38.bundle.js:1008:51
    at http://localhost:3000/bundle.js:139879:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:139894:39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:140021:29)
    at SelectionService.set (http://localhost:3000/bundle.js:144341:44)
    at TreeViewWidget.../../packages/core/lib/browser/tree/tree-widget.js.TreeWidget.updateGlobalSelection (http://localhost:3000/bundle.js:133615:41)
    at TreeViewWidget.../../packages/core/lib/browser/tree/tree-widget.js.TreeWidget.doFocus (http://localhost:3000/bundle.js:133726:18)
    at HTMLDivElement.<anonymous> (http://localhost:3000/bundle.js:134314:78)
    at TreeViewWidget.../../packages/core/lib/browser/tree/tree-widget.js.TreeWidget.onActivateRequest (http://localhost:3000/bundle.js:133712:19)
    at TreeViewWidget.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (http://localhost:3000/bundle.js:27117:22)

```

**Comment by vinokurig** [comment]
@azatsarynnyy @vince-fugnitto 
Looks like you haven't sign in the GitHub authentication provider, see item 5 of the description. The error is not reproduced if the GitHub plugin is authenticated.

**Comment by azatsarynnyy** [comment]
> Looks like you haven't sign in the GitHub authentication provider, see item 5 of the description. The error is not reproduced if the GitHub plugin is authenticated.

It seems so...
Now I can see the PR
image

Shouldn't it warn the user in the UI when one didn't sign in the GitHub authentication provider?
Instead of just logging an error `root ERROR TypeError: Cannot use 'in' operator to search for 'uri' in undefined`

**Comment by vinokurig** [comment]
@azatsarynnyy 
> Shouldn't it warn the user in the UI when one didn't sign in the GitHub authentication provider?
Instead of just logging an error root ERROR TypeError: Cannot use 'in' operator to search for 'uri' in undefined

This PR is about updating existed dummy API with changed interfaces from vscode. The GitHub plugin mentioned here is just an example to show that it works better with this changes. Looks like this error is caused by an empty tree which is shown instead of login panel:
screenshot-github com-2020 10 05-10_43_40
This error should be fixed by https://github.com/eclipse-theia/theia/issues/7178.

**Comment by vinokurig** [comment]
@azatsarynnyy @vince-fugnitto any updates?

**Comment by benoitf** [comment]
I will test right now

**Review by benoitf — APPROVED** [review]
Tested and works as expected
I'm able to use github PR plug-in

image

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that it works with the steps described:

<div align='center'>

image

</div>

Do we need to update the `changelog` with the breaking changes (renaming of namespaces, methods)?

**Comment by benoitf** [comment]
I think that changelog breaking change is kind of optional as
- people will expect that theia match the VS Code API change
- I'm not sure we ever introduce changelog for VS Code API compliance changes (only for Theia extensions)

**Comment by vinokurig** [comment]
I don't think that it has to be mentioned in the changelog because this is just an update of the existing dummy API.

**Comment by vince-fugnitto** [comment]
> I don't think that it has to be mentioned in the changelog because this is just an update of the existing dummy API.

No problem, just wanted to bring it up if it was something we wanted to add.

**Pull request merged**
