### PR TITLE
fall back to default foreground and background colors

### LINKED ISSUE #6991: textmate coloring for some vscode themes is bogus
for instance for `Tomorrow Night Blue` some text in README.md colored differently than in VS Code

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #6991: use proper default colors for all themes 

#### How to test

- open README.md file from this repo and look that everything is colored as in VS Code for all contributed themes
- keep the file opened, reload the page and check again

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@corneliusludmann Could you check again?

**Comment by akosyakov** [comment]
It also fixes https://github.com/eclipse-theia/theia/issues/6951

**Comment by akosyakov** [comment]
@vince-fugnitto Could it be included in the current release? or it is too late?

**Comment by corneliusludmann** [comment]
> @corneliusludmann Could you check again?

Works! Great! Thank you.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Could it be included in the current release? or it is too late?

Sorry, I just got to work :) it looks fine to me I don't think there's anything breaking and it fixes a pull-request that was introduced this month anyways.

**Pull request merged**
