### PR TITLE
Verify checksums while downloading plugins

### PR DESCRIPTION
**Pull request by perrinjerome**
#### What it does

Fixes: #8799 

The syntax of the URLs in `theiaPlugins` of `package.json` is extended so that we can define the expected integrity checksums in URL fragment - this way it remain compatible with existing usages (when there is no hash in URLs the checksums are not verified). The checksums are defined using https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity hash format. The verification part is done using https://www.npmjs.com/package/ssri

This is a bit similar to what yarn uses for its `yarn.lock` file - but the usage is different, unlike yarn which automatically computes the signature on the first download, here we would have to compute and add "manually" the signatures in `package.json`.

#### How to test

The `package.json` have been modified in this PR to include the actual hashes. One way of testing can be to modify a signature in `package.json`, run `yarn download:plugins` and check that an error is reported because the downloaded plugin does not match signature.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by perrinjerome** [comment]
Please tell me what you think, I don't like so much that hashes have to be computed manually. Maybe `yarn download:plugins` could edit the `package.json` in place to add the checksum in the URL on first successful download.
Or maybe it could be another format ( storing the hashes in another key in `package.json` or in another file ). Or maybe you don't like this idea at all :)

**Comment by vince-fugnitto** [comment]
> Please tell me what you think, I don't like so much that hashes have to be computed manually. 

I also do not like that hashes need to be computed manually.

> Or maybe you don't like this idea at all :)

I don't really like the idea of having to compute hashes for each of the `builtin` plugins that an application developer wants to add to their product. I'm not sure I understand the issue #8799, the `yarn download:plugins` script is used to download builtin (included with the application) plugins for a given custom application, and is generally used to pull from `open-vsx`. I'm not sure in it's intended use why the checksums are necessary.

**Comment by marechal-p** [comment]
I am in favor of this PR if we have a `theia-plugins.lock` file that would be a json mapping for the hashes.

@eclipse-theia/core Anyone against this PR?

**Comment by perrinjerome** [comment]
Thank you for your feedback.

That's a good point that nowadays open-vsx is the best choice for downloading plugins. I started to be concerned about the download of plugins being not verified a few months ago, when plugins were downloaded from github releases. With github releases, maintainers can always edit the artifacts from releases at any time, so if I have a `package.json` downloading from extensions from github release, there's a risk that one day this release be removed, or that it becomes a different file, maybe malware. open-vsx prevents all this, since it does not allow removing/altering an already published extension, so using open-vsx really reduces this risk.

A `theia-plugins.lock` seems feasible. https://www.npmjs.com/package/ssri (the package used to verify signatures in this first prototype) also have API to compute signatures.

I feel it would be "too much" to introduce `theia-plugins.lock` only for the purpose of verifying signatures though, especially now that I realised that open-vsx solves most of the problem. On the other hand, this could also allow for a further extensions, for example in `plugins.json` we could define something like:
```js
"theiaPlugins": {
 // "publisher on openvsx/extension on openvsx": "version",
  "vscode/bat": "latest",
}
```
then `theia download:plugins` would resolve "latest" from open-vsx (using API https://open-vsx.org/api/vscode/bat/latest ), see that it is 1.5.1, download 1.5.1 and write in `theia-plugins.lock` the resolved URL for this extension and the corresponding hash, in a way similar to what yarn is doing.

**Comment by perrinjerome** [comment]
I took another look at this and implemented in https://github.com/eclipse-theia/theia/pull/8864 the changes discussed here:
 * use a `theia-plugins.lock` fab50048b851c27938a898c95ac04eb7823d2717
 * allow a new syntax to list plugins as `publisher/extension@version` 9a5e8908146680f0747d0ceee3966893f3613a91 and switch package json to this new syntax 97c29d2a4a0f751dbdbcfcdb837edfe312f8e9f3 
Please let me know what you think.

This PR can probably be closed now, that first version with a process of manually defined hashes in URL was "too manual"

**Comment by perrinjerome** [comment]
Oh sorry, there's no reason to keep this open.
For the records, we solved our need for downloads with verified checkdums by using an ad-hoc download utility.

**Pull request closed without merging**
