### PR TITLE
fixes #12112 Removing exited thread from threads

### LINKED ISSUE #12112: Incorrect handling of exited threads in debugger
### Bug Description:

If debug thread is exited it does not removed from the threads panel till next stop and Threads request to debug adapter.
This leads to incorrect display and sometimes to broken debugger behavior.

### Steps to Reproduce:

1. launch debugger of some language with debug adapter
2. See that no threads shown, only session 
3. stop at breakpoint
4. continue to thread exit
5. see that threads panel still shows thread in a Running state 

Expected: no running threads shown, showing Session only, as it was at very beginning.
Things are getting worse if there's multiple stopped threads and they all continued to the exit.

threads-3

On the picture Thread 24 already exited and not running.
Expected that threads panel looks like this when no debuggable threads available

session

### Additional Information

It seems it should be fixed here https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/debug-session.tsx#L912, need to remove thread from `this._threads` on thread exited.

- Operating System: any
- Theia Version: cloned from master

### PR DESCRIPTION
**Pull request by EvilBeaver**
#### What it does
Fixes #12112

#### How to test
Check that when multiple threads existed, and one of them exited - it removed from threads panel

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
Thank you for your contribution :+1: 

In order to accept your changes please be sure to sure to sign the [eclipse contributor agreement (eca)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) with the same email as your authorship.

**Comment by EvilBeaver** [comment]
@vince-fugnitto should I close this PR and recommit changes with a proper signature? I don't understand what I should do, sorry

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto should I close this PR and recommit changes with a proper signature? I don't understand what I should do, sorry

@EvilBeaver you don't need to modify or close the pull-request, just be sure to [sign the agreement](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) with the same email as authorship and we can re-run the `eclipsefdn/eca` CI check.

**Comment by EvilBeaver** [comment]
@vince-fugnitto I've created eclipse account and signed agreement. Hope I've done everything correct :)

**Comment by EvilBeaver** [comment]
@vince-fugnitto can you give any clues to why ubuntu tests could fail?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto can you give any clues to why ubuntu tests could fail? It seems there's some external problem on build agents...

No problem, there is an issue tracking the ubuntu tests which execute our api test-suite as it is currently known to be flaky (https://github.com/eclipse-theia/theia/issues/12081).

**Comment by EvilBeaver** [comment]
@vince-fugnitto thanks. Can I say that PR is fine and I shouldn't do anything else with it to have it merged?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto thanks. Can I say that PR is fine and I shouldn't do anything else with it to have it merged?

Right, we just need to review the changes and confirm it is correct. I haven't had the time to look into it yet but I will try shortly.
@kittaakos would you like to take a look as well since it affects debug functionality?

**Comment by kittaakos** [comment]
Thanks for the heads-up, @vince-fugnitto 👍 

I could not verify it with the HEAD of Theia, but I applied the change from this PR on 1.31.1, and the [`Marus/cortex-debug`](https://github.com/Marus/cortex-debug/) debugger still works in the Arduino IDE. For the record, I could not reproduce #12112 with the `cortex-debug` VS Code extension either.

**Comment by EvilBeaver** [comment]
> I could not reproduce https://github.com/eclipse-theia/theia/issues/12112 with the cortex-debug VS Code extension either.

To reproduce this, you'll need to have no threads debugged (all exited), but debug session still active. I'm not familiar with cortex-debug, but it's hard to achieve in node.js for example, cause it's usually single threaded.

**Comment by tsmaeder** [comment]
@kittaakos @vince-fugnitto ping. Can we either merge or close this one?

**Comment by kittaakos** [comment]
> Can we either merge or close this one?

Thanks for the ping. Feel free to merge it. I can confirm, It does not cause any regression with the `cortex-debug` VSIX.

**Comment by tsmaeder** [comment]
@kittaakos @vince-fugnitto not without an approval ;-)

**Review by kittaakos — APPROVED** [review]
I tried the changeset (https://github.com/eclipse-theia/theia/pull/12113#issuecomment-1409982564) by manually applying it in the Arduino IDE source code, and I can confirm it does not cause any problems with the `cortex-debug` VS Code extension.

Thanks for the work @EvilBeaver 💪

**Comment by vince-fugnitto** [comment]
@EvilBeaver do you mind rebasing the pull-request so we can run it against the latest CI state?

**Comment by EvilBeaver** [comment]
> @EvilBeaver do you mind rebasing the pull-request so we can run it against the latest CI state?

updated to latest state of master branch

**Review by vince-fugnitto — APPROVED** [review]
LGTM :+1: I did not notice any regressions with the approach and agree with Akos.

**Pull request merged**
