### PR TITLE
[vscode] support TaskPresentationOptions close

### LINKED ISSUE #12611: [vscode] Support TaskPresentationOptions#close property
vscode 1.79 proposes a new option for Task Presentation Options, to close terminal on task completion.

TaskPresentationOptions_close

### PR DESCRIPTION
**Pull request by rschnekenbu**
#### What it does

_Adds the close property to TaskPresentationOptions_
This enables the possibility to close the terminal once the task is finished.

Fixes #12611

Contributed on behalf of ST Microelectronics

#### How to test 
1. Install following extension:
-  extension: [task-provider-samples-0.0.3.zip](https://github.com/eclipsesource/theia/files/11800018/task-provider-samples-0.0.3.zip)
- source: [task-provider-sample-0.0.3-src.zip](https://github.com/eclipsesource/theia/files/11800019/task-provider-sample-0.0.3-src.zip)

2. Copy the content of this archive at the root of your workspace: 
[workspace-test.zip](https://github.com/eclipsesource/theia/files/12104301/workspace-test.zip). It contains several tasks that can be identified by the sample extension. In the extension, the build tasks are supposed to close the terminal after the task is finished (`close` set to `true`) whereas the terminal should remain on completion for other tasks like test tasks.

3. On `master` theia, the terminal always remain after the tasks are finished (this is also the default behavior after the patch when `close` is not defined.). The extension is written so the tasks are configured differently if they are build tasks or any other kind of tasks. This does not do any difference on `master`, as the close property is not known.
12611-before

4. Switch to this PR and run the same tests. The terminal will close for the build tasks, and remain open for reuse for the other tasks like test tasks. 
12611-after

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- [x] As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
@rschnekenbu could you resolve the conflict, please?

**Comment by rschnekenbu** [comment]
@tsmaeder, sure!

**Review by tsmaeder — APPROVED** [review]
Looks good to me. Was able to test after installing ruby/rake.

**Comment by tsmaeder** [comment]
Let's wait for the tests to finish before we merge.

**Pull request merged**
