### PR TITLE
preferences: fix merge method in PreferenceProvider

### PR DESCRIPTION
**Pull request by AlexandraBuzila**
#### What it does

When merging preferences, in the PreferenceProvider, also merge properties of type array. Currently, properties of type object are merged, but for arrays only the value from the target JSON is used.

This fixes the first use case described in issue https://github.com/eclipse-theia/theia/issues/8987, where launch configs defined in the workspace are not visible, if other launch configs exist in a `launch.json` file.

#### How to test

1. Create a workspace with a test folder and a `.theia-workspace` file, e.g.:
```
{
    "folders": [
        {
            "path": "test"
        }
    ],
    "settings": {
        "launch": {
            "configurations": [
                {
                    "name": "from .theia-workspace",
                    "request": "launch",
                    "type": "node",
                }
            ]
        }
    }
}
```
2. Go to the `Debug` view and check that the launch configs from the workspace file are present in the dropdown at the top of the view. 
3. Add a `.theia/launch.json` file with at least one launch configuration, e.g.: 
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "from .theia",
            "request": "launch",
            "type": "node",
        }
    ]
}
```
4. Go to the `Debug` view and check that the launch configs from  `launch.json` are visible in the dropdown, alongside the ones from the workspace file.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by paul-marechal — APPROVED** [review]
Code LGTM and the changes work as described.

**Comment by tsmaeder** [comment]
@AlexandraBuzila can we close the related issue? It didn't auto-close, it seems.

**Comment by AlexandraBuzila** [comment]
I think the main problem that was reported in that ticket is solved by this PR, however there was a second issue mentioned in the ticket description: if there are launch configurations defined both in "someProject/.theia/launch.json" and "someProject/.vscode/launch.json", only the ones from the `.theia` folder are visible. 

If the current behavior is expected and should not be changed, then the ticket can be closed from my point of view :+1:

**Comment by tsmaeder** [comment]
If we're not sure it's completely fixed, you did the right thing leaving it open, IMO. I was just wondering.

**Comment by AlexandraBuzila** [comment]
Hi @marcdumais-work! Thank you for catching this, I will have a look ASAP.

**Pull request merged**
