### PR TITLE
Prevent default browser context-menu

### LINKED ISSUE #4007: [ui][firefox] Right click on editor tab scrollbar shows native menu
When (accidentally) right-clicking the editor tab bars scrollbar the browser native context menu is shown. As a user I would expect that to be suppressed because it breaks the Theia experience:
out

(Happens to me very often when trying to "Close all" editor tabs.

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #4007

_Current Behavior_
- When right-clicking certain content (ex: the application without any editors opened) the default browser menu is displayed. This breaks up the user experience and can become quite annoying.

<div align='center'>

contextmenu

</div>

_PR_
- The PR adds additional handling to the `window` `contextmenu` event to prevent the default browser behavior. Existing context menus such as for an editor, or widgets remain unchanged.

#### How to test

_Verify Default Behavior_
1. open the application
2. ensure that no editors are opened
3. attempt to right-click in the empty area (nothing should happen) - previously the browser context menu was displayed

_Verify Regression_
1. open the application
2. open an editor
3. right-click within the editor, the editor context menu should be visible
4. do the same as step 3 with a widget tab

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by elaihau** [comment]
Tested in my local env.

I confirm:
- no context menu was populated when right-clicking the empty area, if no editors were open
- context menu was populated when right-clicking the editor that is opened in the main, the right, the left, and the bottom panel, 
- no context menu was populated when right-clicking the empty main panel, if the editor was docked in the right, the left, and the bottom panel.

**Comment by elaihau** [comment]
I found https://github.com/eclipse-theia/theia/issues/6431 when testing but I believe it is a separated issue.

**Comment by AndrienkoAleksandr** [comment]
Hello @vince-fugnitto , I tested your pr and I see that after merge this one we are losing context menu for terminal. Maybe we should create separated issue to create context menu for terminal.

**Comment by vince-fugnitto** [comment]
@AndrienkoAleksandr I believe the proper fix for the terminal would be to create it's own context menu in which we can add new items. See https://github.com/eclipse-theia/theia/issues/6216.

I can hold off on this PR if you'd like until the context menu for the terminal is created.
Which current functionality do you use in the terminal default browser context-menu?

**Comment by akosyakov** [comment]
@AndrienkoAleksandr Could you elaborate why browser context menu is helpful for terminals till #6216 is fixed?

**Comment by AndrienkoAleksandr** [comment]
Hello. I don't block merge this pr. I only applied information. Currently terminal context menu is useful only to copy and paste text, but we have shortcuts to do that. And yes, we need implement context menu. By the way Do we have an issue for that? And when we will implement context menu paste will be working only with electron. For browser version paste won't work for browser security reason.

**Comment by kittaakos** [comment]
@vince-fugnitto, please make sure extension developers have an easy way to re-enable the context menus if they want to.

**Comment by kittaakos** [comment]
I have just noticed, the context menu is not available anymore from `input` and `textarea`. It should work. For instance, I should be able to `cut` something via the context menu from the SIW view's `input` and `past` it also via the context menu to the SCM view's `textarea`.

We can do something similar the VS Code guys did, and enable only certain actions: https://github.com/electron/electron/issues/4068

**Comment by lmcbout** [comment]
Tested on Ubuntu 16.04 and Chrome

While testing this PR, I found the following:
Terminal | Problem view: context menu for "Toggle Maximized CTRL +M" is missing (Context menu when selecting the terminal title bar.
If you see the item in the context menu, just select the "explorer" view button to hide + show again the "explorer" view, then try to open the context menu over the terminal view (First occurrence only)

ContextMenuMissingOneItem

Search View: We should have a context menu to "Copy/Paste" as minimal. I know we can use keyboard shortcut to copy/paste, but I would also prefer to have a minimal context menu for some commands .
CopyPasteNoContextMenu


Explorer view: When selecting the context menu over the workspace name, there is no context menu to show the following views:
Npm scripts
Json Outline
FTP Explorere
File Explorer
Test View
ExplorerViewMenu

**Comment by vince-fugnitto** [comment]
> ContextMenuMissingOneItem
> 

This occurs in `master` as well.

> Search View: We should have a context menu to "Copy/Paste" as minimal. I know we can use keyboard shortcut to copy/paste, but I would also prefer to have a minimal context menu for some commands .

This is not in the scope of the PR. I am not adding context menus for widgets.

> Explorer view: When selecting the context menu over the workspace name, there is no context menu to show the following views:
> Npm scripts
> Json Outline
> FTP Explorere
> File Explorer
> Test View

You likely do not have them because you do not have the additional VS Code extensions provided.
They are not there by default in the repository.

**Comment by vince-fugnitto** [comment]
> I have just noticed, the context menu is not available anymore from `input` and `textarea`. It should work. For instance, I should be able to `cut` something via the context menu from the SIW view's `input` and `paste` it also via the context menu to the SCM view's `textarea`.
> 
> We can do something similar the VS Code guys did, and enable only certain actions: [electron/electron#4068](https://github.com/electron/electron/issues/4068) (Edit: I know the referenced issue is a bit off, I added to show that VS Code has support for the context menu in `input` and `textare`, so we cannot disable it either.)

I don't have any real urgency in merging the PR, I'm concerned about the issues you described about how users don't have the contextmenu in `input` and `textarea` fields. I believe the consensus is before merging the PR, to address the context menus in those areas?

**Comment by vince-fugnitto** [comment]
I'll put the pull-request on hold until we complete the following:
- default context menus for 'inputs' and 'textarea'
- default context menu for `terminals`: #7632

**Pull request closed without merging**
