### PR TITLE
plugins: remove the plugins-view

### LINKED ISSUE #7375: question: can the 'plugins view' be removed?
**Description**

Since we now have the `extension` view as part of the vsx integration (#6655), is there a need to keep the `plugins` view? At the moment, it is possible to have both views in a given application.

If we are to remove the `plugins` view, I think it should be done before v1.0.0.

cc @eclipse-theia/core

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### Note

The following pull-request is tentative to the decision of #7375 and `v1.0.0`.

#### What it does

Fixes #7375

The following commit removes the `plugins-view` widget from the framework since it's been replaced by the `extensions-view` which allows users the ability to install plugins from the Open VSX Registry.

Since the `extension-view` widget is added, there is no longer a need to keep the `plugins-view`.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
I'm not sure what the approved approach should be for this pull-request:
- should we pull `vsx-registry` from the plugins so users are able to see their extensions
- should we remove the `plugins` view but keep `vsx-registry` optional
- should we keep both the `plugins` and `extensions` views

**Comment by akosyakov** [comment]
@vince-fugnitto I don't think we should do it:
- an end product can have own marketplace not Open VSX based or decide that only pre-built extensions are supported, so it should be optional
- we still have a concept of Theia plugins which are not VS Code extensions, vsx-registry extension does not care about them

If at some point we decide to drop Theia plugins and go only with VS Code extensions with custom namespaces or allow vsx registry to show Theia plugins we can reconsider it.

**Comment by akosyakov** [comment]
As for now, end products can remove `plugins` view via DI. At least we did it for all customer products like that.

You can add it to a dev meeting if you think it has to be discussed.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I don't think we should do it:

I'm fine with the reasons behind keeping the `plugins-view`, I thought I'd prepare a pull-request to remove it tentatively so we'd be prepared for the release. Since the idea is to keep the `plugins-view` I'll close the pull-request.

cc @marcdumais-work

**Pull request closed without merging**
