### PR TITLE
core: respect `visible` `menuBarVisibility` for fullscreen

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes https://github.com/eclipse-theia/theia/issues/10077.
Closes https://github.com/eclipse-theia/theia/pull/10213.

The pull-request updates the handling of "toggle full screen" (electron) to properly respect the preference `window.menuBarVisibility`. If the preference is set to `visible` then the menu should remain visible on fullscreen for both the `custom` and `native` main-menus. The change also includes a listener to properly update the main-menu when in full-screen.

#### How to test

_toggling behavior_:

1. set the preference `window.titleBarStyle` to `native`
2. for each value in the preference `window.menuBarVisibility`, confirm the behavior

| Style | Visibility | Expectation |
|:---|:---|:---|
| `native` |  `classic` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu |
| `native` | `hidden` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu |
| `native` | `compact` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu |
| `native` | `visible` | toggling full-screen (<kbd>F11</kbd>) should **show** the main menu |
| `custom` | `classic` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu |
| `custom` | `hidden` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu |
| `custom` | `compact` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu |
| `custom` | `visible` | toggling full-screen (<kbd>F11</kbd>) should **show** the main menu |

The behavior of each option should be similar to what is experienced in vscode.

_full-screen behavior_:

1. when in full-screen, confirm for both `custom` and `native` titlebar styles that:
   - updating `menuBarVisibility` will properly update the visibility
   - setting the visibility to `visible` should display the menu in full-screen

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Review by colin-grant-work — COMMENTED** [review]
It looks like the combination of `custom` title bar and `classic` menu bar visibility give an unexpected result.

| Preference | Expectation | Behavior | 
|:---|:---|:---|
| `window.titleBarStyle = native` && `window.menuBarVisibility = classic` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu | Hidden |
| `window.titleBarStyle = native` && `window.menuBarVisibility = hidden` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu | Hidden |
| `window.titleBarStyle = native` && `window.menuBarVisibility = compact` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu | Compact |
| `window.titleBarStyle = native` && `window.menuBarVisibility = visible` | toggling full-screen (<kbd>F11</kbd>) should **show** the main menu | Visible |
| `window.titleBarStyle = custom` && `window.menuBarVisibility = classic` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu | Visible ❌  |
| `window.titleBarStyle = custom` && `window.menuBarVisibility = hidden` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu | Hidden |
| `window.titleBarStyle = custom` && `window.menuBarVisibility = compact` | toggling full-screen (<kbd>F11</kbd>) should hide the main menu | Compact |
| `window.titleBarStyle = custom` && `window.menuBarVisibility = visible` | toggling full-screen (<kbd>F11</kbd>) should **show** the main menu | Visible |

**Comment by vince-fugnitto** [comment]
> It looks like the combination of custom title bar and classic menu bar visibility give an unexpected result.

It seems to be a limitation from the custom menubar style, it doesn't hide ever.
We can probably support it later if needed, the pull-request mainly addressed the `native` menu.

**Comment by vince-fugnitto** [comment]
@colin-grant-work I've updated the pull-request so that it properly handles both `native` and `custom` titlebar styles (previous iteration only properly handled `native`). I also added logic to properly update the visibility when in fullscreen by listening to the `menuBarVisibility` preference update and applying the same handling.

**Review by colin-grant-work — APPROVED** [review]
All 16 combinations of fullscreen, title bar style, and menu bar visibility now behave as expected 👍

**Comment by vince-fugnitto** [comment]
@msujew I just wanted to know if you had any feedback given you touched the menus in the past :)

**Comment by vince-fugnitto** [comment]
I'll try to merge tomorrow if there are no objections.

**Review by msujew — APPROVED** [review]
The changes look reasonable to me!

**Pull request merged**
