### PR TITLE
Add inversify lifecycle to frontend preload script

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Currently, the browser preload scripts has 3 tasks:
* Load the translations for the selected locale
* Load the backend OS to correctly display stuff like line endings
* Set the background of the application based on the last selected theme

However, these tasks are hardcoded and adopters cannot add new scripts that are supposed to be executed during the preload phase of the frontend application. This change adds an inversify lifecycle to the aforementioned frontend preload scripts and a new contribution point to the `package.json` called `frontendPreload`. This allows to define new `PreloadContribution` items.

It also changes the way communication within the preload script is being performed. Instead of using `fetch`, we use the normal rpc messaging system via `WebSocketConnectionProvider`.

As a drive by, also:
Closes https://github.com/eclipse-theia/theia/issues/12670
Closes https://github.com/eclipse-theia/theia/issues/6675

#### How to test

1. Confirm that the tasks outlined above still work as expected.
2. Remove the `frontendPreload` from `@theia/core/package.json`. Assert that the preload module is removed from the generated `index.js` file.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by paul-marechal — COMMENTED** [review]
Changes look mostly good to me but with a few comments.

**Comment by msujew** [comment]
@vince-fugnitto Any chance to look into this change? I think this could be useful for https://github.com/eclipse-theia/theia/pull/12853, since the current preload script doesn't make a lot of sense for a CDN based Theia version.

**Review by vince-fugnitto — COMMENTED** [review]
@msujew the changes seem to work as expected for the browser use-case, however I'm experiencing errors attempting to start the electron application if you can confirm:

1. `git clean -ffdx`
2. checkout the branch
3. `yarn`
4. `yarn electron build`
5. `yarn electron start` - the following will fail

```bash
$ yarn electron start

yarn run v1.22.19
$ yarn -s --cwd examples/electron start
App threw an error during load
Error: Module parse failed: 'return' outside of function (47:4)
File was processed with these loaders:
 * ../../node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|     // There is another instance running, exit now. The other instance will request focus.
|     app.quit();
>     return;
| }
| 
    at ./src-gen/backend/electron-main.js (/home/foobar/workspaces/theia/examples/electron/lib/backend/electron-main.js:10:7)
    at /home/foobar/workspaces/theia/examples/electron/lib/backend/electron-main.js:21:68
    at Object.<anonymous> (/home/foobar/workspaces/theia/examples/electron/lib/backend/electron-main.js:23:12)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at loadApplicationPackage (/home/foobar/workspaces/theia/node_modules/electron/dist/resources/default_app.asar/main.js:121:16)
    at Object.<anonymous> (/home/foobar/workspaces/theia/node_modules/electron/dist/resources/default_app.asar/main.js:233:9)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module parse failed: 'return' outside of function (47:4)
File was processed with these loaders:
 * ../../node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|     // There is another instance running, exit now. The other instance will request focus.
|     app.quit();
>     return;
| }
| 
    at ./src-gen/backend/electron-main.js (/home/foobar/workspaces/theia/examples/electron/lib/backend/electron-main.js:10:7)
    at /home/foobar/workspaces/theia/examples/electron/lib/backend/electron-main.js:21:68
    at Object.<anonymous> (/home/foobar/workspaces/theia/examples/electron/lib/backend/electron-main.js:23:12)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at loadApplicationPackage (/home/foobar/workspaces/theia/node_modules/electron/dist/resources/default_app.asar/main.js:121:16)
    at Object.<anonymous> (/home/foobar/workspaces/theia/node_modules/electron/dist/resources/default_app.asar/main.js:233:9)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
```

**Comment by msujew** [comment]
@vince-fugnitto Thanks for looking into it! Yeah, it seems like my changes completely messed up the generated electron-main.js file. It should work correctly now 👍

**Pull request merged**
