### PR TITLE
vscode: add `hcLight` support

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes: https://github.com/eclipse-theia/theia/issues/11314.
The pull-request adds support for **high contrast light themes** and includes the following updates:
- adds support for `hcLight` themes
- updates our color registrations to include `hcLight` based on values present in vscode
- updates our `change color theme` command to support `hcLight` and adds localizations

Screen Shot 2022-08-19 at 9 17 35 AM

#### How to test

1. include the following test theme [theia-hclight-0.0.2.zip](https://github.com/eclipse-theia/theia/files/9992348/theia-hclight-0.0.2.zip)
2. start the application
3. execute the command `Preferences: Color Theme` - the high contrast light themes should be under `high contrast`, selecting `Test High Contrast Light Theme` should work
4. the new `High Contrast Light (Theme)` should also work

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
The changes looks quite good. I noticed just two minor issues (which might have been partially introduced by me, but weren't noticeable using just the dark high contrast theme). Do you mind taking care of those with your PR?

Tabbar colors:
_vscode_
grafik
_theia_
grafik

Focused notifications:
_vscode_
grafik
_theia_
grafik

**Comment by vince-fugnitto** [comment]
@msujew sure, do you know what the color names are, I wasn't able to find them or identify what might be wrong.

**Comment by vince-fugnitto** [comment]
I noticed issues when setting `Github Dark High Contrast` as a theme so more work is needed.

**Comment by msujew** [comment]
@vince-fugnitto For the notification it should be `list.focusBackground` and for the tab bar its `editorGroupHeader.tabsBorder`. Note that there seems to be some conditional logic attached for both ([1](https://github.com/microsoft/vscode/blob/4291d2b9d98d21708bd3cf6605767ddd2d3a8163/src/vs/base/browser/ui/list/listWidget.ts#L808-L811) and [2](https://github.com/microsoft/vscode/blob/866bddc98bfd99bbfeb1145c85cfcf2179e90f9f/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L1095-L1108)).

**Comment by vince-fugnitto** [comment]
I've opened the issue https://github.com/eclipse-theia/theia/issues/11616 regarding the top border, it seems to be a bug also present on master.

**Comment by msujew** [comment]
@vince-fugnitto Ah, I actually didn't talk about the top border of the tab bar, but rather the slim bar that separates the tabs from the widget area (blue in Theia currently, should be black, see screenshots above).

**Review by msujew — DISMISSED** [review]
Coming back to this: I'm actually in favor of merging it now and fixing any possible issues (i.e. missing/incorrectly used colors, etc.) in follow up PRs.

**Comment by vince-fugnitto** [comment]
I noticed some issues with the support so I'll address them.

**Comment by vince-fugnitto** [comment]
The changes depend on https://github.com/eclipse-theia/theia/pull/11589 to be able to use the `hc-light` `monaco.editor.BuiltinTheme`.

**Comment by vince-fugnitto** [comment]
@msujew I've come back to the pull-request after the monaco uplift and we benefited from proper support for `hc-light`. I've included a plugin to test against that makes use of `hcLight`.

**Review by msujew — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
