### PR TITLE
terminal: fix terminal blank title (#12524)

### LINKED ISSUE #12524: After executing the command, the terminal will have a blank title
### Steps to Reproduce:

1. Press  ctrl+` to open a terminal
2. ping 127.0.0.1
3. after executing the command, the terminal will have a blank title

terminal-issuse

### Additional Information

- Operating System: windows10
- Theia Version: 1.37.0

### PR DESCRIPTION
**Pull request by helloworldmygithub**
The commit fix terminal blank title problem.

#### What it does

fix #12524
#### How to test

terminal-fix

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@msujew I haven't been able to reproduce this issue, perhaps you'll have more luck? I'm not sure if you have a Windows machine as well.

**Comment by msujew** [comment]
@vince-fugnitto I cannot reproduce it either on Windows 11. It appears to work for me exactly as intended:

https://github.com/eclipse-theia/theia/assets/4377073/42ea576a-ddc1-4738-875b-72f69be1d18b

**Comment by helloworldmygithub** [comment]
I cannot reproduce this issue on another Windows computer either. Just ignore it

**Comment by vince-fugnitto** [comment]
@helloworldmygithub I'll close the issue and pr then, we can always re-open if we can find a way to successfully reproduce.

**Pull request closed without merging**
