### PR TITLE
Parse DAP messages to match VS Code API

### LINKED ISSUE #7470: DebugAdapterTracker-onDidSendMessage(): theia sends string, vscode sends object
### Description
It seems that theia sends string to method onDidSendMessage() in DebugAdapterTracker comparing to vscode that sends object.

### Reproduction Steps
Debug onDidSendMessage() implementation of DebugAdapterTracker in theia and in vscode.

**OS and Theia version:**
OS: ubuntu wsl 18.04 in windows 10
Theia version: @theia/example-browser 0.16.0

**Diagnostics:** 
Theia sends json string, vscode sends json object.

### PR DESCRIPTION
**Pull request by sh7dm**
#### What it does

Fixes #7470

#### How to test

Please see https://github.com/eclipse-theia/theia/issues/7470#issuecomment-610841975

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@sh7dm One has to create a simple drop-in VS Code extension and check that it works in VS Code and then in Theia. Such extension gets attached to the issue for others to test. Otherwise it is not clear how one ensure correctness.

**Comment by sh7dm** [comment]
@akosyakov I can't create one, but this extension uses this API: https://github.com/microsoft/vscode/blob/f20785db318ebc6a931108c5c504028a75f8d581/extensions/debug-server-ready/src/extension.ts#L209. Reviewers can try to run it.

**Comment by sh7dm** [comment]
Maybe we should ask issue author about how the issue was found and test in using their extension?

**Comment by akosyakov** [comment]
@sh7dm If some extension is using it, that's also fine, then just write down how an extension should be used to confirm correctness. We will try that it does not work on master and compare to this branch.

**Comment by akosyakov** [comment]
fyi for PR guidances: https://github.com/eclipse-theia/theia/blob/master/doc/pull-requests.md#requesting-a-review

**Comment by sh7dm** [comment]
@akosyakov I tested this with updated extension by @ishche .
VS Code insiders:
image
Theia at 1453157:
image
Theia at 4442eb5 (this PR):
image

**Pull request merged**
