### PR TITLE
Map 'workbench.action.saveWorkspaceAs' to SAVE_WORKSPACE_AS

### PR DESCRIPTION
**Pull request by kaiyue-pan-work**
#### What it does
Map 'workbench.action.saveWorkspaceAs' to SAVE_WORKSPACE_AS so that it can be used by VS Code extensions.

#### How to test
1. Download this [sample extension](https://github.com/kaiyue-pan-work/extension-for-testing/blob/main/sample-extension-0.0.1.vsix) for testing
2. Build Theia from sources
3. Create `plugins` folder under Theia repo folder
4. Run Theia and click the `folder` icon in the activity-bar to open the view
5. Click the `small-folder` icon in the view to run the command
image
6. Confirm that the `Save Workspace As...` dialog shows up

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Kaiyue Pan <kaiyue.a.pan@ericsson.com>

### CODE REVIEW

**Comment by colin-grant-work** [comment]
@kaiyue-pan-work, it looks like you'll need to (re-)sign the Eclipse ECA for the email address you're using.

**Comment by kaiyue-pan-work** [comment]
Thanks @colin-grant-work. I have re-signed the Eclipse ECA using my work email.

**Comment by vince-fugnitto** [comment]
@kaiyue-pan-work the issue with the ECA seems to be due to the authorship email, it looks like you were using a `no-reply` email:

```diff
From bb93304e128ac948ede7c4e9588bede437f69f3d Mon Sep 17 00:00:00 2001
From: Kaiyue Pan <94718614+kaiyue-pan-work@users.noreply.github.com>
Date: Thu, 7 Jul 2022 12:04:25 -0500
Subject: [PATCH] Map 'workbench.action.saveWorkspaceAs' to SAVE_WORKSPACE_AS

Signed-off-by: Kaiyue Pan <kaiyue.a.pan@ericsson.com>
---
 .../src/browser/plugin-vscode-commands-contribution.ts         | 3 +++
 1 file changed, 3 insertions(+)
```

**Comment by kaiyue-pan-work** [comment]
Thanks @vince-fugnitto. I have updated my authorship email and the ECA check looks good now.

**Pull request merged**
