### PR TITLE
Fix failing tests due to #9154 monaco upgrade 0.23.0

### PR DESCRIPTION
**Pull request by EstherPerelman**
Signed-off-by: Esther Perelman <esther.perelman@sap.com>

#### What it does
Fixes: https://github.com/eclipse-theia/theia/issues/9701

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by EstherPerelman** [comment]
I still haven't found a solution for the next issue:
`root INFO   1 failing
root INFO   1) TypeScript
       run reference code lens:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

**Comment by vince-fugnitto** [comment]
> I still haven't found a solution for the next issue

@EstherPerelman any update regarding the last failing _typescript_ test (_run reference code lens_)?

**Comment by EstherPerelman** [comment]
> > I still haven't found a solution for the next issue
> 
> @EstherPerelman any update regarding the last failing _typescript_ test (_run reference code lens_)?

@vince-fugnitto I know where the problem is, but don't know how to solve it

**Comment by vince-fugnitto** [comment]
@EstherPerelman it's been a week now that the CI has been failing which means that new contributions have a failing CI, and `next` is not being published nightly. Perhaps if the test cannot be fixed soon, we can `.skip` it for the moment, and open an issue to track bringing it back?

**Comment by EstherPerelman** [comment]
> @EstherPerelman it's been a week now that the CI has been failing which means that new contributions have a failing CI, and `next` is not being published nightly. Perhaps if the test cannot be fixed soon, we can `.skip` it for the moment, and open an issue to track bringing it back?

@vince-fugnitto It's really bad, I had some progress with it, It seems to be an error inside vsCode which checking for some condition before previous processes have been finished (that causes the condition to return false instead true), It happens only for the first time (what means that it's not so disturbing in real life), There is also one more issue - as the `link.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));` not invoking (I clicked with the mouse and it worked), I think it's a good idea to skip it until there will be a good solution...

**Comment by vince-fugnitto** [comment]
> WDYS?

@EstherPerelman I think proceeding with the fixes you have and the `.skip` is fine for the moment to bring CI back (which I highlighted why is important). You can also create an issue to track bringing the `.skip` back with your findings and hopefully we can think of providing a solution for it.

**Comment by EstherPerelman** [comment]
> I still haven't found a solution for the next issue:
> image



> > WDYS?
> 
> @EstherPerelman I think proceeding with the fixes you have and the `.skip` is fine for the moment to bring CI back (which I highlighted why is important). You can also create an issue to track bringing the `.skip` back with your findings and hopefully we can think of providing a solution for it.

@vince-fugnitto added `.skip` & opened #9714 .

**Review by vince-fugnitto — APPROVED** [review]
Thank you for taking care of the test regressions and opening the follow-up https://github.com/eclipse-theia/theia/issues/9714 :+1:

**Pull request merged**
