### PR TITLE
improve plugins loading

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- partially addresses #6228 extracted from #6252: 
  - use permessage-deflate to compress any ws message greater than 256kb
  - only fetch not yet loaded plugins to the frontend
  - initialize debugger contributions from metadata, instead of sending it first to the plugin host and then back to the frontend
- closes #6233 - superseded
- also addresses https://github.com/eclipse-theia/theia/pull/6252#issuecomment-535367097

#### How to test

- remove native extension from the browse example and rebuild:
  - textmate grammar
  - debug-nodejs
  - java
  - java-debug
- install 57 VS Code extensions in `plugins` folder:
https://drive.google.com/file/d/1tuOsorMVOKi_twL9oAuZxgrD7-VUwNsj/view?usp=sharing
  - could not come up with a command to pull it from the gdrive in the terminal, if someone knows how to, please share
- use system proxy to emulate slow connection, e.g. Charles proxy
  - you cannot do it in Chrome, since it cannot throttle web sockets
- measure how long does it takes to activate all plugins before and after
- observe whether you get yellow status bar and ws frames hangs for 20-30 seconds after and before
- play with unstable connections to confirm that plugins get reloaded/unloaded on the reconnection

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by benoitf** [comment]
hello, why do we have yet another PR then https://github.com/eclipse-theia/theia/pull/6252 ?
is it to bypass requested changes/discussion on the other PR ?

**Comment by akosyakov** [comment]
@benoitf no, I follow you suggestions, from https://github.com/eclipse-theia/theia/pull/6252#issuecomment-534872781:
> remove 2 commits from PR and merge it (but it won't solve the blocking)

Or you are going to review changes to mentioned 2 commits?

**Comment by benoitf** [comment]
@akosyakov I will review the two commits

**Comment by benoitf** [comment]
for me this PR is fine but it is not solving all the issues, so I would better use https://github.com/eclipse-theia/theia/pull/6252

**Comment by akosyakov** [comment]
I don't see yellow status bar with this PR as well, but numbers on 3G are not so good as with #6252
- fetch 3872.8999998420477 ms vs 2785.3900000918657 ms
- starting 7810.244999825954 ms vs 1804.2249998543411 ms

**Comment by akosyakov** [comment]
Closing since #6252 is merged.

**Pull request closed without merging**
