### PR TITLE
plugin-ext-vscode: ignore vsix files in local-plugins dir

### LINKED ISSUE #13222: Builtin VSIX plugin is added to the installed list instead of the builtin list
### Bug Description:
Hi,

I have some vscode plugins (in a VSIX file format) in the plugins folder (where all builtin files exist). After upgrading to the latest Theia 1.45 those plugins are part of the installed view instead of the built-in view! They should be treated as builtin as before since they statically exist in the package plugins folder.

### Steps to Reproduce:

1. add any vsix file to the plugins folder
2. run the browser example
3. check and see that this plugin is under the installed list in the extensions view/panel.

### Additional Information

- Operating System: Mac
- Theia Version: Theia 1.45

### PR DESCRIPTION
**Pull request by xai**
#### What it does

In the local-plugins directory (i.e., the one passed to theia via the --plugins argument), we expect to find and deploy unpacked extensions.

This patch fixes an unexpected behavior where theia would also pick up and deploy .vsix files from the local-plugins directory into the deployedPlugins directory, where they will be treated as user-installed extensions on the next start of theia.

Instead, we now ignore .vsix files in the local-plugins directory and print a warning to the console.

Fixes #13222

Contributed on behalf of STMicroelectronics

#### How to test

1. Add any vsix file to the plugins folder (choose one that is not already in ~/.theia/deployedPlugins/)
2. Start Theia
3. Verify that the extension is NOT loaded in Theia (neither as installed nor as builtin)
4. Verify that the extension was NOT unpacked into ~/.theia/deployedPlugins and that it is NOT loaded in Theia.
5. Unpack the extension in the plugins folder
6. Start Theia
7. Verify that the extension is loaded as builtin in Theia
8. Verify that the extension was NOT unpacked into ~/.theia/deployedPlugins

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
I'm not sure about the approach here: what this PR does is exclude exactly files of type `*.vsix` from exactly the location given via the `--plugins` CLI parameter. I'm not really sure what we consider "built-ins" if I'm looking at the related issue. Looking at the code, I would think that any `PluginDeployerEntry` that is of type `System` should be considered a built-in plugin. Wouldn't it make more sense in that case to simply not apply the file handlers in `PluginDeployerImpl.applyFileHandlers`?

**Comment by tsmaeder** [comment]
@ping?

**Comment by xai** [comment]
Yes, you are right, this would be the better approach instead of a very specific exception. I'll adjust the PR.

**Comment by xai** [comment]
@tsmaeder pong

**Comment by tsmaeder** [comment]
While testing, I found https://github.com/eclipse-theia/theia/issues/13638, but it happens also in master, so unrelated.

**Review by tsmaeder — APPROVED** [review]

**Pull request merged**
