### PR TITLE
vsx: use builtins published on open vsx

### PR DESCRIPTION
**Pull request by vince-fugnitto**
**Motivation**

https://github.com/theia-ide/vscode-builtin-extensions/issues/25#issuecomment-603147214
https://github.com/theia-ide/vscode-builtin-extensions/issues/25#issuecomment-603190961

#### What it does

This commit updates the examples to use the `builtins` published under Open VSX instead of Github releases.

_Update Exceptions:_
- node-debug
- node-debug2
- references-view

#### How to test

With `@theia/cli` built, running the script `yarn download:plugins` at the root of the repository should successfully download the plugins without any errors.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
@vince-fugnitto Could we add exceptions here to publish from original repos: https://github.com/open-vsx/publish-extensions? cc @jankeromnes @spoenemann

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Could we add exceptions here to publish from original repos: https://github.com/open-vsx/publish-extensions? cc @jankeromnes @spoenemann

I opened a pull-request to add the missing builtins:
https://github.com/open-vsx/publish-extensions/pull/16

**Comment by marcdumais-work** [comment]
> Could we add exceptions here to publish from original repos: https://github.com/open-vsx/publish-extensions? 

Nice, I was not aware of this mechanism. We can eventually get rid of the forks we have under `theia-ide` that are there just to publish extensions because they were not freely available elsewhere.

**Comment by marcdumais-work** [comment]
> I might have misunderstood the request, did we mean to add these builtins to the VSX registry or add some other type of handling?

You did what I understood is wanted. The built-ins are already in the registry. The exceptions are the few other extensions we have referenced in the main repo.

**Comment by vince-fugnitto** [comment]
> LGTM, thanks @vince-fugnitto . Quickly tested on Gitpod and looks good. Up-to you if you want to merge this ASAP or wait until the "exceptions" extensions are published to Open VSX and you can update these as well in this PR.

I think we can wait for the exceptions to be added in open vsx first?
I don't mind either way :)

**Comment by akosyakov** [comment]
> Nice, I was not aware of this mechanism. We can eventually get rid of the forks we have under theia-ide that are there just to publish extensions because they were not freely available elsewhere.

@marcdumais-work I think we will need to keep them to avoid to break current adopters.

**Comment by akosyakov** [comment]
It will be fine to make another PR for exceptions tomorrow.

**Comment by vince-fugnitto** [comment]
> It will be fine to make another PR for exceptions tomorrow.

https://github.com/eclipse-theia/theia/issues/7416

**Comment by marcdumais-work** [comment]
> I think we will need to keep them to avoid to break current adopters.

Good point - we can leave them up for a while.

**Pull request merged**
