### PR TITLE
[electron]: Fixed the window reloading issue.

### PR DESCRIPTION
**Pull request by kittaakos**
Refs:
 - electron/electron#22119,
 - electron/electron#18397, and
 - electron/electron#21287
Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does

Fixes the browser window reload on Windows. @mcgordonite, could you please verify the behavior with and without this change on Windows?

#### How to test

Try to reset the workbench layout. It should reload the browser window.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@vince-fugnitto @marechal-p could you check please? it sounds like an important regression after Electron 9 migration

**Comment by mcgordonite** [comment]
Hi @kittaakos, I should have time to verify this change tomorrow.

**Comment by kittaakos** [comment]
@mcgordonite, do you happen to have time to verify the `Reset  Workbench Layout` command behavior on Windows. With the `master` version, the browser window never reloads after resetting the workbench layout with the electron example. With this change, it should work, hopefully 🤞 Thank you!

**Comment by mcgordonite** [comment]
@kittaakos just tested the behaviour on Windows:
- On master the workbench reset starts the page reload, then hangs on the loading spinner. This also happens when using the "reload window" command.
- On this PR, with allowRendererProcessReuse false, workbench reset works correctly.

**Comment by kittaakos** [comment]
> just tested

Thank you for your help, @mcgordonite

**Comment by vince-fugnitto** [comment]
@kittaakos unfortunately I was unable to test since I don't have a Windows machine.
I did try the pull-request on Linux and did not notice any regressions.

**Comment by akosyakov** [comment]
Is it fine to approve on @mcgordonite behalf or someone else is going to try?

**Comment by kittaakos** [comment]
@tsmaeder, can you please help us with the review?

**Pull request merged**
