### PR TITLE
repo: yarn upgrade following `v1.19.0` release

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

The commit performs a `yarn upgrade` following the `v1.19.0` release.

#### How to test

- [x] confirm that ci is green for the build and tests
- [x] ~confirm that the 3pp license check passes (may need to be updated - file updates to)~

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Review by msujew — APPROVED** [review]
CI passes with all tests successfully and Theia passes manual inspection (manual smoke tests) 👍

**Comment by marcdumais-work** [comment]
Let's merge this - thanks @vince-fugnitto

**Comment by marcdumais-work** [comment]
The license check failed: https://github.com/eclipse-theia/theia/actions/runs/1408480659

I'll confirm locally and re-run in automated mode to attempt to clear this dependency

**Comment by marcdumais-work** [comment]
```
ERROR: Found results that aren't part of the baseline!
X npm/npmjs/-/estraverse/5.3.0, BSD-2-Clause
```

**Comment by marcdumais-work** [comment]
>  re-run in automated mode to attempt to clear this dependency

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/1557

**Comment by marcdumais-work** [comment]
It's approved. It might take a little while, but the info will propagate and the license check will pass, if re-run

**Pull request merged**
