### PR TITLE
Unable to restore Theia state when webview and several editor tabs are opened

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
#### What it does

Fixes an error with restoring the editor area when a webview and several editors are opened.

Short video demonstrating a problem is here https://www.youtube.com/watch?v=9ir1hTov350 

#### How to test

Follow 'Steps to reproduce' in the original issue https://github.com/eclipse-theia/theia/issues/8620

This PR is also fixes https://github.com/eclipse-theia/theia/issues/6877. I haven't investigated sources of GitLens extension, but the bug with webview+preferences is not reproducible anymore.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by tsmaeder — CHANGES_REQUESTED** [review]
I'm not convinced this is the right fix: if we don't have a WebviewPanelSerializer, shouldn't we just recreate the webview to it's default state? After all, there are webviews that simply do not have mutable state.
Could you point me to the code that disposes the widget if there's now WebviewPanelSerializer? I didn't find it.

**Comment by vitaliy-guliy** [comment]
> I'm not convinced this is the right fix: if we don't have a WebviewPanelSerializer, shouldn't we just recreate the webview to it's default state? After all, there are webviews that simply do not have mutable state.

Theia finds a WebviewPanelSerializer when saving the layout, as the serializer is used to get the webview html content.

If the serializer is not registered for the webview, theia saves only widget ID, factory ID and empty content.
https://github.com/eclipse-theia/theia/blob/8e3da241a16bfb40ecec9abda6ed0785fa9f1413/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L204-L209

Then when restoring the state after reload, Theia
- creates a widget by a widget factory (which is 'plugin-webview')
https://github.com/eclipse-theia/theia/blob/8e3da241a16bfb40ecec9abda6ed0785fa9f1413/packages/core/src/browser/shell/shell-layout-restorer.ts#L317
- tries to restore the widget, but cannot. `oldState` object is empty, just because empty value was saved. So, it switched to `widget.dispose()`
https://github.com/eclipse-theia/theia/blob/8e3da241a16bfb40ecec9abda6ed0785fa9f1413/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L210-L217
- on the last check `undefined` value is returned for disposed widget
https://github.com/eclipse-theia/theia/blob/8e3da241a16bfb40ecec9abda6ed0785fa9f1413/packages/core/src/browser/shell/shell-layout-restorer.ts#L336-L338

**Comment by tsmaeder** [comment]
The `if (oldState.viewType)` check could win an obfuscated code contest ;-). This could use a commment.

**Comment by vitaliy-guliy** [comment]
Could somebody check this PR?

**Comment by vitaliy-guliy** [comment]
@akosyakov @vince-fugnitto could you please take a look?

**Review by vince-fugnitto — COMMENTED** [review]
Sorry I have not viewed the pull-request sooner, I was busy with EclipseCon.
I tested the functionality only at the moment, I see that editors are properly restored with this patch as compared to `master`.

**Comment by tsmaeder** [comment]
Hmh...the pressing F5 does not restore the order of the editors: python files always first.

**Comment by tsmaeder** [comment]
Master seems to respect editor order. Need to look at that code again.

**Comment by tsmaeder** [comment]
Here's what I do:

1. start the browser example
2. Open a python file, two json files and another python file
3. Observe: the editor tabs are in the order they are opened from left to right
4. Close the "hello" welcome page
5. Press F5
6. Observe: the two python files are the first editor tabs from the beginning. 
7. Observe: the "hello" welcome page is then opened as the second editor tab from the left.

**Comment by vitaliy-guliy** [comment]
> Here's what I do:
> 
> 1. start the browser example
> 2. Open a python file, two json files and another python file
> 3. Observe: the editor tabs are in the order they are opened from left to right
> 4. Close the "hello" welcome page
> 5. Press F5
> 6. Observe: the two python files are the first editor tabs from the beginning.
> 7. Observe: the "hello" welcome page is then opened as the second editor tab from the left.

What devfile did you use to test?

After refreshing the page, the order of opened editors must be restored.
But if the webview is not persisted, it will be opened again the next to active editor tab.

**Comment by tsmaeder** [comment]
> What devfile did you use to test?

No devfile, plain Theia. 

> After refreshing the page, the order of opened editors must be restored.
But if the webview is not persisted, it will be opened again the next to active editor tab.

That is correct, but the order of editors is not preserved in my case. Maybe we're iterating over property keys instead of an array somewhere?

**Comment by vitaliy-guliy** [comment]
@tsmaeder I have just updated and double-checked the PR. The order of opened editors is preserved after refreshing the page.

**Comment by tsmaeder** [comment]
🤦 I'll have to double-check, then. I'm _pretty_ confident I did not dream it.

**Comment by tsmaeder** [comment]
I'm still seeing reordering of the open files running the browser example when opening the following directory:

[First.zip](https://github.com/eclipse-theia/theia/files/5451386/First.zip)

1. Open hello.py, then launch.json, then settings.json, then config.py
2. Refresh the browser
3. Files are in order hello.py config.py launch.json settings.json

**Comment by vitaliy-guliy** [comment]
I reproduced the bug with your project. Sometimes (not always) the ordering of files is broken.
It could be because the speed of restoring of editors could be different for different type of files.
In my PR I changed a bit the order of inserting the widgets to the array. Then, the order could be broken if time for opening of the first widget is bigger comparing to the second one. In this case the second file will appear the first.

**Comment by tsmaeder** [comment]
@vitaliy-guliy of course:
```
const widget = await this.convertToWidget(descs[i], context);
  if (widget) {
    widgets.unshift(widget);
  }
```
compiles to 
```
 this.convertToWidget(descs[i], context).then(()=> {
  if (widget) {
    widgets.unshift(widget);
  }
);
```

**Comment by tsmaeder** [comment]
I'm glad I'm not crazy ;-)

**Comment by vitaliy-guliy** [comment]
I created a PR https://github.com/eclipse-theia/theia/pull/8680 with another approach. In that PR Theia does not store the webview if the serializer is not set.

**Review by azatsarynnyy — COMMENTED** [review]
I've tested it with the provided plug-in. The previously opened files are restored well. But with restoring a WebView I see two problems:
- the position of the WebView tab is not the same as it was before reloading the entire page
- the contributed WebView is restored anyway, even if I've already closed it before reloading the Theia page :smile:

**Comment by vitaliy-guliy** [comment]
> I've tested it with the provided plug-in. The previously opened files are restored well. But with restoring a WebView I see two problems:
> 
> * the position of the WebView tab is not the same as it was before reloading the entire page

It's because the webview is not persisted and the plugin opens it next to active tab.

> * the contributed WebView is restored anyway, even if I've already closed it before reloading the Theia page

The plugin opens a webview always when Theia starts.

**Comment by ericwill** [comment]
> I created a PR #8680 with another approach. In that PR Theia does not store the webview if the serializer is not set.

Does that mean this PR should be closed?

**Pull request closed without merging**
