### PR TITLE
Bumped version of find-git-repositories

### LINKED ISSUE #6529: Electron example not running in windows machine
### Description
Electron example not running in windows machine

### Reproduction Steps
yarn &&  yarn rebuild:electron && cd examples/electron && yarn start
Electron window does not pops up. 
Also observed sometimes failing with native dependency find-git-repositories
Error: The specified procedure could not be found findGitRepos.node

$ yarn rebuild:electron
yarn run v1.7.0
$ theia rebuild:electron
Processing @theia/node-pty
Processing nsfw
Processing native-keymap
Processing find-git-repositories
Done in 7.96s.
$ cd examples/electron/
$ yarn start
yarn run v1.7.0
$ theia start --plugins=local-dir:../../plugins
Done in 2.74s.

**OS and Theia version:**
Windows 10
yarn version:- 1.7.0
node version:- 10.15.3
npm version:- 4.2.0

**Diagnostics:**

### PR DESCRIPTION
**Pull request by federicobozzini**
Bumped version of `find-git-repositories` to version `0.1.1`.

#### What it does

This should fix #6529.

#### How to test

To test, just run Theia on Windows.

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
I verified using [ClearlyDefined](https://github.com/eclipse-theia/theia/wiki/Registering-CQs#case-new-or-updated-npm-production-dependency) and the dependency looks fine.
@marechal-p do you mind testing it quickly since you have a Windows machine?

**Comment by akosyakov** [comment]
@westbury maybe you can check whether it fixes #6529 
@kittaakos is away now for another week at least

**Comment by marechal-p** [comment]
This change fixes https://github.com/eclipse-theia/theia/issues/6529.

**Comment by akosyakov** [comment]
@marechal-p ok, please approve if you tested

**Comment by westbury** [comment]
I have tested this on Windows, Electron and it does appear to the issue.

Also note that the only change between versions 0.1.0 and 0.1.1 of find-git-repositories is the flag change (it's not an active project).

**Pull request merged**
