### PR TITLE
Apply FileDecoration provider API

### PR DESCRIPTION
**Pull request by vinokurig**
#### What it does

Align the FileDecoration vscode Plugin API with the latest vscode version. This API was changed and it is used in the vscode git plugin, so to be able to use the latest vscode git plugin it is needed to apply the changes in the Theia's FileDecoration plugin API.

related CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22921
#### How to test

1. Remove `"@theia/git": "^1.9.0"` from `examples/browser/package.json` file.
2. Download [vscode-git-1.52.1](https://open-vsx.org/api/vscode/git/1.52.1/file/vscode.git-1.52.1.vsix) and copy it to the `plugins` folder.
3. Start Theia and  open a project cloned from GitHub.
4. Make some changes in the project and check them in the SCM panel:
screenshot-localhost_3000-2020 12 29-17_06_55

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by azatsarynnyy — COMMENTED** [review]
~~If I understand correctly, we should check if everything works the same as in `master` branch.
If so, it works as usual on my side.~~

**Review by azatsarynnyy — COMMENTED** [review]
I've tested it according to the provided "How to test" section. The file decorations, in Git view, seems to work in the same way as in VS Code.
image

Except for the tooltips. I don't see the file tooltips as it's in VS Code.
I'm not sure if it's a bug or just not implemented feature yet.
@vinokurig could you check the tooltips, please?

**Comment by vinokurig** [comment]
@azatsarynnyy 
> Except for the tooltips. I don't see the file tooltips as it's in VS Code.
I'm not sure if it's a bug or just not implemented feature yet.

There are no tooltips in the master version either for theia's native git plugin, nor for vscode git plugin. I've created an issue to add them: https://github.com/eclipse-theia/theia/issues/9020

**Comment by azatsarynnyy** [comment]
> There are no tooltips in the master version neither for theia's native git plugin, nor for vscode git plugin. I've created an issue to add them: #9020

I see. Thank you for the explanation!

**Review by azatsarynnyy — APPROVED** [review]
The functionality works as expected and code-wise it looks good to me. Thanks!

**Review by vince-fugnitto — DISMISSED** [review]
@vinokurig I performed a functional test and I noticed the following issues:
- I no longer see decorations for `scm` in the navigator:

image


- I see a lot of the `file-change-tree-root` errors which grows constantly
image

**Comment by vinokurig** [comment]
@vince-fugnitto 
> I no longer see decorations for scm in the navigator:

The navigator scm decorations has been fixed.
> I see a lot of the file-change-tree-root errors which grows constantly

A pull-request that fixes this issue is opened: https://github.com/eclipse-theia/theia/pull/9045

**Comment by vinokurig** [comment]
@vince-fugnitto any updates?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto any updates?

@vinokurig I haven't had a chance to re-review the pull-request, there are a couple of pull-requests currently opened that also need reviewing. If others can help it'd be appreciated.

**Comment by vince-fugnitto** [comment]
@vinokurig I confirmed that the file decorations now work with/without the vscode git plugin.
I encountered an issue when using an older version of the plugin (`1.45.1`), is it expected that it no longer works? If so we should probably document that older versions of the plugin are now broken and should be updated.

image

**Comment by vinokurig** [comment]
@vince-fugnitto 
> I encountered an issue when using an older version of the plugin (1.45.1), is it expected that it no longer works? 

Yes it is expected, the API was changed after `1.49.3` version.
> If so we should probably document that older versions of the plugin are now broken and should be updated.

You mean add a note to the `CHANGELOG.md` file?

**Comment by vince-fugnitto** [comment]
> > If so we should probably document that older versions of the plugin are now broken and should be updated.
> 
> You mean add a note to the `CHANGELOG.md` file?

@vinokurig I think so, there are a few apps which will require an update to the builtin to work properly again, and it might be better to be upfront or transparent about older versions of the plugin not working anymore.

In addition, do you believe we should aim to merge https://github.com/eclipse-theia/theia/pull/9045 first, the following pull-request introduces changes which results in multiple errors with `file-change-root-node` which are not present with the same degree on master.

I believe this is an issue:

image

and it grows constantly:

image

**Comment by vinokurig** [comment]
> In addition, do you believe we should aim to merge #9045 first, the following pull-request introduces changes which results in multiple errors with file-change-root-node which are not present with the same degree on master.

I agree, so could you please review https://github.com/eclipse-theia/theia/pull/9045 as well. There is a discussion around logging an event when a new tree root is set in that PR.

**Comment by vinokurig** [comment]
Depends on https://github.com/eclipse-theia/theia/issues/8969.
VScode git plugin v 1.52.1 has `(Uri as any).joinPath`: https://github.com/microsoft/vscode/blob/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/git/src/emoji.ts#L27 but `joinPath` has been added only in the later versions of the `monaco-editor-core`. This is important because current version of the vscode git plugin won't work after this PR, and newer versions won't work as well because of the missing `joinPath` function.

**Comment by RomanNikitenko** [comment]
@vinokurig
about `joinPath` 
FYI: https://github.com/eclipse-theia/theia/pull/9199

**Comment by vinokurig** [comment]
@vince-fugnitto Since the `joinPath` issue has been resolved I updated this PR with master and now it works as expected. Could you please review it?

**Review by vince-fugnitto — COMMENTED** [review]
I performed a functional review and everything seems to work correctly :+1: 

I verified that the use-case described in the pull-request works for both `browser` and `electron` (scm decorations are present in the nav, and scm view). I also confirmed that using `@theia/git` works like on `master`, decorations are present.

**Comment by edmundreinhardt** [comment]
Any idea when this pull request will be merged and available?

**Pull request merged**
