### PR TITLE
changelog: update changelog for 0.16

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

This commit updates the `changelog` for the `0.16.0` release.

#### How to test

Verify the `changelog` entries.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

 Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
> Looks Ok, but what about the breaking changes , don't we put something in the cjhangelog here !!

@lmcbout which **breaking change** are you referring to?

**Comment by lmcbout** [comment]
What about the removing of textmate and others extension removal ?

**Comment by vince-fugnitto** [comment]
> What about the removing of textmate and others extension removal ?

@lmcbout I don't quite understand, the pull-request is not merged yet (see #6933) therefore there is no entry at the moment in the **breaking changes**. When the pull-request will be merged, the corresponding breaking changes notes will be added.

**Comment by marcdumais-work** [comment]
> > What about the removing of textmate and others extension removal ?
> 
> @lmcbout I don't quite understand, the pull-request is not merged yet (see #6933) therefore there is no entry at the moment in the **breaking changes**. When the pull-request will be merged, the corresponding breaking changes notes will be added.

So I guess we need to commit the other PR first and then @vince-fugnitto will rebase this one here on top?

**Comment by marcdumais-work** [comment]
ok, https://github.com/eclipse-theia/theia/pull/6933 is merged. Vince, can you quickly rebase this one here?

**Comment by vince-fugnitto** [comment]
> ok, #6933 is merged. Vince, can you quickly rebase this one here?

It's been rebased :)

**Pull request merged**
