### PR TITLE
fix broken link in CHANGELOG.md

### PR DESCRIPTION
**Pull request by amiramw**
Signed-off-by: Amiram Wingarten <amiram.wingarten@sap.com>

#### What it does

fix broken link in CHANGELOG.md

#### How to test

Verify the new link works.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by DukeNgn — APPROVED** [review]

**Comment by amiramw** [comment]
Seems I need also approval from someone with write access 🤔

**Review by colin-grant-work — APPROVED** [review]
LGTM

**Comment by colin-grant-work** [comment]
I've never merged something myself before, though, so I'll put merging this on my to-do list for next week when more committers are around and I can check with them to make sure I wouldn't be disrupting some sort of workflow I'm not aware of.

**Comment by amiramw** [comment]
I'll merge. I believe it's ok. Thanks.

**Pull request merged**
