### PR TITLE
Fix remote support in packaged apps

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Closes https://github.com/eclipse-theia/theia/issues/13140

Currently. the `ApplicationPackage` service is bound this way:

```ts
bind(ApplicationPackage).toDynamicValue(({ container }) => {
  const { projectPath } = container.get(BackendApplicationCliContribution);
  return new ApplicationPackage({ projectPath });
}).inSingletonScope();
```

However, the `projectPath` remains undefined, until the CLI app lifecycle has completed. This means that the `ApplicationPackage` may already be injected into other services with its `projectPath` undefined. This seems to be the case in https://github.com/eclipse-theia/theia-blueprint/pull/350 and in https://github.com/eclipse-theia/theia/issues/13140.

This change changes the way the `projectPath` is set. Instead of waiting until the CLI lifecycle completes, we set the `BackendApplicationPath` as soon as possible (at js load time). It didn't really make a lot of sense for the `projectPath` to be a CLI setting anyway, given that we use it to find our own code.

#### How to test

1. Use the SSH remote feature and assert that it works as expected
2. Open a webview from a plugin and assert that it loads and works as expected

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by msujew** [comment]
cc @jfaltermeier This should fix https://github.com/eclipse-theia/theia-blueprint/pull/350. Can you test it?

**Comment by jfaltermeier** [comment]
@msujew Yes I can test it tomorrow.

**Comment by jfaltermeier** [comment]
Hi, so I've built a local next version based on your branch and consumed it in Blueprint. 
I then ran into an error message "Server error while downloading native dependency from", because there is no github release matching my next version, from where it would get the native parts. 
I then more or less hardcoded this URL to the last Github Release and built a new local next version. 

With this I ran into the same issue as before (https://github.com/eclipse-theia/theia-blueprint/pull/350#issuecomment-2034718037)

But I don't know how the remote package works exactly, so maybe with above "fix"/hack it is not expected to work. 
Do I have to rebuild those native parts as well? Do the versions have to match for some copying to work (e.g. I can see that the `.theia-ide-electron-app-1.48.300-remote` directory exists in the container including the native parts. This has the version number of the last release and not my local next version)?

**Comment by msujew** [comment]
@jfaltermeier Thanks for testing. Looking closer at the error, I believe that I misunderstood the source of the issue. Sorry for that :/

I'll try to debug this myself later to see what goes wrong.

**Comment by msujew** [comment]
@jfaltermeier Alright, found the issue. When the application is packaged, the `path.relative` call returned bogus data for some reason. In fact, the mapping using `path.relative` wasn't necessary at all, since `glob` already returns all file paths in relative form. See latest commit on this PR. I've applied the same fix to the theia-blueprint repo and was successfully able to run the dev-container and remote SSH feature.

Note that it still required the other change for me, since otherwise the `projectPath` wasn't correctly computed.

**Review by jfaltermeier — APPROVED** [review]
Looks good to me, thank you!
I was also able to get a dev-container running in Theia Blueprint as well:
ksnip_20240417-142232

**Pull request merged**
