### PR TITLE
Left border for popup menu

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Improves left border of popup menus.

Popup menu without left border:
to 1

With left border it looks consistently with highlighted item in top menu.

after 1

We need to add `!important` suffix for focused menu to prevent popup trembling when it loses focus.

Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
Could it be applied only to top-level menu entries? not to sub (See File -> Settings) and context menus.

**Comment by vitaliy-guliy** [comment]
Sure, I have pushed the updates.

**Comment by vince-fugnitto** [comment]
@vitaliy-guliy it looks like your eca might have expired

**Comment by akosyakov** [comment]
We've completely restyled how menu bar is rendered in https://github.com/eclipse-theia/theia/pull/6722  I don't think it is applicable anymore.

**Pull request closed without merging**
