### PR TITLE
Simplify markdown rendering for preferences

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Instead of using a custom `MarkdownRenderer` (introduced with #10431), we simplify the code by correctly using the `markdownit` library.

#### How to test

The same testing steps as in #10431, confirm that no regression has occurred.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by msujew** [comment]
cc @colin-grant-work You were right, there was a simpler way of handling things. I removed the `MarkdownRenderer` class. Hopefully, not too many downstream-users started depending on it.

**Review by colin-grant-work — APPROVED** [review]
This approach is leaner than the previous one, and I observe no regressions:
 - Clicking on a preference name scrolls that preference into view
 - Clicking on a link opens the link in a new browser window.

**Comment by msujew** [comment]
@colin-grant-work FYI, added the removal of the `MarkdownRenderer` as a breaking change to the changelog. Will merge after CI is green.

**Comment by kittaakos** [comment]
@msujew, I have noted that multiple `markdown-it` instances are used in the preference editor. `markdow-it` will require `linkify-it`, which will have the [following regex](https://github.com/markdown-it/linkify-it/blob/9482bfec2532cfccb8d7a55f1b89facf54760b48/lib/re.js#L9-L12) for each preference value. Could Theia (re)use one `markdown-it` instance for parsing the markdown? With TheiaBlueprint Version `1.32.0 (1.32.0.92)`, I have dozens of the same regex string. Thank you!



https://user-images.githubusercontent.com/1405703/205339732-6d811821-5dc6-4026-abef-9450485f93e3.mp4

**Comment by colin-grant-work** [comment]
With the addition of markdown rendering in the Monaco package, I think it should be possible to get rid of `markdown-it` entirely in `preferences`?

**Pull request merged**
