### PR TITLE
[electron] fix resolution of hostname placeholder

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- improvements for https://github.com/eclipse-theia/theia/issues/7156: derives host and port from URL 

#### How to test

- install https://github.com/vince-fugnitto/webview-example/releases/download/1.0.0/cat-coding-0.0.1.vsix
- comment out https://github.com/eclipse-theia/theia/blob/b50047b886d8cc9eb2f7dccd1907c3485fe6ccda/packages/core/src/electron-node/token/electron-token-backend-contribution.ts#L39-L46 (security token for webview still should be figured out)
- rebuild
- start electron
- check that you can open start coding webview

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
I gave it a try and It did not work for me - still a blank page. No error or warning in either FE or BE logs.

**Comment by akosyakov** [comment]
Forbidden is for sure from this code. Are you sure that recompiled the core package after changes?

**Comment by akosyakov** [comment]
@marcdumais-work I've just realized that you are probably trying in Gitpod. The issue is that Gitpod is using custom webview hostname pattern which is not based on subdomains, such combination will never work in Electron. I've pushed a commit that make sure that in Electron we only use the default hostname patten which is based on localhost subdomains.

**Comment by akosyakov** [comment]
@marcdumais-work @vince-fugnitto my bad, you should comment out: https://github.com/eclipse-theia/theia/blob/b50047b886d8cc9eb2f7dccd1907c3485fe6ccda/packages/core/src/electron-node/token/electron-token-backend-contribution.ts#L39-L46

🤦

**Comment by akosyakov** [comment]
btw there are still some issues with icons in Electron:
Screenshot 2020-05-15 at 10 05 12

**Comment by akosyakov** [comment]
Merging, but someone has to have a look how to set a token for localhost subdomains as well.

**Comment by marcdumais-work** [comment]
> @marcdumais-work I've just realized that you are probably trying in Gitpod. The issue is that Gitpod is using custom webview hostname pattern which is not based on subdomains, such combination will never work in Electron. I've pushed a commit that make sure that in Electron we only use the default hostname patten which is based on localhost subdomains.

Thanks @akosyakov - Indeed I was using Gitpod. There was another issue anyway so it would not have worked in any case.  I just used Gitpod to test Paul's [new PR](https://github.com/eclipse-theia/theia/pull/7847#issuecomment-634273331). The demo Webview worked flawlessly with the new hostname pattern you set :)

**Pull request merged**
