### PR TITLE
Properly re-render problem widget and fix problem matching

### PR DESCRIPTION
**Pull request by martin-fleck-at**
#### What it does
- Ensure we re-render the tree model if the problem widget is activated
- Update Ansi stripping to catch Windows 'clear screen' and other codes
- Consistently use Theia URI in problem matcher protocol

Fixes https://github.com/eclipse-theia/theia/issues/12724

#### How to test
- Follow instructions in bug report or checkout https://github.com/eclipse-theia/theia/tree/martin-fleck-at/issue-12724-test
- Run Electron App (either through launch config or command line)
- Create a task in a workspace with the following content:
```
{
   "version": "2.0.0",
   "tasks": [
      {
         "label": "echo",
         "type": "shell",
         "command": "@echo somefile.abc:1:4: warning: the roof is on fire ",
         "problemMatcher" : ["$myproblemmatcher"]
      }
   ]
}
```
- Run Task 'echo' and check the Problems view:

image
(Windows)

image
(File path on Hover)

image
(Linux)

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by jfaltermeier — COMMENTED** [review]
Thank you! I've tested on Windows and Linux. 
There is no need to resize the problem view anymore. Also the encoding issue in the filename is fixed. 

However the bug report also mentions `ERROR Request resize failed with error: Cannot resize a pty that has already exited Error: Cannot resize a pty that has already exited`. 
I am still seeing this on Windows.

**Comment by martin-fleck-at** [comment]
@jfaltermeier Thanks! I'll look into this and see if there is something I can do.

**Comment by martin-fleck-at** [comment]
@jfaltermeier That was actually quite a messy one but I think I found a good solution based on how VS Code handles the terminals in Windows. Could you please have another look?

**Review by jfaltermeier — APPROVED** [review]
Thanks, lgtm now!

**Comment by martin-fleck-at** [comment]
@tsmaeder @msujew Since you guys also worked on the terminal, do you wanna have another look at this? Since the change is not that small, another pair of eyes might provide additional insights.

**Pull request merged**
