### PR TITLE
Updated inversify to 5.0.1

### LINKED ISSUE #3298: [quality] Update to `inversify` `5.0.1`
`inversify` `5.0.1` is the same as the currently used `inversify@4.14.0`.

Related warning:
```
warning @theia/core > inversify@4.14.0: Re-Released as 5.0.1
```

### PR DESCRIPTION
**Pull request by spoenemann**
#### What it does
Fixes #3298.

CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20823

#### How to test
Everything should work as before.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
I do not know if it is related, but I can see this in the console:
```
Error: Cannot call function 'setApplicationMenu' on missing remote object 11
    at throwRPCError (/Users/akos.kitta/git/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Users/akos.kitta/git/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Users/akos.kitta/git/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)
    at metaToException (/Users/akos.kitta/git/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Users/akos.kitta/git/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Users/akos.kitta/git/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Function.remoteMemberFunction (/Users/akos.kitta/git/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at file:///Users/akos.kitta/git/theia/examples/electron/lib/55.bundle.js:215:38
    at file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:109319:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:109334:39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:109422:29)
    at KeybindingRegistry.../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.setKeymap (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:87590:33)
    at KeymapsService.<anonymous> (file:///Users/akos.kitta/git/theia/examples/electron/lib/48.bundle.js:1416:49)
```

I have tried it on macOS with the electron example. 845829e6e

**Comment by spoenemann** [comment]
@kittaakos that exception seems to be a long-standing Electron problem: https://github.com/electron/electron/issues/8205
I believe it's not related to Inversify.

**Comment by kittaakos** [comment]
> seems to be a long-standing Electron problem

I have not seen this before. Let me compare your changes with the `master` state.

**Comment by kittaakos** [comment]
> Let me compare your changes with the `master` state.

I do not see the same error on the `master`.

**Comment by kittaakos** [comment]
> I do not see the same error on the `master`.

I could not reproduce this on `GH-3298` either.

**Pull request merged**
