### PR TITLE
Virtual keyboard fix.

### PR DESCRIPTION
**Pull request by brettjrea**
Fix for remote connections.
https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by brettjrea** [comment]
Thanks for the quick response. I have been building theia on my android device in debian userland and my keyboard wasn't backspacing. I added that line and everything seemed to work properly so I figured that I would submit it.

**Comment by vince-fugnitto** [comment]
> Thanks for the quick response. I have been building theia on my android device in debian userland and my keyboard wasn't backspacing. I added that line and everything seemed to work properly so I figured that I would submit it.

@brettjrea I'm surprised it works as we do not have support for it yet (https://github.com/eclipse-theia/theia/issues/7919#issuecomment-635413804), are you developing your application using Theia itself or VS Code? In any case, I think the preference should not be enabled globally for everyone that develops this repository as it seems to be a troubleshooting preference (like in your case), but for other cases it may have some implications.

**Comment by brettjrea** [comment]
It was unusable on my android in debian proot until I added it maybe it was coincidence. I understand thanks for your time and the information.

**Comment by vince-fugnitto** [comment]
> It was unusable on my android in debian proot until I added it maybe it was coincidence. I understand thanks for your time and the information.

@brettjrea thank you for contributing anyways, looking forward to any new contributions you may have in the future!
Is the pull-request closeable?

**Comment by brettjrea** [comment]
Sure, thanks for again for the info.

**Pull request closed without merging**
