### PR TITLE
respect keybinding scope and registration order during evaluation

### LINKED ISSUE #7836: Ctrl-c (terminate) not working in Terminals
### Bug Description:
When I run a task and type `<ctrl>-c` in the terminal, the task is not interrupted

### Steps to Reproduce:

1. Start any long running task
2. Click in the terminal window executing said task to give it focus
3. Type `<ctrl>-c?`
4. Observe: the task continues to execute

My expectation would be that the task be interrupted, like in a regular shell.

### Additional Information

- Operating System: Windows 10, Chromium, but also does not work on Linux
- Theia Version: Master

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #7836: see explanation https://github.com/eclipse-theia/theia/issues/7836#issuecomment-630634837
- (performance) Also match only first keybinding on keydown, don't traverse over all keybindings.

#### How to test

- Monaco: see tests from https://github.com/eclipse-theia/theia/pull/6170
- Theia extension: see https://github.com/eclipse-theia/theia/issues/7836 on linux/windows
- VS Code extension: see https://github.com/eclipse-theia/theia/pull/6625#discussion_r354832173
  - install emacs extension
  - open some editor
  - use `ctrl+x ctrl+l` on linux/windows it should not cut, but wait for `ctrl+l`

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@tsmaeder @RomanNikitenko @502647092 Could you check please whether it resolves issues mentioned in https://github.com/eclipse-theia/theia/issues/5749, https://github.com/eclipse-theia/theia/issues/7833 and https://github.com/eclipse-theia/theia/issues/7836? 

I'm testing too, but I'm on Mac.

**Comment by tsmaeder** [comment]
Ctrl-c seems to work on Windows FF and Chromium.

**Comment by tsmaeder** [comment]
I've found a different problem, though: every once in a while (seems more frequent on Firefox), the following task:
```
{
            "type": "shell",
            "command": "timeout /T 10",
            "label": "wait",
            "problemMatcher":"$eslint-compact"
        }
```
Seems to terminate with exit code 0 immediately instead of waiting 10 seconds.
@akosyakov is your branch based on latest master?

**Comment by akosyakov** [comment]
> @akosyakov is your branch based on latest master?

yes, i don't think it is related to keybindings handling

**Comment by akosyakov** [comment]
I'm:
- adding more regression tests for Monaco and terminal extensions
- trying to resurrect some fixes from https://github.com/eclipse-theia/theia/pull/5326 from @JPinkney (code was changed in the meantime unfortunately)

**Comment by tsmaeder** [comment]
I've built master after deleting all node_modules folders, and I can't observer the "early exit"-behaviour anymore. Not sure what did it, though.

**Comment by akosyakov** [comment]
@502647092 I would love to have your feedback whether it resolves issues in https://github.com/eclipse-theia/theia/issues/5749?

**Comment by akosyakov** [comment]
@RomanNikitenko could you double test it please? I have changed a lot since you looked at it. Thank you 🙏

**Comment by RomanNikitenko** [comment]
@akosyakov 
Tested terminate process in terminal and terminate a task after your update - it works well for me!
terminate_test

**Comment by akosyakov** [comment]
@RomanNikitenko ok, thanks, I will merge tomorrow morning it there won't be any other feedback

**Comment by RomanNikitenko** [comment]
Also I tried for emacs:
- `select all` - ctrl-x h
- `quick open` for a file - ctrl-x b 

emacs_ctrl_x

**Comment by 502647092** [comment]
@akosyakov  It looks like it can work

**Pull request merged**
