### PR TITLE
[plugin] fix: dispose deploy listener on close

### PR DESCRIPTION
**Pull request by ensorrow**
#### What it does
image
The deploy listener won't dispose when connection got disposed, which will cause memory leak.

#### How to test
1. Lower the max listener count in `theia/packages/core/src/common/event.ts`
2. trying to disconnect the client (you can use the proxy below to simulate the disposed connection)
```javascript
var express = require('express');
var app = express();
var httpProxy = require('http-proxy');
var proxy = httpProxy.createProxyServer({ target: 'http://localhost:3000', ws: true });

var server = require('http').createServer(app);

// proxy HTTP GET / POST
app.get('/*', function (req, res) {
  console.log("proxying GET request", req.url);
  proxy.web(req, res, {});
});
app.post('/*/*', function (req, res) {
  console.log("proxying POST request", req.url);
  proxy.web(req, res, {});
});

// Proxy websockets
server.on('upgrade', function (req, socket, head) {
  console.log("proxying upgrade request", req.url);
  proxy.ws(req, socket, head);
});

server.listen(3001);
```

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@ensorrow please [sign your work](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#checklist-sign-off) and accept [ECA](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement), otherwise we cannot continue

**Comment by ensorrow** [comment]
> @ensorrow please [sign your work](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#checklist-sign-off) and accept [ECA](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement), otherwise we cannot continue

Done

**Comment by akosyakov** [comment]
@ensorrow thank you @marcdumais-work i am not sure why eca check is still not happy

Maybe an empty line is required before sign-off line.

**Comment by benoitf** [comment]
@ensorrow 

the Signed-Off and the commit e-mail should be the same

```
Author: xunhe.lzy <.....@alibaba-inc.com>
```

```
Signed-off-by: Louis Lv <.....@qq.com>
```

**Comment by akosyakov** [comment]
eca is still not happy :(

**Comment by ensorrow** [comment]
Too busy to fix eca problem in time, sorry for that @akosyakov

**Comment by akosyakov** [comment]
@ensorrow thank you for dealing with ECA check :)

**Pull request merged**
