### PR TITLE
upgrade NPM builtin version to 1.44.2

### LINKED ISSUE #7779: NPM scripts not available with builtin version 1.44.2
### Bug Description:
When you upgrade the npm builtin version from version 1.39.1 to version 1.44.2, you don't see any npm scripts available in the NPM view.

An **error** is reported:
**NPM Scripts: r.Task2 is not a constructor**

- With builtin 1.39.1 NPM View shows the scripts
- With builtin 1.44.2 NPM view is empty

### Steps to Reproduce:

1. Change the builtin package for npm in your package.json
2.FROM
"vscode-builtin-npm": "https://open-vsx.org/api/vscode/npm/1.39.1/file/vscode.npm-1.39.1.vsix"
TO
"vscode-builtin-npm": "https://open-vsx.org/api/vscode/npm/1.44.2/file/vscode.npm-1.44.2.vsix"
3-. Clean up the plugins folder
4. yarn download:plugins
5. Start Theia and use Theia as a workspace
--> Open the NPM view and there is no scripts available

### Additional Information

- Operating System: UBUNTU 18.04
- Theia Version: latest

### PR DESCRIPTION
**Pull request by elaihau**
**upgrade NPM builtin version to 1.44.2**

- The vs code built in extension `npm` does not work with Theia's plugin
extension due to not being able to find the constructor of `Task2`. This
pull request addes the missing constructor, and upgrades the version of
`npm` in Theia.
- fixed #7779 

**added `detail` to the task config schema**

- In VS Code a `detail` property can be added to the contributed and configured tasks. The content of that `detail` property is displayed as part of the task quick open menu items. With changes in this commit, `detail` is added to the task config schema.

Signed-off-by: Liang Huang <lhuang4@ualberta.ca>

#### How to test

- Start a workspace where scripts are defined in `package.json`.
- Check if all scripts are available in the NPM VIEW, and if the scripts can be started from the view.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

### CODE REVIEW

**Comment by akosyakov** [comment]
@elaihau Where do we use `detail2` in the task extension? We should avoid just stubbing APIs when it is possible.

**Comment by elaihau** [comment]
> Where do we use `Task2.detail` in the task extension? We should avoid just stubbing APIs when it is possible.

@akosyakov 
`Task2.detail` is not used in Theia's task extension at all.
However it is used as a property of the Task class in some VS Code extensions that are recently updated :)

In this case, having `Task2.detail` defined or not-defined does not matter to us because
- Theia's task extension does not use the `detail`
- `Task2.detail` is optional anyway, so extensions can run without throwing errors even if `Task2.detail` is not defined.

In my opinion, having `Task2.detail` defined makes Theia API becomes more compatible with VS Code. 

What do you think ?

**Comment by elaihau** [comment]
OK the built-in `npm` breaks more than I thought. 

As the GIF shows the "Run" and "Refresh" icons are invisible after upgraded to 1.44.2
Peek 2020-06-12 11-08

I will see what I can do to bring them back

**Comment by vince-fugnitto** [comment]
> OK the built-in `npm` breaks more than I thought.
> As the GIF shows the "Run" and "Refresh" icons are invisible after upgraded to 1.44.2
> I will see what I can do to bring them back

@elaihau I believe the issue is that we do not yet support codicons as defined in the `package.json` of extensions, something I noticed when I created my own extension. It looks like the `npm` extension uses these codicons now:

https://github.com/microsoft/vscode/commit/573fe9e8002c64af8d7c46b5692eb69511e6cfc6#diff-45afd42bd496e3cf085556a5c1d1a632R57-R60

**Comment by elaihau** [comment]
> > OK the built-in `npm` breaks more than I thought.
> > As the GIF shows the "Run" and "Refresh" icons are invisible after upgraded to 1.44.2
> > I will see what I can do to bring them back
> 
> @elaihau I believe the issue is that we do not yet support codicons as defined in the `package.json` of extensions, something I noticed when I created my own extension. It looks like the `npm` extension uses these codicons now:
> 
> [microsoft/vscode@573fe9e#diff-45afd42bd496e3cf085556a5c1d1a632R57-R60](https://github.com/microsoft/vscode/commit/573fe9e8002c64af8d7c46b5692eb69511e6cfc6#diff-45afd42bd496e3cf085556a5c1d1a632R57-R60)

Thank you for information @vince-fugnitto !
If the codicon support won't be added in this release I guess I should close this pull request for now? We don't want to upgrade `npm` to a version that only works partially in Theia. What do you think?

**Comment by vince-fugnitto** [comment]
> Thank you for information @vince-fugnitto !
> If the codicon support won't be added in this release I guess I should close this pull request for now? We don't want to upgrade `npm` to a version that only works partially in Theia. What do you think?

@elaihau I don't think there's an issue upgrading the builtin in this repo, downstream projects can choose their own compatible versions. At least with the new `npm` we can find other potential issues faster, missing icons can be tracked but aren't a showstopper (it is potentially an issue with other builtins as well).

**Comment by akosyakov** [comment]
> Task2.detail is not used in Theia's task extension at all.

How hard to add it? If it is hard there should be an issue at least that we are of the issue. Stubbing VS Code API does not mean that they are implemented and does not make Theia compatible, since whenever such APIs are used they don't make any effect.

**Comment by elaihau** [comment]
> > Task2.detail is not used in Theia's task extension at all.
> 
> How hard to add it? If it is hard there should be an issue at least that we are of the issue. Stubbing VS Code API does not mean that they are implemented and does not make Theia compatible, since whenever such APIs are used they don't make any effect.

@akosyakov I added one more commit to this pull request to support using `detail` in Theia's task extension.

**Comment by akosyakov** [comment]
@vince-fugnitto Could you retest it please? Please also while reviewing of VS Code compatibility make sure that such APIs are used. 🙏

**Pull request merged**
