### PR TITLE
playwright: Update to latest versions and add new page objects

### PR DESCRIPTION
**Pull request by ndoschek**
#### What it does

- Update `playwright` to the latest version
- Extend page objects for compact and nested folders
- Extend ExplorerView tests with compact folders

Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>

#### How to test

- Run playwright tests via `yarn test:playwright` from root directory

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by ndoschek** [comment]
Hi @planger, as you already had an initial look at my changes, could you please suggest additional reviewers for this PR? Thank you!

**Comment by planger** [comment]
Thank you, Nina! As mentioned, I'm in favor and already reviewed this change.

I think, recently, @marcdumais-work and @vince-fugnitto had a second look at Playwright-related PRs. Are any of you up to a short review? Thank you very much in advance!

**Comment by vince-fugnitto** [comment]
@planger I'm fine with the changes to playwright as long as they pass :) 
I performed a review for the updated dependencies that we should wait for their approval:

- [ ] [npm/npmjs/-/allure-commandline/2.23.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10099)
- [ ] [npm/npmjs/-/allure-js-commons/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10098)
- [ ] [npm/npmjs/-/allure-playwright/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10097)
- [ ] [npm/npmjs/@playwright/test/1.37.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10096)

**Comment by planger** [comment]
@vince-fugnitto Thank you very much! I'll add an approve to this PR then and wait for the approval of the updated dependencies before merging.

Thanks again for the swift response and for filing the dependency updates!

**Review by planger — APPROVED** [review]
Thanks, looks good to me! :+1:

As mentioned [above](https://github.com/eclipse-theia/theia/pull/12843#issuecomment-1686402748), we'll wait with merging until all dependency updates have been approved.

**Pull request merged**
