### PR TITLE
repo: perform `yarn upgrade` following `v1.20.0` release

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

The pull-request performs a `yarn upgrade` following the `v1.20.0` release of the framework.
The update of the repository's lockfile is important in order to identify issues with our version ranges that downstream applications may experience.

#### How to test

- [x] confirm the build is successful
- [x] confirm the tests pass
- [x] confirm the application starts
- [x] confirm that the 3PP license check passes    

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@marcdumais-work would it be possible to run the automatic licencing tool to get the licenses approved:

```
INFO: Checking results against the baseline...
WARN: Some entries in the baseline did not match anything from dash-licenses output:
npm/npmjs/-/jsmin/1.0.1: Approved as 'works-with': https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23640https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23640
npm/npmjs/-/seek-bzip/1.0.6: Approved by CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17349#c7
npm/npmjs/-/typescript/4.4.3: Approved manually: https://github.com/eclipse-theia/theia/pull/10247
ERROR: Found results that aren't part of the baseline!
error Command failed with exit code 1.
> npm/npmjs/-/seek-bzip/1.0.6
> npm/npmjs/-/typescript/4.4.3
X npm/npmjs/-/electron-to-chromium/1.4.2, 
X npm/npmjs/-/typescript/4.5.2, Apache-2.0
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

I'll also remove the entries not present in the dash-licenses output afterwards.

**Comment by marcdumais-work** [comment]
@vince-fugnitto done. Only a new version of `typescript` needed scrutiny, I think - it's ongoing:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/1671

**Comment by vince-fugnitto** [comment]
@marcdumais-work thank you for the automatic submission to get the new dependency versions approved :+1: everything is now passing!

**Review by alvsan09 — APPROVED** [review]
I can confirm that the application builds and starts as expected :+1: 

The updates look good to me !!

**Comment by marcdumais-work** [comment]
I re-ran `dash-licenses`. Automatic review setup for `npm/npmjs/-/istanbul-reports/3.1.1`: 
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/1710

**Review by paul-marechal — APPROVED** [review]

**Pull request merged**
