### PR TITLE
output: improve output display

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

The previous font-weight of the ouput-view made the visibility difficult (especially on lighter themes), and this pull-request updates it to be more consistent and easier to use.

The following pull-request updates the **output-view** to improve the output display:
- updates the output-view content (including an update to the font-weight).
- refactors the output-view to make use of css variables.
- renames `--theia-terminal-font-family` to the more generic name `--theia-monospace-font-family` (the variable was previously unused).

<details>

<summary>Before & After</summary>

<br />
_Before_:

<div align='center'>

Screen Shot 2020-05-15 at 10 07 32 AM

Screen Shot 2020-05-15 at 10 07 19 AM

</div>

_After_:

<div align='center'>

Screen Shot 2020-05-15 at 10 04 10 AM

Screen Shot 2020-05-15 at 10 04 16 AM

</div>

</details>

#### How to test

_master_:
1. start the application, open the output-view and select 'my test channel'
2. view the output under different themes (light + dark) - the output is difficult to see conformably

_pull-request_:
1. perform the same steps above with the pull-request built 

Alternatively you may also set the JSON trace to verbose and open a JSON file (ex: 'package.json') to see much more output.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
We will switch to monco editor with #7570. Would that make this issue obsolete?

**Comment by vince-fugnitto** [comment]
> We will switch to monaco editor with #7570. Would that make this issue obsolete?

Yes I remember :) The switch to the monaco-editor will make the output-view will definitely improve the view (like vscode).

I noticed the output was not easy to read during a pull-request review and thought that a quick fix (even if obsolete when the switch happens) might be an improvement to end-users. I also do not know when the switch will happen as the pull-request is already quite involving and still needs to be finalized and reviewed.

**Comment by kittaakos** [comment]
> make this issue obsolete?

> can close the pull-request

No no, I was stupid and did not notice it is already a PR. It affects only the electron-based app, right? I am happy to verify right now...

**Comment by vince-fugnitto** [comment]
> > make this issue obsolete?
> 
> > can close the pull-request
> 
> No no, I was stupid and did not notice it is already a PR. It affects only the electron-based app, right? I am happy to verify right now...

No problem! It is for both the `browser` and `electron` targets.

**Comment by kittaakos** [comment]
> It is for both the `browser`

I see.

Browser before:
Screen Shot 2020-05-15 at 17 29 26

Browser after:
Screen Shot 2020-05-15 at 17 29 18

It is a bit too "heavy" for me in the browser...

> and `electron` targets.

but I agree, it is hardly visible in electron (with the dark theme) so it is a reasonable change. 👍  Other committers can vote or decide I do not have any objections. Please keep in mind #7570.

----

Regarding the code change you did just to understand, it's all equivalent with adding `'fontWeight': 500` to the object, right?

**Comment by vince-fugnitto** [comment]
> Regarding the code change you did just to understand, it's all equivalent with adding `fontWeight: 600` to the object, right?

Yes, I refactored the code from the widget itself into the css stylesheet, and updated the font-weight for the monospace font-family. Originally, the font-weight on electron was too thin and made it difficult to easily view the content. I think it will look much better like you said when we start using monaco in the view.

**Pull request merged**
