### PR TITLE
Update nls metadata file for vscode version 1.77.0

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Closes https://github.com/eclipse-theia/theia/issues/12517.

Updates the `nls.metadata.json` file for version 1.77.0 of vscode. See also https://github.com/eclipse-theia/theia/pull/12516.

#### How to test

The Lint CI passes, indicating no incorrect localization usages.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
@msujew if we update the API version in 1.37.2, this change should be cherry-picked, as well, right?

**Comment by tsmaeder** [comment]
see https://github.com/eclipse-theia/theia/issues/12518

**Comment by msujew** [comment]
@tsmaeder Preferably, yes.

**Comment by vince-fugnitto** [comment]
@msujew would it be possible to add documentation on how to retrieve or produce the `nls.metada.json` file, perhaps as a [wiki](https://github.com/eclipse-theia/theia/wiki) page? It would probably be useful for others to know how to perform the update if needed.

**Comment by msujew** [comment]
@vince-fugnitto [Done :)](https://github.com/eclipse-theia/theia/wiki/Internationalization-Updates)

**Review by vince-fugnitto — APPROVED** [review]
LGTM :+1: 
Thank you for also taking the time to document the process!

**Pull request merged**
