### PR TITLE
8969-upgrade-monaco-editor-core-to-standalone-0.22.x

### PR DESCRIPTION
**Pull request by danarad05**
In preparation for upgrading `monaco-editor-core` to `standalone/0.22.x` these changes were implemented:
1) signatures alignment to `standalone/0.22.x`
2) editor preferences synced with `standalone/0.22.x`

Signed-off-by: Dan Arad <dan.arad@sap.com>

#### What it does
This PR updates Theia repo with these changes:
1) signatures alignment to `standalone/0.22.x`
2) editor preferences synced with `standalone/0.22.x`

It is also second part of 8969 where first part is generating `monaco-editor-core@0.22`.
 
#### How to test
1) `How to test` section for the previous PR #8010.
2) Integration tests in: #7265.

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by marechal-p — APPROVED** [review]
CI is unrelated

**Comment by marechal-p** [comment]
@danarad05 I was wondering if there's any reason why we can't use things from vscode's monaco editor rather than copying everything?

**Comment by RomanNikitenko** [comment]
I guess the PR is only one part of https://github.com/eclipse-theia/theia/issues/8969
and the changes should be tested and applied when a new version of `@theia/monaco-editor-core` is applied to `Theia`.

I mean - at the moment `Theia` uses `0.20.0` version of `Monaco`, but the current changes for `0.22` version.

@danarad05 
should it be a draft PR or maybe I missed something...

**Review by RomanNikitenko — COMMENTED** [review]
I guess the PR is only one part of https://github.com/eclipse-theia/theia/issues/8969
and the changes should be tested and applied when a new version of `@theia/monaco-editor-core` is applied to `Theia`.

I mean - at the moment `Theia` uses `0.20.0` version of `Monaco`, but the current changes for `0.22` version.

@danarad05 
should it be a draft PR or maybe I missed something...

**Comment by danarad05** [comment]
> I guess the PR is only one part of #8969
> and the changes should be tested and applied when a new version of `@theia/monaco-editor-core` is applied to `Theia`.
> 
> I mean - at the moment `Theia` uses `0.20.0` version of `Monaco`, but the current changes for `0.22` version.

correct. this PR is second part of new 0.22 version - whose repo location is currently debated.

> should it be a draft PR or maybe I missed something...

If that it the procedure then it should be draft.. don't remember if there was an option. can you change type to draft? I'm unable.
Thanks

**Comment by danarad05** [comment]
@marechal-p Thanks for reviewing.

> wondering if there's any reason why we can't use things from vscode's monaco editor rather than copying?

That is a good question. I'm not sure what are reasons for this approach - currently there are many diffs - maybe in past there were more. 
@RomanNikitenko - do you know?

**Comment by RomanNikitenko** [comment]
> If that it the procedure then it should be draft.. don't remember if there was an option. can you change type to draft? I'm unable.

I meant - it's better to have the draft status for the current state of the PR, so people can see that it's still in progress.

It should be possible to change a PR status from `Reviewers` menu => `Convert to draft`
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

**Comment by RomanNikitenko** [comment]
> @marechal-p Thanks for reviewing.
> 
> > wondering if there's any reason why we can't use things from vscode's monaco editor rather than copying?
> 
> That is a good question. I'm not sure what are reasons for this approach - currently there aren't many diffs - maybe in past there were more.
> @RomanNikitenko - do you know?

You can see some info about it here:
- https://github.com/eclipse-theia/theia/issues/7457  
- https://github.com/eclipse-theia/theia/issues/7261

**Comment by danarad05** [comment]
> > If that it the procedure then it should be draft.. don't remember if there was an option. can you change type to draft? I'm unable.
> 
> I meant - it's better to have the draft status for the current state of the PR, so people can see that it's still in progress.
> 
> It should be possible to change a PR status from `Reviewers` menu => `Convert to draft`
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

Don't know how I missed it:).. Thanks

**Comment by danarad05** [comment]
Closing this PR as created a new one - #9154 - for version **standalone/0.23.x**  which has been released in meantime.

**Pull request closed without merging**
