### PR TITLE
Support frontend extensions in asWebviewUri

### PR DESCRIPTION
**Pull request by thegecko**
Signed-off-by: robmor01 <Rob.Moran@arm.com>

#### What it does

Added support for the `asWebviewUri()` function in frontend plugins. Previously, the default (backend) URLs were being created which embed the `file` scheme in the URL. This doesn't work in frontend plugins.

The refactor of `webview-environment.resourceRoot()`takes into account the plugin host to return a URL with the correct hostname and path.

`asWebviewUri` has been simplified to undertake just replacement on the resourceRoot without modifying the URL too much.

Tested to work with a VS Code Web Extension webview in these environments:

- Backend plugin in browser Theia (currently works)
- Backend plugin in electron Theia (currently works)
- Frontend plugin in browser Theia (now fixed)

Unsupported:

- Frontend plugin in electron Theia

#### How to test

Create a frontend webview (VS Code Web Extension or frontend Theia plugin) which utilises the `asWebviewUri()` function (e.g. to load JAvaScript or CSS assets from the plugin).

Let me know if I need to create a test extension.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by msujew** [comment]
@thegecko I would gladly look into this. Do you mind creating a minimal test extension for this?

**Comment by thegecko** [comment]
Thanks @msujew , this should do it:

https://github.com/thegecko/simple-webview

**Comment by thegecko** [comment]
Did the test extension help?

**Review by msujew — APPROVED** [review]
I can confirm that the changes allow to correctly load webviews for frontend extensions.

**Comment by thegecko** [comment]
Thanks!

**Pull request merged**
