### PR TITLE
fix(prepare-travis): Always use JSON output of the yarn workspaces command

### PR DESCRIPTION
**Pull request by benoitf**
#### What it does

With yarn v1.22.0 the output is not rendered in JSON when it's the last parameter
Fixes https://github.com/eclipse-theia/theia/issues/7118

#### How to test
bump to yarn v1.22.0

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Change-Id: I98a0d59a98e3e3226cbc242c1a5e264aaa6fd607
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
Does it work with yarn 1.21?

**Comment by benoitf** [comment]
@akosyakov yes

**Comment by benoitf** [comment]
@akosyakov also seems to work with
```bash
$ yarn --version
1.15.2
```
used on CI

**Comment by benoitf** [comment]
If no more feedback today, will merge it.

**Comment by akosyakov** [comment]
@benoitf please do 👍

**Pull request merged**
