### PR TITLE
Fixed confirmExit behaviour for Electron apps

### PR DESCRIPTION
**Pull request by mcgordonite**
#### What it does

This PR restores the confirmation dialog shown in Electron mode when the user tries to exit without saving changes. On master, there is no confirmation, the app exits without saving.

This relates to an existing Electron issue: https://github.com/electron/electron/issues/9966. Not opening a dialog in the beforeunload handler and using the [will-prevent-unload](https://electronjs.org/docs/api/web-contents#event-will-prevent-unload) event gets around this.

theia-confirm

#### How to test

Start the Electron app then disable Auto Save. Either:
- Set the "application.confirmExit" preference to "ifRequired", make a change in a file but do not save it.
- Set the "application.confirmExit" preference to "always".

 Then try:
- Opening a new workspace.
- Refreshing the page.
- Closing the app.

In these cases, a confirmation dialog should be displayed.
- Clicking "Yes" should close the modal and unload the window.
- Clicking "No" should close the modal without unloading.

In all other cases, the app should behave as before with no confirmation modal.

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
I am verifying this...

**Comment by mcgordonite** [comment]
@kittaakos that's interesting, I can reproduce it every time. I have tried it on:
- Windows 10 (1809), node 10.16.1.
- Ubuntu 19.04, node 10.16.3.
- My colleague's mac.

I start from a fresh Theia clone, then:
1. Checkout https://github.com/eclipse-theia/theia/commit/24f5d20ea99b214f4a4c75540cc1d0a2727465ce
2. `yarn`
3. `yarn rebuild:electron`
4. `cd examples/electron`
5. `yarn start`

Then I follow the steps in the PR description.

For what it's worth, here's Ubuntu 19.04 with `always`:
theia-ubuntu

Windows 10 with `ifRequired`:
theia-windows

One possible difference is that I use the close button in the title bar, but it also happens when I use the ALT-F4 shortcut.

**Comment by kittaakos** [comment]
> I can reproduce it every time

I will try it on my Windows image.

**Comment by kittaakos** [comment]
> I will try it on my Windows image.

The `master` state is broken on Windows so I am going to review your changes and merge if it is OK.

**Pull request merged**
