### PR TITLE
Flaky Playwright test - notebook split cell #14450

### PR DESCRIPTION
**Pull request by dhuebner**
#### What it does

- Removed flaky expectation that assumes a line element has state `visible` #14450 
- Added logging to see the line element state if the test should fail again
- Updated Playwright to `^1.47.0` because earlier versions are not working with OS X Sequoia
- Added `allure-results` to .gitignore .  It is produced during Playwright tests run
- Adjusted test workspace location detection, because in the latest Playwright plug-in the working directory is the workspace root. In the older version it was the playwright configuration file directory. 

 
#### How to test

Tests are running automatically 

#### Follow-ups

Further investigate failing flaky test using new logging data as it is not reproducible locally. 

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by planger — APPROVED** [review]
Thank you! Code changes look good and the Playwright upgrade is also more than welcome. Let's observe whether this already resolves the flakiness. At least it'll give us more insights.

Thanks again!

**Comment by dhuebner** [comment]
@planger 
Do you know what causes the (Apache-2.0) License problem in playwright package?

**Comment by planger** [comment]
@dhuebner No unfortunately not, I'm afraid. Did they add some problematic dependency?

**Comment by dhuebner** [comment]
@tsmaeder 
Thank you a lot for your hints. 
Review ticked created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17367

**Pull request merged**
