### PR TITLE
Prevent task terminal title from being changed by task process

### LINKED ISSUE #13002: Task terminal title can be modified by task process
### Bug Description:

Normally when a task is spawned it has the title `Task: <task_title>`, however processes can [change the terminal title](https://unix.stackexchange.com/a/177598) by emitting an ANSI escape code which is captured by the terminal. This seems like suprising behaviour since it doesn't make much sense for the task tab to not have a corresponding task title.

### Steps to Reproduce:

1. In an open theia workspace, create the following `.theia/task.json`
```json
{
	"tasks": [
        {
            "label": "test task",
            "type": "process",
            "command": "scripts/test.sh",
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": []
        }
    ]
}
```
2. Create a shell file at `scripts/test.sh`, then run `chmod +x scripts/test.sh`
```bash
#!/bin/sh

echo hi
printf "\e]2;YOUR TITLE GOES HERE\a"
```
3. In theia command palette, run `Task: Run Task...` > choose `test task`

### Additional Information

- Operating System: Ubuntu 22.04.3
- Theia Version: 1.42.1

### PR DESCRIPTION
**Pull request by bryanchenmchp**
#### What it does

Set the terminal widget used by tasks to not use server title, so that the title of the task widget is not changed by the task process.

Resolves #13002 

#### How to test

Follow the steps to reproduce in #13002, the terminal title should not change

#### Follow-ups

N/A

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by martin-fleck-at — APPROVED** [review]
Nice catch! This also aligns the behavior with VSCode where a task execution does not change title of the terminal. We already prevent the title change in other places (e.g., debug or the terminal creation through plugins) the same way so very nice contribution. Thank you!

**Comment by martin-fleck-at** [comment]
@bryanchenmchp Could you please fix the conflict in the CHANGELOG.md? It should be something minor and then we can merge your PR.

**Comment by bryanchenmchp** [comment]
Is there a way to re-run failed CI checks?

**Comment by martin-fleck-at** [comment]
> Is there a way to re-run failed CI checks?

I was already out for the day but yes there is but I believe only for committers, I re-triggered the failed check.

**Pull request merged**
