### PR TITLE
Remove unused injections of ResourceProvider

### PR DESCRIPTION
**Pull request by amiramw**
## What it does
Remove unused injections of ResourceProvider.

#### How to test
Compile theia successfully.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by amiramw** [comment]
i forgot to sign my commit. should the eca voter fail on that?

**Comment by akosyakov** [comment]
> i forgot to sign my commit. should the eca voter fail on that?

cc @eclipsewebmaster @marcdumais-work ?

**Comment by amiramw** [comment]
signed it now

**Comment by marcdumais-work** [comment]
> i forgot to sign my commit. should the eca voter fail on that?

I did not have time to look before you signed. Did the ECA check  pass without the signature?

**Comment by amiramw** [comment]
> I did not have time to look before you signed. Did the ECA check pass without the signature?

correct

**Comment by marcdumais-work** [comment]
> correct

My memory is a bit hazy but IIRC the signature may only be required when the author is not a committer on the project. @vince-fugnitto is trying to test this with bogus PRs and the help of our non-committer students.

**Comment by marcdumais-work** [comment]
> the signature may only be required when the author is not a committer on the project. @vince-fugnitto is trying to test this with bogus PRs and the help of our non-committer students.

Not definite proof that this is the way it's intended to be, but it looks like the theory above checks-out in practice. Here are 3 PRs that have an unsigned commit: 
-  [PR](https://github.com/eclipse-theia/theia/pull/7602) by a __committer__ directly in this repo: __ECA check passed__
- [PR](https://github.com/eclipse-theia/theia/pull/7604) by a __committer__ originating from a fork: __ECA check passed__
-  [PR](https://github.com/eclipse-theia/theia/pull/7603) by a __non-committer__ originating from a fork: __ECA check NOT passed__

**Comment by marcdumais-work** [comment]
This seems to confirm the theory:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=466480#c1

**Pull request merged**
