### PR TITLE
Remove deprecated API: unfocusSearchFieldContainer, doUnfocusSearchFieldContainer()

### PR DESCRIPTION
**Pull request by SarveshMishra**
#### What it does

Fixes: https://github.com/eclipse-theia/theia/issues/10622
Remove deprecated API: unfocusSearchFieldContainer, doUnfocusSearchFieldContainer()

#### How to test

confirm that theia builds and that example application it starts.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by tsmaeder — DISMISSED** [review]
When we remove API, we should add an entry to the "breaking changes" section of the changelog document.

**Comment by marcdumais-work** [comment]
@SarveshMishra Please feel free to ping me on this issue here, for any further help needed. I think you just need to complete the CHANGELOG entry, amend your commit and force-push to your branch.

**Comment by SarveshMishra** [comment]
> @SarveshMishra Please feel free to ping me on this issue here, for any further help needed. I think you just need to complete the CHANGELOG entry, amend your commit and force-push to your branch.

@marcdumais-work I created a new entry in the CHANGELOG.md file v1.22.0 as you suggested please look into it.

**Comment by JonasHelming** [comment]
> > @SarveshMishra Please feel free to ping me on this issue here, for any further help needed. I think you just need to complete the CHANGELOG entry, amend your commit and force-push to your branch.
> 
> @marcdumais-work I created a new entry in the CHANGELOG.md file v1.22.0 as you suggested please look into it.

Did you stage/commit the changelog.md? It does not show up in the PR

**Comment by SarveshMishra** [comment]
> > > @SarveshMishra Please feel free to ping me on this issue here, for any further help needed. I think you just need to complete the CHANGELOG entry, amend your commit and force-push to your branch.
> > 
> > 
> > @marcdumais-work I created a new entry in the CHANGELOG.md file v1.22.0 as you suggested please look into it.
> 
> Did you stage/commit the changelog.md? It does not show up in the PR

I amend the commit then forced push. Should I do another commit for this?

**Comment by SarveshMishra** [comment]
> > > > @SarveshMishra Please feel free to ping me on this issue here, for any further help needed. I think you just need to complete the CHANGELOG entry, amend your commit and force-push to your branch.
> > > 
> > > 
> > > @marcdumais-work I created a new entry in the CHANGELOG.md file v1.22.0 as you suggested please look into it.
> > 
> > 
> > Did you stage/commit the changelog.md? It does not show up in the PR
> 
> I amend the commit then forced push. Should I do another commit for this?

After changing done in changelog.md file now it is showing conflict in files. Do I have to edit something on my side?

**Comment by marcdumais-work** [comment]
> After changing done in changelog.md file now it is showing conflict in files. Do I have to edit something on my side?

Probably someone has modified `CHANGELOG.md` and merged, since your branched-off for your PR. 

You need to rebase your branch on the latest upstream master, and force-push again. e.g.: 
``` bash
$ git fetch origin
$ git rebase origin/master
```

**Review by JonasHelming — APPROVED** [review]

**Comment by marcdumais-work** [comment]
Thanks @SarveshMishra - looks good. 

@tsmaeder can you have another look?

**Review by vince-fugnitto — APPROVED** [review]
The changes look good to me :+1: Thank you for your first contribution!

**Comment by marcdumais-work** [comment]
We have a couple of approvals - let's merge this PR. Thanks @SarveshMishra for this first contribution to Eclipse Theia!

**Comment by SarveshMishra** [comment]
> We have a couple of approvals - let's merge this PR. Thanks @SarveshMishra for this first contribution to Eclipse Theia!

@marcdumais-work  @JonasHelming @tsmaeder @vince-fugnitto Thanks for helping me with this first contribution.
So do I have to delete this branch and then create a fresh new branch for any next issue.., right??

**Comment by marcdumais-work** [comment]
> Thanks for helping me with this first contribution

You're welcome - thanks for participating to the hackathon.

> So do I have to delete this branch and then create a fresh new branch for any next issue.

It's up-to you, but probably yes: the source branch is no longer needed (by us) after merge.

**Comment by SarveshMishra** [comment]
> > Thanks for helping me with this first contribution
> 
> You're welcome - thanks for participating to the hackathon.
> 
> > So do I have to delete this branch and then create a fresh new branch for any next issue.
> 
> It's up-to you, but probably yes: the source branch is no longer needed (by us) after merge.

Ok, now I will try to solve level 1 or 2 issues and try to create PR for them. Thanks

**Pull request merged**
