### PR TITLE
plugin-ext: cleanup

### PR DESCRIPTION
**Pull request by marechal-p**
#### What it does

While working on a different PR I noticed outdated things and went on to fix those.

See commit messages for more information.

#### How to test

Everything should work like before.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marechal-p** [comment]
@benoitf I was a bit confused as to what the `/plugin/:path(*)` endpoint is used for, do you know if it is used and if so by what?

**Comment by benoitf** [comment]
@marechal-p do you have tried theia frontend plug-ins as well .

**Comment by marechal-p** [comment]
@benoitf tried [this one](https://github.com/eclipse/che-theia-samples/tree/master/samples/hello-world-frontend-plugin) and it worked.

**Comment by marechal-p** [comment]
cc @tsmaeder is the `/plugin/...` endpoint really a left over? Couldn't find where it is used in Theia's sources.

**Comment by azatsarynnyy** [comment]
What I see from the git history, it has been introduced with the initial implementation of Plug-in system
https://github.com/eclipse-theia/theia/commit/64903a302ed28b3deabf5efd7d05aaa77f42e647#diff-0387516bdf4e48bc4fd1ed19d1db0ef827fd98bbff503e7416b0237d952a4892

I suppose it was replaced later with`/hostedPlugin` endpoint
https://github.com/eclipse-theia/theia/blob/4641a2984244d38c242884c6777a4ebfdc4f6705/packages/plugin-ext/src/hosted/node/plugin-reader.ts#L45
but the previous one (`/plugin`) wasn't removed.

Maybe I'm wrong...

**Comment by marechal-p** [comment]
@azatsarynnyy I came to the same conclusion too, thanks!

**Review by azatsarynnyy — APPROVED** [review]
I think it's safe to get rid of `/plugin/:path(*)` endpoint.

**Review by benoitf — APPROVED** [review]
I think it's OK as well to get rid of it, seems to be a leftover

I test it with a couple of plug-ins which is working fine

**Comment by marechal-p** [comment]
I fixed the conflicts, thanks!

**Pull request merged**
