### PR TITLE
Support progress indicators in trees

### PR DESCRIPTION
**Pull request by westbury**
Often tasks can be executing against a project that will temporarily disable actions against that project.  Also projects may take a while to clone and initialize before the project is ready.  Our UX team asked for a progress indicator to appear beside a project when it is in such a state.

This PR adds support for such indicators.

image

### CODE REVIEW

**Comment by westbury** [comment]
This has been tested within our Electron application.  To test it, here are some bits of code that may help.
(This is the test code I used to show the indicator by the 'docs' folder in the screenshot).

```
import { FileStatNode } from '@theia/filesystem/lib/browser';
import { Emitter } from '@theia/core/lib/common';
import { TreeNode, TreeProgress } from '@theia/core/lib/browser/tree';

@injectable()
export class TestTreeProgressContribution implements TreeProgress {

    protected readonly emitter = new Emitter<void>();
    readonly onDidChangeProgress = this.emitter.event;

    getProgressIndicator(node: TreeNode) {
        if (FileStatNode.is(node)) {
            if (node.fileStat.uri.endsWith('docs')) {
                return { title: 'my test' };
            }
        }
    }
}

```

**Comment by vince-fugnitto** [comment]
I'd rather we implement a progress similar to vscode, something like the following (the blue bar), unless you don't think it meets your specific needs:

<div align='center'>

progress


</div>

**Comment by westbury** [comment]
> I'd rather we implement a progress similar to vscode, something like the following (the blue bar), unless you don't think it meets your specific needs:

Yes, the blue bar is good in certain situations.  However our needs are to specifically to show which projects are not ready.  I would expect, for example, the 'git clone' progress to be hooked to this.  The intent is to indicate to users that actions may not be available against that particular tree item but that they will be when the process has completed.  This solves a UX issue that a unified progress at the top of the view does not.

**Comment by vince-fugnitto** [comment]
> > I'd rather we implement a progress similar to vscode, something like the following (the blue bar), unless you don't think it meets your specific needs:
> 
> Yes, the blue bar is good in certain situations. However our needs are to specifically to show which projects are not ready. I would expect, for example, the 'git clone' progress to be hooked to this. The intent is to indicate to users that actions may not be available against that particular tree item but that they will be when the process has completed. This solves a UX issue that a unified progress at the top of the view does not.

I understand :) I was just wondering what might be a better way to display an unavailable action on a tree item, and thought perhaps showing a `disabled` state with a unique tooltip or a decorator would be sufficient?

**Comment by westbury** [comment]
> thought perhaps showing a `disabled` state with a unique tooltip or a decorator would be sufficient?

The tooltips are helpful but we need a moving progress indicator as otherwise users do not realize that the project initialization task is still in progress.  Moving progress indicators mixed up with the decorators would look odd.

**Comment by vince-fugnitto** [comment]
> > thought perhaps showing a `disabled` state with a unique tooltip or a decorator would be sufficient?
> 
> The tooltips are helpful but we need a moving progress indicator as otherwise users do not realize that the project initialization task is still in progress. Moving progress indicators mixed up with the decorators would look odd.

I wouldn't show the spinning icon as a decorator, maybe simply displaying a `disabled` state for the tree would be sufficient. However, I'll let others decide as well if they agree with the design, I'm not holding it back :) it's up to a developer to use the functionality when applicable of course :)

**Comment by vince-fugnitto** [comment]
@westbury by the way, I'm sure you've already noticed but the Eclipse ECA check if failing on the PR.

**Comment by westbury** [comment]
> @westbury by the way, I'm sure you've already noticed but the Eclipse ECA check if failing on the PR.

Thanks for pointing that out.  The wrong e-mail got into the commit.  It's now fixed.

**Comment by akosyakov** [comment]
@westbury i think it is a good idea, could you rebase this PR, i hope we can review it next week

**Comment by akosyakov** [comment]
Could it be generalized to show loading indicator only when a node is refreshing after some delay?

**Comment by akosyakov** [comment]
I also wonder whether we can based it on tree decorations and progress service, i.e. there can be `ProgressTreeDecorator` which listens to `ProgressService` notifications and update loading decorations.

**Comment by AlexTugarev** [comment]
@akosyakov @westbury I missed this issues :-( 

using the `ProgressService` to report progress next to a tree node identifiable by some sort of key (maybe `URI`) would be a nice solution, indeed. currently we use just a plain string as a location id, e.g. `scm`, or `search`, but we could extend to provide an additional position data optionally. a renderer client which feel responsible to render for a location id should do the job then.

**Comment by akosyakov** [comment]
@AlexTugarev I was thinking just to add a new property `loading` to `CompositeTreeNode` which gets set after some timeout like 800ms (to align with VS Code timing). It happens in `Tree.refresh` for all trees and it get unset after refresh is complete. Whenever the value of a flag an event will be fired which triggers rerendering as usual. Do you think it is worth in this case to hook in ProgressService for DOM nodes rendered by react? I'm not sure.

**Comment by akosyakov** [comment]
> Often tasks can be executing against a project that will temporarily disable actions against that project. Also projects may take a while to clone and initialize before the project is ready. Our UX team asked for a progress indicator to appear beside a project when it is in such a state.

@westbury Have you tried to use the notification manager? It is the proper to display a task progress, i.e. it worked well for the file upload. Combination of the blueish bar in the navigator plus explanatory notification message probably would be enough for the user.

https://github.com/eclipse-theia/theia/issues/3450 is just about handling long node refresh, I would like to tackle this issue without introducing new tree API services, especially when we have already existing like decorations which allow to style any node already. Although I could name a new tree node property not `loading`, but `busy` so one could use it to display loading indicator in other cases as well.

**Comment by akosyakov** [comment]
I'm closing it, i don't think we need more APIs.

Generally I think we should distinguish 2 level of progress reporting:
- on the shell-level use `ProgressService` to display that something is going in some area via the bluish bar in some view container (left/right area) or window (main area/status bar) + provide detail information via the notification center.
- on the widget-level use means of a widget to busy state for some element, e.g. loading indicator in the tree node with (TreeModel.markAsBusy) or loading indicator in the reference peek editor widget while it is resolving references.

This 2 levels should work together, so one do something like:
```ts
const tokenSource = new CancellationTokenSource();
// mark some not busy after some timeout on widget-level
treeModel.maskAsBusy(node, 800, tokenSource.token);
try {
   // report progress on the shell level
   return await this.progressService.withProgress('some message', 'someVIewContainer', async () => {
      // actual work
   }
} finally {
    tokenSource.cancel();
}
```

It could be combined different, i.e if one wants to show shell progress after some timeout or report to the notification center.

**Pull request closed without merging**
