### PR TITLE
fix unneeded URI conversion

### PR DESCRIPTION
**Pull request by Alexander-Taran**
#### What it does
refactoring of decorations-service
removes unneeded URI -> string ->URI conversion
https://github.com/eclipse-theia/theia/issues/13348

#### How to test
Everything should work as before.

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by Alexander-Taran** [comment]
Seriously.. I went and tried to sign bloody eca.. Whole process is a downer..  And half an hour later it is still not "signed"
not gona try again.

**Comment by JonasHelming** [comment]
@Alexander-Taran Hi, could you describe the issue you faced? Usually that should work within a minute so it would be interesting to learn what went wrong for you.

**Comment by Alexander-Taran** [comment]
@JonasHelming 
1. Need to create account with eclipse..
2. Flash my email..
3. Consider password leaking
4. Captchas
5. extra required fields
6. can't log in straight after creating. no message that i have to confirm my email.
7. after all that done my commit still can't be verified.. yet it is verified by github. I authored it in github.
8. most probably I have to check it out locally and alter the commit message file for signing or something.. ( but my effort budget was 0 at this moment)

and that is all too much for a find and replace commit.. that's a very strong barrier of entry.

**Comment by msujew** [comment]
> I authored it in github.

Ah, that's probably the issue. The commit was created with an `@users.noreply.github.com` email address. You need to sign the ECA with the same email that was used to create the commit.

**Comment by Alexander-Taran** [comment]
> You need

I don't actually

**Comment by JonasHelming** [comment]
I can understand that setting up a account for contributing a very simple change seems like overhead and it actually is. Even if it has to done only once, of course, it is a entry barrier.
However, this process allows us to be part of the IP process that the Eclipse Foundation provides to us. In a nutshell, this ensures that people who contribute have agreed to the ECA, which ensures that the code in the repository complies with the respective license.
This is an important criterium for many companies adopting Theia in a commercial setting, which is important for a platform such as Theia. For this reason, Theia decided to become an Eclipse Project many years ago.
Could the ECA process be simplified and improved? Yes, but this is unfortunately not under our control. We have to consider that we as an open source project consume these services for free, too.
Therefore, if you feel like, I suggest you report your ECA experience directly to the Eclipse Foundation, you can use your new Eclipse Account :-) https://gitlab.eclipse.org/eclipsefdn/helpdesk
I am sorry that your first contribution experience was frustrating due to infrastructural barriers. I hope you can get over this, once you have set up the ECA, it will never affect you again. We would love to welcome you as a new contributor!

Best regards,
Jonas

**Review by msujew — APPROVED** [review]
Alright looks good to me 👍 Everything still works as expected.

**Comment by Alexander-Taran** [comment]
Yay!!

**Pull request merged**
