### PR TITLE
Use C/C++ grammar files from VSCode

### PR DESCRIPTION
**Pull request by alexl0gan**
#### What it does
Update textmate-grammars package to use vscode grammar files as defined here:
https://github.com/jeff-hykin/cpp-textmate-grammar
https://github.com/microsoft/vscode/tree/master/extensions/cpp/syntaxes

#### How to test
Open a C/C++ file and enjoy a richer syntax colourisation.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Alex Logan <Alex.Logan@arm.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@alexl0gan the extension `@theia/texmate-grammars` will be deprecated soon https://github.com/eclipse-theia/theia/pull/6933 in favor of using the builtin extensions. Perhaps the grammars would be more appropriate if added to [theia-cpp-extensions](https://github.com/eclipse-theia/theia-cpp-extensions).

**Comment by vince-fugnitto** [comment]
Also, you referenced that your changes are based on https://github.com/jeff-hykin/cpp-textmate-grammar, would it not be simpler just to use it as a plugin?

**Comment by alexl0gan** [comment]
@vince-fugnitto I thought the grammar files were moved out of that repo?

I guess when the move is made to builtin extensions then theia will start using these files anyway

**Comment by vince-fugnitto** [comment]
> I guess when the move is made to builtin extensions then theia will start using these files anyway

We have already moved towards using the builtin extensions in the examples (#6883), and any other extension such as https://github.com/jeff-hykin/cpp-textmate-grammar can now simply be used as a plugin. In the end, there will be less need for maintenance and to copy files in our sources.

**Comment by vince-fugnitto** [comment]
I believe this pull-request can be closed based on our discussions.

**Pull request closed without merging**
