### PR TITLE
Fix file tree alignment issue

### PR DESCRIPTION
**Pull request by shuyaqian**
Signed-off-by: shuyaqian 717749594@qq.com

#### What it does

fix file tree alignment issue

#### How to test

Before：
Files in the root directories, such as `.gitignore`, are aligned with the `src` subfolders when the `src` folder is expanded.
image
image

After Fix：
image
image

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by colin-grant-work — CHANGES_REQUESTED** [review]
The problem isn't limited to files at the root of a workspace (for which `props.depth === 0`). For example, with this code, files that are children of a subfolder of the workspace continue to show the same alignment relative to sibling folders that you describe as the problem in the PR description:

image

The solution should address all levels of embedding.

**Comment by shuyaqian** [comment]
> 

image

**Review by colin-grant-work — COMMENTED** [review]
The update is an improvement, but it looks like the changes are negatively affecting trees other than the navigator. For example, the Search-in-Workspace widget:
<table>
<thead><tr><td>Master</td><td>This PR</td></tr></thead>
<tbody><tr><td></img></td><td></img></td></tr></tbody>
</table>

**Comment by vince-fugnitto** [comment]
Closing due to inactivity. We can re-open the pull-request when https://github.com/eclipse-theia/theia/pull/10566#pullrequestreview-838624189 is addressed.

**Pull request closed without merging**
