### PR TITLE
nls: add additional localizations

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

In additon to https://github.com/eclipse-theia/theia/pull/11367, I noticed a couple of other instances where we do no localize.
The pull-request updates both the `open` and `save` dialog to localize all user facing strings, including tooltips.

#### How to test

1. confirm that the strings updated in the pull-request are not actually localized when changing display language on master
2. the strings should be properly localized when we perform https://github.com/eclipse-theia/theia/issues/10885.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by msujew — APPROVED** [review]
Thanks, LGTM 👍

**Comment by vince-fugnitto** [comment]
Sorry @msujew, I noticed that the `keyboard shortcuts` widget was completely not localized so I added a commit for it, should I open a separate pull-request instead? I might do a pass to see if we have other areas that are no localized.

**Comment by msujew** [comment]
@vince-fugnitto I'm fine with having multiple non-localized areas fixed in a single PR.

**Comment by vince-fugnitto** [comment]
I went ahead and update other occurrences of missing localisations I could identify :+1:

**Comment by msujew** [comment]
@vince-fugnitto Thanks 👍 Do you plan on merging this today? I could include it in the localization update.

**Pull request merged**
