### PR TITLE
Remove unncessary use of RPCProtocol. Fixes #11970

### LINKED ISSUE #11970: Terminal Connections use Unnecessary RPC Protocol
### Bug Description:
The input/output streams of terminals use an rpc protocol to connect the typing input and the output of the shell in the back end. This is unnecessary, since we can just use a `Channel` instead.

### PR DESCRIPTION
**Pull request by tsmaeder**
Signed-off-by: Thomas Mäder <t.s.maeder@gmail.com>

#### What it does
Fixes #11970
Removes the unnecessary use of a `RPCProtocol` instance to communicate with shell processes in terminals. 

Contributed on behalf of ST Microelectronics

#### How to test
Open terminals and make sure they work as usual. Tested on Windows 11. It might be interesting to test this on OSX and Linux. I've made sure performance is not significantly affected for large, fast output. For example, you can output the contents of large files in the terminal.

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by paul-marechal — COMMENTED** [review]
LGTM otherwise.

**Review by paul-marechal — APPROVED** [review]
The code makes sense to me, and terminals on Windows still work.

**Review by paul-marechal — APPROVED** [review]

**Comment by vince-fugnitto** [comment]
I believe this change may be resulting in our CI failing:

_PR_:

image

_Master_:

image


All subsequent builds are now failing due to a `task` test:

```
@theia/task:   1 failing
@theia/task:   1) Task server / back-end
@theia/task:        task running in terminal - expected data is received from the terminal ws server:
@theia/task:      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/theia/theia/packages/task/lib/node/task-server.slow-spec.js)
@theia/task:       at listOnTimeout (node:internal/timers:559:17)
@theia/task:       at processTimers (node:internal/timers:502:7)
```

**Comment by vince-fugnitto** [comment]
@tsmaeder do you have time to investigate a fix for the test, else we may need to revert the changes for the time being.

**Comment by paul-marechal** [comment]
CI failure fixed by #12054.

**Pull request merged**
