### PR TITLE
terminal: bump `xterm` and addons

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

The pull-request bumps `xterm` and related addons to their latest versions to benefit from additional improvements and bug fixes.

#### How to test

1. start the example application(s)
2. spawn a terminal - confirm it works as expected
3. confirm that resizing and searching within the terminal works as expected
4. confirm that `split terminal` works as expected
5. confirm that updating terminal related preferences takes effect

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
The change works well on Chromium based browsers, but breaks on FireFox, since we do a bit of monkey-patching:

https://github.com/eclipse-theia/theia/blob/abc45782eb7f9b132a2680eec3df540e40fac74a/packages/terminal/src/browser/terminal-widget-impl.ts#L644-L661

`_onIntersectionChange` doesn't seem to be a method in the `renderService` anymore.

**Comment by msujew** [comment]
I was able to get it to work again by replacing the existing code with this:

```ts
const renderService: any = (this.term as any)._core._renderService;
const originalFunc: (entry: IntersectionObserverEntry) => void = renderService._handleIntersectionChange.bind(renderService);
const replacement = function (entry: IntersectionObserverEntry): void {
    if (entry.target.ownerDocument !== document) {
        // in Firefox, the intersection observer always reports the widget as non-intersecting if the dom element
        // is in a different document from when the IntersectionObserver started observing. Since we know
        // that the widget is always "visible" when in a secondary window, so we refresh the rows ourselves
        renderService._pausedResizeTask.flush();
        renderService.refreshRows(0, renderService._rowCount - 1);
    } else {
        originalFunc(entry);
    }
};

renderService._handleIntersectionChange = replacement;
```

**Comment by vince-fugnitto** [comment]
> I was able to get it to work again by replacing the existing code with this:

@msujew good catch and thank you for the suggestion! I'll add you as a co-author whenever we merge :)

**Comment by msujew** [comment]
> Was there a reason you changed more than just the method name?

Yep, just using the correct method fixed the error in the console, but terminals still experienced a render issue. Any terminal didn't re-render anymore after popping it out to a secondary window.

**Comment by tsmaeder** [comment]
I think this is worth investigating: if you look at the code in RendererService.ts, I think the only time the `_isPaused` flag is set is in the  `_handleIntersectionChange` method, which means `_needsFullRefresh` is never reset to `false`. We're effectively turning off incremental paints, just at a glance. That doesn't sound like the right thing to do.

**Review by tsmaeder — DISMISSED** [review]
Putting a block on this one so nobody accidentally merges it: I believe we have a performance problem with incremental updates after the library update.

**Comment by tsmaeder** [comment]
@msujew can you remember what the exact rendering issue was on firefox? For me, there are rendering issues when I resize the external window, but they are the same on chrome and on firefox. 
@vince-fugnitto mind if I take over this one?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto mind if I take over this one?

Sure, go ahead!

**Comment by tsmaeder** [comment]
@msujew I fixed the tests. Could you give this one another review?

**Review by msujew — APPROVED** [review]
Yep, perfect. Works good now. No sluggishness on Firefox anymore.

**Pull request merged**
