### PR TITLE
vscode: add support for `onDidChangeFoldingRanges`

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Closes: https://github.com/eclipse-theia/theia/issues/11127.
Closes: https://github.com/eclipse-theia/theia/pull/11320.

The pull-request adds support for the `FoldingRangeProvider. onDidChangeFoldingRanges` VS Code API.

#### How to test

1. include the following test plugin ([folding-range-provider-0.0.2.vsix](https://github.com/eclipse-theia/theia/files/9633400/folding-range-provider-0.0.2.vsix.zip))
2. start the application
3. create a file `folding.test` and add multiple lines
4. confirm that no folding ranges are present:
Screen Shot 2022-09-23 at 8 06 26 AM
5. execute the command `Custom Folding Range: Update` - the command triggers the `onDidChangeFoldingRanges` event from the provider signalling that `provideFoldingRanges` should be re-calculated (each call should create a new range)
6. confirm that folding ranges are present:
Screen Shot 2022-09-23 at 8 08 00 AM

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Review by msujew — APPROVED** [review]
LGTM 👍 

- [x] The file doesn't contain any foldings after starting the application
- [x] Executing the command updates the foldings as expected

Note that I only get one folding after `a`, not 3 like in your example. @vince-fugnitto Is that expected?

image

**Comment by vince-fugnitto** [comment]
> Note that I only get one folding after `a`, not 3 like in your example. @vince-fugnitto Is that expected?

@msujew yea, running the `Custom Folding Range: Update` command will continue to create folding ranges.

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    const disposables: vscode.Disposable[] = [];
    const provider = new CustomFoldingRangeProvider();
    vscode.languages.registerFoldingRangeProvider({ scheme: 'file' }, provider);
    disposables.push(
        vscode.commands.registerCommand('custom-folding-range:update', () => {
            provider.refresh();
        })
    );
    context.subscriptions.push(...disposables);
}

export function deactivate() { }

class CustomFoldingRangeProvider implements vscode.FoldingRangeProvider {

    protected count = 1;

    private onDidChangeFoldingRangesEvent = new vscode.EventEmitter<void>();
    public onDidChangeFoldingRanges?: vscode.Event<void>;

    constructor() {
        this.onDidChangeFoldingRanges = this.onDidChangeFoldingRangesEvent.event;
    }

    provideFoldingRanges(document: vscode.TextDocument, context: vscode.FoldingContext, token: vscode.CancellationToken): vscode.ProviderResult<vscode.FoldingRange[]> {
        const ranges: vscode.FoldingRange[] = [];
        if (this.count > document.lineCount) {
            return;
        }
        for (let i = 0; i < this.count; i++) {
            ranges.push(new vscode.FoldingRange(i - 1, i));
        }
        return ranges;
    }

    public refresh(): void {
        this.count++;
        this.onDidChangeFoldingRangesEvent.fire();
    }

}

```

**Comment by msujew** [comment]
@vince-fugnitto Ah, thanks for the info. Yep, then everything works as expected 👍

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Ah, thanks for the info. Yep, then everything works as expected 👍

@msujew the results are different than what happens in vscode however, but that's unrelated to these changes, in vscode I see the folding range for every second line.

**Comment by msujew** [comment]
@vince-fugnitto I can confirm that, but I believe that's due to vscode not allowing to display a folding start at a line where another folding ends. The foldings are still correctly created, just not displayed. I guess that makes sense, but it is indeed unrelated to your changes.

**Pull request merged**
