### PR TITLE
[keybinding] add api for unregistering keybindings by Command

### LINKED ISSUE #8209: [keybinding] As an extension developer I want to unregister keybindings by the command
Currently, one can unregister a keybinding with a keybindings object or a keybinding string:

https://github.com/eclipse-theia/theia/blob/4c63f08a6283f19f6f28727727378f7c1e38e316/packages/core/src/browser/keybinding.ts#L197-L198

The current approach is inconvenient:
 - as the keybindings strings are case sensitive and the order of the keys do matter (#8170), and
 - a command can have multiple keybindings (#8202).

A `unregisterKeybinding(command: Command): void;` API would be neat, and the deletion should be based on `command` instead of `keybinding`.

### PR DESCRIPTION
**Pull request by minyoungyang**
Fixes #8209 

#### What it does

* Add API that can unregister keybindings by Command

#### How to test

* Unregister keybinding for opening preference widget

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Min-young Yang <didalsdud@gmail.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
@akosyakov, this PR was based on https://github.com/eclipse-theia/theia/issues/8209#issuecomment-661686777 if I am not mistaken. It wouldn't be fair approving my own snippet.

**Comment by akosyakov** [comment]
ok, adding some unit tests will be good then :D

**Comment by JonasHelming** [comment]
I missed this PR and created another one doing essentially the same, but with unit tests:
https://github.com/eclipse-theia/theia/pull/8269
@minyoungyang : Feel free to integrate my unit tests or an adapted version into yours if you want. Alternativly, we can also use the other PR, where the are already integrated, I do not mind...

**Comment by minyoungyang** [comment]
@JonasHelming It's OK. It would be better to precess it with your PR. I will close this PR.

**Pull request closed without merging**
