### PR TITLE
Update Built-in Extensions Version

### LINKED ISSUE #9014: Build fails when downloading built-ins
### Bug Description:
A build of master fails on the step where the built-ins are downloaded with these messages:

<details>

```
x vscode-builtin-configuration-editing: failed to download with: 404 Not Found
x vscode-builtin-emmet: failed to download with: 404 Not Found
x vscode-builtin-csharp: failed to download with: 404 Not Found
x vscode-builtin-go: failed to download with: 404 Not Found
x vscode-builtin-cpp: failed to download with: 404 Not Found
x vscode-builtin-handlebars: failed to download with: 404 Not Found
x vscode-builtin-grunt: failed to download with: 404 Not Found
x vscode-builtin-bat: failed to download with: 404 Not Found
x vscode-builtin-scss: failed to download with: 404 Not Found
x vscode-builtin-fsharp: failed to download with: 404 Not Found
x vscode-builtin-coffeescript: failed to download with: 404 Not Found
x vscode-builtin-pug: failed to download with: 404 Not Found
x vscode-builtin-objective-c: failed to download with: 404 Not Found
x vscode-builtin-debug-auto-launch: failed to download with: 404 Not Found
x vscode-builtin-clojure: failed to download with: 404 Not Found
x vscode-builtin-sql: failed to download with: 404 Not Found
x vscode-builtin-python: failed to download with: 404 Not Found
x vscode-builtin-shellscript: failed to download with: 404 Not Found
x vscode-builtin-ruby: failed to download with: 404 Not Found
x vscode-builtin-rust: failed to download with: 404 Not Found
x vscode-builtin-shaderlab: failed to download with: 404 Not Found
x vscode-builtin-theme-defaults: failed to download with: 404 Not Found
x vscode-builtin-theme-monokai-dimmed: failed to download with: 404 Not Found
x vscode-builtin-theme-abyss: failed to download with: 404 Not Found
x vscode-builtin-theme-tomorrow-night-blue: failed to download with: 404 Not Found
x vscode-builtin-typescript-language-features: failed to download with: 404 Not Found
x vscode-builtin-npm: failed to download with: 404 Not Found
x vscode-builtin-css: failed to download with: 404 Not Found
x vscode-builtin-theme-monokai: failed to download with: 404 Not Found
x vscode-builtin-theme-kimbie-dark: failed to download with: 404 Not Found
x vscode-builtin-theme-solarized-dark: failed to download with: 404 Not Found
x vscode-builtin-yaml: failed to download with: 404 Not Found
x vscode-builtin-theme-red: failed to download with: 404 Not Found
x vscode-builtin-typescript: failed to download with: 404 Not Found
x vscode-builtin-theme-quietlight: failed to download with: 404 Not Found
x vscode-builtin-vb: failed to download with: 404 Not Found
x vscode-builtin-xml: failed to download with: 404 Not Found
x vscode-builtin-icon-theme-seti: failed to download with: 404 Not Found
x vscode-builtin-swift: failed to download with: 404 Not Found
x vscode-builtin-docker: failed to download with: 404 Not Found
x vscode-builtin-lua: failed to download with: 404 Not Found
x vscode-builtin-r: failed to download with: 404 Not Found
x vscode-builtin-ini: failed to download with: 404 Not Found
x vscode-builtin-javascript: failed to download with: 404 Not Found
x vscode-builtin-less: failed to download with: 404 Not Found
x vscode-builtin-java: failed to download with: 404 Not Found
x vscode-builtin-make: failed to download with: 404 Not Found
x vscode-builtin-markdown: failed to download with: 404 Not Found
x vscode-builtin-merge-conflict: failed to download with: 404 Not Found
x vscode-builtin-powershell: failed to download with: 404 Not Found
x vscode-builtin-groovy: failed to download with: 404 Not Found
x vscode-builtin-hlsl: failed to download with: 404 Not Found
x vscode-builtin-log: failed to download with: 404 Not Found
x vscode-builtin-perl: failed to download with: 404 Not Found
x vscode-builtin-markdown-language-features: failed to download with: 404 Not Found
x vscode-builtin-jake: failed to download with: 404 Not Found
x vscode-builtin-gulp: failed to download with: 404 Not Found
x vscode-builtin-razor: failed to download with: 404 Not Found
```

</details>

I suspect some extension versions have been purged from open-vsx

### Steps to Reproduce:

1. git clone https://github.com/eclipse-theia/theia
2. cd theia
3. yarn
4. Observe: error at the last build step

### Additional Information
Using the browser to download a missing built-in extension (`https://open-vsx.org/api/vscode/java/1.44.2/file/vscode.java-1.44.2.vsix`) shows that the extension is indeed missing. 

- Operating System: Windows
- Theia Version: master

### PR DESCRIPTION
**Pull request by seantan22**
#### What it does

Fixes #9014

- Update necessary built-ins to version 1.45.1

#### How to test

1. `git clone https://github.com/eclipse-theia/theia`
2. `cd theia`
3. `yarn`
Confirm that all built-ins are successfully downloaded.

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: seantan22 <sean.a.tan@ericsson.com>

### CODE REVIEW

**Review by marcdumais-work — COMMENTED** [review]
LGTM. Let me quickly try it on Gitpod before approving.

**Review by marcdumais-work — APPROVED** [review]
I confirmed MarkDown rendering works. Thanks @seantan22!

**Comment by marcdumais-work** [comment]
CI is green - merging.

**Comment by vince-fugnitto** [comment]
The `markdown-language-features` extension displays the following error related to `custom-editor-apis`:

Screen Shot 2021-02-02 at 9 20 17 AM

**Pull request merged**
