### PR TITLE
Updated CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Destrae**
updated to covenant 1.4

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@Destrae thank you for your first contribution! 👍 

In order to accept the pull request, the commit must contain a [signed-off](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#sign-your-work) and the [Eclipse ECA](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) must be signed. In general you can take a look at our contributing guidelines.

**Comment by svenefftinge** [comment]
Maybe we should use the version adapted by Eclipse Foundation https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php

**Comment by tsmaeder** [comment]
> Maybe we should use the version adapted by Eclipse Foundation https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php

I agree: that one more closely mirrors our actual organization.

**Comment by vince-fugnitto** [comment]
> Maybe we should use the version adapted by Eclipse Foundation https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php

Since there hasn't been a response for a while, I've created the following issue https://github.com/eclipse-theia/theia/issues/6691 if any others would like to contribute the updated code of conduct covenant.

**Comment by vince-fugnitto** [comment]
Closing due to inactivity by the original author.
I've created the issue #6691 in order to track the update and see if a new contributor would like to take care of handling it.

**Pull request closed without merging**
