### PR TITLE
monaco: uplift to `1.72.3`

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

The pull-request uplifts **monaco** to `1.72.2` (latest vscode tag).

image

image

#### How to test

_Checklist_:

- [x] confirm that `syntax highlighting` works for multiple languages
- [x] confirm that the outline-view is properly populated
- [x] confirm that problem markers work properly 
- [x] confirm that language-features work properly (`go to definition`, `call hierarchy`, `peek >`, `refactor`)
- [x] confirm that `quick fixes` work
- [x] confirm that the `quick input` and `quick open` menu works
- [x] confirm that editor styling works
- [x] confirm that the new preferences work (ex: `editor.stickyScroll.enabled`)    
- [x] confirm other editor or monaco related features work 

#### Additional Information

- [x] ~[CQ for `@theia/monaco-editor-core@1.72.2`](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/4117)~
- [x] [CQ for `@theia/monaco-editor-core@1.72.3`](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/4560)

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by planger** [comment]
@vince-fugnitto I saw that this PR breaks the playwright tests. Please feel free to ping me anytime if we can help out adapting the page object library to make the tests work again.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I saw that this PR breaks the playwright tests. Please feel free to ping me anytime if we can help out adapting the page object library to make the tests work again.

@planger thanks! You can take a look at them if you'd like, I was having a hard time actually debugging playwright.

**Comment by planger** [comment]
@vince-fugnitto Thanks, we'll take a look! As many of us are currently on EclipseCon, I'm not sure we'll get to it this week though. To avoid blocking your PR, feel free to disable the failing test temporarily, and we'll open a PR at latest next week to fix and re-enable it.

Thanks!

**Comment by planger** [comment]
@vince-fugnitto I've had a look at the failing test. It seems like Monaco now adds a "zero width non-joiner" character (`&zwnj;` or `\u200c`) to the HTML text content. So the most direct way to resolve this is to replace the method `replaceEditorSymbolsWithSpace(content: string)` in `examples/playwright/src/theia-text-editor.ts` with the one below:

```typescript
    protected replaceEditorSymbolsWithSpace(content: string): string | Promise<string | undefined> {
        // [ ] &nbsp; => \u00a0 -- NO-BREAK SPACE
        // [·] &middot; => \u00b7 -- MIDDLE DOT
        // [] &zwnj; => \u200c -- ZERO WIDTH NON-JOINER
        return content.replace(/[\u00a0\u00b7]/g, ' ').replace(/[\u200c]/g, '');
    }
```

**Review by msujew — APPROVED** [review]
The changes look good to me. I've tried testing the monaco features and the added preferences in particular. Everything seems to work as expected 👍 

I would propose to merge this PR rather sooner than later to catch potential issues before the next release.

**Comment by vince-fugnitto** [comment]
> I would propose to merge this PR rather sooner than later to catch potential issues before the next release.

Thank you for the review!

I performed an official release of `@theia/monaco-editor-core@1.72.3` and filed a [CQ](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/4560) for it with the modifications to license and third-party-notices the foundation asked for.

**Comment by vince-fugnitto** [comment]
The latest CQ has been approved :+1:

**Comment by vince-fugnitto** [comment]
As mentioned in the dev meeting, I'll merge the pull-request tomorrow and we have the rest of the month to identify any potential regressions.

**Comment by vince-fugnitto** [comment]
@planger I'm experiencing errors in playwright following a rebase, would you mind helping out again to investigate them?

**Comment by vince-fugnitto** [comment]
The test seems to fail due to [`quickInputList.ts#getAriaLabel`](https://github.com/microsoft/vscode/blob/78f6c8cdd31e1b90a99c2c2034041a0cea0e2767/src/vs/base/parts/quickinput/browser/quickInputList.ts#L859-L863), where the `recently used` seperator is added to the `aria-label`.

**Pull request merged**
