### PR TITLE
blur cell on shift+enter, only update cell height when changed

### PR DESCRIPTION
**Pull request by jonah-iden**
#### What it does

Small fix for notebook shift+enter keybinding. When having an editor focused it should blur the previously selected, if a new cell is created that should be focused, but if switching to an existing cell there should be no editor focus.
Also small fix so that the height changed event only fired if the height acutally changed

#### How to test

Open a notebook.
Edit a cell and use shift+enter to execute it and focus the next one or create a next one.
The next cell should be selected and have text focus

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by dhuebner — CHANGES_REQUESTED** [review]
Works good except in case of the last cell. A new cell is created, but didn't grab the editor focus.

**Comment by dhuebner** [comment]
@jonah-iden 
Could you please also check the behavior of `ALT+Enter` ?

Btw. the markdown cell works a bit different in both cases Shift+Enter  and Alt+Enter.

**Comment by jonah-iden** [comment]
sure thanks for testing

**Comment by jonah-iden** [comment]
ups i just realized i remembered vscode behaviour wrong... 
I'll rework it so its aligned

**Review by dhuebner — APPROVED** [review]
Works as expected, thanks!

**Pull request merged**
