### PR TITLE
Upgrade the Theia build to use Typescript 5.4.5

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
Upgrades the Theia build to use Typescript 5.4.5

Fixes https://github.com/eclipse-theia/theia/issues/13627

Most updates are just typing to accommodate stricter checks in 5.4.5.

Contributed on behalf of STMicroelectronics

#### How to test
Run Theia and observe the logs for any uncommon events. The one "real" change is in the nls extractor, I tested that it still generates a reasonable file using this incantation:
```
theia nls-extract -o ./packages/core/i18n/nls.json -e vscode -f ./packages/**/browser/**/*.{ts,tsx}
```

@msujew can you chime in if that is sufficient testing for that script or if not, how to test?

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by JonasHelming** [comment]
Does this fix https://github.com/eclipse-theia/theia/issues/13627?

**Review by msujew — COMMENTED** [review]
For some reason, this breaks the `nls-extract` call for me. I have managed to fix this by exposing the full path to the TypeScript API [here](https://github.com/eclipse-theia/theia/blob/746f8ff1aeb0922dcb601dec7c9ca52ce0138118/dev-packages/localization-manager/src/localization-extractor.ts#L85C9-L85C88):

```diff
-const fileLocalization = await extractFromFile(file, content, errors, options);
+const fileLocalization = await extractFromFile(filePath, content, errors, options);
```

**Comment by tsmaeder** [comment]
Probably best to merge this after the release.

**Comment by msujew** [comment]
@tsmaeder Do you mind applying my recommendation? Afterwards, this PR should be good to go.

**Review by rschnekenbu — COMMENTED** [review]
From what I could test (building and running electron & browser example, that PR is good for me. I did not test the part already covered by Mark.

**Comment by tsmaeder** [comment]
@msujew finally getting back to this. For me, doing `npx theia nls-extract -o foo.txt` at the base of the theia repo works just fine. What are you doing differently?

**Comment by msujew** [comment]
@tsmaeder On Ubuntu, the `yarn theia nls-extract -o ./packages/core/i18n/nls.json -e vscode -f ./packages/**/browser/**/*.{ts,tsx}` command in Theia's root yields me `{}`. With my change in place, it works as expected.

**Comment by tsmaeder** [comment]
@msujew unfortunately, your change seems to break the extraction on Windows.

**Comment by tsmaeder** [comment]
It works for me, though if I replace the command line with 
```
npx theia nls-extract -o ./foo.txt -e vscode -f packages/**/browser/**/*.{ts,tsx}
```

Note the missing leading `./` on the glob pattern.

**Comment by msujew** [comment]
@tsmaeder In that case the [automated translation](https://github.com/tsmaeder/theia/blob/eb8e4ecbabf54e15ee76c861d199aa782d4931fe/scripts/translation-update.js#L20-L25) process will break. Given the intransparency of the change (having to remove `./` from a CLI call is pretty weird to make it work), I would like to have my change in there, as it makes the CLI behave as expected.

**Comment by tsmaeder** [comment]
@msujew  I think I've found a fix.

**Comment by msujew** [comment]
It's now working correctly on Ubuntu, but using a leading `./` breaks on Windows and it again yields `{}`. Wouldn't it just make sense to strip the leading `./`, since that seems to work on both Ubuntu and Windows?

**Comment by tsmaeder** [comment]
@msujew `theia nls-extract -o foo.txt -e vscode -f ./packages/**/browser/**/*.{ts,tsx}` works fine for me on Windows. What's your command line?

**Comment by msujew** [comment]
@tsmaeder I'm using `yarn theia nls-extract -o foo.txt -e vscode -f "./packages/**/browser/**/*.{ts,tsx}"`:

image

**Comment by tsmaeder** [comment]
This exact command line (copy/paste) works for me. I even switched to PowerShell.

**Review by msujew — APPROVED** [review]
Interesting. It works on Ubuntu so I'm alright with it. We can change the nls-localize stuff once someone complains :D

**Pull request merged**
