### PR TITLE
align max listeners check with VS Code extensions' expectations

### LINKED ISSUE #6659: Error: Possible Emitter memory leak detected
### Description
Not sure if that is the right place or too plugin specific, but I'll drop it here anyway.
Let me know if you need more information and I'll try to provide them.

**OS and Theia version:**
Chrome OS 79.0.3945.42
Che-Theia https://github.com/eclipse/che-theia/commit/4769b1a using Theia 84d8678

**Diagnostics:** 

```
Extension-Host:PLUGIN_HOST(3678) starting instance
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/init()
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/ports-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/theia-containers-plugin@0.0.2 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/theia-factory-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/theia-ssh-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/welcome-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(task-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@theia/yeoman-plugin@0.0.1-1562576566 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(git@1.0.0 with /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/main)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/theia_yeoman_plugin.theia/lib/theia-yeoman-plugin-backend-plugin.js)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/task_plugin.theia/lib/task-plugin-backend.js)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_welcome_plugin.theia/lib/welcome-plugin.js)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_theia_ssh_plugin.theia/lib/ssh-plugin-backend.js)
Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia/lib/factory-plugin.js)
Extension-Host:Error: Possible Emitter memory leak detected. 31 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:403:9)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 32 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at Object.onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at new AutoFetcher (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/autofetch.js:22:28)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:409:31)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 33 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new ProgressManager (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:310:9)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:422:33)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 34 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:403:9)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 35 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at Object.onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at new AutoFetcher (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/autofetch.js:22:28)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:409:31)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Error: Possible Emitter memory leak detected. 36 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new ProgressManager (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:310:9)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:422:33)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia/lib/containers-plugin.js)
Extension-Host:Error: Possible Emitter memory leak detected. 37 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:403:9)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 38 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at Object.onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at new AutoFetcher (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/autofetch.js:22:28)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:409:31)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 39 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new ProgressManager (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:310:9)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:422:33)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/ports-plugin.js)
Extension-Host:Error: Possible Emitter memory leak detected. 40 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:403:9)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 41 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at Object.onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at new AutoFetcher (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/autofetch.js:22:28)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:409:31)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 42 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new ProgressManager (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:310:9)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:422:33)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
```

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #6659

Since we support multi root workspaces and VS Code extensions we started seeing many false positive leaking emitters. This PR addresses it in similar approach as VS Code does:
- increase the max listeners threshold to 175 listeners
- only warn on first exceed and then every time the limit is exceeded by 50% again. So only real leaking emitter will be reported more than once.
- report the top stack trace

#### How to test

- For leaking configurations: install python, java and go VS Code extensions (use Extensions view) and open typescript, python, java and go files
- For leaking FS wathcing: add more than 6 workspace roots.
- Check that you don't have many repetitive warning in both cases.
- Check for leaking editors: https://github.com/eclipse-theia/theia/pull/7508#issuecomment-610303923

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
I have not time to test it myself yet, I will do later today if no one does it before.

**Comment by RomanNikitenko** [comment]
Using these changes I can not reproduce the use case described here https://github.com/eclipse-theia/theia/pull/7506#pullrequestreview-388340435

**Comment by akosyakov** [comment]
@RomanNikitenko about `onPreferencesChanged`, I want to remove custom threshold 64, but I have to understand whether it is false positive (which are expected sometimes) or it is a real leak (looking at stack trace it is not). I am struggling to reproduce. Do you know how many editors did you open to reproduce? Could you do it reliably? If so then how?

**Comment by akosyakov** [comment]
ok, I found a pretty serious memory leak: `DisposableCollection.onDispose` is never disposed, so clients like `editor.onDispose(() => { lalal })` actually keeping a reference to an editor, the same for other places where we delegate to `DisposableCollection.onDispose`.

There is a problem that `DisposableCollection` can be reused many times, so if we dispose `onDispose` then on next `dispose` there won't be an event. Looking at clients though I could not find a single expecting second event, so it seems to be alright. 

I'm going to dispose this event on first dispose. If we break some clients they should be fixed then. cc @svenefftinge @AlexTugarev

**Comment by akosyakov** [comment]
Monaco editors are also leaking somehow via our quick open controller:

Screenshot 2020-04-06 at 20 26 25

**Comment by RomanNikitenko** [comment]
@akosyakov 
> I am struggling to reproduce. Do you know how many editors did you open to reproduce? Could you do it reliably? If so then how?

Yes, I can reproduce it. I have about 10 open editors then go to `TaskService` -> `@inject(WidgetManager) `, use `Peek` -> `Peek References`, open 8 editors to get the error.
I refreshed a page to have a clean state before testing.

error_memory_leak

**Comment by RomanNikitenko** [comment]
@akosyakov 
btw: looks like I caught the error related to `serializeURI` at testing memory leak, you can see it on video of my previous comment.

uri_error

**Comment by akosyakov** [comment]
@RomanNikitenko i think you stumbled over https://github.com/eclipse-theia/theia/issues/6733

**Comment by akosyakov** [comment]
Leaking editors should be leaked by removing custom closure on editor dispose. They used to capture an editor instance.

One can verify by:
- opening multiple editors
- using quick open command and peek references 
- closing all editors
- triggering garbage collection
- taking the heap shanshot
- and checking that there is no many MonacoEditor instances anymore

**Comment by akosyakov** [comment]
@RomanNikitenko Could you check again please? I've fixed leaking editors.

**Comment by RomanNikitenko** [comment]
Also tested using the heap snapshots.
I had 24 `MonacoEditor` objects when editors were open.
and 2 objects after closing them.
One of them is `MonacoDiffEditor`, can not recognize another one
  
heap_snapshots

**Comment by akosyakov** [comment]
@RomaNikitenko sometimes widgets are hold temporarily by some contribution, for instance, the toolbar holds a reference to latest current widget. But it is not a real leak, since a reference gets removed when another widget becomes current.

**Comment by RomanNikitenko** [comment]
> for instance, the toolbar holds a reference to latest current widget.

agree, I had the same idea when faced with it

**Pull request merged**
