### PR TITLE
Fix API tests on windows and add missing await on ts test

### PR DESCRIPTION
**Pull request by amiramw**
Signed-off-by: Amiram Wingarten <amiram.wingarten@sap.com>

#### What it does
Fixes https://github.com/eclipse-theia/theia/issues/7644
Fixes API tests on windows and add missing await on typescript.spec.js.

#### How to test

Run `yarn test:browser` on windows and see that it completes successfuly.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by amiramw** [comment]
@akosyakov is this missing await related to https://github.com/eclipse-theia/theia/issues/7635 maybe?

**Comment by akosyakov** [comment]
@amiramw you are my hero! sure it fixes https://github.com/eclipse-theia/theia/issues/7635

**Comment by amiramw** [comment]
Now travis fail on typescript.spec.js:

       editor.action.peekDefinition
         within an editor:
[0m[31m     Error: Timeout of 45000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.[0m[90m

**Comment by akosyakov** [comment]
@amiramw I can reproduce it locally. It seems to be sometimes dispatching esc button happens too early and Monaco does not handle it. Looking into it. I will push a commit to this PR ok?

I will reduce timeout back to 30s, i've increased it because could not understand flakiness, but it was missing await.

**Comment by amiramw** [comment]
sure. thanks!

**Comment by akosyakov** [comment]
Pushed. There were a race in tests, that close happens before the peek widget was actually focused. Merging if the build is green.

**Pull request merged**
