### PR TITLE
download-plugins: display errors at the end of the script

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes https://github.com/eclipse-theia/theia/issues/7878

The following commit updates the `download:plugins` script to display errors (download failures) at the end of the script so application developers can easily see the failed downloads together.

#### How to test

1. update the root's `package.json` to include bogus download links
2. perform `yarn download:plugins`
3. the errors should be displayed at the end of the script:

<details>
<summary>Example</summary>

```
┌─[±][vf/gh-7878 U:1 ✗][theia][]
└─▪ yarn download:plugins
yarn run v1.22.4
$ theia download:plugins
--- downloading plugins ---
+ vscode-builtin-clojure: downloaded successfully 
+ vscode-builtin-csharp: downloaded successfully 
+ vscode-builtin-fsharp: downloaded successfully 
+ vscode-builtin-css: downloaded successfully 
+ vscode-builtin-debug-auto-launch: downloaded successfully 
+ vscode-builtin-bat: downloaded successfully 
+ vscode-builtin-configuration-editing: downloaded successfully 
+ vscode-builtin-grunt: downloaded successfully 
+ vscode-builtin-hlsl: downloaded successfully 
+ vscode-builtin-cpp: downloaded successfully 
+ vscode-builtin-coffeescript: downloaded successfully 
+ vscode-builtin-json: downloaded successfully 
+ vscode-builtin-docker: downloaded successfully 
+ vscode-builtin-handlebars: downloaded successfully 
+ vscode-builtin-perl: downloaded successfully 
+ vscode-builtin-rust: downloaded successfully 
+ vscode-builtin-r: downloaded successfully 
+ vscode-builtin-razor: downloaded successfully 
+ vscode-builtin-pug: downloaded successfully 
+ vscode-builtin-python: downloaded successfully 
+ vscode-builtin-ruby: downloaded successfully 
+ vscode-builtin-shaderlab: downloaded successfully 
+ vscode-builtin-scss: downloaded successfully 
+ vscode-builtin-lua: downloaded successfully 
+ vscode-builtin-groovy: downloaded successfully 
+ vscode-builtin-objective-c: downloaded successfully 
+ vscode-builtin-ini: downloaded successfully 
+ vscode-builtin-log: downloaded successfully 
+ vscode-builtin-java: downloaded successfully 
+ vscode-builtin-go: downloaded successfully 
+ vscode-builtin-powershell: downloaded successfully 
+ vscode-builtin-less: downloaded successfully 
+ vscode-builtin-make: downloaded successfully 
+ vscode-builtin-shellscript: downloaded successfully 
+ vscode-builtin-theme-kimbie-dark: downloaded successfully 
+ vscode-builtin-typescript: downloaded successfully 
+ vscode-builtin-sql: downloaded successfully 
+ vscode-builtin-theme-abyss: downloaded successfully 
+ vscode-builtin-theme-solarized-dark: downloaded successfully 
+ vscode-builtin-theme-monokai-dimmed: downloaded successfully 
+ vscode-builtin-theme-red: downloaded successfully 
+ vscode-builtin-swift: downloaded successfully 
+ vscode-builtin-theme-tomorrow-night-blue: downloaded successfully 
+ vscode-builtin-theme-monokai: downloaded successfully 
+ vscode-builtin-theme-quietlight: downloaded successfully 
+ vscode-builtin-xml: downloaded successfully 
+ vscode-builtin-markdown: downloaded successfully 
+ vscode-builtin-theme-defaults: downloaded successfully 
+ vscode-builtin-yaml: downloaded successfully 
+ vscode-editorconfig: downloaded successfully 
+ vscode-builtin-vb: downloaded successfully 
+ vscode-builtin-jake: downloaded successfully 
+ vscode-builtin-node-debug: downloaded successfully 
+ vscode-builtin-icon-theme-seti: downloaded successfully 
+ vscode-eslint: downloaded successfully 
+ vscode-builtin-node-debug2: downloaded successfully 
+ vscode-builtin-npm: downloaded successfully 
+ vscode-builtin-emmet: downloaded successfully 
+ vscode-references-view: downloaded successfully 
+ vscode-builtin-markdown-language-features: downloaded successfully 
+ vscode-builtin-typescript-language-features: downloaded successfully 
x vscode-builtin-html: failed to download with: 404 Not Found
x vscode-builtin-gulp: failed to download with: 404 Not Found
x vscode-builtin-merge-conflict: failed to download with: 404 Not Found
x vscode-builtin-javascript: failed to download, last error:
 FetchError: request to https://aopen-vsx.org/api/vscode/javascript/1.44.2/file/vscode.javascript-1.44.2.vsix failed, reason: getaddrinfo ENOTFOUND aopen-vsx.org aopen-vsx.org:443
✨  Done in 8.67s.
```

</details>

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by lmcbout** [comment]
For some reasons, I introduce 3 errors in package.json, the second error did not show at the end , it showed in sequence of the download plugins, This error was a 404: (Change a file to a wrong file version)
+ vscode-builtin-coffeescript: downloaded successfully 
x jbvscodetest2: failed to download with: 404 Not Found
+ vscode-builtin-configuration-editing: downloaded successfully 
+ vscode-builtin-csharp: downloaded successfully 

The errors at the end were  ":FetchError: request to https:...."

**Comment by vince-fugnitto** [comment]
> For some reasons, I introduce 3 errors in package.json, the second error did not show at the end , it showed in sequence of the download plugins, This error was a 404: (Change a file to a wrong file version)
> 
> * vscode-builtin-coffeescript: downloaded successfully
>   x jbvscodetest2: failed to download with: 404 Not Found
> * vscode-builtin-configuration-editing: downloaded successfully
> * vscode-builtin-csharp: downloaded successfully
> 
> The errors at the end were ":FetchError: request to https:...."

Do you have steps to reproduce?

**Comment by lmcbout** [comment]
Steps to reproduce:
1- Open package.json and in section "theiaPlugins:, introduce the following
```
line 1 (83):     "jbvscodetest1": "https://aopen-vsx.org/api/vscode/javascript/1.44.2/file/vscode.javascript-1.44.2.vsix",
 
line 6 (89):     "jbvscodetest2": "https://open-vsx.org/api/vscode/csharp/1.44.2/file/vscode.csharp-1.44.3.vsix",

line 19 (102):     "jbvscodetest3": "https://bbopen-vsx.org/api/vscode/javascript/1.44.2/file/vscode.javascript-1.44.2.vsix",
```

2- remove the plugins folder (rm -rf plugins)
3- Run the script: yarn download:plugins

**Comment by vince-fugnitto** [comment]
> Steps to reproduce:
> 1- Open package.json and in section "theiaPlugins:, introduce the following
> 
> ```
> line 1 (83):     "jbvscodetest1": "https://aopen-vsx.org/api/vscode/javascript/1.44.2/file/vscode.javascript-1.44.2.vsix",
>  
> line 6 (89):     "jbvscodetest2": "https://open-vsx.org/api/vscode/csharp/1.44.2/file/vscode.csharp-1.44.3.vsix",
> 
> line 19 (102):     "jbvscodetest3": "https://bbopen-vsx.org/api/vscode/javascript/1.44.2/file/vscode.javascript-1.44.2.vsix",
> ```
> 
> 2- remove the plugins folder (rm -rf plugins)
> 3- Run the script: yarn download:plugins

@lmcbout it works for me, are you sure you checked out the branch and rebuilt `@theia/cli`?

<div align='center'>

Screen Shot 2020-05-25 at 11 27 57 AM


</div>

**Comment by lmcbout** [comment]
Let me rebuild a  clean version and I will let you know

**Pull request merged**
