### PR TITLE
feat(ai): Improve agent history recording

### PR DESCRIPTION
**Pull request by planger**
#### What it does

* Simplify recording for chat requests/responses by providing a util
* Introduce explicit optional system message field
* Show messages and system message in history view as a context
* A few minor typos and nitpicks

#### How to test

Use all agents and check whether their history:
* They should show a system message
* They should show the context messages (if available)

#### Follow-ups

None

#### Review checklist

- [X] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by JonasHelming — COMMENTED** [review]
Code looks great, it is a shame how often I misspelled Orchestrator :-)

I believe the Orchestrator and the Terminal Assistant do not list the messages in the context, is this expected?

On a fresh start, when the history is not open, the drop down of the history view is empty and I get this error when clicking it. Not sure, whether this is related to your change, though, probably rather to: https://github.com/eclipse-theia/theia/issues/14236

root ERROR The above error occurred in the <SelectComponent> component:

    at SelectComponent (http://127.0.0.1:3000/bundle.js:342317:9)
    at div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

I have to reload to recover from this.

**Comment by JonasHelming** [comment]
One question: Why do you use the fork, it would be simple to create a branch in the Theia repo.

**Comment by planger** [comment]
@JonasHelming Thank you for your feedback!

Right, the Orchestrator didn't include the messages, even though they are technically part of the context. So I added it.
I didn't change the Terminal Assistant as it isn't a chat agent and therefore doesn't have any additional chat messages as context.

The react error is unrelated imho, but I pushed a fix for it too.

**Review by JonasHelming — APPROVED** [review]
Great, LGTM!

**Pull request merged**
