### PR TITLE
fix preview of search result

### PR DESCRIPTION
**Pull request by shuyaqian**
Signed-off-by: shuyaqian 717749594@qq.com

#### What it does

Fix [#10045](https://github.com/eclipse-theia/theia/issues/10045)
Fix https://github.com/eclipse-theia/theia/issues/7589
Closes  #8735

#### How to test

1. set 'Enable Preview' true in preferences
2. search in workspace
3. click tree item in search results

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by shuyaqian** [comment]
I still have some questions I'd like to discuss. If `Enable Preview` is set to true, whether to open file when double-clicking the file? And if I double-click the preview tab , should block fullscreen events to open this file?

**Comment by msujew** [comment]
Hi @shuyaqian thank you for contributing again!

> And if I double-click the preview tab , should block fullscreen events to open this file?

I noticed that someone already tried to fix this in #8735. In there, some discussion on the double clicking behavior already happened. That PR isn't active anymore, so I recommend we should continue discussion on that in here. 

The specific double-clicking change in question will be adressed here: #9567. I would argue that we should wait until that is merged to continue the preview related question.

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that it works well for now, when we single-click and `editor.enablePreview` is enabled we can now open search-in-workspace results in preview-editors. As for the double-click behavior we can do what @msujew mentioned and wait for https://github.com/eclipse-theia/theia/pull/9567 first.

**Comment by vince-fugnitto** [comment]
@shuyaqian do you mind rebasing the pull-request?

**Comment by shuyaqian** [comment]
> @shuyaqian do you mind rebasing the pull-request?

I wonder if I should wait until [#9567](https://github.com/eclipse-theia/theia/pull/9567) be merged before rebase.

**Comment by vince-fugnitto** [comment]
Thank you for contributing, the pull-request is no longer applicable as the issue was fixed in https://github.com/eclipse-theia/theia/pull/10839.

**Pull request closed without merging**
