### PR TITLE
Bugfix/Stringify Task ENUMs for Presentation and PanelKind

### PR DESCRIPTION
**Pull request by kenneth-marut-work**
#### What it does

This PR addresses #7956 where `ENUM` values for `PanelKind` and `RevealKind` were not properly being stringified to their values defined in the `task-schema-updated.ts` (referenced below) when using `.setTaskConfigurations()` to write tasks to a `tasks.json` file, causing an `Invalid task configurations are found` error :
https://github.com/eclipse-theia/theia/blob/309b21892eedfadf0cd559afff64a26750933c4f/packages/task/src/browser/task-schema-updater.ts#L572
https://github.com/eclipse-theia/theia/blob/309b21892eedfadf0cd559afff64a26750933c4f/packages/task/src/browser/task-schema-updater.ts#L583

#### How to test

- Create an extension that injects the TaskConfigurationManager
- Build an object of type TaskConfiguration with some values (fill in proper scope/source value), use 
enum types for presentation panel and reveal, for example:
``` 
       const pendingTaskConfiguration: TaskConfiguration = {
            label: 'my task',
            type: 'shell',
            command: 'top',
            problemMatcher: [],
            args: '',
            _scope: 2,
            _source: scopeURI,
            options: {
                cwd: '',
            },
            presentation: {
                reveal: RevealKind.Always,
                panel: PanelKind.Shared
            },
        };
```
- Attempt to call this.taskConfigurationManager.setTaskConfigurations(scopeURI, [pendingTaskConfiguration])

- Open corresponding tasks.json file and observe that reveal and panel values have been properly set to their string values and no errors are thrown.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@elaihau do you have time to review this PR?

**Comment by marcdumais-work** [comment]
@akosyakov fine to merge?

**Comment by RomanNikitenko** [comment]
I tried to test the use case described above, but faced with the related issue for master branch https://github.com/eclipse-theia/theia/issues/8047

So, it's OK for me to merge the PR as is, we can come back and check the use case after resolving https://github.com/eclipse-theia/theia/issues/8047

**Comment by marcdumais-work** [comment]
@elaihau Ready to merge I think?

**Comment by elaihau** [comment]
> @elaihau Ready to merge I think?

@marcdumais-work Yes. I don't see objections from Roman either.

**Comment by marcdumais-work** [comment]
> Yes. I don't see objections from Roman either.

Please do the honours, Liang

**Comment by elaihau** [comment]
> Please do the honours, Liang

Oui chef

**Comment by marcdumais-work** [comment]
> Oui chef

:+1: 

Peek 2020-06-22 19-13

**Comment by kenneth-marut-work** [comment]
thanks for the review + merge ✌

**Pull request merged**
