### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by RDIL**
Signed-off-by: Reece Dunham <me@rdil.rocks>
I swear it works this time I think

### CODE REVIEW

**Comment by kittaakos** [comment]
@RDIL, how did you end up with changes only in the `yarn.lock` file?

**Comment by RDIL** [comment]
I just relocked; since most of the dependencies are dynamic it automatically updates them

**Comment by kittaakos** [comment]
> I just relocked

I see. Well, it seems something was not committed correctly. See the logs from the CI:
```
ERR: The git repository state changed after the build, this should not happen.
3920
3921HEAD detached at FETCH_HEAD
3922Changes not staged for commit:
3923  (use "git add <file>..." to update what will be committed)
3924  (use "git checkout -- <file>..." to discard changes in working directory)
3925
3926	modified:   yarn.lock
3927
3928no changes added to commit (use "git add" and/or "git commit -a")
3929
3930HINT: Did you update and commit your 'yarn.lock' ?
```

Do you see any outgoing Git changes after you run `yarn` locally? There shouldn't be any.

**Comment by marechal-p** [comment]
Just tried on Gitpod, ran the following:

```
yarn upgrade
git diff # no diff
yarn
git diff # still no diff
```

Otherwise since everything looked up-to-date I would have said LGTM, but idk how to address CI.

**Comment by marechal-p** [comment]
```sh
$ yarn --version
1.15.2
```
Maybe just a matter of updating yarn on Travis?

**Pull request closed without merging**
