### PR TITLE
GH-8654: Fix SelectAll/Copy/Paste Keyboard Shortcuts are not working within DevTools and native input and file dialogs for macOS

### LINKED ISSUE #6217: [vscode][webview] can't copy content from webview use Ctrl + C
### Reproduction Steps

- ext install humao.rest-client
- create a `test.http` file
```
GET http://baidu.com
```
- Click Send Request
- select response at webview
- Copy use hotkey `Ctrl + C`
- nothing happend

**OS and Theia version:**

**Diagnostics:**

### LINKED ISSUE #8654: SelectAll/Copy/Paste Keyboard Shortcuts are not working within DevTools and native input and file dialogs
### Bug Description:
Copy/Paste Keyboard Shortcuts are not working within DevTools

### Steps to Reproduce:

1.Open Devtools
2.try Cmd+C/Cmd+V  copy/paste anything in Devtools, Nothing happened

I can see that it executed the COPY command, but nothing todo
image

### Additional Information

- Operating System: macOS 10.15.6
- Theia Version: 1.6.0

### PR DESCRIPTION
**Pull request by zhaomenghuan**
#### What it does
Fixed #8654
Fixed #6217

#### How to test
System environment：mac OS
You can operate copy (⌘+C), paste (⌘+V) and other operations on DevTools and mini-browser. It is found that the operation cannot be performed normally before the repair, and the operation is normal after the repair.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: 赵梦欢 <zhaomenghuan02@meituan.com>

### CODE REVIEW

**Comment by christlee1989** [comment]
LGTM

**Comment by kittaakos** [comment]
@zhaomenghuan, thank you for your contribution. I'd have a few remarks, and I was wondering if you're still interested in adjusting the PR a little bit.

The approach is good, VS Code [does very similar](https://github.com/microsoft/vscode/blob/5d1e300546ec84818e4cdc6ff95408b487ac1b6f/src/vs/platform/menubar/electron-main/menubar.ts#L648-L676). It turned out copy/pasting works just as is on Windows. I tried with the [Theia electron app](https://download.eclipse.org/theia/1.10.0/windows/) on Windows. Based on the [VS Code codebase](https://github.com/microsoft/vscode/blob/5d1e300546ec84818e4cdc6ff95408b487ac1b6f/src/vs/platform/menubar/electron-main/menubar.ts#L648), it's most likely not an issue on Linux either. Can you please make your special `role` handling only for macOS?

**Comment by zhaomenghuan** [comment]
> @zhaomenghuan, thank you for your contribution. I'd have a few remarks, and I was wondering if you're still interested in adjusting the PR a little bit.
> 
> The approach is good, VS Code [does very similar](https://github.com/microsoft/vscode/blob/5d1e300546ec84818e4cdc6ff95408b487ac1b6f/src/vs/platform/menubar/electron-main/menubar.ts#L648-L676). It turned out copy/pasting works just as is on Windows. I tried with the [Theia electron app](https://download.eclipse.org/theia/1.10.0/windows/) on Windows. Based on the [VS Code codebase](https://github.com/microsoft/vscode/blob/5d1e300546ec84818e4cdc6ff95408b487ac1b6f/src/vs/platform/menubar/electron-main/menubar.ts#L648), it's most likely not an issue on Linux either. Can you please make your special `role` handling only for macOS?

@kittaakos Thank you for your comment and modification suggestion, the modification has been completed, please take the time to review it.

**Review by kittaakos — APPROVED** [review]
Thank you for your help, @zhaomenghuan 👍

**Comment by kittaakos** [comment]
I assume the `before each`, `after each` [test failures](https://github.com/eclipse-theia/theia/pull/8943/checks?check_run_id=1925289029#step:7:4946) are unrelated to this change. Thank you for your help, @zhaomenghuan 👍

**Review by kittaakos — APPROVED** [review]

**Pull request merged**
