### PR TITLE
console: do not clear output when a session ends

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes: https://github.com/eclipse-theia/theia/issues/10653.

The pull-request fixes an issue which caused the debug console output to clear when a session was completed. 
The change now preserves the output so end-users can view the output of their debug session.

It namely reverts a change proposed in https://github.com/eclipse-theia/theia/pull/10333.

#### How to test

1. start a debug session (with and without debug breakpoints).
2. when the session is terminated, the console output should be preserved.
3. confirm that subsequent sessions also work correctly.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@msujew do you mind reviewing whenever you get a chance? I reverted the logic from https://github.com/eclipse-theia/theia/pull/10333 which broke the output, and am unsure if no longer setting the cached session to `undefined` will cause any side-effects.

**Comment by colin-grant-work** [comment]
I believe that the motivation behind removing the reference to the debug session was to ensure that it would be garbage-collected when the session was terminated. With this change, that doesn't happen:

image

The `ConsoleWidget` isn't the only retainer of old sessions: of the four in that screenshot, two are retained by something in `debug-hover-source.ts`, one by something in `debug-stack-frame.tsx`, and it appears that the reference retained by the console is released when the session is replaced by another console session, but it seems that there ought to be some way to release the debug session without deleting the content.

**Comment by colin-grant-work** [comment]
But if push comes to shove, I think retaining a reference to the session is better than deleting the output, so if there's no way to preserve the output without retaining the reference for now, that's OK.

**Review by colin-grant-work — APPROVED** [review]
Better than the alternative for now, though it may be worth making an issue to allow for retention of output when session is set to undefined.

**Review by msujew — APPROVED** [review]
Looks good to me as well. I agree with Colin, we can fix the dangling debug session reference sometime else.

**Comment by vince-fugnitto** [comment]
I'll merge for the moment since it improves the behavior for end-users, and open a follow-up issue to track the cleanup.
Thanks guys!

**Pull request merged**
