### PR TITLE
fix deleting hosted plugin directory when undeploy

### PR DESCRIPTION
**Pull request by shuyaqian**
Signed-off-by: shuyaqian 717749594@qq.com

#### What it does

fix [9855](https://github.com/eclipse-theia/theia/issues/9855)

#### How to test

1. execute the command `hosted plugin: start instance` to debug plugin 
2. install the debugging plugin package  in development host
3. the debugging plugin directory will be removed 
4. After the fix, the directory will only be refreshed.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by colin-grant-work** [comment]
@shuyaqian, would you be able to provide some testing instructions to allow reviewers to confirm the bug on `master` and confirm the fix here?

**Comment by shuyaqian** [comment]
> @shuyaqian, would you be able to provide some testing instructions to allow reviewers to confirm the bug on `master` and confirm the fix here?

1. debugging plugin
2. install the hosted plugin package in development host
3. the hosted plugin directory will be removed because of ‘undeploy’

**Comment by shuyaqian** [comment]
@colin-grant-work

**Comment by vince-fugnitto** [comment]
> execute the command hosted plugin: start instance to debug plugin

It cannot be tested until https://github.com/eclipse-theia/theia/pull/9874 is approved and merged.

**Comment by colin-grant-work** [comment]
@shuyaqian, I'm afraid I'm still not entirely sure how to test your changes. On `master` I followed the following steps:
1. Open browser application.
2. Run the command `Hosted Plugin: Start Instance`
3. Select a folder containing plugin source code.
4. --> Hosted plugin starts in separate window
5. Return to main window (host)
6. Run 'Install from vsix' on a VSIX file built from the same plugin selected in step (3).
7. Plugin starts up in the host instance.

I also tried doing steps (6) and (7) in the hosted plugin window. As I understand the issue, one of those scenarios should have triggered the deletion of some part of the source code selected in step (3), but I never observed any deletion. Since I can't reproduce the issue on `master`, I can't be sure whether your code fixes it. Can you provide more information so that I can reproduce the issue?

**Comment by shuyaqian** [comment]
> @shuyaqian, I'm afraid I'm still not entirely sure how to test your changes. On `master` I followed the following steps:
> 
> 1. Open browser application.
> 2. Run the command `Hosted Plugin: Start Instance`
> 3. Select a folder containing plugin source code.
> 4. --> Hosted plugin starts in separate window
> 5. Return to main window (host)
> 6. Run 'Install from vsix' on a VSIX file built from the same plugin selected in step (3).
> 7. Plugin starts up in the host instance.
> 
> I also tried doing steps (6) and (7) in the hosted plugin window. As I understand the issue, one of those scenarios should have triggered the deletion of some part of the source code selected in step (3), but I never observed any deletion. Since I can't reproduce the issue on `master`, I can't be sure whether your code fixes it. Can you provide more information so that I can reproduce the issue?

Sorry, I re-compared my branch code with the master code and found that I encapsulated the reinstall command and called the `undeploy` method. This problem does not recur on the master.

**Pull request closed without merging**
