### PR TITLE
core: Workaround for Electron not installing a handler to ignore SIGPIPE error

### LINKED ISSUE #8534: Error：Kill child process will case "kill ESRCH" when "Error in connection establishment: net::ERR_CONNECTION_REFUSED"
### Bug Description:

Two problems that can be reproduced stably.

- Error in connection establishment: net::ERR_CONNECTION_REFUSED
- Kill ESRCH

### Steps to Reproduce:

When I opened the Electron desktop application built on Theia, and did not operate for a period of time, when I opened DevTools, I could see the following error:
屏幕快照 2020-09-21 下午2 09 09
I click the exit button：
屏幕快照 2020-09-21 下午2 08 48
Error popup will pop up：
屏幕快照 2020-09-21 下午2 08 31
The code that caused the error is:
```
process.kill(backendProcess.pid);
```

### Additional Information

- Operating System: macOS
- Theia Version:

### PR DESCRIPTION
**Pull request by zhaomenghuan**
#### What it does

Fixes #8534 
- Workaround for Electron Backend Process not installing a handler to ignore SIGPIPE errors.

#### How to test

I have tested my application and related issues have been resolved. [https://github.com/eclipse-theia/theia/issues/8534](url)

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: zhaomenghuan <zhaomenghuan02@meituan.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
@zhaomenghuan, thank you again! What OS are you using? I would like to reproduce the issue with and without your changes; do I have to hibernate my OS and that's all I have to do?

**Comment by zhaomenghuan** [comment]
@kittaakos I am using macOS. I can't reproduce the problem with the theia examples and Arduino Pro IDE. Currently, it can only be reproduced in the application I built.

**Comment by kittaakos** [comment]
> I am using macOS.

👍  Thanks for the info. Me too, at least this simplifies the verification.

> I can't reproduce the problem with the theia examples and Arduino Pro IDE. Currently, it can only be reproduced in the application I built.

Good to know.

I was not aware of it, but macOS can be configured to go to hibernation mode instead of sleep with `pmset`. Did you tune `pmset` on your side?

**Comment by zhaomenghuan** [comment]
In my impression, I haven't made any settings about `pmset`, and used the default behavior of the system. If SIGPIPE is not processed in my application, the process will die in sleep mode. I have analyzed the memory-related data and can confirm that it is normal.

**Comment by kittaakos** [comment]
OK, fair enough. Your contribution is super useful for Electron clients; I will figure out how to reproduce it locally and try to merge the PR this week so it will be part of the next release.

**Review by kittaakos — APPROVED** [review]
I have verified it with the demo version of [SmartSleep](https://www.jinx.de/SmartSleep.html) on macOS: `QuickSleep` > `Hibernate Now`. It works great 👍

**Pull request merged**
