### PR TITLE
Added tab related APIs - without functionality implemented yet

### PR DESCRIPTION
**Pull request by jbicker**
#### What it does
It adds tab related APIs. For now it just solves the problem that we get an error when an extension uses the VSCode Tab API.
Functionality is not implemented on theia side yet. 

#### How to test

1. Download this test extension: 
[tab-test-0.0.1.zip](https://github.com/eclipse-theia/theia/files/10318724/tab-test-0.0.1.zip)
and change the file type from zip to vsix
or create it [here](https://github.com/jbicker/tab-api-test-extension)
or use another extension which uses the VSCode Tab API
2. install it in theia
3. trigger the command 'Close Active Tab'
4. see that nothing happens, even no errors notified anymore

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by paulalexwilson** [comment]
https://github.com/jbicker/tab-api-test-extension is not accessible to me

**Comment by JonasHelming** [comment]
This is great! Would you mind marking the members in theia.d.ts as @stubbed (see [here](https://github.com/eclipse-theia/theia/pull/11993/files#diff-039a4c69e33f1a425bb709ef2f423d6152fc269f759c70130b69980f4d883c10) for an example. This way, the stubbed members are showsn correctly as stubbed in the compat report (see [here](https://eclipse-theia.github.io/vscode-theia-comparator/status.html))

**Comment by jbicker** [comment]
@paulalexwilson, sorry about that. Try again!

**Comment by jbicker** [comment]
I squashed and force pushed with @stubbed markers.

**Comment by JonasHelming** [comment]
@rschnekenbu Could you run the VS Code compat checker over this branch and see whether all members are shown as stubbed (or supported)?

**Comment by rschnekenbu** [comment]
@JonasHelming, sure, I will run the tool tomorrow and give the result here

**Comment by rschnekenbu** [comment]
All members related to 'Tab' API are shown as `@stubbed` or implemented in @jbicker branch. That looks good to me on that aspect.

report: [status.zip](https://github.com/eclipse-theia/theia/files/10342708/status.zip)

**Review by JonasHelming — APPROVED** [review]

**Pull request merged**
