### PR TITLE
[filesystem] Fix missing "out of sync error"

### PR DESCRIPTION
**Pull request by AlexTugarev**
which should be shown if one try to save pending editor changes to a file which was modified in background.

Fixes eclipse-theia/theia#7102

Thanks @akosyakov to provide this fix!

#### How to test
- do some changes to a file
- modify the opened file on terminal
- try to save the dirty editor
  - it should warn you:
    Screen Shot 2020-02-12 at 11 20 34
- test closing with dirty and not against the file modified in the background and not
- test typing fast and slow with auto save
- test reloading a page with a file deleted in the meantime
- test file move and delete with dirty and not editors

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
Just had to check now why we broke it, probably we tried to fix something else :)

**Comment by akosyakov** [comment]
ok, it seems i overlooked it by while introducing incremental updates: https://github.com/eclipse-theia/theia/commit/bace685a8a77ad1ddfe986f1663cd7e081376c6b#diff-bc50ceab9ceca36de64ebebbe8a2987bL64 How did we live with that for such long time 😬

**Comment by akosyakov** [comment]
It does not work very well :( It does ask, but if i say don't save then it asks again and then it does not allow me to save anymore.

**Comment by akosyakov** [comment]
It would be good to create integration tests for it as well.

**Comment by akosyakov** [comment]
@AlexTugarev Can i push to this PR?

**Comment by AlexTugarev** [comment]
Please, yes!

**Comment by akosyakov** [comment]
@AlexTugarev i'm going to close it and open a new PR, fine? that we can revert author and reviewer roles?

**Comment by akosyakov** [comment]
@alainbernard It's turned out to be really complicated. The main issue that monaco model does not know about resource stat while dirty but it still can fetch a resource and reset it to latest stat because of it. In such case, monaco model will overwrite fs. I wonder should we expose something like stat on resource.

**Comment by akosyakov** [comment]
Discussed with @svenefftinge that we will add optional version attribute to Resource which clients can pass to save operation.

**Comment by akosyakov** [comment]
Also noticed that on reload deleted files are not marked as deleted and overwrite content on the disk if saved after file is added again to the disk in background.

**Comment by akosyakov** [comment]
@AlexTugarev @marcdumais-work @vince-fugnitto @lmcbout Could you test please? I've added integration tests for all kind of cases of save cycle, but it would be good to test manually as well that saving works well generally and against changed state on the disk.

**Comment by akosyakov** [comment]
It should also fix https://github.com/eclipse-theia/theia/issues/7054, but i did not verify it yet.

**Comment by marcdumais-work** [comment]
Testing on Gitpod, I notice something strange: I do the scenario in this PRs description: open a file in both a Theia editor and in the terminal (using vi). I made some unchanged change in the Theia editor and do other changes and save in the terminal. Then I save in the Theia editor:
- I do not get the dialog about if I want to overwrite the file that has changed on disk
- The editor seems to silently be aware of the change in the file but does not display it. 
- After saving from the editor, if I look at the file on disj (e.g. re-open it in terminal), I see both the changed I did from `vi` and in the editor.

Peek 2020-02-14 08-09

**Comment by akosyakov** [comment]
@marcdumais-work my bad i will add one more test, here https://github.com/eclipse-theia/theia/pull/7139/files#diff-bc50ceab9ceca36de64ebebbe8a2987bR128 it has to be `||` before last expression

**Comment by marcdumais-work** [comment]
> It should also fix #7054, but i did not verify it yet.

Question: this was reported on Gitpod - was `@theia/java` or the Java by Red Hat VS Code extension used?

**Comment by akosyakov** [comment]
@marcdumais-work Gitpod use only vscode extensions for language support, but wait a bit with testing please, you discovered a bug, i will push a fix for it in half an hour. Already managed to break tests.

**Comment by akosyakov** [comment]
@marcdumais-work could you try again please?

**Comment by akosyakov** [comment]
There is still something with move of dirty files when i test with Java, now editor is properly moved, but there is an error in the editor. It looks like Java LS is missing some updates for the target editor.

**Comment by marcdumais-work** [comment]
> @marcdumais-work could you try again please?

Works better now - the problem I had earlier is fixed. Will test some more.

**Comment by marcdumais-work** [comment]
> 
> Also add tests for:
> 
> * [x]  removing file

Seems to work well (same as master):

- remove a file that's open in editor (dirty) -> editor kept, marked as deleted on disk
- remove a file that's open in editor (not dirty) -> editor immediately closed. (note: VS Code keeps the editor in this case - I have no strong opinion which is better)

> * [x]  moving file

Seems to work well (same as master):

- move file opened in editor (dirty) -> editor kept and marked as deleted from disk
- move file opened in editor (not dirty) -> editor closed (note: VS Code keeps the editor in this case - I have no strong opinion which is better)


> * [x]  deleted files cannot be opened (or deleted files should be closed on reload)

- remove file opened in editor (dirty)  -> editor not re-opened after frontend reload
- remove file opened in editor (not dirty)  -> editor closed immediately and not re-opened after reload

With this PR the editor for the deleted file is not restored after reload :+1:  

> test typing fast and slow with auto save 

On its own, autosave works fine as far as I can tell. However if we add concurrent modifications done from outside Theia, it does not work great compared to VS Code. (but no worse than theia master as far as I can tell). So maybe this could be tackled separately.

The result seems to depend on the timing of auto-save vs timing of outside modifications. It's very easy for the changes from outside to be silently overwritten without the user noticing it's the case if the changes are concurrent. 

- create/open a file in Theia: e.g. `toto`
- in a terminal run the following one-liner script that appends to the file periodically: `for i in {1..1000}; do sleep 1; echo "OOO" >> toto;  done`
- in a second terminal run `tail -f toto` to see the updates to the file as they happen

At times, depending on timing, I can see : 
- the outside change is seen being added to the file by `tail` but not shown at all in Theia editor
- the outside change is seen in the editor. However it's selected and so overwritten as soon as a key is pressed. 

Peek 2020-02-14 15-33

Peek 2020-02-14 15-39

**Comment by akosyakov** [comment]
> The result seems to depend on the timing of auto-save vs timing of outside modifications. It's very easy for the changes from outside to be silently overwritten without the user noticing it's the case if the changes are concurrent.

Do you test with auto save on both in Theia and VS Code?

**Comment by marcdumais-work** [comment]
> > The result seems to depend on the timing of auto-save vs timing of outside modifications. It's very easy for the changes from outside to be silently overwritten without the user noticing it's the case if the changes are concurrent.
> 
> Do you test with auto save on both in Theia and VS Code?

yes, both.

**Comment by akosyakov** [comment]
@marcdumais-work I cannot reproduce, i get consistently a dialog asking me to overwrite in Theia.

I also don't think behaviour in VS Code is good, on overwrite it appends some content to the editor from the disk instead of overwriting the disk with the editor content. Do you think it is expected?

**Comment by akosyakov** [comment]
> move file opened in editor (dirty) -> editor kept and marked as deleted from disk

that sounds bogus, on move, old editor should be closed regardless whether dirty or not, target editor should be opened instead with the same state.

@marcdumais-work Could you check that the build was successful for this PR? Maybe you were testing without changes applied?

**Comment by akosyakov** [comment]
@AlexTugarev Could you have a look whether you can reproduce @marcdumais-work issues? See https://github.com/eclipse-theia/theia/pull/7139#issuecomment-586464982

**Comment by AlexTugarev** [comment]
@marcdumais-work and @AlexTugarev, in the test from above where you're trying to catch periodic changes from outside, that's actually what I would even assume what should happen, given:
 1. the frequency of the change cycles is 1 Hz
 2. `nsfw` debounces at `debounceMS = 500` by default
So, chances are good that you just miss changes quite often, or am I wrong?

**Comment by AlexTugarev** [comment]
@marcdumais-work I re-tested the "outside-changes" scenario with auto-save enabled from above, and it looks good. are you 100% sure, that it's not the master state you're looking at? I tried several times to make sure not posting bs again ;-)

**Comment by AlexTugarev** [comment]
Screen Shot 2020-02-18 at 10 03 59

@akosyakov that "deleted from disk" still exists when using `mv` from terminal. (auto-save is disabled, and editor was dirty in the screen shot ☝️ )

**Comment by akosyakov** [comment]
> that "deleted from disk" still exists when using mv from terminal. (auto-save is disabled, and editor was dirty in the screen shot ☝️ )

@AlexTugarev I know, we don't participate in move from outside, only then they triggered by Theia, there is no reliable way to detect it. It is the same on master. I'm more concerned with cases when we programmatically rename or move something, like in https://github.com/eclipse-theia/theia/issues/7054 Could you file a new issue? I'm not sure that it is solvable since we have to take snapshot of the state before move and events come only after.

**Comment by AlexTugarev** [comment]
@akosyakov thanks for clarification!

**Comment by AlexTugarev** [comment]
@marcdumais-work, it would be great if you can retest 🙏 This PR solves a lot of issues already.

**Comment by marcdumais-work** [comment]
Hi @AlexTugarev , @akosyakov ,

Back to work this morning. I pulled the latest version of this PR and it's building. Let me retest a bit and comment. 

> This PR solves a lot of issues already.

:+1:

**Comment by marcdumais-work** [comment]
Update: I can't reproduce the "concurrent file update" issue. It's possible that there is a race-condition in the scenario where we may wrongly overwrite outside updates, but if so it's not so easy to trigger anymore.

> that sounds bogus, on move, old editor should be closed regardless whether dirty or not, target editor should be opened instead with the same state.

I confirm that's what happens when renaming a dirty file from inside Theia :+1: 

As I think @AlexTugarev figured, I was originally renaming the file from the terminal using `mv` - sorry for the confusion.

Conclusion: looks good to merge, behavior-wise.

**Comment by akosyakov** [comment]
@marcdumais-work @AlexTugarev thank you for the review could someone approve please?

I've also pushed one more commit to insulate tests against nsfw failures: https://github.com/eclipse-theia/theia/pull/7139/commits/bd6f947467248ef3906408b98031f7c662d09c2f It should make sure that file resource operates even if nsfw failed given that file operations are triggered via Theia UI (FileSystem API). If not then we are out of luck if nsfw failed.

**Comment by akosyakov** [comment]
@AlexTugarev said (offline) that he will review the code once

**Comment by AlexTugarev** [comment]
✔️ I went through the changes and tested once again. It looks very good! Thanks for investing so much time into this issue, Anton!

**Pull request merged**
