### PR TITLE
Update the 'outline-view' documentation

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

- updates the documentation for the `outline-view`.
- in order to globally update the documentation for all `tree-widgets`,
including the `outline-view-widget`, the `tree-widget.tsx` documentation
was updated from `@theia/core`.

The following additional `tslint` checks were added to the `errors.tslint.json` during development, and the documentation was updated in order to make the build pass.

```json
"rules": {
    "completed-docs": [true, "enums", "enum-members", "functions", "interfaces", "methods"],
    "no-redundant-jsdoc": true,
}
```

#### How to test

Verify the documentation.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
I'm fine merging such PRs. But i'm not going to write and update such docs. I don't see any new information from such docs, except repetition of method names and parameters.

**Comment by vince-fugnitto** [comment]
@akosyakov I understand your point, documentation should in fact bring extra value and should accurately describe the non-trivial parts of a method. I'll try to update the documentation to be more descriptive and thorough and attempt to explain internally what the methods perform. 

Thank you for the feedback!

**Comment by vince-fugnitto** [comment]
@elaihau you can verify the PR now. I've updated the documentation and am open to more feedback.

**Comment by vince-fugnitto** [comment]
@elaihau thank you for the review!

**Pull request merged**
