### PR TITLE
fix #8669: .gitignore entries shouldn't be excluded from workspaceContains events

### LINKED ISSUE #8669: workspaceContains activation event doesn't fire if matched with .gitignore outside of the workspace
### Bug Description:
For plugins activated by workspaceContains, event doesn't fire if matched file is present in .gitignore, even if .gitignore is not in the current workspace. This behavior is down to ripgrep, which by default ignores entries found in .gitignore and knows nothing about theia workspaces. This can be fixed by running ripgrep with '--no-ignore-vcs'.

### Steps to Reproduce:

1. Consider following folder structure:
```
my-parent-repo/
   .gitignore
   modules/
       my-module/   <- workspace root
          src/
          build/
             compile_commands.json
```
2. .gitignore contents:
```
**/build/*
compile_commands.json
```
3. Plugin activation events:
"activationEvents": [
        "workspaceContains:**/compile_commands.json"
        ...
],
4. Refresh workspace => plugin not activated
5. Change workspace root to: my-parent-repo/modules/my-module/build => plugin activated

### Additional Information

- Operating System: macOS 10.14.6
- Theia Version: git master

### PR DESCRIPTION
**Pull request by vnfedotov**
#### What it does

Fixes #8669: workspaceContains activation event doesn't fire if matched file found in .gitignore, it's expected behavior of ripgrep.

This PR changes arguments for fileSearchService when looking for files matched by workspaceContains pattern, adding useGitIgnore=false, in result ripgrep will run with '-uu' flag and include .gitignore entries in search results.

Impact is limited to workspaceContains activation event behavior.

#### How to test

1. Create plugin with following activation events:
```
"activationEvents": [
        "workspaceContains:**/compile_commands.json"
]
```

2. Create following folder structure:
```
my-parent-repo/
   .gitignore
   modules/
       my-module/   <- workspace root
          src/
          build/
             compile_commands.json
```
3. Add following entries to .gitignore:
`**/build/*`
4. Load plugin, point workspace root to: my-parent-repo/modules/my-module/
5. Plugin should activate

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vladimir Fedotov <vfl@ispras.ru>

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@vnfedotov thank you for your investigation into the issue and your subsequent pull-request contribution :+1: Please be sure to complete the [Eclipse Contributor Agreement (ECA)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) so we can accept your changes.

**Review by vince-fugnitto — COMMENTED** [review]
@vnfedotov were you able to confirm the behavior in vscode, I do not believe they search in ignored files when determining the activation event for `workspaceContains`. I verified with a custom extension which displays a message when `compile_commands.json` is present in the workspace.

During my tests in vscode, I noticed that the _compile_commands.json_ added under `node_modules` (which is gitignored) does not trigger the activation event, while if it outside gitnignored files it does. This is the behavior I expect since I do not believe gitignored files should trigger extensions eagerly.

**Comment by vnfedotov** [comment]
@vince-fugnitto I did. I've tested with vscode-clangd extension (https://github.com/clangd/vscode-clangd) modified to have following activationEvents:
```
"activationEvents": [
        "workspaceContains:**/compile_commands.json",
        "onCommand:clangd.activate",
        "onCommand:clangd.install",
        "onCommand:clangd.update"
    ],
```

In fact, underlying workspace.findFiles() behaves differently in vscode, which initially made me think in has something to do with #6460 -- in vscode it finds gitignored files, in theia it doesn't (because useGitIgnore is true by default).

**Comment by vince-fugnitto** [comment]
@vnfedotov when testing, did you add a `compile_commands.json` file under a gitignored folder and no where else (ex: under `node_modules`)? For this case, vscode did not activate the extension and it is the behavior I expect but is broken by these changes.


To test, I created a minimal  [extension](https://github.com/vince-fugnitto/workspace-contains-test/releases/download/0.0.1/workspace-contains-0.0.1.vsix) with the following [activation event](https://github.com/vince-fugnitto/workspace-contains-test/blob/a329556c51c59b5a13672c2cdcafd888ab41263b/package.json#L13-L15):

```json
"activationEvents": [
    "workspaceContains:**/compile_commands.json"
],
```

Upon activation it will display an information message to end-users (for test purposes). The two use case are:

| Use-Case | Observed VS Code Behavior |
|:---|:---|
| _compile_commands.json_ exists in a non-gitignored folder (ex: root of workspace) | Extension **activates** |
| _compile_commands.json_ exists in a gitignored folder (ex: `node_modules`) | Extension **does not activate** |

**Comment by vince-fugnitto** [comment]
@vnfedotov I believe the fix would not be to ignore all gitignored files, but rather parent ones which seem to be your initial bug:

```
--no-ignore-parent
Don't respect ignore files (.gitignore, .ignore, etc.) in parent directories.
```

**Comment by vnfedotov** [comment]
@vince-fugnitto These are ripgrep args that I've extracted from vscode:
```
--files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --no-ignore-parent --follow --no-config --no-ignore-global
```

You can probably guess why workspaceContains doesn't fire when compile_commands.json is placed in node_modules.
I would suggest following test case, using your extension:

1. `git clone https://github.com/vnfedotov/workspace-contains-test-repo`
2. `cd workspace-contains-test-repo && mkdir build && touch build/compile_commands.json`
3. open vscode on workspace-contains-test-repo -> message appears
4. verify that compile_commands.json is gitignored (greyed out in project explorer)
5. `mv build/compile_commands.json node_modules/`
6. reopen workspace -> message doesn't appear

**Comment by vince-fugnitto** [comment]
> You can probably guess why workspaceContains doesn't fire when compile_commands.json is placed in node_modules.
> I would suggest following test case, using your extension:

@vnfedotov I understand that vscode does not activate the extension when it is under `node_modules`, what I'm trying to illustrate is how this pull-request breaks that behavior. With your changes, if my `compile_commands.json` is placed under `node_modules` (which is gitignored) the extension is incorrectly activated. While it may resolve your initial bug, it introduces a breaking behavior which should instead be fixed alternatively than simply ignoring all gitignored folders.

**Comment by vnfedotov** [comment]
@vince-fugnitto The point I was trying to make is that `node_modules` is ignored not because it's in .gitignore, but because vscode explicitly excludes it from search results, along with `.git/`, `CVS/` and others.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto The point I was trying to make is that `node_modules` is ignored not because it's in .gitignore, but because vscode explicitly excludes it from search results, along with `.git/`, `CVS/` and others.

@vnfedotov I placed a `compile_commands.json` under another gitignored folder (ex: `vince`) for test purposes, the extension is not activated in vscode while it is with this pull-request.

**Comment by vnfedotov** [comment]
@vince-fugnitto I'm not sure what to tell you, because I'm observing exactly [opposite behaviour](https://gifyu.com/image/RvET)

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I'm not sure what to tell you, because I'm observing exactly [opposite behaviour](https://gifyu.com/image/RvET)

In your example `build` is not properly gitignored (it is also not decorated as ignored), try:

```
build
```

You'll see that the activation event does not occur, while this pull-request does.

**Comment by vnfedotov** [comment]
@vince-fugnitto Ah, I see. It does work if file is gitignored, but doesn't if folder is also gitignored. 
I'm not sure what to do with this. File search implementation in theia substantially differs from vscode. We can put bandage on it, adding `no-ignore-parent` as you suggested, but it won't fix underlying issues.

Tbh, I don't really get the logic behind vscode implementation, it leaves out use cases that are useful. In fact, we need some way to trigger plugin activation, if compilation database (compile_commands.json) exists in the workspace, and its common to put it in .gitignore as a build artifact.

**Comment by vince-fugnitto** [comment]
I believe the pull-request can be closed, from the last feedback (https://github.com/eclipse-theia/theia/pull/8671#issuecomment-717972652) the changes will incorrectly activate the extension which differs from behavior compared to vscode. If we continue we should find a way which does not break this behavior.

**Pull request closed without merging**
