### PR TITLE
Centered file icons in the sidebars

### PR DESCRIPTION
**Pull request by kaiyue0329**
Fixes: #4712 

#### What it does
- Fix alignment for the file icons in the sidebars to make sure they are all centered

#### How to test
- Move editors (ex: settings.json) and dock them in the sidepanels.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kaiyue0329** [comment]
@vince-fugnitto I verified all file types and all the icons are centered except for .LOG file and .png file. They are only off by a little bit. 

I don't think there is a css variable available for -2px.

**Comment by kaiyue0329** [comment]
@vince-fugnitto I verified that all icons for different file types are now centered except for .LOG and .png file (which are off only by a little bit).

I don't think there is a `css variable` that we could use for -2px.

**Comment by akosyakov** [comment]
As usual verify with all default file icon themes, i.e. none, minimal, seti files-js from theia.

**Comment by vince-fugnitto** [comment]
> As usual verify with all default file icon themes, i.e. none, minimal, seti files-js from theia.

I wonder what the behavior should be when using `none` icons in the sidebars:

image

**Comment by akosyakov** [comment]
> I wonder what the behavior should be when using none icons in the sidebars

it is an issue indeed, but should not be in the scope of this PR. Maybe use some default icon but only for none theme? please open another issue

**Comment by vince-fugnitto** [comment]
> > I wonder what the behavior should be when using none icons in the sidebars
> 
> it is an issue indeed, but should not be in the scope of this PR. Maybe use some default icon but only for none theme? please open another issue

Sure, I agree it is not in the scope of the pull-request but I believe it is somewhat related to https://github.com/eclipse-theia/theia/issues/4616.

**Comment by lmcbout** [comment]
Testing this issue, when dragging a JAVA file to the sidebar, the files cannot be open anymore, no data available. On the side effect, when trying to open the same file from the explorer view, it compress the sidebar, but the file is somewhere not visible anymore .
FileGoesAway

**Comment by vince-fugnitto** [comment]
> Testing this issue, when dragging a JAVA file to the sidebar, the files cannot be open anymore, no data available. On the side effect, when trying to open the same file from the explorer view, it compress the sidebar, but the file is somewhere not visible anymore .
> FileGoesAway

I think it is out of scope for this pull-request, it is a known issue with `preview-editors` https://github.com/eclipse-theia/theia/issues/4719

You can confirm by testing with actual editors (non-previewed editors).

**Comment by kaiyue0329** [comment]
image
@vince-fugnitto I tried improving the display for this type of icon in the seti theme. Since they don't  have a unique `css class name`, I can't find a way to apply a specific style to them.

All other icons in the seti theme and minimal theme are centered.

**Comment by kaiyue0329** [comment]
Also, I noticed that these two bubbles appearing when using none icons. I wonder what the behavior should be.
image

**Comment by vince-fugnitto** [comment]
> Also, I noticed that these two bubbles appearing when using none icons. I wonder what the behavior should be:
> image

I think we discussed there should be a default icon for such cases (when in the sidebar) https://github.com/eclipse-theia/theia/issues/7038 How were you able to reproduce it on your end?

**Comment by kaiyue0329** [comment]
@vince-fugnitto

image

image

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto
> 
> image
> 
> image

I was able to reproduce as well :(
I think if we handle the default icon when in the sidebar it will solve the issue as well.

**Pull request closed without merging**
