### PR TITLE
Updated `dugite-extra` and `find-git-exec`.

### PR DESCRIPTION
**Pull request by kittaakos**
The updated dependencies contain fix for:
 - The termination of the spawned process. The bogus process termination resulted in an empty string from the `stdout` as the `exec-path`. The empty string "path" was incorrectly normalized to `.`. (See: eclipse-theia/theia#6587)
 - [win32]: Enhanced `git` discovery. The new logic falls back to `which`.
 - [win32]: The unstaging command. `-u` was added to ensure that git's index reflects a consistent view of the working tree after the operation has been performed.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does

See above 👆 

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

@marcdumais-work, I would like to request you for a review becasue of the dependencies update. We maintain both dependencies, both have MIT license. `find-git-exec` was [inspired by VS Code](https://github.com/TypeFox/find-git-exec/blob/201e26e50a6c8bc0f5b96102ed979234809f97d0/src/find-git-exec.ts#L6), but it was always the case. Please check if we are good with the PR. Thank you!

- [x] as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
> if some else verify this on Windows

I will.

**Comment by kittaakos** [comment]
I have verified the unstaging on Windows. It worked. The not on PATH defect was never an issue with my Windows env. I am merging it.

**Comment by marcdumais-work** [comment]
> @marcdumais-work, I would like to request you for a review becasue of the dependencies update. We maintain both dependencies, both have MIT license. find-git-exec was inspired by VS Code, but it was always the case. Please check if we are good with the PR. Thank you!

Checking now, thanks for your patience :)

**Comment by marcdumais-work** [comment]
@kittaakos Everything looks good:
- I did the 3rd party license check using `clearlydefined` on master and all dependencies are still good
- about the two dependencies maintained under the `typefox` org: from what I can see you handled the license correctly for the copied code in `find-git-exec` and the process above covers any new 3rd party dependency that might be newly pulled from these two.

**Comment by kittaakos** [comment]
> Everything looks good:

Thank you for your help, @marcdumais-work!

**Pull request merged**
