### PR TITLE
feat(ci): use GitHub Actions for CI/CD 

### PR DESCRIPTION
**Pull request by marechal-p**
Replace `.travis.yml` with GitHub Actions.

Splitting scripts was needed to correctly run in CI:
- `yarn` now only install deps and builds example apps.
- `yarn lint` lints our TypeScript sources.

`THEIA_SKIP_BUILD=1` can be enabled to only install deps when doing `yarn`.

Notes:

I skipped the flakiest tests, but it seems like some are still causing trouble. Feel free to restart the jobs.

### CODE REVIEW

**Comment by marechal-p** [comment]
It is not ready, I am trying to get the workflows running.

**Comment by marechal-p** [comment]
@kittaakos just a heads up that I think this PR is ready for review.

What's done:

- Install, lint, build, and test.
- Publishing next? Wasn't able to test, and I think we are missing a secret (`NPM_TOKEN`).

What's missing:

- Caching of `node_modules`.
- Publishing the `gh_pages`.

I think the missing parts can be added later, but feel free to push on this branch to add things you think should be there.

**Comment by marechal-p** [comment]
cc @vince-fugnitto

**Comment by kittaakos** [comment]
Thank you for preparing it, @marechal-p. There are a few things I do not really like: such as unnecessary configs, changed npm scripts, hacks, and the publish build does not wait. [Here](https://github.com/eclipse-theia/theia/compare/master...kittaakos:gh-actions) is my proposal. There is one thing I do not understand, the macOS build fails for some reason.

```
$ yarn build && run lint && run build "@theia/example-*" --stream --parallel
$ tsc -b configs/root-compilation.tsconfig.json
ERR! lerna Invalid command!
ERR! lerna Pass --help to see all available commands and options.
```

[Here](https://github.com/kittaakos/theia/actions/runs/382872196) is the build without the macOS image, and [here](https://github.com/kittaakos/theia/runs/1452955784) is with macOS.

I also [updated](https://github.com/eclipse-theia/theia/issues/8772#issuecomment-733622141) the issue for this PR: we do the codec thingy after the `tsc` build. Is that correct? I guess you are the one who has the most experience with the code logic.

**Comment by kittaakos** [comment]
> There is one thing I do not understand, the macOS build fails for some reason.

There is something odd with the `theia-run.js` module when manipulating the `proceee.argv`:

Here are the outputs from Linux and macOS:

macOS:
```
process.argv: ["/Users/runner/hostedtoolcache/node/12.19.0/x64/bin/node","/Users/runner/work/theia/theia/node_modules/.bin/run","lint"]
args: ["/Users/runner/work/theia/theia/node_modules/.bin/run","lint"]
scopedArgs: ["/Users/runner/work/theia/theia/node_modules/.bin/run","lint"]
modified process.argv: ["/Users/runner/hostedtoolcache/node/12.19.0/x64/bin/node","run","/Users/runner/work/theia/theia/node_modules/.bin/run","--scope","lint"]
```

Linux:
```
process.argv: ["/opt/hostedtoolcache/node/12.19.0/x64/bin/node","/home/runner/work/theia/theia/node_modules/.bin/run","lint"]
args: ["lint"]
scopedArgs: ["lint"]
modified process.argv: ["/opt/hostedtoolcache/node/12.19.0/x64/bin/node","/home/runner/work/theia/theia/node_modules/.bin/run","run","lint"]
```

**Comment by kittaakos** [comment]
> but feel free to push on this branch to add things you think should be there.

Here is an alternative solution: https://github.com/eclipse-theia/theia/pull/8780

**Comment by marechal-p** [comment]
> There is something odd with the `theia-run.js` module when manipulating the `proceee.argv`:

Yes and since I did not have access to a Mac I avoided this issue by not using `theia-run.js`. I see that you have a fix, nice.

> we do the codec thingy after the `tsc` build. Is that correct?

It happens on `postinstall` for the `@theia/electron` package. From the commit history, we had to explicitly call the ffmepg test scripts because the `@theia/electron` package was being cached, so `postinstall` did not run somehow? At any rate, the tests should happen when we do `yarn` on the monorepo.

**Comment by marechal-p** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/pull/8780

**Pull request closed without merging**
