### PR TITLE
Perform remote backend copy via http

### PR DESCRIPTION
**Pull request by jonah-iden**
#### What it does

There is a strong indication that copying the backend to remote systems via http is a faster than using sftp. 
On my local system copying the zipped theia backend, http was 2.5x faster then sftp. I sadly wasn't able to test it with an actual remote system.

#### How to test

i created a small docker container here https://hub.docker.com/repository/docker/jonahiden/remote-test-ubuntu-ssh/general
you can connect to it via ssh with user: test pass: test 
also open port 8080 or some other port (other ports need configuration in the theia settings) for the http copy

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
Can you rebase the changes on top of the latest `master`?

**Comment by JonasHelming** [comment]
@jonah-iden Is this ready for a re-review?

**Comment by msujew** [comment]
I'll look into this in the new year. This isn't a high prio topic.

**Comment by JonasHelming** [comment]
@msujew Let's get this one done :-)

**Comment by msujew** [comment]
@JonasHelming Thanks for the reminder. I'll look into this in the next few days :)

**Comment by msujew** [comment]
We've decided to not continue with this. If anyone is interested, feel free to pick this up again. However, I would recommend a CDN based solution that we might eventually build into the framework.

**Pull request closed without merging**
