### PR TITLE
[playwright] Update documentation

### PR DESCRIPTION
**Pull request by marcdumais-work**
#### What it does

Note: this goes along with this `theia-playwright-template` PR:
https://github.com/eclipse-theia/theia-playwright-template/pull/9

Since a recent enhancement/refactoring of @theia/playwright \[1\], to permit using it in Theia Electron applications, the way to load an application has changed. This commit is an attempt to update the examples that are part of the documentation. I validated the changes in the "theia-playwright-template" repository, and so I have adapted the sample code to that repo's linting rules (using single quotes instead of double).

It's possible that other things have changed, that I have not yet encountered, but this should be a good step forward, at least for those just getting started integrating playwright to test their Theia-based app.

\[1\]: "Basic playwright electron support (#12207)"
https://github.com/eclipse-theia/theia/commit/487e92be7bba38e56ba63c872efa55cc6aee49e3

#### How to test

This is mostly a documentation change. I guess it could be tested after the PR listed above is merged, reproducing the documentation's examples using the latest "theia-playwright-template" code. But perhaps a visual inspection could be enough.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by planger — APPROVED** [review]
Thank you very much @marcdumais-work! We totally missed updating the docs when adding the Electron support. Your changes look good to me! :+1:

**Comment by marcdumais-work** [comment]
Thanks for the quick review @planger ! 
Ok to merge?

**Comment by marcdumais-work** [comment]
> in #13491 I've removed some deprecated API and actions. We should probably also switch in [this template](https://github.com/eclipse-theia/theia-playwright-template) to Node 18 and avoid using the deprecated `GabrielBB/xvfb-action@v1` GH action.

Would similarly updating the workflow for `theia-playwright-template` be welcomed, as part of https://github.com/eclipse-theia/theia-playwright-template/pull/9?

**Comment by planger** [comment]
> > in #13491 I've removed some deprecated API and actions. We should probably also switch in [this template](https://github.com/eclipse-theia/theia-playwright-template) to Node 18 and avoid using the deprecated `GabrielBB/xvfb-action@v1` GH action.
> 
> Would similarly updating the workflow for `theia-playwright-template` be welcomed, as part of [eclipse-theia/theia-playwright-template#9](https://github.com/eclipse-theia/theia-playwright-template/pull/9)?

Yes. definitely! That would be great. However, don't feel obligated to do it, I'm happy to put it on our list too. Thank you!

**Pull request merged**
