### PR TITLE
[debug] Wait for debugger capabilities initialization before breakpoint update

### PR DESCRIPTION
**Pull request by vakosta**
#### What it does
Fixes: https://github.com/eclipse-theia/theia/issues/11606
Fix an issue where debugger doesn't send breakpoints on first run.

#### How to test
1. Open any project in Theia.
2. Switch to the debugger tab.
3. Add function breakpoint by clicking on "Add Function Breakpoint" button.
4. Run debugger.
5. Make sure that debugger wait for capability initialization and catches breakpoints correctly.

#### Review checklist
- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers
- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
Hey @Vakosta, thank you for your first contribution 👍 

A few general remarks:
1. Please keep methods/class properties open for extension by making them `protected`.
2. Emitters have a certain convention sorrounding their names. In your case it would be `onDidConfigureCapabilities`.

Regarding the issue at hand: While using emitters/events works fine for this issue, we can probably improve the async handling of this using the `Deferred` class. It should resolve once we run `updateCapabilities` and the exposed promise should be awaited at `updateBreakpoints`.

**Comment by msujew** [comment]
@Vakosta I'm having trouble to test this successfully, since the Node.js debugger doesn't support function breakpoints at all. What language/extension are you using to test this?

**Comment by Vakosta** [comment]
@msujew Language and extension are internal commercial development in the company, where I work. Unfortunately, I can't name them, because they are under NDA.

**Comment by EvilBeaver** [comment]
@msujew as an author of another debug adapter (https://marketplace.visualstudio.com/items?itemName=EvilBeaver.oscript-debug) I think this is good fix and capabilities now should work better. What else should be done to make this PR merged?

**Review by msujew — APPROVED** [review]
Alright, while I can't really test the changes for the specific use case (function breakpoints), I can confirm that nothing else regressed with these changes. As the change looks reasonable, I'll approve this.

@vince-fugnitto Do you think it's alright to include this change in the upcoming release or should we merge it shortly afterwards to catch potential issues?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Do you think it's alright to include this change in the upcoming release or should we merge it shortly afterwards to catch potential issues?

@msujew I'd wait for right after the release since we didn't get the opportunity to test the actual functionality of the change as no plugin was provided.

**Comment by msujew** [comment]
@vince-fugnitto Alright, sounds good to me 👍

**Pull request merged**
