### PR TITLE
8691 support in operator for when clauses

### LINKED ISSUE #8691: Support  new vscode 'in' operator for 'when' clauses
### Feature Description:
There is a new `in` operator for `when` clauses that vscode added. This new operator allows for a dynamic lookup of a context key's value within another context key's value. For example, if you wanted to add a context menu command to folders that contain a certain type of file (or something that can't be statically known), you can now use the `in` operator to achieve it.

Example:

Capture

For more info:
https://code.visualstudio.com/updates/v1_49#_in-operator-for-when-clauses

### PR DESCRIPTION
**Pull request by danarad05**
#### What it does
Fixes #8691 

#### How to test
**_Note: This PR is dependent on merging of #9154 as it requires latest monaco typings._**

1. Open a project - i.e. "helloworld sample" from "vscode-extension-samples"
2. Update `extension.ts` to setContext i.e.:
image

3. Add to sample `package.json` - menus dependent on context key:
image

4. Run as hosted plugin
5. Run command "extension.helloWorld" from command palette
6. Right click on "src" folder and see that "Hello World" command is added to opened context menu:
image
7. Right-clicking on file and not folder - doesn't display "Hello World" command in context menu:
image

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by EstherPerelman** [comment]
@paul-marechal @tsmaeder @RomanNikitenko 
After merging #9154 , Could you please review this PR (and finally approve & merge)?

**Comment by EstherPerelman** [comment]
> @paul-marechal @tsmaeder @RomanNikitenko
> After merging #9154 , Could you please review this PR (and finally approve & merge)?

Anyone🤔?

**Review by RomanNikitenko — APPROVED** [review]
`Theia` has got `Support new vscode 'in' operator for 'when' clauses`with the `Monaco` upgrade. 
I tested `master` branch according to the `How to test` section of the PR - it works well.

If I understand correctly, the current PR contains refactoring related to this area. The changes look good for me, I tested them - it works.

@EstherPerelman 
there is one failing job - please pick up last changes from the `master` and check that all jobs are successful before merging the PR

**Comment by EstherPerelman** [comment]
> `Theia` has got `Support new vscode 'in' operator for 'when' clauses`with the `Monaco` upgrade.
> I tested `master` branch according to the `How to test` section of the PR - it works well.
> 
> If I understand correctly, the current PR contains refactoring related to this area. The changes look good for me, I tested them - it works.
> 
> @EstherPerelman
> there is one failing job - please pick up last changes from the `master` and check that all jobs are successful before merging the PR

@RomanNikitenko Thanks for approving! 
I picked up last changes but ubuntu still failing, Is it cause of this PR?

**Comment by RomanNikitenko** [comment]
failing_test

I have restarted all checks, waiting...

**Comment by EstherPerelman** [comment]
> failing_test
> 
> I have restarted all checks, waiting...

 @RomanNikitenko Thank you it passed! Are you able to merge?

**Pull request merged**
