### PR TITLE
fix: Update eslint to v7

### PR DESCRIPTION
**Pull request by RDIL**
#### What it does

ESLint (and its typescript counterpart) have been updated.  This really just removes deprecated rules and updates the recommended presets, so not too much here.

#### How to test

Tests passed locally.

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
It does not seem that you pushed updated yarn.lock.

**Comment by RDIL** [comment]
Fixed.  My Yarn version was newer than Travis's.

**Comment by akosyakov** [comment]
There seems to be another rule https://github.com/typescript-eslint/typescript-eslint/issues/2251.

btw I've already upgraded eslint in https://github.com/eclipse-theia/theia/pull/7908/files I think I've done it to enable latest `deprecation` rule which was lost during migration from tslint. I would prefer to have `deprecation` rule working than `@typescript-eslint/class-name-casing`. I am not even sure we have latter rule with tslint before.

**Comment by RDIL** [comment]
Alright.  I'm just trying to keep everything up-to-date in the toolchain, so I'll look into this or find something else that needs updating.

**Comment by marcdumais-work** [comment]
> Alright. I'm just trying to keep everything up-to-date in the toolchain, so I'll look into this or find something else that needs updating.

Thanks @RDIL

**Pull request closed without merging**
