### PR TITLE
Fix file data streaming for http polling

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Closes https://github.com/eclipse-theia/theia/issues/14067

When using socket.io's long polling mechanism, sending messages to the frontend in the backend while responding to a request from the frontend might result in messages arriving in an unexpected order. In particular, it might result in those notifications arriving before the request response arrives.

Usually this is no issue, since we rarely depend on the exact order of messages. However, in the file data streaming, we expect the response before any of the notifications arrive. This seems to be the case with websockets, but not with long polling.

This change makes the frontend in charge of the sequence id handle instead of the backend. This entirely removes the possibility of a race condition without impacting the behavior of the file streaming feature.

#### How to test

1. Follow the reproduction steps from https://github.com/eclipse-theia/theia/issues/14067.
2. Ensure that files can be successfully opened.

#### Follow-ups

We might want to look into any potential other places where we depend on notifications + a response for a backend RPC call. I don't think there are any others, but I wouldn't guarantee it.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
@msujew I have to disagree that message ordering is not important, see for example: https://github.com/eclipse-theia/theia/issues/13960. This is exactly the kind of problem that is totally baffling and seems to appear at randoem. Can we fix the problem in the polling socket implementation so that it respects message ordering?

**Comment by msujew** [comment]
@tsmaeder I've changed the code so that the race condition observed in the initial post is no longer possible. The frontend is now in charge of the file handle instead of receiving the file handle from the backend.

**Comment by msujew** [comment]
@tsmaeder I've read up on this a bit [socket.io guarantees message ordering on both websocket and http fallback](https://socket.io/docs/v4/delivery-guarantees). I would generally assume that this works as intended. However, what we've been doing is a bit of a hack anyway: We attempt to respond with a handler id, that we already use in the events, without making any guarantees about the order. This doesn't seem to be a problem in websocket contexts, but likely due to some specific implementation details. I see no reason why this also shouldn't fail on websockets.

The new implementation fixes this issue by specifiying the handler on the frontend level, something that is way cleaner anyway and something that we do throughout the rest of the codebase as well.

**Comment by tsmaeder** [comment]
Ah, I get it:

1. Front end requests stream read
2. back end starts servicing request
3. back end allocates handle for stream
4. back end starts reading the file, generating events sent to front end
5. back end sends hande as reply to original request.

Just wanted to make sure we don't overlook some deeper problem here.

**Comment by tsmaeder** [comment]
The only difference I can see for polling is that websocket probably uses some native event mechanism, whereas the polling likely goes through a timeout. That might reorder the execution releative to promises.

**Comment by tsmaeder** [comment]
Never mind, I was able to reproduce to for some files in the browser version.

**Review by tsmaeder — APPROVED** [review]

**Pull request merged**
