### PR TITLE
custom-editor: fix closing dirty custom text editor issue

### PR DESCRIPTION
**Pull request by safisa**
#### What it does

Fix the issue: Closing a dirty/modified custom editor based on CustomTextEditorProvider doesn't ask the user to save, it just saves it on close (https://github.com/eclipse-theia/theia/issues/11592)

#### How to test

1. use the cat scratch custom editor extension example from vscode (you can download it from this issue https://github.com/eclipse-theia/theia/issues/10787)
2. open the example.cscratch file
3. do some changes in the custom editor UI (add some cats by clicking on the scratch button)
4. close the dirty tab, you need to see the popup asking to save the file.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
Thank you for your contribution :+1: 

In order to accept your changes please be sure to sure to sign the [eclipse contributor agreement (eca)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) with the same email as your authorship.

**Comment by vince-fugnitto** [comment]
> I already signed it. It is my first PR to Theia, do I need to do anything else? Thanks in advance

@safisa just the ECA for the moment, I verified and there does not seem to be a valid one registered yet (for safi@k2view.com):


Screen Shot 2022-08-22 at 8 41 08 AM

**Comment by safisa** [comment]
I used my private email: safi.sa@gmail.com
This email is also linked to my Github account.

**Comment by vince-fugnitto** [comment]
> I used my private email: [safi.sa@gmail.com](mailto:safi.sa@gmail.com) This email is also linked to my Github account.

@safisa in order for the ECA check to actually pass you'll need to use the same email in both your authorship and ECA.
At the moment there is a mismatch:

```patch
From 02ec66c106d900818ff3ed9e92e0422c2f4522b9 Mon Sep 17 00:00:00 2001
From: Safi <safi@k2view.com>
Date: Mon, 22 Aug 2022 14:52:53 +0300
Subject: [PATCH 1/2] This will fix the issue: Closing a dirty/modified custom
 editor based on CustomTextEditorProvider doesn't ask the user to save, it
 just save it on close https://github.com/eclipse-theia/theia/issues/11592
...
```

**Comment by safisa** [comment]
Hi @vince-fugnitto  @msujew 
Can you review this PR?

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the changes work well 👍 
- [x] if a custom-editor is dirty, closing the editor triggers the prompt
- [x] `save` from the prompt will save the editor
- [x] `cancel` will close the dialog
- [x] `don't save` will revert the changes and close the editor

**Comment by safisa** [comment]
Hi @vince-fugnitto 
This PR is already approved, is it going to be merged before the next Theia version?

**Comment by vince-fugnitto** [comment]
@safisa it should, I just wanted to give others a chance to review.
Do you mind removing the changelog entry since it is in the wrong release? (I'll re-add it when I perform the release at the end of the month).

**Pull request merged**
