### PR TITLE
Make cpp UI test work on Windows

### PR DESCRIPTION
**Pull request by simark**
The cpp-change-build-config.ui-spec.ts test currently fails on
Windows.  The problem is that the paths in the JSON files generated by the
test contain unescaped backslashes.

This patch changes the way we generate the JSON files to use
JSON.stringify.  This way, the strings will be properly escaped.

Change-Id: I315f4c6ea888d06cce4cb03102eecb340810046a
Signed-off-by: Simon Marchi <simon.marchi@ericsson.com>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Looks good but I will wait for Windows CI results.

**Comment by marechal-p** [comment]
https://ci.appveyor.com/project/kittaakos/theia/builds/19982917#L4241

**Comment by marcdumais-work** [comment]
> AppVeyor failure: https://ci.appveyor.com/project/kittaakos/theia/builds/19982917#L4241

Indeed, and the error for the cpp tests is the same or similar. Maybe easier to debug this locally on our Windows VM? Before running the UI tests, we can do as it says [here](https://github.com/theia-ide/theia/blob/master/examples/browser/wdio.base.conf.js#L8) so the workspaces used in the tests are left behind for us to troubleshoot the issue. 

@vince-fugnitto would you have a bit of time to have a look? The compile_commands.json that we generate on Windows is probably the first suspect, but it could be something else.

**Comment by marcdumais-work** [comment]
Running locally on Linux, the UI tests pass, but only if the actual cpp test file is skipped, because 'clangd' is not found in the path. When clangd is present, the UI test fails. 

That probably explains why CI passed on Linux, where clangd is not installed, but did not on Windows, where we noticed that, somehow, clangd is available by default.

**Comment by simark** [comment]
> Indeed, and the error for the cpp tests is the same or similar. Maybe easier to debug this locally on our Windows VM? Before running the UI tests, we can do as it says [here](https://github.com/theia-ide/theia/blob/master/examples/browser/wdio.base.conf.js#L8) so the workspaces used in the tests are left behind for us to troubleshoot the issue.
> 
> @vince-fugnitto would you have a bit of time to have a look? The compile_commands.json that we generate on Windows is probably the first suspect, but it could be something else.

Well, (at least yesterday) the test passed on our Windows VM.

**Comment by simark** [comment]
> Running locally on Linux, the UI tests pass, but only if the actual cpp test file is skipped, because 'clangd' is not found in the path. When clangd is present, the UI test fails.

On my two Linux computers (work and personal) the test passes... I'll try to debug it with one of you.

**Comment by simark** [comment]
So, this has passed on AppVeyor, and it passes locally too.  Maybe there is some flakiness, but it's hard to tell with just one run... maybe it's just that the timeout needs to be increased, I don't know.  It works on @vince-fugnitto's and @marechal-p's computers (they were using outdated clangds).  So do you think this would be ready to merge, and we look closely at the CI for the next few days to fix any potential issue?

**Comment by vince-fugnitto** [comment]
@simark closing since the `@theia/cpp` extension has recently moved to [theia-cpp-extensions](https://github.com/eclipse-theia/theia-cpp-extensions)

**Pull request closed without merging**
